### ISSUE TITLE
I have geode but it crashes im on pc with 2.1

### ISSUE THREAD

**Issue by SdkSdkilovegeode** [geode-sdk/geode#1000]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.0.0

### Mods Installed

no mods

### Steps to Reproduce

i opend geometry dash but at 10 or so seconds it crashes

**Comment by SdkSdkilovegeode** [comment]
i meant 1.2.1

**Comment by Helloausername** [comment]
1.2.1? I think u need to update ur geode

**Comment by matcool** [comment]
stale, reopen if needed
