### ISSUE TITLE
"There were errors loading some mods" message

### ISSUE THREAD

**Issue by Myron472** [geode-sdk/geode#1001]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.2.0

### Expected Behavior

After I delete all non-ported mods this message will disappear

### Actual Behavior

After I deleted all non-ported mods this message stays.

### Steps to Reproduce

Idk i can give you my AnyDesk so you could understand why this thing happens.

### Additional Information

Firstly i did a backup of .geode files and for some reason decided to delete the .geode files manually instead of deleting them in game. Then I saw this issue and deleted folders in _unzipped_ folder. Still saw the message and then I placed .geode files back in the folder and deleted every uncompatible mod in the game. And still got this message.

**Comment by hiimjustin000** [comment]
This error occured because the mods were unported. Maybe if you went to the Geode page like it told you to, you wouldn't be posting this issue.

**Comment by Myron472** [comment]
> This error occured because the mods were not ported. Maybe if you went to the Geode page like it told you to, you wouldn't be posting this issue.

You understood it wrong. I have DELETED all this uncompatible this mods and still this message appears. The funny thing is if I press Show errors only button it says it didn't find any mods.

**Comment by hiimjustin000** [comment]
Okay, my apologies. This is actually a bug I encountered myself.

**Comment by Myron472** [comment]
I wrote from my phone previously so here's images to be sure.
![20240715163351_1](https://github.com/user-attachments/assets/f38e0a04-78c7-453b-862e-1b71ef42a4c2)
![20240715163347_1](https://github.com/user-attachments/assets/8b58e708-5a9f-4caa-bff9-4e90de3d6393)

**Comment by OmgRod** [comment]
Try deleting the unzipped ones too maybe?

**Comment by HenrySck075** [comment]
try looking at the logs

**Comment by Aa12355322** [comment]
is there any fix for this yet? im experiencing the same issue
