### ISSUE TITLE
Why was i banned from the geode server?

### ISSUE THREAD

**Issue by GD-Geode** [geode-sdk/geode#1004]
### Your Question

I went afk as i went to the shops and when i come back to the server; i am banned. Can someone explain why?
![image](https://github.com/user-attachments/assets/a5bffec9-bbdf-461b-8dba-1712cbf6ad33)
This is my discord for reference

**Comment by GD-Geode** [comment]
?????

**Comment by cdc-sys** [comment]
because you're viper, stop pretending u arent LMAOO

**Comment by MuhXd** [comment]
I love banning a rando LOL (I'm still in the server you just banned a rando lol) this is going on my wall of best moments. I hope GD-Geode doesn't get unbanned lol

**Comment by MuhXd** [comment]
on a note like something, idk how to start this it's funny
