### ISSUE TITLE
How do i remove swelvy BG on android?

### ISSUE THREAD

**Issue by polygoners1** [geode-sdk/geode#1005]
### Your Question

I really want to get rid of that useless background, it gets in the way of the icons! I cant rename the files or else, uhhhh, UUHHHHH
![Screenshot_20240716-192052_Geode](https://github.com/user-attachments/assets/d968a9c8-c74e-4b73-a933-7bc7c19b3513)
![Screenshot_20240716-191850_Geode](https://github.com/user-attachments/assets/b505c415-b343-4d3a-970d-41556a940d39)
![Screenshot_20240716-192152_Geode](https://github.com/user-attachments/assets/bad9670a-3165-403a-8cf8-c8ee2747d4c6)

**Comment by hiimjustin000** [comment]
Disable BetterMenu
