### ISSUE TITLE
If its not possible install on samsung a14, THEN HOW ITS POSSIBLE N INSTALL ANDROID 13 REDMI NOTE 6 PRO!

### ISSUE THREAD

**Issue by enessmr** [geode-sdk/geode#1006]
### Your Question

How did you make this compatible with 2018 DEVICE? I wasn't expecting to see this question.

**Comment by enessmr** [comment]
:(

**Comment by matcool** [comment]
Geode targets android 6 and newer. not specific to any manifacturer

**Comment by enessmr** [comment]
oh

**Comment by enessmr** [comment]
then samsung galaxy tab 10.1 (normal 4g + wifi, p4 model) with android 7 custom rom????
