### ISSUE TITLE
no x_input1_9

### ISSUE THREAD

**Issue by agooddietconsistsoffood** [geode-sdk/geode#1008]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.0.2?

### Mods Installed

none

### Expected Behavior

I expected the installer to actually install most of the files

### Actual Behavior

X_input_1_9 did not install and therefore geode didn't load in the geometry dash menu

### Steps to Reproduce

1, I install geode
2, I look in my folders
3, I scroll through to Geometry_Dash
4, X_input_1_9 isn't there

**Comment by agooddietconsistsoffood** [comment]
oh and im an idiot so please put simpler terms in

**Comment by matcool** [comment]
since 2.206 geode uses xinput1_4 to load, not 9_1_0.

**Comment by fbfnysnshnsgnwg** [comment]
this should be closed
