### ISSUE TITLE
Crash when i start a level

### ISSUE THREAD

**Issue by Thoriaxe** [geode-sdk/geode#1013]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.3.0

### Mods Installed

-Attempt Utulities
-Custom Keybinds
-Death Tracker
-Editor Level ID API
-Enter Search
-Globed
-Mega Hack v8 pro (geode)
-Node IDs
-Separate Dual Icons

### Steps to Reproduce

1) I install Geode
2) I put all the mod up
3) I install a texture pack
4) I lunch a level and it crashes

### Crash Report

When i put a texture pack (any of it) it crashes and i just change the texture pack folders not the entire folders.
I don't do it with the texture pack loader beceause the texture bug with some icons or blocks in the airs.

### Additional Information

It crashes only when i play a level i can stay 6h in the menu anything.
(idk if i did it nice)

**Comment by hiimjustin000** [comment]
Can you post the log? Geometry Dash/geode/crashlogs directory

**Comment by Thoriaxe** [comment]
(It crashed with 8 other texture pack i tried to play with)
2024-07-24T23:52:44+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.3.0
Loader Commit: ecc83ca
Bindings Commit: fd133d1
Installed mods: 11
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FF64441D35D (GeometryDash.exe + 18d35d)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 18d35d
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2353e4
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 38b2ab
 - 000002E0466F4172 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1aa590
 - 000002E0466F4172 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 38a2eb
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 38358c
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + c78f8
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 97e02
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1aa0a5
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll + 2d8d8
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll + 1c5c2
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 186288
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 57832
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\elohmrow.death_tracker\elohmrow.death_tracker.dll + 7ff18
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\elohmrow.death_tracker\elohmrow.death_tracker.dll + 102d
 - 000002E0465E7872 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 382844
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2fd7e5
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 2f808 (cocos2d::CCCallFunc::execute + 24)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 36c41 (cocos2d::CCSequence::update + 257)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 3832e (cocos2d::CCActionManager::update + 142)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c03ed (cocos2d::CCScheduler::update + 93)
 - 000002E036B34472 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1ca63f
 - 000002E036B34472 (Hook handler)
 - 000002E036B34472 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 16c575
 - 000002E04659D8D2 (Hook handler)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\Geode.dll + 23c28a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Users\Thomas\Desktop\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 000000f1d395d728
RBX: 0000000000000000
RCX: 000000f1d395d720
RDX: 000000f1d395d728
RBP: 0000000000000000
RSP: 000000f1d395f7f0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffa373aaf28
R8:  000000f1d395d7d0
R9:  0000000000000001
R10: 0000000000000003
R11: 000000f1d395d600
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.0.0] cvolton.level-id-api
x | [v1.5.1] dankmeme.globed2
x | [v2.1.0] elohmrow.death_tracker
x | [v1.7.1] geode.custom-keybinds
x | [v3.3.0] geode.loader
x | [v1.13.1] geode.node-ids
  | [v1.6.1] geode.texture-loader
x | [v1.0.0] iswilljr.enter-search
x | [v1.2.0] techstudent10.attempt_utils
x | [v1.2.0] weebify.separate_dual_icons

**Comment by enessmr** [comment]
It's most likely the textures collapsed itself and past the 32-bit integer limit or the textures are mixed and due to incompatiblity, crash.

**Comment by Thoriaxe** [comment]
How can i fix it ?

**Comment by Thoriaxe** [comment]
Thx it worked now.
