### ISSUE TITLE
Bug with texture loader

### ISSUE THREAD

**Issue by Thoriaxe** [geode-sdk/geode#1016]
### Geode Issue

- [ ] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.3.0

### Mods Installed

-Attempt Utulities
-Custom Keybinds
-Death Tracker
-Editor Level ID API
-Gd-roulette
-Globed
-Mega Hack v8 pro (geode)
-Integred Demon list
-Node IDs
-texture pack loader

### Expected Behavior

Th texture loader work

### Actual Behavior

The game bug with texture at the wrong place
![Capture d'écran 2024-07-26 163130](https://github.com/user-attachments/assets/ee9f4abe-e711-4140-bd70-450d71c01087)
![Capture d'écran 2024-07-26 163154](https://github.com/user-attachments/assets/fcba25c9-b835-4e44-a629-b65ba086e1cd)

### Steps to Reproduce

I install a online texture pack
And i put it with the texture pack loader

### Additional Information

The texture pack is :Ultimate Icon Mix Texture Pack Release from Choco

**Comment by AnhNguyenlost13** [comment]
is it a 2.2 texture pack, ported or neither?

**Comment by Thoriaxe** [comment]
Yes its a 2.2 texture and i try with 2 other texture pack and do the same bug.
