### ISSUE TITLE
gd crashes mid attempt in either normal or platformer levels

### ISSUE THREAD

**Issue by YF00789** [geode-sdk/geode#1017]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.3.0(latest)

### Mods Installed

x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.0.1] alphalaneous.is_it_sent
x | [v1.0.6] cdc.level_thumbnails
x | [v4.2.5] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.3.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.1.2] mat.draw-divide
x | [v1.0.0-alpha.2] sabe.persistenceapi
x | [v1.0.1-alpha.3] sabe.platformersaves
x | [v1.1.20] syzzi.click_between_frames

### Steps to Reproduce

1.) play any level, e.g TIdal Wave
2,) suddenly get extremely low fps mid-attempt which quickly builds up to a crash

### Crash Report

2024-07-27T12:05:01+0600
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.3.0
Loader Commit: ecc83ca
Bindings Commit: fd133d1
Installed mods: 16
Problems: 0

== Exception Information ==
Faulty Module: D:\Program Files\Steam\steamapps\common\Geometry Dash\Geode.dll
Faulty Mod: Unknown
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFF7B9BFE77 (Geode.dll + 3fe77 (GeodeNodeMetadata::getFieldContainer + 407 | /home/runner/work/geode/geode/loader/src/hooks/GeodeNodeMetadata.cpp:70))
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\Geode.dll + 3fe77 (GeodeNodeMetadata::getFieldContainer + 407 | /home/runner/work/geode/geode/loader/src/hooks/GeodeNodeMetadata.cpp:70)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\sabe.platformersaves\sabe.platformersaves.dll + e55c
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\sabe.platformersaves\sabe.platformersaves.dll + 17b74
 - 000001F36D264472 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 391513
 - 000001F36D264872 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1aa33e
 - 000001F36D264872 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\sabe.platformersaves\sabe.platformersaves.dll + 37c4f
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\sabe.platformersaves\sabe.platformersaves.dll + 134e2
 - 000001F36D264872 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 228c6d
 - 000001F36D26D8D2 (Hook handler)
 - 000001F36D26D8D2 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c041d (cocos2d::CCScheduler::update + 141)
 - 000001F35BC14472 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1ca63f
 - 000001F35BC14472 (Hook handler)
 - 000001F35BC14472 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\mat.draw-divide\mat.draw-divide.dll + 32ec
 - 000001F35C918472 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 16c758
 - 000001F35C918472 (Hook handler)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\Geode.dll + 23c28a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - D:\Program Files\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 17344 (BaseThreadInitThunk + 20)
 - C:\Windows\SYSTEM32\ntdll.dll + 526b1 (RtlUserThreadStart + 33)

== Register States ==
RAX: 0000000000000002
RBX: 0000000000000000
RCX: 00000100000001b3
RDX: 000001f349e1b124
RBP: 0000000000000000
RSP: 00000061f94ff7e0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007fffed4e26b1
R8:  4b73bfcadd6e2c14
R9:  4b73bfcadd6e2c14
R10: 0000000000000002
R11: 6d185279cc31564f
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.0.1] alphalaneous.is_it_sent
x | [v1.0.6] cdc.level_thumbnails
x | [v4.2.5] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.3.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.1.2] mat.draw-divide
x | [v1.0.0-alpha.2] sabe.persistenceapi
x | [v1.0.1-alpha.3] sabe.platformersaves
x | [v1.1.20] syzzi.click_between_frames

### Additional Information

this didn't happen before updating from v3.0.0 something

**Comment by YF00789** [comment]
> sabe.platformersaves.dll

turning it off along with sabe.persistenceapi didn't help

**Comment by Kingminer7** [comment]
could also be megahack

**Comment by YF00789** [comment]
> could also be megahack

so, is it considered a geode or mh issue if it stopped working after a geode update?

**Comment by HJfod** [comment]
MH issue. Unless Geode accidentally broke an API guarantee, Geode updates should never break mods that are using it properly

**Comment by YF00789** [comment]
yeah. thanks
