### ISSUE TITLE
Vsync not working

### ISSUE THREAD

**Issue by AksLolCoding** [geode-sdk/geode#1026]
### Geode Issue

- [ ] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.4.0

### Mods Installed

i disabled all mods

### Expected Behavior

there is no screen tearing

### Actual Behavior

Vsync is not working even though the in-game setting for it is enabled
this is causing screen tearing
uninstalling geode fixes the issue so im pretty sure geode is causing it
disabling vsync in game doesnt fix it either

### Steps to Reproduce

1) install geode latest version
2) open the game
3) enable fullscreen borderless and vsync
4) screen tearing still happens and the only way to make it go away is to disable fullscreen (which i dont want to do)

### Additional Information

in windowed mode it works fine but in fullscreen borderless it doesnt work

**Comment by iNUCi** [comment]
this is a GD bug, robtop broke vsync on borderless in 2.206

**Comment by AksLolCoding** [comment]
oh ok thanks
