### ISSUE TITLE
geode loader libcocos2d.dll error EXCEPTION ACCESS VIOLATION

### ISSUE THREAD

**Issue by AvKlol** [geode-sdk/geode#1033]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.4.0

### Mods Installed

x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.0.7] cdc.level_thumbnails
x | [v4.2.6] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.0.9] firee.goldenbest
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.5.5] hiimjustin000.integrated_demonlist
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.37] minemaker0430.gddp_integration
x | [v1.1.21] syzzi.click_between_frames

### Steps to Reproduce

i opened demon list mod
suddenly the game crashed, showing me the error.

i can confirm this is not due to a mod because the game has crashed before with the same error, but if it is then just close the repo, ill delete it ig

### Crash Report

2024-08-07T14:38:33+0530
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 21
Problems: 0

== Exception Information ==
Faulty Module: F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFC0D0B85A0 (libcocos2d.dll + 485a0 (cocos2d::CCLabelBMFont::limitLabelWidth + 64))
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 485a0 (cocos2d::CCLabelBMFont::limitLabelWidth + 64)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 3fea
 - F:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 1494e3
 - F:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 13e587
 - F:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 13e484
 - 000001C45DB6E872 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + f1b30
 - F:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 25777
 - 000001C45DB6E872 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libExtensions.dll + 1805a (cocos2d::extension::CCHttpClient::dispatchResponseCallbacks + 170)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + c0629 (cocos2d::CCTimer::update + 105)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + c049b (cocos2d::CCScheduler::update + 267)
 - 000001C45D6E4472 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 1cf60f
 - 000001C45D6E4472 (Hook handler)
 - 000001C45D6E4472 (Hook handler)
 - 000001C45D6E4472 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 000001C46A3C9C72 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 16c5e8
 - 000001C46A3C9C72 (Hook handler)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - F:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - F:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - F:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 00007ffc0d154510
RBX: 0000000000000000
RCX: 000001c43bf03a80
RDX: 0000005357f4e398
RBP: 0000000000000000
RSP: 0000005357f4f970
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffc39deaf28
R8:  6f2030206f742001
R9:  0000000000000030
R10: 00007ffc1ae90000
R11: 0000005357f4e320
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.0.7] cdc.level_thumbnails
x | [v4.2.6] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.0.9] firee.goldenbest
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.5.5] hiimjustin000.integrated_demonlist
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.37] minemaker0430.gddp_integration
x | [v1.1.21] syzzi.click_between_frames

### Additional Information

heres my pc specs just incase:
Processor	Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz   2.20 GHz
GPU       Intel(R) UHD Graphics 620
Installed RAM	8.00 GB
Device ID	53D19D3C-3761-455B-8D87-E7CD3E8E39EB
Product ID	00327-35888-96110-AAOEM
System type	64-bit operating system, x64-based processor

**Comment by enessmr** [comment]
is your gpu shit

**Comment by enessmr** [comment]
mostly gpu

**Comment by AvKlol** [comment]
i just reinstalled geode, tysm.
