### ISSUE TITLE
When installing geode it says Cant Write to every file (SOLVED)

### ISSUE THREAD

**Issue by GlieGT** [geode-sdk/geode#1037]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.4.0

### Expected Behavior

install geode

### Actual Behavior

![Screenshot 2024-08-10 205721](https://github.com/user-attachments/assets/f926224e-d1d7-4dc8-96f6-4639aed397c9)

### Steps to Reproduce

i tried to reinstall

### Additional Information

idk why

**Comment by hiimjustin000** [comment]
@GlieGT Check your storage

**Comment by GlieGT** [comment]
> @GlieGT Check your storage

what do you mean?
i got a brand new pc yesterday

**Comment by hiimjustin000** [comment]
run the setup as administrator

**Comment by GlieGT** [comment]
> run the setup as administrator

thank you so much bro!
you solved the problem in 5 words wow

**Comment by hiimjustin000** [comment]
Great! Now you can click "Close issue" at the bottom 🙂

**Comment by GlieGT** [comment]
solved by hiimjustin000 thanks!
