### ISSUE TITLE
Problem loading mods (also i have a problem downloading mods)

### ISSUE THREAD

**Issue by GlieGT** [geode-sdk/geode#1038]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.4.0

### Mods Installed

qolmod
click between frames
gddp integration
run info
grandpa demon
better progression
gmd api
betteredit
gdutils
autonong
globed2
betterinfo

### Expected Behavior

Supposed to load my mods but instead it says problem loading mods
When i try to install them i have to drag it to the folder and when i open gd it says problem loading mods

### Actual Behavior

Said that in expected behavior
Screenshot: ![Screenshot 2024-08-10 234626](https://github.com/user-attachments/assets/05080398-4bbc-47c7-ab18-60cf3543430f)

### Steps to Reproduce

I just wanted to download mods

**Comment by matcool** [comment]
based off your previous issue (#1037), you have gd installed in a folder thats admin protected, and thus geode cant write any files to it. consider moving your game install somewhere else, as running gd as administrator is a bad idea
