### ISSUE TITLE
Installed Indicators misplaced

### ISSUE THREAD

**Issue by KontrollFreek** [geode-sdk/geode#104]
### Platform

Windows

### Geode Version

v0.6.1 Alpha

### Mods Installed

hjfod.devtools v0.0.5
hjfod.betteredit v5.0.2
mat.circle-tool v1.0.0
mat.practice-music v1.0.1

### Expected Behavior

Glow-y Squares around Mod Icons are Centered around Icon.
![image](https://user-images.githubusercontent.com/72424960/209882839-290d1114-aa9f-4a40-b1ed-506077240a65.png)

### Actual Behavior

Both Mod Icon and Square around Icon are Misplaced by about 10 pixels left and down.
![image](https://user-images.githubusercontent.com/72424960/209882825-6ae50538-81ba-4dea-9e24-32e00d8faa6d.png)

### Steps to Reproduce

1) Install Mod from Download Menu in Geode
2) Enable "Show Installed" Option in Download Menu
3) View Downloads Page

**Comment by altalk23** [comment]
Known bug, fixed in 1.0.0

Though will still leave the issue up because we havent made the release yet

**Comment by altalk23** [comment]
We made the release oops
