### ISSUE TITLE
A question about iOS support

### ISSUE THREAD

**Issue by DDAN-17** [geode-sdk/geode#1042]
### Your Question

I know that all other requests about iOS support have been closed, and I know that the reason why Geode won’t work on iOS is because apple doesn’t allow loading .dylibs on iOS, but I was wondering if apple just doesn’t like it, or if iOS doesn’t allow it.

**Comment by TheSillyDoggo** [comment]
Both

**Comment by DDAN-17** [comment]
Why would that make hooking harder?
