### ISSUE TITLE
Is there an un-upload hack in geode

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [geode-sdk/geode#1048]
### Your Question

So here's why I'm wondering

So on July 7th, GD's shitty anti-bot system thought I was a bot and deleted all my levels, including 6 rateworthy levels, 5 of which got into the magic tab.

If I want to reupload the levels in vanilla GD, I will have to create copies of them, which will reset the "time spent in editor" thingy, which will prevent them from getting into the magic tab and cause people to think they are stolen (they are not, all 6 levels were made solely by me)

Is there any Geode hack that lets me reupload them without resetting the time spent in editor, and get the levels into the magic tab?

Sorry if I'm not asking in the right place

**Comment by RoootTheFox** [comment]
try QOLMod or Prism Menu, they might have something like this

side note: this isn't a Geode issue

**Comment by ImmediateMurderProfessionals** [comment]
> try QOLMod or Prism Menu, they might have something like this
> 
> side note: this isn't a Geode issue

ok

**Comment by ImmediateMurderProfessionals** [comment]
Ignore this issue
