### ISSUE TITLE
Geode refuses to load (or even show) mods for older game versions

### ISSUE THREAD

**Issue by TPEcool** [geode-sdk/geode#1063]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

v1.4.1

### Mods Installed

Geode, Backups, BetterEdit, BetterPause, BetterSave, Custom Keybinds, Easing Preview, Editor Level ID API, GMD API, Geometry Dash

### Expected Behavior

2.205 mods should work on 2.206 and 2.205 and """incompatible""" mods should not be hidden (in xdBot's case)

### Actual Behavior

Using mods on 2.206 results in xdBot not even displaying in neither the downloaded not downloadable mod lists. Also, the following mods did not load because they expected 2.205:
- BetterPause
- BetterSave
- Easing Preview

If I instead download 2.205, even more mods fail to load, saying 2.205 is not a supported version.

### Steps to Reproduce

2.206:
1. Install game and Geode
2. Run game
3. "Some mods failed to load"
4. xdBot doesn't exist and some mods fail to load

2.205:
1. Steps 1-3 of 2.206
2. xdBot shows up but it and a lot more mods fail to load

### Additional Information

Geode is up to date.
Mods that say they want 2.205 are also non-existent on the Download tab.

**Comment by TPEcool** [comment]
https://github.com/geode-sdk/geode/issues/895 might be the why xdBot doesn't show up

**Comment by qimiko** [comment]
> 2.205 mods should work on 2.206

no they shouldn't? please send your game logs, i don't think you're wording this issue properly

**Comment by Fleeym** [comment]
Most mods (with a few exceptions, that only alter the game's engine itself) will not work across game versions. The index doesn't return mods not made for your game version, which is intended behavior.

**Comment by TPEcool** [comment]
> > 2.205 mods should work on 2.206
> 
> no they shouldn't? please send your game logs, i don't think you're wording this issue properly

https://hastebin.com/share/abamamadeq.makefile

> no they shouldn't
How the heck do I use mods then?! Nothing works on 2.206 and even less works on 2.205

**Comment by TPEcool** [comment]
Are there _**so many**_ changes between 206 and 205 to break nearly all my mods?
Moreover, why are mods in a literal "love-hate" relationship with 2.2.205? On 206 they say they require 205 but on 205 they say it's not a supported version

**Comment by matcool** [comment]
mods are made for 2.206. whether they work in 2.205 (they shouldnt) is none of our business

**Comment by TPEcool** [comment]
> mods are made for 2.206. whether they work in 2.205 (they shouldnt) is none of our business

Okay but that did not answer my question. What am I supposed to do about my mods?

**Comment by TPEcool** [comment]
Do people of this repository just close issues without helping and then proceed to ignore any follow-up messages? That's one hell of a contribution

**Comment by TPEcool** [comment]
Y'all have completely ignored my actual issue and gave me useless compatibility info. Is it THAT hard to actually help people?

What I need is information about what _**I can do**_ about this limbo mod state, not useless information about **_why it is as it is_**. So far the support I've been given was less helpful than a video on how to beat a GD level.

**Comment by TPEcool** [comment]
> mods are made for 2.206. whether they work in 2.205 (they shouldnt) is none of our business

Well clearly they are not, they literally **_do not work_** on 2.2.206

**Comment by Alphalaneous** [comment]
If a mod doesn’t work, remove it from the mods folder. Mods usually cannot be cross version due to how the nature of modding in C++ works. Every update, method addresses shift around, thus they won’t work on newer versions of the game without them being refound and then the mod recompiled. This is pretty much unavoidable. In some cases, a mod can be cross version, such as if it doesn’t hook anything GD related.

**Comment by Alphalaneous** [comment]
As for why it doesn’t even show it in the mod list sometimes (phantom problems popup). This is due to the mod.json format being different from old geode versions to the new one. This is ultimately likely a bug and it should show the mod in some way, rather than it just being invisible due to an invalid mod.json (even if it were to just show the mod ID in my honest opinion)

**Comment by TPEcool** [comment]
> If a mod doesn’t work, remove it from the mods folder.

Removing the problematic mods would essentially be equivalent to not playing with mods at all. 2/3 of the problematic mods are dependencies.

**Comment by Alphalaneous** [comment]
A lot of the problematic mods need to be reinstalled from the downloads tab of the index, as an update popup will not show for them. A majority of the old mods have been ported and work on 2.206.

**Comment by matcool** [comment]
> > mods are made for 2.206. whether they work in 2.205 (they shouldnt) is none of our business
> 
> Okay but that did not answer my question. What am I supposed to do about my mods?

every mod made in the past ~3 months has been for 2.206. we have don't provide support for older updates of the game, and as alpha said most mods have been ported already

**Comment by TPEcool** [comment]
> A lot of the problematic mods need to be reinstalled from the downloads tab of the index, as an update popup will not show for them. A majority of the old mods have been ported and work on 2.206.

I uninstalled every problematic mod (turns out xdBot shows up with the "errors only filter") but now I can't find any of them on the download tab.

**Comment by hiimjustin000** [comment]
If you can't find them on the download tab, that means they haven't been ported yet.

**Comment by TPEcool** [comment]
Follow-up.
Turns out Geode is literally lying.
xdBot has a release for the new GD version for Android32 on its GitHub and it works when installed as a `.geode` file.
Geode still was not showing xdBot on the download tab.

**Comment by hiimjustin000** [comment]
"Geode is literally lying"

It literally isn't. ZiLko hasn't uploaded xdBot to the Geode index at the moment, so that's why it isn't showing on the download tab.

**Comment by Fleeym** [comment]
Big Geode is stealing your mods, wear your tinfoil with pride
