### ISSUE TITLE
Geode crash found after immediately running Geometry Dash 

### ISSUE THREAD

**Issue by MishaSklyar** [geode-sdk/geode#1078]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.6.0

### Mods Installed
== Installed Mods ==
x | [v0.3.3-alpha] alk.allium
x | [v1.8.3] beat.click-sound
! | [v1.0.2] capeling.soggy-mod
! | [v2.0.3] colon.gd_in_2019
x | [v1.0.1] cvolton.level-id-api
x | [v1.6.2] dankmeme.globed2
x | [v1.9.0] firee.prism
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.6.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.1.0] hjfod.backups
! | [v6.7.0] hjfod.betteredit
  | [v1.1.21] syzzi.click_between_frames
x | [v1.6.4] thesillydoggo.qolmod
x | [v7.0.0-beta.14] user95401.mainlevelseditor
~ | [v2.0.0-alpha.4] zilko.xdbot
x | [v1.2.0-beta.1] zmx.cbf-lite

### Steps to Reproduce

1) Use GEFORCE RTX 3060 12 GB
2) INSTALL Geode
3)Run Geometry dash.
4) be seen with a crash

### Crash Report

[2024-09-13_19-25-30.log](https://github.com/user-attachments/files/16996822/2024-09-13_19-25-30.log)

### Additional Information

This is likely caused by The GPU (because of render crash)

**Comment by Alphalaneous** [comment]
Main levels editor crash. Geode update broke something

**Comment by MishaSklyar** [comment]
I think so too, when a launched some level it started doing that, waiting for a patch!

**Comment by MishaSklyar** [comment]
it is still interesting why is it a render crash lol.

**Comment by Mystifyjackk** [comment]
2024-11-01T20:31:40-0500
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.9.0
Loader Commit: bd8387d
Bindings Commit: caeff54
Installed mods: 9
Problems: 2

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: Integrated Demonlist v1.6.3 (hiimjustin000.integrated_demonlist)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 5fe4c (RaiseException + 108)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 57689 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:411)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 2a0ee9 (matjson::Value::as_array + 73 | /home/runner/work/geode/geode/cpm-cache/json/7be1271964142fe09a9ce8136cda20080acc1e08/src/value.hpp:66)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + d2fe
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 121a4
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 12340
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 58b4
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 523c
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 7bb4b (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 154d83 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:275)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 8e5a2 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 6881d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 0000026FF69E4482 (Hook handler)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 0000026F8B181C82 (Hook handler)
 - 0000026F8B181C82 (Hook handler)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 29218a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af08 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000040
RBX: 0000000000000000
RCX: 0000026ff34e0de0
RDX: 0000000000000000
RBP: 0000000000000000
RSP: 000000bd628ffa30
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff950baaf08
R8:  0000000000000004
R9:  0000000000000000
R10: 000000bd628fe269
R11: 0000026ff35b0000
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.4] alphalaneous.click_after_frames
! | [v1.6.2] dankmeme.globed2
x | [v1.7.0] geode.devtools
x | [v3.9.0] geode.loader
x | [v1.15.0] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.6.3] hiimjustin000.integrated_demonlist
! | [v1.2.2] syzzi.click_between_frames
x | [v1.6.10] thesillydoggo.qolmod

**Comment by HenrySck075** [comment]
dementia
