### ISSUE TITLE
Hooking into `PlayLayer` crashes the game

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#108]
### Platform

Windows

### Geode Version

v0.6.1

### Mods Installed

(mods prefixed with my name aren't on the index)

hjfod.devtools | HJfod | v0.0.5 | Enabled | Loaded | 
com.mat.fps-bypass | mat | v1.0.0 | Enabled | Loaded | 
techstudent10.gdtools | TechStudent10 | v1.0.0 | Enabled | Loaded | 
techstudent10.lightning | TechStudent10 | v0.0.1 | Disabled | Unloaded | 
techstudent10.noclip_deaths | TechStudent10 | v1.0.0 | Enabled | Unloaded | 

### Steps to Reproduce

1. Generate a new Geode mod
2. Hook into `PlayLayer::destroyPlayer` and `PlayLayer::update`
3. Launch game

### Crash Report

https://gist.github.com/TechStudent10/097d63b9e7c0d5badd1be119e4219725

### Additional Information

This was caused by own mod. The code for which is:

```cpp
// Imports and all...
class $modify(MyPlayLayer, PlayLayer) {
	int m_deaths;
	bool m_incrementDeaths;
	bool m_isColliding;

	MyPlayLayer() : m_deaths(0), m_incrementDeaths(false), m_isColliding(false) {}

	void destroyPlayer(PlayerObject* playerObject, GameObject* gameObject) {
        if (!m_fields->m_incrementDeaths) {
			m_fields->m_deaths++;
		}
		m_fields->m_isColliding = true;
    }

	void update() {
		if (m_isDead && m_fields->m_isColliding) {
			m_incrementDeaths = false;
		} else {
			m_incrementDeaths = true;
		}
	}
};
```

**Comment by TechStudent10** [comment]
uh hi

**Comment by TechStudent10** [comment]
You didn't provide a solution

**Comment by altalk23** [comment]
you are not using m_fields for m_incrementDeaths, you should be using it

**Comment by TechStudent10** [comment]
> you are not using m_fields for m_incrementDeaths, you should be using it

ah thanks, that was all I was looking for
