### ISSUE TITLE
Geode resetting mod settings after restart

### ISSUE THREAD

**Issue by MishaSklyar** [geode-sdk/geode#1081]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.6.1

### Mods Installed

x | [v0.3.3-alpha] alk.allium
x | [v1.8.3] beat.click-sound
! | [v1.0.2] capeling.soggy-mod
! | [v2.0.3] colon.gd_in_2019
x | [v1.0.1] cvolton.level-id-api
x | [v1.6.2] dankmeme.globed2
x | [v1.9.0] firee.prism
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.6.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.1.0] hjfod.backups
! | [v6.7.0] hjfod.betteredit
  | [v1.1.21] syzzi.click_between_frames
x | [v1.6.4] thesillydoggo.qolmod
x | [v7.0.0-beta.14] user95401.mainlevelseditor
~ | [v2.0.0-alpha.4] zilko.xdbot
x | [v1.2.0-beta.1] zmx.cbf-lite

### Expected Behavior

expected that the settings would save, but they didn't, jukebox thinks im running it the first time. though im not

### Actual Behavior

it just resetted every mod setting except geode

### Steps to Reproduce

1) change something in mod settings (like qolmod)
2) restart and the settings are default

### Additional Information

this is likely caused because of the new update

**Comment by HJfod** [comment]
fixed in 3.7.0
