### ISSUE TITLE
I install geode but button dont show

### ISSUE THREAD

**Issue by BluGitHubXD** [geode-sdk/geode#1085]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta27

### Expected Behavior

![lhgyf](https://github.com/user-attachments/assets/65542c3b-4341-4669-bac1-1e84ce478be3)

### Actual Behavior

![Captura de pantalla 2024-09-16 111138](https://github.com/user-attachments/assets/308845e1-c2c1-469e-83ef-6df592b437dd)

### Steps to Reproduce

I installed geode
Open GD (Steam)
Geode button dont shows itself

**Comment by HenrySck075** [comment]
> 2.0.0-beta.27

?

**Comment by HenrySck075** [comment]
what are you doing there

**Comment by BluGitHubXD** [comment]
what??

**Comment by STGamer24YT** [comment]
> what??

Update Geode to version 3.7.1 (go to the [installation page](https://geode-sdk.org/install) and reinstall it) and update GD to 2.206 if you didn't already do it. If that doesn't work try to disable mods that modify the menu (press shift while opening GD and click "Yes" to enable Safe Mode so you can recognize the mods more easily)

**Comment by BluGitHubXD** [comment]
thanks :)
