### ISSUE TITLE
Load failing on linux

### ISSUE THREAD

**Issue by Explodingcr** [geode-sdk/geode#1090]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.7.1

### Expected Behavior

Geometry Dash launches with Geode activated

### Actual Behavior

Geometry Dash launches and works, but Geode is not active. An error message launches along with Geometry Dash
![Screenshot_20240923_210614](https://github.com/user-attachments/assets/72ca99b3-c430-4dd8-8109-8a6f0aacb5ed)

### Steps to Reproduce

Use the Geode installer on Linux using Proton or Wine
Install Geode
Put recommended DLL overrides from the Geode website into the steam launch options for Geometry Dash
(WINEDLLOVERRIDES="xinput1_4=n,b" %command%)
Launch Geometry Dash

### Additional Information

This was done on Linux, not Windows. There is no Linux option on the platform dropdown menu.
DLL overrides included:
WINEDLLOVERRIDES="xinput1_4=n,b" %command%

**Comment by dankmeme01** [comment]
How is Geometry Dash installed? If you're running it through Steam that is installed via snap, this is a known issue, Geode does not work well because of snap's restrictions

**Comment by Explodingcr** [comment]
Steam isn't installed through snap. Geode used to work pre-2.206.

**Comment by Explodingcr** [comment]
Issue solved on latest version of Geode by renaming the Geode installer to "GeometryDash.exe" and running it through steam, rather than running it through Proton separately.
