### ISSUE TITLE
Geode crashes when i open it

### ISSUE THREAD

**Issue by Niki123G** [geode-sdk/geode#1092]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.7.1

### Mods Installed

== Installed Mods ==
~ | [v1.0.0] alphalaneous.editortab_api
~ | [v1.2.12] alphalaneous.pages_api
~ | [v1.2.10] alphalaneous.projectedstars
~ | [v1.1.7] alphalaneous.random_tab
~ | [v1.8.3] beat.click-sound
~ | [v1.1.0] capeling.colored_level_info_bg
~ | [v1.2.1] capeling.demons_in_garage
~ | [v1.0.1] capeling.garage-stats-menu
~ | [v1.2.1] capeling.icon_profile
~ | [v1.0.4] capeling.startpos_switcher
~ | [v1.0.3] colon.gold_user_coins
~ | [v1.2.3] coopeeo.hideplus
~ | [v4.2.9] cvolton.betterinfo
x | [v1.2.1] cvolton.misc_bugfixes
~ | [v1.6.2] dankmeme.globed2
~ | [v1.3.3-alpha.2] elnexreal.copy_song_id
~ | [v1.0.9] firee.goldenbest
x | [v1.9.1] firee.prism
~ | [v2.11.0] fleym.nongd
~ | [v1.9.0] geode.custom-keybinds
x | [v3.7.1] geode.loader
x | [v1.14.1] geode.node-ids
~ | [v1.4.8] hiimjustin000.fake_rate
~ | [v1.1.0] hjfod.backups
~ | [v6.7.0] hjfod.betteredit
~ | [v1.0.0] hjfod.bettersave_recovery
~ | [v1.3.0] hjfod.gdshare
~ | [v1.2.1] hjfod.gmd-api
~ | [v1.0.0] hjfod.trashcan
~ | [v1.2.1] itzkiba.better_progression
~ | [v1.2.0] itzkiba.grandpa_demon
~ | [v1.3.4] legowiifun.unlisted_objects_in_editor
  | [v1.1.0] mat.song-preview
~ | [v1.0.0-beta.44] minemaker0430.gddp_integration
~ | [v1.0.1] ml5.shopping-list
~ | [v1.3.0-beta.5] ml5.treasure-checklist
~ | [v1.1.2] n.level-pronouns
x | [v1.0.0-alpha.2] sabe.persistenceapi
~ | [v2.1.0] spaghettdev.gd-roulette
~ | [v1.1.0] thesillydoggo.comment_emojis
~ | [v1.2.1] uproxide.autosong
~ | [v1.1.1] xanii.youtubers

### Steps to Reproduce

Open the game on steam or on shortcut

### Crash Report

2024-09-26T18:52:42+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.7.1
Loader Commit: d82a344
Bindings Commit: d42aa7e
Installed mods: 45
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FF7B1A231A2 (GeometryDash.exe + 2a31a2)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2a31a2
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 27221a
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1a2f8 (DS_Dictionary::getObjectForKey + 424)
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 194ca (DS_Dictionary::getArrayForKey + 154)
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 146cb9
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 17dc05
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 69745
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 172bf7
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 80fee
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 7299b (cocos2d::CCApplication::run + 299)
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\Geode.dll + 28ed4a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Users\Korisnik\Downloads\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 000000004173695f
RBX: 0000000000000000
RCX: 0000029951728cc9
RDX: fffffe0a823d64e8
RBP: 0000000000000000
RSP: 000000a3d3affeb0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff8fafaaf28
R8:  0000000000000000
R9:  0000000000000000
R10: 000000002baceb11
R11: 000000a3d3aff1a8
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
~ | [v1.0.0] alphalaneous.editortab_api
~ | [v1.2.12] alphalaneous.pages_api
~ | [v1.2.10] alphalaneous.projectedstars
~ | [v1.1.7] alphalaneous.random_tab
~ | [v1.8.3] beat.click-sound
~ | [v1.1.0] capeling.colored_level_info_bg
~ | [v1.2.1] capeling.demons_in_garage
~ | [v1.0.1] capeling.garage-stats-menu
~ | [v1.2.1] capeling.icon_profile
~ | [v1.0.4] capeling.startpos_switcher
~ | [v1.0.3] colon.gold_user_coins
~ | [v1.2.3] coopeeo.hideplus
~ | [v4.2.9] cvolton.betterinfo
x | [v1.2.1] cvolton.misc_bugfixes
~ | [v1.6.2] dankmeme.globed2
~ | [v1.3.3-alpha.2] elnexreal.copy_song_id
~ | [v1.0.9] firee.goldenbest
x | [v1.9.1] firee.prism
~ | [v2.11.0] fleym.nongd
~ | [v1.9.0] geode.custom-keybinds
x | [v3.7.1] geode.loader
x | [v1.14.1] geode.node-ids
~ | [v1.4.8] hiimjustin000.fake_rate
~ | [v1.1.0] hjfod.backups
~ | [v6.7.0] hjfod.betteredit
~ | [v1.0.0] hjfod.bettersave_recovery
~ | [v1.3.0] hjfod.gdshare
~ | [v1.2.1] hjfod.gmd-api
~ | [v1.0.0] hjfod.trashcan
~ | [v1.2.1] itzkiba.better_progression
~ | [v1.2.0] itzkiba.grandpa_demon
~ | [v1.3.4] legowiifun.unlisted_objects_in_editor
  | [v1.1.0] mat.song-preview
~ | [v1.0.0-beta.44] minemaker0430.gddp_integration
~ | [v1.0.1] ml5.shopping-list
~ | [v1.3.0-beta.5] ml5.treasure-checklist
~ | [v1.1.2] n.level-pronouns
x | [v1.0.0-alpha.2] sabe.persistenceapi
  | [v1.0.1-alpha.3] sabe.platformersaves
~ | [v2.1.0] spaghettdev.gd-roulette
~ | [v1.1.0] thesillydoggo.comment_emojis
  | [v1.2.3] undefined0.autocheckpoint
~ | [v1.2.1] uproxide.autosong
~ | [v1.1.1] xanii.youtubers
  | [v1.0.2] zeozeozeo.zcblive

**Comment by hiimjustin000** [comment]
Data corruption (CCGameManager.dat)

**Comment by Niki123G** [comment]
I replaced the corrupted CCGameManager with one from a geode backup and now the game works
![322170_57](https://github.com/user-attachments/assets/9af22676-d8e5-4e29-b82a-eb9292a73138)
