### ISSUE TITLE
Can't Download Geode On Mac

### ISSUE THREAD

**Issue by HelpICantDownloadGeode** [geode-sdk/geode#1101]
### Your Question

I can't download Geode on Mac, it just comes up with installation failed.

**Comment by HelpICantDownloadGeode** [comment]
When I download the geode-installer-v3.8.1-mac.pkg and try to run it on geometry dash it doesnt work

**Comment by HelpICantDownloadGeode** [comment]
I'm using the geometry dash from the app store btw not steam

**Comment by Alphalaneous** [comment]
The App Store GD is just iOS GD, it has to be the one from Steam

**Comment by HelpICantDownloadGeode** [comment]
seriously

**Comment by HelpICantDownloadGeode** [comment]
bruh

**Comment by HelpICantDownloadGeode** [comment]
well thanks bro
