### ISSUE TITLE
Game crashes on startup on Linux

### ISSUE THREAD

**Issue by keratomalacian** [geode-sdk/geode#1105]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.8.1

### Mods Installed

== Installed Mods ==
x | [v1.4.12] alphalaneous.happy_textures
x | [v1.1.12] b1rtek.gddlintegration
x | [v1.0.7] cdc.level_thumbnails
x | [v1.2.1] cvolton.misc_bugfixes
x | [v0.3.2] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.9.0] geode.custom-keybinds
x | [v3.8.1] geode.loader
x | [v1.14.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.0.0-beta.44] minemaker0430.gddp_integration
x | [v1.2.2] syzzi.click_between_frames
x | [v1.1.0] thesillydoggo.comment_emojis
x | [v1.6.10] thesillydoggo.qolmod
x | [v1.3.0] ziegenhainy.xxlify

### Steps to Reproduce

1) Open the game using Wine version 9.18.
2) During the "verifying loader resources" phase, the game will crash.

### Crash Report

https://pastebin.com/4wvC7Tik

### Additional Information

The game worked fine yesterday, opened it today and now it crashes on the "verifying loader resources" phase. I removed all of the mods and tried opening it, but the exact same thing happened. Tried deleting my save files to see if that was the issue, but that also doesnt fix the problem. Uninstalled and installed geode again, same issue (even though the vanilla game does work without geode). Tried deleting the wineprefix, same thing.

**Comment by keratomalacian** [comment]
alright so i tried running it using Proton through Lutris instead of wine and then it worked fine. so i guess it is an issue with wine itself or with the Arch Linux version of wine. I still think this should be investigated since the vanilla game works fine with wine, so its a geode issue.

**Comment by dankmeme01** [comment]
this should've been fixed a few commits ago, can you try the [nightly build](https://github.com/geode-sdk/geode/actions/runs/11150199003)? see if it works fine there

**Comment by keratomalacian** [comment]
yep. works fine using the nightly build and wine 9.16. closing this now
