### ISSUE TITLE
Building a mod for an older version

### ISSUE THREAD

**Issue by nosleepfor** [geode-sdk/geode#1110]
How can i build a mod for an older version of Geometry Dash (2.204) and Geode (2.0.0-beta.27). I installed sdk for needed Geode version and binaries, but when i try to build it says:

```
  No valid loader binary to link to! Install pre-built binaries with `geode
  sdk install-binaries`, or build Geode from source and add
  `set(GEODE_LINK_NIGHTLY ON)` to your CMakeLists.txt in the line before
  calling add_subdirectory for Geode.
```

Is this a arch linux related issue?

(Sorry for my english)

**Comment by nosleepfor** [comment]
It builds just fine for latest version of geode

**Comment by Fleeym** [comment]
try running `geode sdk install-binaries`

**Comment by nosleepfor** [comment]
> try running `geode sdk install-binaries`

I already did

**Comment by Fleeym** [comment]
Then can you give me the following:

- Output of `geode sdk version`
- Contents of your `Documents\Geode\bin` folder

**Comment by nosleepfor** [comment]
Oh, i fixed it, no need for help anymore, but thanks anyway!
