### ISSUE TITLE
android not updating past 2.00

### ISSUE THREAD

**Issue by Djspac3** [geode-sdk/geode#1116]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-BETA.27

### Expected Behavior

it should update to the newest version?

### Actual Behavior

it just doesnt update past 2.0.0

### Steps to Reproduce

install the android geode and try running it on a 64 bit android

### Additional Information

tried reinstalling geode did the same problem on galaxy tab a8

**Comment by iNUCi** [comment]
This means you are using pirated gd 2.205, if you can't pay for the play store find a pirated gd 2.206

**Comment by Djspac3** [comment]
What im using the google play store for it! 
Ahh forgot update oops

**Comment by Djspac3** [comment]
God I need to update stuff more!
