### ISSUE TITLE
accept mods please someone some day pls god

### ISSUE THREAD

**Issue by user95401** [geode-sdk/geode#1118]
### Geode Version

v3

### Related Problem

# accept mods please
### Your Solution

# accept mods please
### Additional Information

# accept mods please
## https://geode-sdk.org/mods/user95401.jelly_cube?version=1.0.0

**Comment by HJfod** [comment]
* Mod comments is unacceptable due to defining `GEODE_EXPOSE_SECRET_INTERNALS_IN_HEADERS_DO_NOT_DEFINE_PLEASE`
* Platformered Menu Game is unacceptable due to bad metadata (poor description, no icon)
* Robots Bidirectional Rotation is also unacceptable due to bad metadata (poor description, no icon)
* Jelly Cube once again has bad metadata (no icon)

Also this is not the right repo to ask for accepting mods

**Comment by user95401** [comment]
seriously?
every mod here is actually has icon, just you guys return 404 on pending mods

and why the fuck u ever care for description. its even not bad and atleast saying what the mod doin

**Comment by HJfod** [comment]
I wasn't aware of our servers being silly with the icons, sorry about that :(

Good descriptions are important to let people know what the mod does. People shouldn't need to install a mod just to figure out what its point is, the name, description, and tags should give all of that away

**Comment by user95401** [comment]
yes, it's true
but what u should write in description so?
i wrote basic explain of what things mod doing

**Comment by user95401** [comment]
or i just should do aaa
```php
qwerty -> Qwerty
```
?

**Comment by HJfod** [comment]
![image](https://github.com/user-attachments/assets/bf4af6af-a8e7-4682-84f2-861f5f62f00e)
This description is very personally frightened and unsure of what the mod does. Give it some self-confidence, I can't know what a mod does if it doesn't even know itself what it does

![image](https://github.com/user-attachments/assets/bedd35a3-9d16-4edc-bb53-5e2e15d6a67a)
What does this mean? Can't you write at least like one more sentence to clarify what "acts like swing" means? Is this in platformer mode? Normal mode? When is it spinning?

**Comment by user95401** [comment]
Aaaaahhh oke
how about this
# Platformered Menu Game

That mod modify `MenuGameLayer` that being used in `MenuLayer`.
MenuLayer is a 2nd layer that you see when game was just launched.

In `MenuGameLayer::update` method, that calls on every frame, mod freezes background and ground. That can be disabled in settings.

In `MenuGameLayer::tryJump` method, that calls every ~100ms, mod set player object variable that stands for platformer mode. And also randomly changes variables about holding left/right.

Mod have also updating schedule that make player object run away from mouse. It can be disabled in settings.
