### ISSUE TITLE
ccColor4F MacOS Constructor

### ISSUE THREAD

**Issue by at4pm** [geode-sdk/geode#1123]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v3.9.0

### Expected Behavior

Expected to create a ccColor4F using 4 parameters.

e.g. cocos2d::ccColor4F(0, 1, 0, 1); Should produce a green colour.

### Actual Behavior

Constructor error 

### Steps to Reproduce

1. Initialise a ccColor4F using 4 parameters.
2. Build for MacOS.

**Comment by matcool** [comment]
that syntax will only work on msvc, youre supposed to use brace initialization `ccColor4F{ 0, 1, 0, 1 };`
