### ISSUE TITLE
Music desync when lagging 

### ISSUE THREAD

**Issue by Krix1029** [geode-sdk/geode#1129]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

3.9.0

### Mods Installed

Better edit, globed, better info, level thumbnails 

### Expected Behavior

Normal music sync, even when lagging.

### Actual Behavior

Started playing sayitback on normal gd and nothing was wrong. Installed geode and tried playing l, but the moment the games lags Evel a little bit, the music desyncs from the level. Tried save mode, but it only reduced the lag slightly and didn't solve the problem. The issue persists in practice mode, but the music syncs up with the level upon death.

### Steps to Reproduce

Start playing a demanding level, wait for the first lag spike, music gets desynced

### Additional Information

Android 14 Xiaomi poco F5 8gb ram

**Comment by Quelnan** [comment]
That is Geometry Dash bug itself. (im not spam bot my acc is new cuz i lost old acc)
