### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by GiveMeFox** [geode-sdk/geode#1141]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.9.0

### Expected Behavior

for geode to load

### Actual Behavior

![image](https://github.com/user-attachments/assets/f9b5fbaa-848e-41e8-a918-841493f3776b)

### Steps to Reproduce

launch gd

**Comment by Alphalaneous** [comment]
Gonna blow your mind. When you read, you can figure out what the issue is.

**Comment by Alphalaneous** [comment]
(2.207 came out)

**Comment by GiveMeFox** [comment]
> (2.207 came out)


damn

**Comment by HJfod** [comment]
@heavyutils We are obviously working on updating Geode to 2.207, we just don't want a bunch of issues about it clogging up our bug tracker.
