### ISSUE TITLE
geode doesnt work

### ISSUE THREAD

**Issue by Shcraftee** [geode-sdk/geode#1154]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.9.0

### Mods Installed

abb2k.custom_icon_size
alphalaneous.awesome_modifier_icons
alphalaneous.editorsounds
alphalaneous.improved_group_view
alphalaneous.improvedlink
cdc.level_thumbnails
cvolton.betterinfo
cvolton.level-id-api
cvolton.misc_bugfixes
dankmeme.globed2
elnexreal.copy_song_id
firee.prism
geode.custom-keybinds
geode.devtools
geode.node-ids
hjfod.backups
hjfod.betteredit
hjfod.gmd-api
hjfod.trashcan
itzkiba.better_progression
itzkiba.grandpa_demon
ml5.shopping-list
rynat.better_unlock_info
shineua.geometrize2gd
techstudent10.settings_plus
thesillydoggo.comment_emojis
thesillydoggo.icon_kit_switcher
thesillydoggo.qolmod
undefined0.editormusic
user95401.mainlevelseditor
weebify.separate_dual_icons
zilko.platformer_ghosts

### Steps to Reproduce

this one time i booted it up and it said "Geode is running in a newer version of GD than Geode targets". and it dooes not let me use my mods, pls help :(

### Crash Report

log: https://pastebin.com/gsCA1srk
crashlog: https://pastebin.com/Le5T0LQh

**Comment by iNUCi** [comment]
this is because of GD 2.207. wait for geode to update
