### ISSUE TITLE
some mods don't work

### ISSUE THREAD

**Issue by Limakruzam2** [geode-sdk/geode#1163]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.0.0-beta.1

### Mods Installed

betterinfo, death tracker are not working, because some other mode failed to load

### Expected Behavior

i wish you would fix it

### Actual Behavior

mods are not working

### Steps to Reproduce

1) for example install betterinfo
2) restart the game
3) Geode says:" there were errors loading some mods"

**Comment by matcool** [comment]
learn how to read
