### ISSUE TITLE
Geode keeps crashing the game

### ISSUE THREAD

**Issue by AndyMan34Git** [geode-sdk/geode#1166]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.0.0

### Mods Installed

~ | [v8.0.3] absolllute.megahack
~ | [v1.1.3] adam_729.deathmarkers
x | [v1.1.8] adyagd.godlikefaces
x | [v1.0.4] alphalaneous.awesome_modifier_icons
x | [v1.0.7] alphalaneous.editortab_api
x | [v1.0.8] alphalaneous.improved_group_view
x | [v1.0.9] alphalaneous.improvedlink
x | [v1.3.0] alphalaneous_raydeeux.changefont19
~ | [v1.0.0] bigmancozmo.skip_editor_save_confirm
  | [v1.0.0] bingy3.enter_submit
~ | [v1.0.5] bitz.moregames
~ | [v1.1.0] capeling.colored_level_info_bg
~ | [v1.0.5] capeling.gamemode_picker
~ | [v1.2.1] capeling.icon_profile
~ | [v1.1.3] capeling.main_level_pages
x | [v1.0.8] cdc.level_thumbnails
~ | [v1.0.1] cdc.statuses
~ | [v1.0.1] coderqc.gdswearfilter
~ | [v1.0.3] colon.gold_user_coins
x | [v4.3.0-beta.2] cvolton.betterinfo
x | [v1.1.0] cvolton.level-id-api
x | [v1.3.0] cvolton.misc_bugfixes
~ | [v1.6.2] dankmeme.globed2
~ | [v1.3.1] elsai.a_daily_shop
x | [v1.0.11] firee.goldenbest
x | [v1.4.0-beta.1] gdutilsdevs.gdutils
x | [v1.10.0] geode.custom-keybinds
x | [v1.8.0] geode.devtools
x | [v4.0.0] geode.loader
x | [v1.17.0] geode.node-ids
x | [v1.3.1] hiimjustin000.demons_in_between
x | [v1.4.10] hiimjustin000.fake_rate
x | [v1.2.2] hiimjustin000.level_size
x | [v1.2.0] hjfod.backups
x | [v6.9.1] hjfod.betteredit
~ | [v1.0.0] hjfod.bettersave_recovery
x | [v1.4.1] hjfod.gdshare
x | [v1.4.1] hjfod.gmd-api
x | [v1.1.0] hjfod.trashcan
~ | [v1.2.1] itzkiba.better_progression
~ | [v1.2.0] itzkiba.grandpa_demon
~ | [v1.1.0] itzkiba.id_hyperlinks
x | [v1.2.0-beta.3] jouca.badgesapi
x | [v1.3.5] legowiifun.unlisted_objects_in_editor
~ | [v1.0.4] mat.max-window
x | [v1.1.1] mat.reference-image
~ | [v1.3.0] nytelyte.wave_trail_drag_fix
~ | [v1.2.0] petitfrapo.nomoregrayfilter
x | [v1.6.1] prevter.bettercrash
x | [v1.3.0] raydeeux.camerashadertoggles
x | [v1.4.2] raydeeux.endscreentweaks
~ | [v1.0.1] relative.advanced_song_search
~ | [v1.2.2] shineua.geometrize2gd
~ | [v1.1.1] sofabeddd.geometry_dash
~ | [v1.2.2] syzzi.click_between_frames
~ | [v1.1.0] techstudent10.settings_plus
~ | [v1.1.0] thesillydoggo.comment_emojis
~ | [v1.6.8] tpdea.betterpause-Better
~ | [v1.0.0] uproxide.accupracatt
x | [v1.7.1] uproxide.more_difficulties
~ | [v1.1.1] xanii.youtubers
x | [v1.3.1] ziegenhainy.xxlify

### Steps to Reproduce

some things that i did that crashed the game:
1. search for levels
2. open my saved levels
3. try to load the nex even level

### Crash Report

https://pastebin.com/WMYS4UDh
https://pastebin.com/iMPBGQ9Y

### Additional Information

no idea why this happened

**Comment by AndyMan34Git** [comment]
i dont actually know if its geode or a mod tbh

**Comment by hiimjustin000** [comment]
Forward this to https://github.com/Uproxide/more-difficulties, then close this issue

**Comment by AndyMan34Git** [comment]
> Forward this to https://github.com/Uproxide/more-difficulties, then close this issue

how do i forward

**Comment by hiimjustin000** [comment]
@AndyMan34Git make a new issue there, then close the issue here (click "close with comment")

**Comment by AndyMan34Git** [comment]
> @AndyMan34Git make a new issue there, then close the issue here (click "close with comment")

ok
