### ISSUE TITLE
Infinite mods list everywhere

### ISSUE THREAD

**Issue by BouncingBallisAFK** [geode-sdk/geode#1167]
### Geode Version

V4.X.X

### Your Solution

I would really like it if you made it so that you make the mods lists in featured, download, recent, and others be infinite as well as installed.

**Comment by iNUCi** [comment]
did you know that this is actually already added. In geode settings, the option is called "expand installed mods list"

**Comment by BouncingBallisAFK** [comment]
Oh makes sense andriodd would explode if you did that
