### ISSUE TITLE
game crashes when opening the geode mod menu

### ISSUE THREAD

**Issue by octopuswindow** [geode-sdk/geode#117]
### Platform

MacOS

### Geode Version

0.6.1

### Steps to Reproduce

Open geometry dash, open the geode menu, press check for updates, popup appears saying "index appears to not have been downloaded, or is fully empty", exit the geode menu and when you enter the menu next time it crashes.

### Crash Report

https://pastebin.com/5RM5UWxK

**Comment by HJfod** [comment]
The index was recently updated and is currently incompatible with v0.6.1, update to v1.0.0-beta and see if that helps.

**Comment by altalk23** [comment]
Can you please try it on the latest geode version? You may need to manually update it.
