### ISSUE TITLE
Geode and gd crashes after switching from vga to hdmi cables on gpu

### ISSUE THREAD

**Issue by godlycorridor** [geode-sdk/geode#1176]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.0.1

### Mods Installed

no mods

### Steps to Reproduce

i open gd and it crashes

### Crash Report

2024-11-25T09:19:11-0800
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v4.0.1
Loader Commit: ed97f3b
Bindings Commit: e30b176
Installed mods: 1
Outdated mods: 0
Problems: 0

== Exception Information ==
Faulty Module: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll
Faulty Mod: <Unknown>
Exception Code: c000001d (EXCEPTION_ILLEGAL_INSTRUCTION)
Exception Flags: 0
Exception Address: 00007FF9BF5E99A3 (nvoglv64.dll + 9c99a3)
Number Parameters: 0
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + 9c99a3
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + 9c6db9
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + 74d78c
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + 74af82
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + a590f5
 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035\nvoglv64.dll + 9bc1cf (DrvValidateVersion + 47)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 21445
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 218a8
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 23f5c
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3f530
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 40551 (wglDescribePixelFormat + 241)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3f953 (wglChoosePixelFormat + 99)
 - C:\WINDOWS\System32\gdi32full.dll + 6a089 (ChoosePixelFormat + 57)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + daa00
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + d3fc8
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + d21fc
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + 769f2 (cocos2d::CCEGLView::setupWindow + 66)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + 75a01 (cocos2d::CCEGLView::initWithRect + 241)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + 757f6 (cocos2d::CCEGLView::initWithFullScreen + 262)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + 74fa9 (cocos2d::CCEGLView::createWithFullScreen + 89)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\GeometryDash.exe + 827f0
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\libcocos2d.dll + 7290b (cocos2d::CCApplication::run + 299)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\GeometryDash.exe + 4b6e32
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\Geode.dll + 2402ad (gdMainHook + 557 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Users\???\Desktop\games\GD_2.2074_windows_vanilla\GeometryDash.exe + 4b821a
 - C:\WINDOWS\System32\KERNEL32.DLL + 17374 (BaseThreadInitThunk + 20)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 4cc91 (RtlUserThreadStart + 33)

== Register States ==
RAX: 0000000000000001
RBX: 0000000000000000
RCX: 0000000000000001
RDX: 000001e6a5542ba0
RBP: 0000000000000000
RSP: 0000004126aff8a0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffa0d99cc91
R8:  0000000000000001
R9:  000001e6a5542b80
R10: 0000000000000001
R11: 0000000000000003
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v4.0.1] geode.loader

### Additional Information

how to fix

**Comment by dankmeme01** [comment]
is this a geode-specific issue? does it not happen in vanilla GD?

**Comment by godlycorridor** [comment]
i already fixed the issue just had to install a older nvidia driver
