### ISSUE TITLE
Geode se crashea en editor

### ISSUE THREAD

**Issue by Diegodashthepro** [geode-sdk/geode#1177]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

ed97f3b

### Geode Version

4.0.1

### Expected Behavior

al morir en el editor no pasa nada

### Actual Behavior

al morir en el editor se crashea

### Steps to Reproduce

1:inicio el playtest 2:choco con un bloque 3: se crashea

**Comment by STGamer24YT** [comment]
Tienes algún mod instalado? Es posible que el crasheo sea causado por algún mod que tengas instalado
Aunque no se como instalar la versión que tienes así que es posible que si haya sido un bug de Geode.
Espero que esto sea útil
