### ISSUE TITLE
Geode shows an error, but when I check it; it comes up with nothing.

### ISSUE THREAD

**Issue by MoonstarMaster** [geode-sdk/geode#1179]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.0.1

### Mods Installed

x | [v1.0.5] abb2k.custom_icon_size
x | [v1.0.3] abb2k.duration_filter
  | [v1.0.7] absolllute.installer
* | [v1.0.0] aceinet.level_edit
x | [v1.1.8] adyagd.godlikefaces
* | [v0.3.3-alpha] alk.allium
x | [v1.2.0] alphadev.custom_profile_image
x | [v1.0.6] alphalaneous.awesome_modifier_icons
x | [v1.0.5] alphalaneous.click_after_frames
x | [v1.0.7] alphalaneous.editortab_api
* | [v1.1.5] alphalaneous.ezclipboard
x | [v1.1.1] alphalaneous.fine_outline
x | [v1.6.3] alphalaneous.happy_textures
x | [v1.0.8] alphalaneous.improved_group_view
x | [v1.0.11] alphalaneous.improvedlink
* | [v1.0.1] alphalaneous.is_it_sent
x | [v1.0.2] alphalaneous.level_info_backgrounds
x | [v1.0.2] alphalaneous.moddevbranding
x | [v1.1.4] alphalaneous.object_summary
x | [v1.3.2] alphalaneous.pages_api
x | [v1.2.11] alphalaneous.projectedstars
x | [v1.0.1] alphalaneous.quick_search_backgrounds
x | [v1.0.1] alphalaneous.rainbow_checkpoints
x | [v1.0.10] alphalaneous.relocate_build_tools
  | [v1.0.2] alphalaneous.responsive_closing
x | [v1.0.4] alphalaneous.vanilla_pages
x | [v1.0.1] alphalaneous.volume_input
* | [v1.0.0] ata.100_life_challenge
* | [v1.1.0] ata.cat
* | [v1.0.4] ata.completions
* | [v1.8.3] beat.click-sound
x | [v1.1.3-alpha.1] bitz.customprofiles
* | [v1.0.5] bitz.darkmode_v4
* | [v1.0.0] bitz.fakegdmod
x | [v1.2.6] blueblock6.cleanstartpos
  | [v1.0.4] blueblock6.transparent_checkpoints
* | [v1.1.0] bobby_shmurner.zoom
* | [v1.0.0] bry400.no_block_glow
* | [v1.1.1] camila314.text-select
* | [v1.2.1] capeling.demons_in_garage
* | [v1.0.1] capeling.garage-stats-menu
x | [v1.0.6] capeling.startpos_switcher
x | [v1.0.8] cdc.level_thumbnails
* | [v1.4.1] cgytrus.menu-shaders
* | [v1.0.3] colon.gold_user_coins
x | [v1.5.5] coopeeo.customname
x | [v4.3.0-beta.4] cvolton.betterinfo
x | [v1.2.0] cvolton.compact_lists
x | [v1.1.0] cvolton.level-id-api
x | [v1.3.0] cvolton.misc_bugfixes
x | [v1.7.1] dankmeme.globed2
* | [v1.0.2] dasshu.gauntletredesign
* | [v1.2.1] deaen.underdash
* | [v1.1.0] dogotrigger.level_history
* | [v1.1.6] dogotrigger.roulette
* | [v1.0.4] dogotrigger.triggersearch
x | [v1.0.0-beta.4] eclipse.eclipse-menu
x | [v1.1.2] eclipse.ffmpeg-api
* | [v1.3.3-alpha.2] elnexreal.copy_song_id
x | [v2.4.3] elohmrow.death_tracker
* | [v1.0.1] fig.authentication
x | [v1.0.11] firee.goldenbest
x | [v1.4.3] firee.object-workshop
x | [v1.1.2] firee.overchargedlevels
  | [v1.9.5] firee.prism
* | [v0.3.2] flafy.autonong
x | [v3.0.1] fleym.nongd
x | [v1.4.0-beta.4] gdutilsdevs.gdutils
x | [v1.10.0] geode.custom-keybinds
x | [v1.8.0] geode.devtools
x | [v4.0.1] geode.loader
x | [v1.18.0] geode.node-ids
x | [v1.6.6] geode.texture-loader
x | [v1.3.1] grian.art_importer
x | [v1.4.4] hiimjustin000.better_icon_randomizer
x | [v1.1.2] hiimjustin000.better_safe
  | [v1.4.5] hiimjustin000.demons_in_between
x | [v1.0.3] hiimjustin000.developer_badges
x | [v1.4.10] hiimjustin000.fake_rate
x | [v1.0.3] hiimjustin000.gauntlet_projection
x | [v2.0.0] hiimjustin000.icon_randomizer_api
  | [v1.0.2] hiimjustin000.level_info_colors
x | [v1.5.0] hiimjustin000.more_icons
* | [v1.0.2] hiimjustin000.more_icons_api
  | [v1.0.12] hiimjustin000.more_object_info
x | [v1.1.1] hiimjustin000.search_history
x | [v1.2.0] hjfod.backups
x | [v6.9.2] hjfod.betteredit
* | [v1.0.0] hjfod.bettersave_recovery
x | [v1.4.1] hjfod.gdshare
x | [v1.4.1] hjfod.gmd-api
x | [v1.1.0] hjfod.trashcan
x | [v1.1.0] iandyhd3.autosort_lists
  | [v1.2.0] iandyhd3.known_players
x | [v1.0.4] iswilljr.enter-search
x | [v1.3.0] itzkiba.better_progression
* | [v1.2.0] itzkiba.grandpa_demon
  | [v1.2.1] jojo989.main_menu_bg_customizer
x | [v1.2.0] jouca.badgesapi
x | [v1.2.2] khronophobia.inputs_viewer
* | [v1.2.1] khronophobia.shortcuts_menu
  | [v1.2.4] kittenchilly.randomize_icon_on_death
x | [v1.0.2] km7dev.audio-offset
x | [v1.3.5] legowiifun.unlisted_objects_in_editor
  | [v1.0.5] lilnibblit.chestalert
x | [v1.2.3] limegradient.betterachievements
* | [v1.0.0] limegradient.dashify
x | [v1.2.0] m336.autoleaderboard
  | [v1.3.9] m336.levelinfo
x | [v1.1.1] m336.modbadgeinfo
x | [v1.0.1] mariomastr.progress_of_editor_levels
x | [v1.2.1] mat.circle-tool
x | [v1.1.1] mat.reference-image
x | [v1.2.3] mat.run-info
x | [v1.1.1] mat.song-preview
* | [v1.1.0] midair.fullscreen_keybind
x | [v1.1.3] mishpro.comments_in_pause_menu
x | [v1.5.0] ml5.treasure-checklist
* | [v1.0.0] moonstarmaster.eh
x | [v1.1.0] moonstarmaster.hamstermod
* | [v1.0.0] moonstarmaster.test
x | [v3.2.1-alpha.1] naxrin.garage_in_editor
* | [v2.1.1] naxrin.rgb_icons
  | [v1.2.0] ninkaz.blending_glow
x | [v1.0.4] ninkaz.colorful-icons
x | [v1.0.4] ninsam.to-do_list
* | [v1.0.1] ninxout.more_level_options
* | [v1.1.3] ninxout.redash
* | [v2.1.2] omgrod.garage_plus
  | [v1.5.2] omgrod.geodify
* | [v1.2.0] petitfrapo.nomoregrayfilter
  | [v1.2.3] raydeeux.109780665
x | [v1.0.1] raydeeux.alertlayertweaks
x | [v1.4.3] raydeeux.deathscreentweaks
x | [v1.0.3] raydeeux.gameobjectidstacksize
x | [v1.3.0] raydeeux.pausemenuloop
x | [v1.0.1] raydeeux.revisedlevelcells
x | [v1.0.0] raydeeux.xeroxedhalloffame
x | [v1.0.1] raydeeux_limegradient.warbledcompletions
x | [v1.1.2] raydeeux_thesillydoggo.decimalpercentages
  | [v0.2.0] rooot.custom-gamemode-colors
* | [v1.1.7] rynat.better_unlock_info
* | [v1.0.0-alpha.2] sabe.persistenceapi
* | [v1.0.1-alpha.3] sabe.platformersaves
* | [v1.1.6] sawblade.song_trash_can
* | [v1.2.2] shineua.geometrize2gd
* | [v1.1.1] sofabeddd.geometry_dash
x | [v1.1.3] sorkopiko.dailystreak
x | [v1.0.2] sorkopiko.saveretry
  | [v1.3.0] syzzi.click_between_frames
  | [v3.0.1] techstudent10.discord_rich_presence
* | [v1.2.0] techstudent10.settings_plus
* | [v2.0.1] thesillydoggo.animatedprofiles
* | [v1.1.0] thesillydoggo.comment_emojis
* | [v2.3.1] thesillydoggo.gradientpages
* | [v1.0.4] thesillydoggo.icon_kit_switcher
* | [v1.0.0-beta.1] thesillydoggo.newgrounds_explorer
x | [v1.7.5-beta.6] thesillydoggo.qolmod
  | [v1.2.9] timestepyt.deltarune_textboxes
* | [v1.2.3] undefined0.autocheckpoint
* | [v1.0.5] undefined0.buttoneasing
x | [v1.1.1] undefined0.icon_ninja
x | [v1.1.2] uproxide.animated_fire
x | [v1.7.3] uproxide.more_difficulties
x | [v1.3.5] uproxide.textures
* | [v1.1.2] user95401.geode-mod-comments
* | [v1.1.1] vinsterplays.music_integrations
x | [v1.2.0] weebify.coins_in_pause_menu
* | [v1.0.4] weebify.congregation_jumpscare
* | [v1.0.2] weebify.disable_black_glow
* | [v1.0.0] weebify.index_modder_points
* | [v1.3.3] weebify.jumpscare
x | [v1.1.0] weebify.level_info_in_pause_menu
x | [v1.2.1] weebify.restartbtn
x | [v1.3.0] weebify.separate_dual_icons
* | [v22.0.60] weebify.st2_wallpaper
* | [v1.0.0] windows_20.clearhack
* | [v1.0.0] xanii.auto_music_sync
* | [v1.1.1] xanii.youtubers
* | [v1.1.1] yellowcat98.totem_of_undying
x | [v1.1.1] zilko.platformer_ghosts
  | [v2.1.2] zilko.xdbot

### Expected Behavior

Showing the faulty mod

### Actual Behavior

Coming up with nothing, despite it saying there's an error

![Screenshot 2024-11-28 15-15-42](https://github.com/user-attachments/assets/263ad3b1-e372-443b-9fec-5548128d0c31)

### Steps to Reproduce

I am unsure how to reproduce

**Comment by hiimjustin000** [comment]
@MoonstarMaster Send me the log C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\logs

**Comment by MoonstarMaster** [comment]
> @MoonstarMaster Send me the log C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\logs

[Geode 2024-11-28 14.28.31.log](https://github.com/user-attachments/files/17952588/Geode.2024-11-28.14.28.31.log)

**Comment by hiimjustin000** [comment]
```
14:28:31 ERROR [Main] [Geode]:           Failed to queue: "C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\mods\moonstarmaster.alt test.geode" - [[moonstarmaster.alt test/v1.0.0/mod.json].id]: json value is not [a-z0-9\-_]+\.[a-z0-9\-_]+
```
You can't have spaces in your mod ID

**Comment by MoonstarMaster** [comment]
> ```
> 14:28:31 ERROR [Main] [Geode]:           Failed to queue: "C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\mods\moonstarmaster.alt test.geode" - [[moonstarmaster.alt test/v1.0.0/mod.json].id]: json value is not [a-z0-9\-_]+\.[a-z0-9\-_]+
> ```
> 
> You can't have spaces in your mod ID

I've uninstalled this mod and this happens, though

**Comment by hiimjustin000** [comment]
Okay now close issue
