### ISSUE TITLE
editorcollab broke geode

### ISSUE THREAD

**Issue by KontrollFreek** [geode-sdk/geode#118]
### Platform

Windows

### Geode Version

v1.0.0-beta

### Mods Installed

alk.editorcollab v1.4.0-beta
geode.devtools v1.0.0

### Steps to Reproduce

\>Open the game
error
\>click the non-textures geode button
error and crash

### Crash Report

2023-01-24T22:00:35-0500
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.0.0-beta
Installed mods: 2
Failed mods: 1

== Exception Information ==
Faulty Module: C:\Users\Ki\Downloads\CastersGDPS\Geode.dll
Faulty Mod: <Unknown>
Exception Code: 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 7973AAB7 (Geode.dll + 0xfaab7)
Number Parameters: 2

== Register States ==
EAX: 0
EBX: 0xefe62c
ECX: 0
EDX: 0
EBP: 0xefe5b4
ESP: 0xefe5ac
EDI: 0xefe5f0
ESI: 0xd7cac28
EIP: 0x7973aab7

== Stack Trace ==
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xfaab7
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xf97f3
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x1015a6
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x103c84
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x103a9b
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xfd2b7
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x17b200
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x17c21b
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x17bea7
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x17b05a
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x17ac69
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xfd6cc
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xfc067
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xfb634
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xf93cf
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xf8f4e
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xf8b82
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0xd987b
 - C:\Users\Ki\Downloads\CastersGDPS\Geode.dll + 0x148a19
 - C:\Users\Ki\Downloads\CastersGDPS\Catsters GDPS.exe + 0x23394
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xaaf1d
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xf5919
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xbb37c
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xc4046
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xc406e
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0x111b29
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0x113679
 - C:\WINDOWS\System32\USER32.dll + 0x4148b
 - C:\WINDOWS\System32\USER32.dll + 0x3844a
 - C:\WINDOWS\System32\USER32.dll + 0x37b27
 - C:\WINDOWS\System32\USER32.dll + 0x35ccb
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 0x4696f
 - C:\WINDOWS\System32\USER32.dll + 0x4148b
 - C:\WINDOWS\System32\USER32.dll + 0x3844a
 - C:\WINDOWS\System32\USER32.dll + 0x361ba
 - C:\WINDOWS\System32\USER32.dll + 0x35f80
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0x1122d2
 - C:\Users\Ki\Downloads\CastersGDPS\libcocos2d.dll + 0xc190b
 - C:\Users\Ki\Downloads\CastersGDPS\Catsters GDPS.exe + 0x261175
 - C:\Users\Ki\Downloads\CastersGDPS\Catsters GDPS.exe + 0x2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 0x200f9
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67bbe
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67b8e

== Installed Mods ==
alk.editorcollab | alk | v1.4.0-beta | Enabled | Unloaded | 
geode.devtools | Geode Team | v1.0.0 | Enabled | Unloaded |

**Comment by HJfod** [comment]
If you're missing textures, the crash is because of that. We've fixed resource downloading in a4188283943dc4556868de7b5041cd4295925134, which should get released as `v1.0.0-beta1` / `v1.0.0-beta` later today. You can try manually downloading resources for now.
