### ISSUE TITLE
Geode fails to install on pirated version of GD

### ISSUE THREAD

**Issue by Doominator1** [geode-sdk/geode#1181]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v4.0.1

### Expected Behavior

The installation is successful.

### Actual Behavior

Geode failed to install.

### Steps to Reproduce

Install Geode on any 2.2074 pirated version of GD.

### Additional Information

I did buy GD on steam but I only use a pirated version because I don't want to wait forever for steam to load with every launch.
My mac is an Apple silicone M2.
Geode v3.9.3 installs without any problems to 2.206 (pirated version), but v4.0.1 fails to install on 2.2074 (pirated version).
Geode does install successfully on the official steam version.
No error code is provided.

**Comment by Doominator1** [comment]
Before you call me poor, read the text I DID BUY REAL GD.

**Comment by iNUCi** [comment]
sorry for off topic but where did you find pirated 2.2074 for mac?

**Comment by Doominator1** [comment]
> sorry for off topic but where did you find pirated 2.2074 for mac?

Ofcourse u want it...

**Comment by iNUCi** [comment]
> Ofcourse u want it...

nah i have it on steam too, but i once found a crack of gd for mac that had a weird file layout inside which is why geode might be failing to install

**Comment by Lilicogamer13** [comment]
> Does anyone have any solution, I see the comments have been deleted (for good reason.)

remember, the 2.2074 from archive.org is actully 2.2073

**Comment by Fleeym** [comment]
locking this for obvious reasons
