### ISSUE TITLE
Geode is not loads

### ISSUE THREAD

**Issue by AlekseyShvartsGD** [geode-sdk/geode#1188]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

j2pa4kr

### Geode Version

v4.0.0

### Mods Installed

texture loader v1.0.0.

### Expected Behavior

expected when geode button showing with linux by using Wine

### Actual Behavior

geode button not showing

### Steps to Reproduce

1) i installed the geode
2) i open geometry dash and geode button was not showing

### Additional Information

this is likely not showing button because not supporting geode linux with Wine

**Comment by iNUCi** [comment]
you have to add wine dll override for xinput1_4

**Comment by matcool** [comment]
read the instructions on the website, reopen if still broken
