### ISSUE TITLE
error LNK2019: reference to an unresolved external character ‘__declspec(dllimport) void __cdecl geode::log::vlogIm

### ISSUE THREAD

**Issue by hruzdishe** [geode-sdk/geode#1192]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

4.1.0

### Expected Behavior

build mod

### Actual Behavior

I create a new project and try to compile without changes. The latest version of SDK and CLI are used. 

error LNK2019: reference to an unresolved external character ‘__declspec(dllimport) void __cdecl geode::log::vlogIm
pl(struct geode::Severity,class geode::Mod *,class fmt::v10::basic_string_view<char>,class fmt::v10::basic_format_args<
class fmt::v10::basic_format_context<class fmt::v10::appender,char> >)’ (__imp_?vlogImpl@log@geode@@@YAXUSeverity@2@PEAV
Mod@2@V?$basic_string_view@D@v10@fmt@@@V?$basic_format_args@V?$basic_format_context@Vappender@v10@fmt@@@D@v10@fmt@@@@@@67@@@@@Z
) in the function ‘public: virtual void __cdecl geode::modifier::ModifyDerive<struct MyMenuLayer,class MenuLayer>::apply(void
)’ (?apply@?$ModifyDerive@UMyMenuLayer@@@VMenuLayer@@@@@modifier@geode@@@UEAAXXZ).

### Steps to Reproduce

idk

**Comment by matcool** [comment]
cant repro
