### ISSUE TITLE
Geode is redefining Cocoa's "CommentType", and messing up MacOS!!!

### ISSUE THREAD

**Issue by FireDasher** [geode-sdk/geode#1198]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

4.1.1

### Steps to Reproduce

compile custom key binds for macOS

### What is happening

Some stupid Script.h thing is getting messed up because Geode is redefining CommentType but Script.h uses Cocoa's CommentType, which Geode deleted and replaced with GD's CommentType. And Script.h is an internal Mac thing so I can't modify it.

**Comment by qimiko** [comment]
the easy solution is just to 
```c++
#define CommentType CommentTypeDummy

// your macos specific includes here

#undef CommentType
```
i think there's been attempts to avoid it but it basically just does the same thing as this (but this actually works and those attempts... don't)
