### ISSUE TITLE
crash after respawn in editor

### ISSUE THREAD

**Issue by mottyan1991** [geode-sdk/geode#1199]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.1.1

### Mods Installed

== Installed Mods ==
x | [v1.0.9] beat.click_sounds_lite
x | [v1.0.0-beta.4] eclipse.eclipse-menu
x | [v1.1.2] eclipse.ffmpeg-api
x | [v3.0.0-beta.11] fig.zbot
  | [v1.9.5] firee.prism
x | [v1.10.1] geode.custom-keybinds
x | [v4.1.1] geode.loader
x | [v1.18.0] geode.node-ids
x | [v1.6.7] geode.texture-loader
x | [v1.4.1] hjfod.gmd-api
x | [v1.0.5] mat.max-window
  | [v1.0.0-beta.1] rainixgd.geome3dash
x | [v1.7.7] thesillydoggo.qolmod
x | [v4.9.0-beta.1] tobyadd.gdh
x | [v1.0.4] zeozeozeo.zcblive
x | [v2.2.4] zilko.xdbot

### Steps to Reproduce

Die in editor

### Crash Report

2024-12-22T12:43:31+0900
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v4.1.1
Loader Commit: e558bd3
Bindings Commit: 93441dc
Installed mods: 16
Outdated mods: 0
Problems: 0

== Exception Information ==
Faulty Module: Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FF7241E1BB8 (GeometryDash.exe + 221bb8)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 221bb8
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 2131bf
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 213321
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 232a32
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 2c64ab
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 459fc
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1399db
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1399db
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 640e0
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\zeozeozeo.zcblive\zeozeozeo.zcblive.dll + 40666d
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\zeozeozeo.zcblive\zeozeozeo.zcblive.dll + 3f2641
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\tobyadd.gdh\tobyadd.gdh.dll + 10bcab
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\tobyadd.gdh\tobyadd.gdh.dll + 64e4b
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\fig.zbot\fig.zbot.dll + 1728cb
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 31765b
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 31765b
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 2c64ab
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 2c64ab
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 9de6d
 - 000001357F227082 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 2d036a
 - 000001357F60F882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\tobyadd.gdh\tobyadd.gdh.dll + 10c76b
 - 000001357F60F882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 31c68b
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + e84cd
 - 000001357F60F882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\libcocos2d.dll + c0919 (cocos2d::CCTimer::update + 105)
 - Z:\Geometry.Dash.v2024.11.12\libcocos2d.dll + c078b (cocos2d::CCScheduler::update + 267)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 10b882
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - 000001357F224882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\libcocos2d.dll + bbf14 (cocos2d::CCDirector::drawScene + 36)
 - 000001350B11A882 (Hook handler)
 - 000001350B11A882 (Hook handler)
 - Z:\Geometry.Dash.v2024.11.12\libcocos2d.dll + bc62b
 - Z:\Geometry.Dash.v2024.11.12\libcocos2d.dll + 72c42 (cocos2d::CCApplication::run + 1122)
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 4b6e32
 - Z:\Geometry.Dash.v2024.11.12\Geode.dll + 24433d (gdMainHook + 557 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - Z:\Geometry.Dash.v2024.11.12\GeometryDash.exe + 4b821a
 - C:\WINDOWS\System32\KERNEL32.DLL + 2dbe7 (BaseThreadInitThunk + 23)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + dfbec (RtlUserThreadStart + 44)

== Register States ==
RAX: 0000013547db5570
RBX: 0000000000000000
RCX: 88073e00acd5317c
RDX: 0000000000000000
RBP: 0000000000000000
RSP: 000000077b2ffa90
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffa5783fbec
R8:  0000013547db5570
R9:  00000135453e86f0
R10: 000001355b2d65b0
R11: 000001355c564020
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

### Additional Information

idk its loader problem?

**Comment by Prevter** [comment]
zbot and also physics bypass in eclipse if you have that enabled
