### ISSUE TITLE
where do i put the resources file

### ISSUE THREAD

**Issue by octopuswindow** [geode-sdk/geode#120]
### Your Question

i updated Geode to 1.0 and it tells me that i have to put a resource file somewhere in the geometry dash folder but it doesn't specify where. where am i supposed to put it?

**Comment by TechStudent10** [comment]
`GD Directory` is wherever your GD install is (so probably in your `steamapps` folder)

**Comment by HJfod** [comment]
The directory is `<GD Directory>/geode/resources/geode.loader`. A new release should be coming soon that automatically downloads the resources there

**Comment by octopuswindow** [comment]
> The directory is `<GD Directory>/geode/resources/geode.loader`. A new release should be coming soon that automatically downloads the resources there

i think i put them in that directory but it still says that it's missing the resources.
