### ISSUE TITLE
geode wont work running steam via whisky

### ISSUE THREAD

**Issue by mozibites** [geode-sdk/geode#1201]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

4.1.1 (latest)

### Mods Installed

none

### Expected Behavior

Wanted geode to work.

### Actual Behavior

Geometry Dash loaded but geode wasnt installed but the files were in the geometry dash folder.

### Steps to Reproduce

It could just be me but I followed the Linux tutorial.

### Additional Information

I was running geometry dash from a folder with the game files and the exe and using the program Whisky

**Comment by iNUCi** [comment]
the linux launch option doesn't work on macos, because you're running the windows version of steam in whisky. for macos, you have to open wine configuration in whisky, go to libraries, and add a dll override for xinput1_4

**Comment by mozibites** [comment]
ill try that thanks

**Comment by mozibites** [comment]
> the linux launch option doesn't work on macos, because you're running the windows version of steam in whisky. for macos, you have to open wine configuration in whisky, go to libraries, and add a dll override for xinput1_4

I have added the override WINEDLLOVERRIDES="xinput1_4=n,b" %command%. and it sadly failed

**Comment by iNUCi** [comment]
> > the linux launch option doesn't work on macos, because you're running the windows version of steam in whisky. for macos, you have to open wine configuration in whisky, go to libraries, and add a dll override for xinput1_4
> 
> I have added the override WINEDLLOVERRIDES="xinput1_4=n,b" %command%. and it sadly failed

Do what i said, don't touch the launch options

**Comment by mozibites** [comment]
k ty

**Comment by mozibites** [comment]
OMG TY IT FINALLY WORKS
<img width="1680" alt="Screenshot 2024-12-24 at 11 13 16 PM" src="https://github.com/user-attachments/assets/131e9803-1845-4064-a034-e257d2dd5bec" />

**Comment by iNUCi** [comment]
> OMG TY IT FINALLY WORKS <img alt="Screenshot 2024-12-24 at 11 13 16 PM" width="1680" src="https://private-user-images.githubusercontent.com/187491352/398409590-131e9803-1845-4064-a034-e257d2dd5bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDI5MTMsIm5iZiI6MTczNTA0MjYxMywicGF0aCI6Ii8xODc0OTEzNTIvMzk4NDA5NTkwLTEzMWU5ODAzLTE4NDUtNDA2NC1hMDM0LWUyNTdkMmRkNWJlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxMjE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmZjMGUwMTM2MjhmMTAyNmVhNmM4NjZlNWEwNTRjMjEwNjNiMzRmYTM3ZDNlOWZlMzIxYTM4NzVlMDE3ZTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vmLTeFXmhJZPTT8ljAtUxeyuSI1LmGwOTommkyY4RC0">

You're welcome
