### ISSUE TITLE
Buttons Below Mods Aren't Working!

### ISSUE THREAD

**Issue by Gild56** [geode-sdk/geode#1202]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

last version (updated)

### Expected Behavior

The Discord and GitHub buttons below the mods should working.

### Actual Behavior

The Discord and GitHub buttons below the mods aren't working.

### Steps to Reproduce

Go into a mod page and click on a button.

### Additional Information

It's not working since long time

**Comment by matcool** [comment]
the mod didnt set it
