### ISSUE TITLE
game crashes when mods are installed

### ISSUE THREAD

**Issue by octopuswindow** [geode-sdk/geode#123]
### Platform

MacOS

### Geode Version

v1.0.0-beta

### Steps to Reproduce

when i finish downloading a mod, the game crashes, and the game crashes on startup until i delete the mod manually.

### Crash Report

https://pastebin.com/K4k2S91M

**Comment by matcool** [comment]
Are you on at least https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta3 ? this looks like a bug which was fixed in 5bbd34cd730e8aa75893b064a9533ed82942af9d

**Comment by octopuswindow** [comment]
> Are you on at least https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta3 ? this looks like a bug which was fixed in [5bbd34c](https://github.com/geode-sdk/geode/commit/5bbd34cd730e8aa75893b064a9533ed82942af9d)

maybe, i will try downloading the new version.

**Comment by octopuswindow** [comment]
i've updated to the latest version and it still seems to be happening

**Comment by iAndyHD3** [comment]
Windows, same issue started happening after 6.0/6.1 so maybe try with 6.0 and with a mod compiled for that version (temporarily until it gets fixed)

**Comment by matcool** [comment]
does this still happen on [v1.0.0-beta5](https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta5) ?

**Comment by octopuswindow** [comment]
> does this still happen on [v1.0.0-beta5](https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta5) ?

No it does not although it still does something similar when i try to download demonlist-button.

**Comment by altalk23** [comment]
any updates on this issue on the latest geode version?

**Comment by octopuswindow** [comment]
> any updates on this issue on the latest geode version?

it doesn't happen anymore i think i can close this issue
