### ISSUE TITLE
Geode does not work (error 127)

### ISSUE THREAD

**Issue by Matto58** [geode-sdk/geode#128]
### Platform

Windows

### Geode Version

the one downloaded from geode-sdk.org

### Expected Behavior

The game should start with Geode working.

### Actual Behavior

The game started, did not crash but before gave me these errors:
![error 1](https://user-images.githubusercontent.com/60749494/217062470-e86365af-6bf1-4bb2-a73c-c1a93c54ec77.png)
![error 2](https://user-images.githubusercontent.com/60749494/217062534-a53a655d-734a-4cff-87fa-a96cb23ba7bd.png)

And then the game starts after these errors.

### Steps to Reproduce

1) Download geode from geode-sdk.org
2) Install it
3) Start Geometry Dash
4) Get these errors

**Comment by matcool** [comment]
cant reproduce, are you sure you're on 2.113 gd?

**Comment by Matto58** [comment]
> cant reproduce, are you sure you're on 2.113 gd?

i am def on 2.11, not sure on the last digit
