### ISSUE TITLE
Check boxes/info buttons in mod settings don't work

### ISSUE THREAD

**Issue by frag188** [geode-sdk/geode#130]
### Platform

Windows

### Geode Version

v1.0.0-beta

### Mods Installed

Better Edit

### Expected Behavior

Check boxes/info buttons can be clicked/toggled

### Actual Behavior

Check boxes/info buttons do not work in the settings menu, like I just can't click them (even without any other mods)

### Steps to Reproduce

I went to a mods settings, and couldn't click them

### Additional Information

Tried with and without other mods, still didn't work

**Comment by matcool** [comment]
this was fixed in 65f2cbb286cc1e5af57e43451862a2233d66453e, since theres no release with it yet you can use https://github.com/geode-sdk/geode/releases/tag/Nightly for now

**Comment by matcool** [comment]
fixed in [v1.0.0-beta5](https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta5)
