### ISSUE TITLE
Mod incompatibility 

### ISSUE THREAD

**Issue by Aktimoose** [geode-sdk/geode#131]
### Platform

Windows

### Geode Version

v1.0.0-beta

### Mods Installed

camila314.acbypass | camila314 | v1.0.0 | Enabled | Loaded | 
camila314.startswitcher | camila314 | v1.0.0 | Enabled | Loaded | 
mat.fps-bypass | mat | v1.0.1 | Enabled | Loaded | 

### Steps to Reproduce

1) Install FPS Bypass by mat
2) Install StartPos Switcher by camila314 (+ac bypass dependency)
3) Enter any level
4) Exit
5) Crash

### Crash Report

2023-02-13T14:47:40+0000
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.0.0-beta
Installed mods: 3
Failed mods: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00C70845 (00C70845)
Number Parameters: 2

== Register States ==
EAX: 0x5c0b1390
EBX: 0
ECX: 0x5c0be5a4
EDX: 0x1a115d20
EBP: 0x16ff6d4
ESP: 0x16ff6a8
EDI: 0x1a1c1f80
ESI: 0x1a009768
EIP: 0xc70845

== Stack Trace ==
 - 00C70845
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 0x52b00 (geode::FloatSetting::FloatSetting + 258897)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 0x52f7b (geode::FloatSetting::FloatSetting + 260044)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x693dc (cocos2d::CCObject::release + 12)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xa1a0b (cocos2d::CCLayer::~CCLayer + 203)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x10b004
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x1fb672
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x1fafcb
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x693dc (cocos2d::CCObject::release + 12)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x62430 (cocos2d::CCArray::~CCArray + 224)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x693dc (cocos2d::CCObject::release + 12)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xa4028 (cocos2d::CCScene::~CCScene + 88)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x693dc (cocos2d::CCObject::release + 12)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x693dc (cocos2d::CCObject::release + 12)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xffb2d (cocos2d::CCDirector::levelForSceneInStack + 125)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x261175
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 0x18039 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x6da5b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x6d9dd (RtlGetAppContainerNamedObjectPath + 237)

== Installed Mods ==
camila314.acbypass | camila314 | v1.0.0 | Enabled | Loaded | 
camila314.startswitcher | camila314 | v1.0.0 | Enabled | Loaded | 
mat.fps-bypass | mat | v1.0.1 | Enabled | Loaded |

**Comment by matcool** [comment]
startpos switcher issue, fixed whenever camila updates it
