### ISSUE TITLE
Starter mod won't recompile to DLL (tl;dr starter mod doesn't work)

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#135]
### Platform

Windows

### Geode Version

v1.0.0 (https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta5)

### Mods Installed

geode.devtools
(my mod here)

### Expected Behavior

The starter mod from running `geode new` should be able to decompile into a DLL and work in game.

### Actual Behavior

The mod did compile, but Geode threw an error..(Screenshot below)

### Steps to Reproduce

1. Run `geode new`
2. Compile in VSCode
3. See error

### Additional Information

I am on the latest version of both Geode, the Geode CLI and the Geode SDK.

Error:

![image](https://user-images.githubusercontent.com/76978184/219396611-d59b7198-1e48-4b8f-afa1-2aa65f2f8115.png)

**Comment by altalk23** [comment]
If you are going to use beta5, make sure you compile your mods with beta5 commit (git checkout v1.0.0-beta5) because we recently have made some abi breaking changes to improve compile times

**Comment by TechStudent10** [comment]
> If you are going to use beta5, make sure you compile your mods with beta5 commit (git checkout v1.0.0-beta5) because we recently have made some abi breaking changes to improve compile times

In my SDK folder?

**Comment by altalk23** [comment]
Yes

**Comment by TechStudent10** [comment]
@altalk23 I'm still getting the same error after switching to the `v1.0.0-beta5` branch in my SDK folder and recompiling the mod.

**Comment by TechStudent10** [comment]
I then tried to open my online level and got whatever the crap this is:

![image](https://user-images.githubusercontent.com/76978184/219399121-bceb07ba-566b-4e01-9dd0-a1930536cc01.png)

**Comment by TechStudent10** [comment]
(yes I installed more mods)

**Comment by HenrySck075** [comment]
> I then tried to open my online level and got whatever the crap this is:
> 
> ![image](https://user-images.githubusercontent.com/76978184/219399121-bceb07ba-566b-4e01-9dd0-a1930536cc01.png)

demonlist button issue tbh, dk what camila does tho

and why the heck db also crash on daily chest btn

**Comment by TechStudent10** [comment]
> > I then tried to open my online level and got whatever the crap this is:
> 
> demonlist button issue tbh, dk what camila does tho
> 
> and why the heck db also crash on daily chest btn

I uninstalled it don't worry. And idk report to camilla314.

**Comment by HenrySck075** [comment]
am i using too much abbreviation? i think i might be

**Comment by TechStudent10** [comment]
@altalk23 do you have a fix or...

**Comment by iAndyHD3** [comment]
1. did you compile in release? (make sure you do)
2. delete the geode folder/files in gd appdata and try again

**Comment by TechStudent10** [comment]
@iAndyHD3 

1. yes I am
2. okay I'll try

**Comment by TechStudent10** [comment]
@iAndyHD3 No that didn't work

**Comment by TechStudent10** [comment]
Any update to the situation?

**Comment by matcool** [comment]
cant repro.

```
C:\Users\Mateus\Desktop\coding\c++\geode>geode new
Name: dummy
Version: v1.0.0
Developer: mat
Description (optional):
Location: C:\Users\Mateus\Desktop\coding\c++\geode\dummy
| Info | Creating project mat.dummy
| Done | Succesfully initialized project! Happy modding :)

C:\Users\Mateus\Desktop\coding\c++\geode>cd dummy

C:\Users\Mateus\Desktop\coding\c++\geode\dummy>cmake -A win32 -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30146.0

[...]

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Mateus/Desktop/coding/c++/geode/dummy/build

C:\Users\Mateus\Desktop\coding\c++\geode\dummy>cmake --build build --config Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking File Globs
  
[...]

  Building Custom Rule C:/Users/Mateus/Desktop/coding/c++/geode/dummy/CMakeLists.txt
  cmake_pch.cxx
  main.cpp
  entry.cpp
  Generating Code...
  dummy.vcxproj -> C:\Users\Mateus\Desktop\coding\c++\geode\dummy\build\Release\mat.dummy.dll
  | Info | Zipping
  | Done | Successfully packaged dummy.geode
  | Done | Installed dummy.geode
  Building Custom Rule C:/Users/Mateus/Desktop/coding/c++/geode/dummy/CMakeLists.txt
  Building Custom Rule C:/Users/Mateus/Desktop/coding/c++/geode/dummy/CMakeLists.txt
```

![image](https://user-images.githubusercontent.com/26722564/221190713-ab92aba5-1f5a-4300-b35c-b6be6d5c6740.png)

**Comment by TechStudent10** [comment]
> cant repro.

I'm using VSCode to compile. I'll try with CMD and see if that works.

**Comment by TechStudent10** [comment]
> > cant repro.
> 
> I'm using VSCode to compile. I'll try with CMD and see if that works.

For some odd reason, this worked! Before closing I'm going to try it with the source code I was originally attempting to compile.

**Comment by TechStudent10** [comment]
The C/C++ VSCode extension was bugging out with Geode. Using the command line worked. Thanks to everyone who helped 👍🏾
