### ISSUE TITLE
Geometry Dash crashes as soon as it finishes loading

### ISSUE THREAD

**Issue by octopuswindow** [geode-sdk/geode#138]
### Platform

MacOS

### Geode Version

geode-v1.0.0-beta.6

### Steps to Reproduce

Open the game and as soon as it finishes loading it crashes

### Crash Report

https://pastebin.com/nGCQRa6S

**Comment by matcool** [comment]
fixed on d024dbb858b5282ddc5ca92d7cbddf62f1ebf8a3, will close when beta 7 releases
