### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#139]
### Geode Version

v1.0.0-beta5

### Related Problem

As developers, I think we've all experience the need to add a bunch of logs to the standard output to fix a bug.

### Your Solution

If there was an **obvious** way to log in **realtime** while the mod running, I think that'd be cool.

### Additional Information

Maybe viewing the logs could be implemented in Geode DevTools.

**Comment by matcool** [comment]
mod list -> geode -> settings -> enable platform console
