### ISSUE TITLE
Hitbox bug

### ISSUE THREAD

**Issue by GDcuber** [geode-sdk/geode#142]
### Platform

MacOS

### Geode Version

v0.6.1

### Mods Installed

CrystalClient.geode

### Expected Behavior

i use the hitbox thing on the CrystalClient it shows me the hitbox and if i turn it off it does not show me the hitbox

### Actual Behavior

i use the hitbox thing on the CrystalClient it shows me the hitbox and if i turn it off it still shows me the hitbox i tryed very much to fix this and turned them ALL on and off and turned some on and some off. and a few times it worked but when i turn off show hitboxes it STILL shows me the hitboxes

### Steps to Reproduce

Turn on show hitboxes in the gd CrystalClient and turn it off

### Additional Information

idk why

**Comment by altalk23** [comment]
Please report bugs related to GeodeSDK, and not the mods made using it. You can report bugs related to CrystalClient to its developer ninXout.

**Comment by F1NS3N** [comment]
Same problem. The answer, of course, killed

**Comment by F1NS3N** [comment]
Same problem
