### ISSUE TITLE
Hooking into `destroyPlayer` crashes GD on the latest version of Geode

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#143]
### Platform

Windows

### Geode Version

v.1.0.0-beta10

### Mods Installed

camila314.acbypass

hjfod.gdshare

hjfod.gmd-api

(my own mods)

ChallengeMod

noclip-acc-new

techstudent10.challenge_mod

### Steps to Reproduce

1. Generate a new Geode Mod
2. Use the following code:

```cpp
#include <Geode/Geode.hpp>
// #include <Geode/modify/MenuLayer.hpp>
#include <Geode/modify/PlayLayer.hpp>

USE_GEODE_NAMESPACE();

class $modify(MyPlayLayer, PlayLayer) {
	void destroyPlayer(PlayerObject* playerObject, GameObject* gameObject) {
		this->destroyPlayer(playerObject, gameObject);
	} 
};

```

(this is hooking and recalling `destroyPlayer`)

3. See error

### Crash Report

https://gist.github.com/TechStudent10/12fdbc8725c5f655e18e76603ee1db19

**Comment by matcool** [comment]
https://docs.geode-sdk.org/tutorials/modify#accidental-recursion

**Comment by TechStudent10** [comment]
Ah I see thank you

**Comment by TechStudent10** [comment]
> try to call the original like this
> 
> ```c++
> PlayLayer::destroyPlayer(playerObject, gameObject);
> ```

I get the same result with this :/

**Comment by altalk23** [comment]
any updates on this issue?

**Comment by TechStudent10** [comment]
Eh am not working on whatever this mod was intended to be. I'll close it.
