### ISSUE TITLE
Geode crashed when I view my online levels

### ISSUE THREAD

**Issue by DaniSilva-25** [geode-sdk/geode#148]
### Platform

Windows

### Geode Version

v1.0.0-beta.10

### Mods Installed

Demonlist button, GDShare

### Steps to Reproduce

I went to my levels, I clicked the online button

### Crash Report

2023-03-19T21:56:09+0000
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.0.0-beta.10
Installed mods: 6
Failed mods: 0

== Exception Information ==
Faulty Module: C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00DAF9E3 (GeometryDash.exe + 0x9f9e3)
Number Parameters: 2

== Register States ==
EAX: 0x11cd3f54
EBX: 0x40
ECX: 0x3f
EDX: 0xef
EBP: 0x9eeb58
ESP: 0x9eeb38
EDI: 0x3f
ESI: 0x11cd3f30
EIP: 0xdaf9e3

== Stack Trace ==
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x9f9e3
 - 031C26FD
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\geode\unzipped\camila314.demonlist-button\camila314.demonlist-button.dll + 0x417f
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\geode\unzipped\camila314.demonlist-button\camila314.demonlist-button.dll + 0x1628
 - 031C2599
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x15b3dc
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x15b045
 - 031C03D5
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\Geode.dll + 0x72dee (geode::FloatSetting::FloatSetting + 389064)
 - 031C0229
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\geode\unzipped\hjfod.gdshare\hjfod.gdshare.dll + 0x1d646
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\geode\unzipped\hjfod.gdshare\hjfod.gdshare.dll + 0x1721e
 - 031C0229
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x159f85
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x15ce36
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xabe83 (cocos2d::CCMenuItem::activate + 35)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xaaf1d (cocos2d::CCMenu::ccTouchEnded + 29)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xf5919 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xbb37c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xc4046 (cocos2d::CCEGLView::onGLFWMouseCallBack + 198)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xc406e (cocos2d::CCEGLView::onGLFWMouseCallBack + 238)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0x111b29 (cocos2d::CCPoint::unrotate + 8057)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0x113679 (cocos2d::CCPoint::unrotate + 15049)
 - C:\windows\System32\USER32.dll + 0x410eb (AddClipboardFormatListener + 75)
 - C:\windows\System32\USER32.dll + 0x380aa (GetClassLongW + 1962)
 - C:\windows\System32\USER32.dll + 0x37787 (GetSystemMetricsForDpi + 5959)
 - C:\windows\System32\USER32.dll + 0x3592b (CallWindowProcW + 27)
 - C:\windows\SYSTEM32\OPENGL32.dll + 0x4696f (glDebugEntry + 3631)
 - C:\windows\System32\USER32.dll + 0x410eb (AddClipboardFormatListener + 75)
 - C:\windows\System32\USER32.dll + 0x380aa (GetClassLongW + 1962)
 - C:\windows\System32\USER32.dll + 0x35e1a (DispatchMessageW + 586)
 - C:\windows\System32\USER32.dll + 0x35be0 (DispatchMessageW + 16)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0x1122d2 (cocos2d::CCPoint::unrotate + 10018)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\libcocos2d.dll + 0xc190b (cocos2d::CCApplication::run + 779)
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x261175
 - C:\Users\Daniel\Documents\Geometry.Dash.v07.24.2021\GeometryDash.exe + 0x2621fd
 - C:\windows\System32\KERNEL32.DLL + 0x200f9 (BaseThreadInitThunk + 25)
 - C:\windows\SYSTEM32\ntdll.dll + 0x67bbe (RtlGetAppContainerNamedObjectPath + 286)
 - C:\windows\SYSTEM32\ntdll.dll + 0x67b8e (RtlGetAppContainerNamedObjectPath + 238)

== Installed Mods ==
geode.loader | Geode Team | v1.0.0-beta.10 | Enabled | Loaded | 
camila314.demonlist-button | camila314 | v1.0.0 | Enabled | Loaded | 
hjfod.gdshare | HJfod | v1.0.0 | Enabled | Loaded | 
hjfod.gmd-api | HJfod | v1.0.0 | Enabled | Loaded |

**Comment by altalk23** [comment]
Not a geode bug, but rather a bug related to one of your mods (Demonlist button). Ask the creator of the mod for the fix.
