### ISSUE TITLE
You can click on mod creator names over and over, creating a new FLAlertLayer with each click

### ISSUE THREAD

**Issue by Fleeym** [geode-sdk/geode#153]
### Platform

Windows

### Geode Version

v1.0.0-beta.13

### Expected Behavior

Clicking on a mod author (which shows their created mods), then clicking again on the mod author should not open a new popup.

### Actual Behavior

Clicking on a mod author (which shows their created mods), then clicking again on the mod author opens another popup. Every time you click on the mod author, a new popup appears

### Steps to Reproduce

1. Open the Geode Index
2. Click on a mod author's name, opening their created mods.
3. in this new popup, click on the mod author's name again. Repeat.

**Comment by HJfod** [comment]
This is intentional behaviour (it's funny)

**Comment by Fleeym** [comment]
understandable
