### ISSUE TITLE
Game crash while playtesting

### ISSUE THREAD

**Issue by Bituvo** [geode-sdk/geode#156]
### Platform

Windows

### Geode Version

v1.0.0-beta.13

### Mods Installed

geode.loader | Geode Team | v1.0.0-beta.13
mat.circle-tool | mat | v1.0.0
mat.rgb-color-input | mat | v1.0.0

### Steps to Reproduce

I left the level editor with "save and play", and started playing the level from the start pos that was there. After about a second, the game crashed.

### Crash Report

https://pastebin.com/Wjtn5YJs

**Comment by altalk23** [comment]
This doesn't look like a geode issue, can you replicate the problem with circle-tool disabled?

**Comment by Bituvo** [comment]
I can't, the issue happened randomly and I don't know how to reproduce it.
