### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by RedRavenYouTube** [geode-sdk/geode#158]
### Platform

MacOS

### Geode Version

beta 1.0.0

### Mods Installed

anticheat bypass
circle tool
geode
GDShare
GMD api
start pos switcher

### Steps to Reproduce

I went into the editor and when I play and go back to the editor, the game crashes. The missing textures when I try to install them, the geode/update/resources folder gets deleted entirely.

### Crash Report

[Geode 16 Apr 10.13.01.log](https://github.com/geode-sdk/geode/files/11242689/Geode.16.Apr.10.13.01.log)

**Comment by altalk23** [comment]
That is the log file, not the crash report
