### ISSUE TITLE
New beta 15 crashes

### ISSUE THREAD

**Issue by OMEGA6405** [geode-sdk/geode#162]
### Platform

Windows

### Geode Version

Beta 15

### Mods Installed

None

### Steps to Reproduce

Run it

### Crash Report

Na

**Comment by altalk23** [comment]
yeah i will need windows people to test this
im gonna release a beta 16 hotfix for macos but i guesss windows needs it too

**Comment by OMEGA6405** [comment]
> yeah i will need windows people to test this
> im gonna release a beta 16 hotfix for macos but i guesss windows needs it too
> 

I guess I could help when I can if you need it

**Comment by altalk23** [comment]
try running gd using a debugger like x32dbg
i basically need a crash report

**Comment by OMEGA6405** [comment]
> try running gd using a debugger like x32dbg
> i basically need a crash report

Okay I got an error code (code 1114)

**Comment by altalk23** [comment]
any backtrace?

**Comment by OMEGA6405** [comment]
> any backtrace?

No that was just the code geode gave me it said it failed to load (code 1114)

**Comment by OMEGA6405** [comment]
> any backtrace?

Also it doesn't crash it just failed to load

**Comment by OMEGA6405** [comment]
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing Zydis...
Getting directory information...
Start file read thread...
Retrieving syscall indices...
Symbol Path: C:\Users\jackg\Downloads\snapshot_2023-04-30_13-19 2\release\x32\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
Handling command line...
  "C:\Users\jackg\Downloads\snapshot_2023-04-30_13-19 2\release\x32\x32dbg.exe" 
Syscall indices loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!
Database file: C:\Users\jackg\Downloads\snapshot_2023-04-30_13-19 2\release\x32\db\GeometryDash.exe.dd32
Process Started: [00D30000](x64dbg://localhost/address32#00D30000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
  "C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe"
  argv[0]: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
Attached to process!
DLL Loaded: [77CB0000](x64dbg://localhost/address32#77CB0000) C:\Windows\SysWOW64\ntdll.dll
Thread 2988 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [0000000A](x64dbg://localhost/address32#0000000A)
Thread 26076 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [00010009](x64dbg://localhost/address32#00010009)
Thread 22504 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [0000000B](x64dbg://localhost/address32#0000000B)
Thread 26544 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [0000000B](x64dbg://localhost/address32#0000000B)
Thread 25768 created, Entry: [5CC79980](x64dbg://localhost/address32#5CC79980), Parameter: [00000000](x64dbg://localhost/address32#00000000)
Thread 24784 created, Entry: [52A7102D](x64dbg://localhost/address32#52A7102D), Parameter: [001F1458](x64dbg://localhost/address32#001F1458)
Thread 18956 created, Entry: [69637310](x64dbg://localhost/address32#69637310), Parameter: [00000000](x64dbg://localhost/address32#00000000)
Thread 22004 created, Entry: [69663200](x64dbg://localhost/address32#69663200), Parameter: [00000000](x64dbg://localhost/address32#00000000)
Thread 9528 created, Entry: [6962F3C0](x64dbg://localhost/address32#6962F3C0), Parameter: [00000000](x64dbg://localhost/address32#00000000)
Thread 24732 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [0000000B](x64dbg://localhost/address32#0000000B)
Thread 22988 created, Entry: [5116DB76](x64dbg://localhost/address32#5116DB76), Parameter: [00000000](x64dbg://localhost/address32#00000000)
Thread 23788 created, Entry: [5116DB76](x64dbg://localhost/address32#5116DB76), Parameter: [1246FDCC](x64dbg://localhost/address32#1246FDCC)
Thread 20156 created, Entry: [5116DB76](x64dbg://localhost/address32#5116DB76), Parameter: [125AFB00](x64dbg://localhost/address32#125AFB00)
DLL Loaded: [771A0000](x64dbg://localhost/address32#771A0000) C:\Windows\SysWOW64\kernel32.dll
DLL Loaded: [766D0000](x64dbg://localhost/address32#766D0000) C:\Windows\SysWOW64\KernelBase.dll
DLL Loaded: [76630000](x64dbg://localhost/address32#76630000) C:\Windows\SysWOW64\advapi32.dll
DLL Loaded: [77AF0000](x64dbg://localhost/address32#77AF0000) C:\Windows\SysWOW64\msvcrt.dll
DLL Loaded: [76470000](x64dbg://localhost/address32#76470000) C:\Windows\SysWOW64\sechost.dll
DLL Loaded: [52AE0000](x64dbg://localhost/address32#52AE0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libExtensions.dll
DLL Loaded: [521B0000](x64dbg://localhost/address32#521B0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll
DLL Loaded: [72C90000](x64dbg://localhost/address32#72C90000) C:\Windows\SysWOW64\opengl32.dll
DLL Loaded: [75B90000](x64dbg://localhost/address32#75B90000) C:\Windows\SysWOW64\rpcrt4.dll
DLL Loaded: [759E0000](x64dbg://localhost/address32#759E0000) C:\Windows\SysWOW64\user32.dll
DLL Loaded: [77BC0000](x64dbg://localhost/address32#77BC0000) C:\Windows\SysWOW64\win32u.dll
DLL Loaded: [76A20000](x64dbg://localhost/address32#76A20000) C:\Windows\SysWOW64\shell32.dll
DLL Loaded: [779C0000](x64dbg://localhost/address32#779C0000) C:\Windows\SysWOW64\gdi32.dll
DLL Loaded: [75D40000](x64dbg://localhost/address32#75D40000) C:\Windows\SysWOW64\msvcp_win.dll
DLL Loaded: [76940000](x64dbg://localhost/address32#76940000) C:\Windows\SysWOW64\gdi32full.dll
DLL Loaded: [76200000](x64dbg://localhost/address32#76200000) C:\Windows\SysWOW64\ucrtbase.dll
DLL Loaded: [77690000](x64dbg://localhost/address32#77690000) C:\Windows\SysWOW64\combase.dll
DLL Loaded: [62AA0000](x64dbg://localhost/address32#62AA0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\glew32.dll
DLL Loaded: [51080000](x64dbg://localhost/address32#51080000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\fmod.dll
DLL Loaded: [52AA0000](x64dbg://localhost/address32#52AA0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\steam_api.dll
DLL Loaded: [765D0000](x64dbg://localhost/address32#765D0000) C:\Windows\SysWOW64\ws2_32.dll
DLL Loaded: [76320000](x64dbg://localhost/address32#76320000) C:\Windows\SysWOW64\ole32.dll
DLL Loaded: [5A4C0000](x64dbg://localhost/address32#5A4C0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\zlib1.dll
DLL Loaded: [10000000](x64dbg://localhost/address32#10000000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\pthreadVCE2.dll
DLL Loaded: [52120000](x64dbg://localhost/address32#52120000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libtiff.dll
DLL Loaded: [52A90000](x64dbg://localhost/address32#52A90000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\XInput9_1_0.dll
DLL Loaded: [52020000](x64dbg://localhost/address32#52020000) C:\Windows\SysWOW64\msvcp120.dll
DLL Loaded: [50F90000](x64dbg://localhost/address32#50F90000) C:\Windows\SysWOW64\msvcr120.dll
DLL Loaded: [6BF60000](x64dbg://localhost/address32#6BF60000) C:\Windows\SysWOW64\glu32.dll
DLL Loaded: [74C10000](x64dbg://localhost/address32#74C10000) C:\Windows\SysWOW64\winmm.dll
DLL Loaded: [61F10000](x64dbg://localhost/address32#61F10000) C:\Windows\SysWOW64\msacm32.dll
DLL Loaded: [5F6B0000](x64dbg://localhost/address32#5F6B0000) C:\Windows\SysWOW64\vcruntime140.dll
DLL Loaded: [684C0000](x64dbg://localhost/address32#684C0000) C:\Windows\SysWOW64\wsock32.dll
DLL Loaded: [50EE0000](x64dbg://localhost/address32#50EE0000) C:\Windows\WinSxS\x86_microsoft.vc90.crt_[1fc8b3b9](x64dbg://localhost/address32#1fc8b3b9)[a1e18e3b](x64dbg://localhost/address32#a1e18e3b)_9.0.30729.9635_none_[508ff82e](x64dbg://localhost/address32#508ff82e)[bcbafee0](x64dbg://localhost/address32#bcbafee0)\msvcr90.dll
DLL Loaded: [62040000](x64dbg://localhost/address32#62040000) C:\Windows\SysWOW64\XInput1_4.dll
DLL Loaded: [6AF30000](x64dbg://localhost/address32#6AF30000) C:\Windows\SysWOW64\DXCore.dll
DLL Loaded: [68520000](x64dbg://localhost/address32#68520000) C:\Windows\SysWOW64\cfgmgr32.dll
DLL Loaded: [68560000](x64dbg://localhost/address32#68560000) C:\Windows\SysWOW64\devobj.dll
DLL Loaded: [50D20000](x64dbg://localhost/address32#50D20000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\sqlite3.dll
DLL Loaded: [50DB0000](x64dbg://localhost/address32#50DB0000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcurl.dll
DLL Loaded: [77BE0000](x64dbg://localhost/address32#77BE0000) C:\Windows\SysWOW64\Wldap32.dll
DLL Loaded: [56F60000](x64dbg://localhost/address32#56F60000) C:\Windows\SysWOW64\msvcr100.dll
DLL Loaded: [75C50000](x64dbg://localhost/address32#75C50000) C:\Windows\SysWOW64\imm32.dll
DLL Loaded: [50BD0000](x64dbg://localhost/address32#50BD0000) C:\Program Files (x86)\Steam\GameOverlayRenderer.dll
DLL Loaded: [770A0000](x64dbg://localhost/address32#770A0000) C:\Windows\SysWOW64\oleaut32.dll
DLL Loaded: [779B0000](x64dbg://localhost/address32#779B0000) C:\Windows\SysWOW64\psapi.dll
DLL Loaded: [5CC10000](x64dbg://localhost/address32#5CC10000) C:\Windows\SysWOW64\InputHost.dll
DLL Loaded: [67E20000](x64dbg://localhost/address32#67E20000) C:\Windows\SysWOW64\CoreMessaging.dll
DLL Loaded: [52A70000](x64dbg://localhost/address32#52A70000) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeodeBootstrapper.dll
DLL Loaded: [55460000](x64dbg://localhost/address32#55460000) C:\Windows\SysWOW64\msvcp140.dll
DLL Loaded: [75C80000](x64dbg://localhost/address32#75C80000) C:\Windows\SysWOW64\SHCore.dll
Breakpoint at [5BE8A9E1](x64dbg://localhost/address32#5BE8A9E1) (TLS Callback 1 (steamclient.dll)) set!
DLL Loaded: [5B2A0000](x64dbg://localhost/address32#5B2A0000) C:\Program Files (x86)\Steam\steamclient.dll
DLL Loaded: [779F0000](x64dbg://localhost/address32#779F0000) C:\Windows\SysWOW64\shlwapi.dll
DLL Loaded: [77580000](x64dbg://localhost/address32#77580000) C:\Windows\SysWOW64\crypt32.dll
DLL Loaded: [766B0000](x64dbg://localhost/address32#766B0000) C:\Windows\SysWOW64\imagehlp.dll
DLL Loaded: [74E80000](x64dbg://localhost/address32#74E80000) C:\Windows\SysWOW64\IPHLPAPI.DLL
DLL Loaded: [74FE0000](x64dbg://localhost/address32#74FE0000) C:\Windows\SysWOW64\version.dll
DLL Loaded: [5F720000](x64dbg://localhost/address32#5F720000) C:\Program Files (x86)\Steam\tier0_s.dll
DLL Loaded: [5DC90000](x64dbg://localhost/address32#5DC90000) C:\Program Files (x86)\Steam\vstdlib_s.dll
DLL Loaded: [74D70000](x64dbg://localhost/address32#74D70000) C:\Windows\SysWOW64\mswsock.dll
DLL Loaded: [6AF10000](x64dbg://localhost/address32#6AF10000) C:\Windows\SysWOW64\bcrypt.dll
DLL Loaded: [74780000](x64dbg://localhost/address32#74780000) C:\Windows\SysWOW64\secur32.dll
DLL Loaded: [050B0000](x64dbg://localhost/address32#050B0000) C:\Windows\SysWOW64\setupapi.dll
DLL Loaded: [74750000](x64dbg://localhost/address32#74750000) C:\Windows\SysWOW64\sspicli.dll
DLL Loaded: [75940000](x64dbg://localhost/address32#75940000) C:\Windows\SysWOW64\cryptbase.dll
DLL Loaded: [76500000](x64dbg://localhost/address32#76500000) C:\Windows\SysWOW64\bcryptprimitives.dll
DLL Loaded: [50AD0000](x64dbg://localhost/address32#50AD0000) C:\Program Files (x86)\Steam\Steam.dll
DLL Loaded: [67A50000](x64dbg://localhost/address32#67A50000) C:\Windows\SysWOW64\TextShaping.dll
DLL Loaded: [73CE0000](x64dbg://localhost/address32#73CE0000) C:\Windows\SysWOW64\uxtheme.dll
DLL Loaded: [774A0000](x64dbg://localhost/address32#774A0000) C:\Windows\SysWOW64\msctf.dll
DLL Loaded: [66C20000](x64dbg://localhost/address32#66C20000) C:\Windows\SysWOW64\dbghelp.dll
DLL Loaded: [74E30000](x64dbg://localhost/address32#74E30000) C:\Windows\SysWOW64\kernel.appcore.dll
DLL Loaded: [599F0000](x64dbg://localhost/address32#599F0000) C:\Windows\SysWOW64\dbgcore.dll
DLL Loaded: [67EF0000](x64dbg://localhost/address32#67EF0000) C:\Windows\SysWOW64\TextInputFramework.dll
DLL Loaded: [520F0000](x64dbg://localhost/address32#520F0000) C:\Program Files (x86)\Steam\CSERHelper.dll
DLL Loaded: [75210000](x64dbg://localhost/address32#75210000) C:\Windows\SysWOW64\windows.storage.dll
DLL Loaded: [75140000](x64dbg://localhost/address32#75140000) C:\Windows\SysWOW64\WinTypes.dll
DLL Loaded: [6BC30000](x64dbg://localhost/address32#6BC30000) C:\Windows\SysWOW64\dwmapi.dll
DLL Loaded: [772A0000](x64dbg://localhost/address32#772A0000) C:\Windows\SysWOW64\clbcatq.dll
DLL Loaded: [616E0000](x64dbg://localhost/address32#616E0000) C:\Windows\SysWOW64\AppXDeploymentClient.dll
DLL Loaded: [686D0000](x64dbg://localhost/address32#686D0000) C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_[f840d03a](x64dbg://localhost/address32#f840d03a)[202f8a32](x64dbg://localhost/address32#202f8a32)\nvoglv32.dll
DLL Loaded: [75910000](x64dbg://localhost/address32#75910000) C:\Windows\SysWOW64\wtsapi32.dll
DLL Loaded: [6AEB0000](x64dbg://localhost/address32#6AEB0000) C:\Windows\SysWOW64\msasn1.dll
DLL Loaded: [686A0000](x64dbg://localhost/address32#686A0000) C:\Windows\SysWOW64\cryptnet.dll
DLL Loaded: [68590000](x64dbg://localhost/address32#68590000) C:\Windows\SysWOW64\drvstore.dll
DLL Loaded: [684D0000](x64dbg://localhost/address32#684D0000) C:\Windows\SysWOW64\wldp.dll
DLL Loaded: [77C40000](x64dbg://localhost/address32#77C40000) C:\Windows\SysWOW64\wintrust.dll
DLL Loaded: [74690000](x64dbg://localhost/address32#74690000) C:\Windows\SysWOW64\ntmarta.dll
DLL Loaded: [6B5E0000](x64dbg://localhost/address32#6B5E0000) C:\Windows\SysWOW64\powrprof.dll
DLL Loaded: [6AE70000](x64dbg://localhost/address32#6AE70000) C:\Windows\SysWOW64\umpdc.dll
DLL Loaded: [74400000](x64dbg://localhost/address32#74400000) C:\Windows\SysWOW64\winsta.dll
DLL Loaded: [679D0000](x64dbg://localhost/address32#679D0000) C:\Windows\SysWOW64\MMDevAPI.dll
DLL Loaded: [614C0000](x64dbg://localhost/address32#614C0000) C:\Windows\SysWOW64\AudioSes.dll
DLL Loaded: [67820000](x64dbg://localhost/address32#67820000) C:\Windows\SysWOW64\Windows.UI.dll
DLL Loaded: [6B5C0000](x64dbg://localhost/address32#6B5C0000) C:\Windows\SysWOW64\winmmbase.dll
DLL Loaded: [61F50000](x64dbg://localhost/address32#61F50000) C:\Windows\SysWOW64\wdmaud.drv
DLL Loaded: [67AF0000](x64dbg://localhost/address32#67AF0000) C:\Windows\SysWOW64\avrt.dll
DLL Loaded: [68090000](x64dbg://localhost/address32#68090000) C:\Windows\SysWOW64\ksuser.dll
DLL Loaded: [65D70000](x64dbg://localhost/address32#65D70000) C:\Windows\SysWOW64\msacm32.drv
DLL Loaded: [61F40000](x64dbg://localhost/address32#61F40000) C:\Windows\SysWOW64\midimap.dll
DLL Loaded: [614B0000](x64dbg://localhost/address32#614B0000) C:\Windows\SysWOW64\ResourcePolicyClient.dll
Thread 25380 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [033A7F10](x64dbg://localhost/address32#033A7F10)
INT3 breakpoint "TLS Callback 1 (steamclient.dll)" at steamclient.[5BE8A9E1](x64dbg://localhost/address32#5BE8A9E1)!
Thread 10544 created, Entry: ntdll.[77CEE400](x64dbg://localhost/address32#77CEE400), Parameter: [033A7F10](x64dbg://localhost/address32#033A7F10)

**Comment by OMEGA6405** [comment]
Dose this help? @altalk23

**Comment by altalk23** [comment]
not really, you need to skip the int3 breakpoints

**Comment by OMEGA6405** [comment]
> not really, you need to skip the int3 breakpoints

I've never used dbg 32 before so can you tell me what to do?

**Comment by altalk23** [comment]
you should continue execution with the continue button when you get into a int3 breakpoint / debug breakpoint

**Comment by OMEGA6405** [comment]
bpcnd 00000000, ""
bpl 00000000, ""
bplogcondition 00000000, ""
SetBreakpointCommand 00000000, ""
SetBreakpointCommandCondition 00000000, ""
SetBreakpointFastResume 00000000, 0
SetBreakpointSilent 00000000, 0
SetBreakpointSingleshoot 00000000, 0

**Comment by OMEGA6405** [comment]
This it?![Screenshot_20230501_055259.jpg](https://user-images.githubusercontent.com/98067930/235437481-83e36b8d-12af-4155-a0a3-35360c4ebfc0.jpg)

**Comment by OMEGA6405** [comment]
@altalk23

**Comment by OMEGA6405** [comment]
geometrydash.00F92711
.text:00F9227B geometrydash.exe:$26227B #26167B <EntryPoint>

**Comment by altalk23** [comment]
can you try the nightly release? https://github.com/geode-sdk/geode/releases/tag/nightly
wine seems to work with this release for me

**Comment by OMEGA6405** [comment]
> can you try the nightly release? https://github.com/geode-sdk/geode/releases/tag/nightly
> wine seems to work with this release for me

Did I help at all?

**Comment by altalk23** [comment]
yeah by informing about the crash and testing that the nightly works
thanks

**Comment by OMEGA6405** [comment]
> yeah by informing about the crash and testing that the nightly works
> thanks

Yay
