### ISSUE TITLE
Crash on editor

### ISSUE THREAD

**Issue by dprmaxYT** [geode-sdk/geode#167]
### Platform

Windows

### Geode Version

1.0.0 beta 16

### Mods Installed

Anticheat bypass v1.0.0
circle tool v1.0.0
editor collab v1.10.0 beta
FPS Shower v1.0.0
GDShare v1.0.0
GMD API v1.0.1
Geode v1.0.0 Beta 16
Noclip v1.0.0
Nongd v1.0.2
practice music v1.0.3
RGB Color Imput v1.0.2

### Steps to Reproduce

1)
Opens the editor mode completely empty
2)
put a yellow path
3)
two squares above the path place another
4)
select both
5)
in the edit section, press the last button (the one of a mod)
6)
circle tool will open
7)
Leave everything as it is, but in case the same thing doesn't appear to you:
ARC: 180
Step: 5
Squish: 0
Copies: 35
objects: 70
8)
hit apply
9)
The crash should be almost instantaneous.

### Crash Report

[2023-05-14_20-30-59.log](https://github.com/geode-sdk/geode/files/11472668/2023-05-14_20-30-59.log)
[Geode 14 May 19.48.01.log](https://github.com/geode-sdk/geode/files/11472670/Geode.14.May.19.48.01.log)
I don't know if I have to send it like that :v

### Additional Information

I think it's a bug of the mod itself

**Comment by matcool** [comment]
whats a yellow path?

**Comment by dprmaxYT** [comment]
the first one in the tab, the one that makes you jump without having to press it

**Comment by altalk23** [comment]
seems to be a mod specific issue, please report it to the mod author
