### ISSUE TITLE
GD crashed after using Circle Tool

### ISSUE THREAD

**Issue by Jimmy106-e** [geode-sdk/geode#178]
### Platform

Windows

### Geode Version

v2.4.0

### Mods Installed

geode.CircleTool

### Steps to Reproduce

Went to the editor to try the circle tool and my game crashed when i clicked the "apply" button

### Crash Report

[Geode 27 May 15.47.44.log](https://github.com/geode-sdk/geode/files/11581778/Geode.27.May.15.47.44.log)

**Comment by matcool** [comment]
from your logs you clearly have more than circle tool installed
