### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Z-Coder2100** [geode-sdk/geode#191]
### Platform

Windows

### Geode Version

v1.0.0-beta.18

### Mods Installed

alk.fps-shower v1.0.0
camila314.acbypass v1.0.0
camila314.noclip.geode v1.0.0 (disabled)
cattodev.gatobot v1.3.0
fig.video_player v1.0.1
fleym.nongd v1.0.3
geode.devtools v1.1.1
hjfod.gdshare v1.0.0
hjfod.gmd-api v1.0.1
mat.fps-bypass v1.0.3
mat.practice-music v1.0.3
mat.scroll-zoom v1.0.0

### Steps to Reproduce

Not sure what happened. I opened the game and it crashed. The next session worked perfectly fine. I am running on Windows 10 with Steam.

### Crash Report

https://pastebin.com/dRvdA3RM

### Additional Information

This may be caused by a mod, but unsure

**Comment by cgytrus** [comment]
can you test if the issue persists on the latest [dev release](https://github.com/geode-sdk/geode/releases/tag/nightly)?

**Comment by altalk23** [comment]
Fixed on latest releases as we got rid of keystone as a dependency
