### ISSUE TITLE
Crash from startup

### ISSUE THREAD

**Issue by Aural0** [geode-sdk/geode#192]
### Platform

Windows

### Geode Version

v1 b18

### Mods Installed

bezier
alignto
circletool
custom keybinds
gdshare
gmd api
rgb color inpit
small addons

### Steps to Reproduce

Dont know why it happens just happens

### Crash Report

[2023-07-10_09-58-26.log](https://github.com/geode-sdk/geode/files/11999275/2023-07-10_09-58-26.log)
[Geode 10 Jul 10.02.54.log](https://github.com/geode-sdk/geode/files/11999278/Geode.10.Jul.10.02.54.log)

### Additional Information

It also rarely boots when opening the exe, have to open it 4-5 times

**Comment by altalk23** [comment]
known crash, fixed in the lastest commits (not nightly cause updating that is broken too

**Comment by cgytrus** [comment]
dev releases are working now also yeah this should be fixed so closing the issue now
