### ISSUE TITLE
Crashes when double tapped escape

### ISSUE THREAD

**Issue by Dimplycelery584** [geode-sdk/geode#193]
### Platform

Windows

### Geode Version

v1.0.0-beta.18

### Mods Installed

editor collab
acbypass
beizer
gatobot
capacity_fix
video_player
nongd
custom-keybinds
gdshare
gmd-api
circle-tool
fps-bypass
practice-music
rgb-color-input
scroll-zoom
startpos-switcher

### Steps to Reproduce

i opened clutterfunk and double tapped esc to go out of the level, it then crashed, i have tries this many times and they have all crashed

### Crash Report

[2023-07-10_18-59-51.log](https://github.com/geode-sdk/geode/files/12005025/2023-07-10_18-59-51.log)

**Comment by Dimplycelery584** [comment]
[2023-07-10 20-34-53.zip](https://github.com/geode-sdk/geode/files/12006005/2023-07-10.20-34-53.zip)

**Comment by Dimplycelery584** [comment]
== Installed Mods ==
fleym.nongd | Fleym | v1.0.3 | Enabled | Loaded | 
camila314.acbypass | camila314 | v1.0.0 | Enabled | Loaded | 
geode.loader | Geode Team | v1.0.0-beta.18 | Enabled | Loaded | 
cattodev.gatobot | CattoDev | v1.3.0 | Disabled | Unloaded | 
camila314.bezier | camila314 | v1.0.0 | Enabled | Loaded | 
alk.editorcollab | alk | v1.12.1-beta | Enabled | Loaded | 
cvolton.capacity_fix | Cvolton | v1.0.1 | Enabled | Loaded | 
fig.video_player | fig | v1.0.1 | Disabled | Unloaded | 
hjfod.custom-keybinds | HJfod | v1.0.0 | Enabled | Loaded | 
hjfod.gdshare | HJfod | v1.0.0 | Enabled | Loaded | 
hjfod.gmd-api | HJfod | v1.0.1 | Enabled | Loaded | 
mat.circle-tool | mat | v1.0.0 | Enabled | Loaded | 
mat.fps-bypass | mat | v1.0.3 | Disabled | Unloaded | 
mat.practice-music | mat | v1.0.3 | Enabled | Loaded | 
mat.rgb-color-input | mat | v1.0.2 | Enabled | Loaded | 
mat.scroll-zoom | mat | v1.0.0 | Disabled | Unloaded | 
camila314.demonlist-button | camila314 | v1.0.0 | Disabled | Unloaded | 
camila314.startswitcher | camila314 | v1.0.0 | Enabled | Loaded |

**Comment by Dimplycelery584** [comment]
?

**Comment by Dimplycelery584** [comment]
anybody?

**Comment by cgytrus** [comment]
> anybody?

fyi, an issue tracker is not a real-time chat like Discord.

**Comment by Dimplycelery584** [comment]
ok, sorry

**Comment by cgytrus** [comment]
can't seem to reproduce on latest commit, can you try to reproduce the issue on the latest [dev release](https://github.com/geode-sdk/geode/releases/tag/nightly)?

**Comment by altalk23** [comment]
likely a custom keybinds related issue, can you reproduce without it
