### ISSUE TITLE
How to fix VSCode #include errors

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#194]
### Your Question

VSCode won't stop with the #include errors. I was attempting to create a new file for a dialog but VSCode outputs this error:

![image](https://github.com/geode-sdk/geode/assets/76978184/8c712ced-0c27-4de8-95d6-680b52f178e6)

I've followed the guide on the Geode Docs and have tried [this StackOverflow answer](https://stackoverflow.com/a/52796636), but they both did not work. The mod compiles just fine. How can I fix them?

**Comment by SpaghettDev** [comment]
try using Visual Studio lol

**Comment by cgytrus** [comment]
are you using the cmake tools vscode extension?

**Comment by TechStudent10** [comment]
Turns out not opening the project for 3 weeks works

**Comment by cgytrus** [comment]
well, that's fixed then, i guess. reopen if the problem appears again
