### ISSUE TITLE
Cobalt menu

### ISSUE THREAD

**Issue by NuggDev** [geode-sdk/geode#198]
### Platform

Windows

### Geode Version

v1.0.0

### Mods Installed

Cobalt Menu v0.1.2

### Expected Behavior

I expected it to update 

### Actual Behavior

It didnt fully download and gave me an error message

### Steps to Reproduce

I honestly don't know, I just tried to update the Cobalt menu and it have me a bug error

**Comment by Igbalabanov** [comment]
Same thing happens to me, o think this is an error with the mod repo/indexer

**Comment by cgytrus** [comment]
was fixed manually
~ courtesy of mat
