### ISSUE TITLE
Geode was working perfectly fine until now

### ISSUE THREAD

**Issue by Broccoliwagon** [geode-sdk/geode#201]
### Platform

MacOS

### Geode Version

v1.0.1(?)

### Mods Installed

anticheat (2).geode
camila314.acbypass.geode
camila314.demonlist-button.geode
fleym.nongd.geode
hjfod.custom-keybinds.geode
mat.practice-music.geode
mat.rgb-color-input.geode
mat.scroll-zoom.geode
ninxout.crystalclient.geode

### Expected Behavior

Expected to open as usual, as all the usual geode files I've been using forever were, and still are in their usual folders.

### Actual Behavior

Geometry Dash keeps opening without any signs of geode, just the normal untouched game. All my stats and noclipped levels are still there, but no mods, geode buttons, or hacks are present.

### Steps to Reproduce

I just opened GD one day and it wasn't loading geode.

### Additional Information

I did verify the integrity of the GD files beforehand, but when it no longer worked, I triple checked the geode files, and again they were all in the right spots, but just didn't work for some reason. My game also wasn't opening because of missing libraries (Which is why I verified the files) And I've tried re-installing, doing everything, and nothing has worked.

**Comment by Broccoliwagon** [comment]
I found the version, its 1.0.0. I don't think it matters though

**Comment by matcool** [comment]
did your game auto update, or did you install the new version?

**Comment by altalk23** [comment]
the 1.0.0 installer for macos was broken, I'd recommend using nightly installer right now

**Comment by Broccoliwagon** [comment]
> did your game auto update, or did you install the new version?

Well, steap updated about twice while I was working on this, but not recently beforehand.

**Comment by Broccoliwagon** [comment]
Does anyone know what geode means by "Unable to find restored fmod?"

**Comment by altalk23** [comment]
what is the exact message?

**Comment by Broccoliwagon** [comment]
> what is the exact message?

I just saw that when trying to uninstall geode using the installer.

**Comment by altalk23** [comment]
the old installer/uninstaller is deprecated currently, we now have new installers bundled with every release, you should be using them instead
and dont use the 1.0.0 one because its broken, use 1.0.1 when we release it in like 10 min

**Comment by Broccoliwagon** [comment]
> the old installer/uninstaller is deprecated currently, we now have new installers bundled with every release, you should be using them instead and dont use the 1.0.0 one because its broken, use 1.0.1 when we release it in like 10 min

Heres an error I get when trying to download a newer version: 
![Screen Shot 2023-08-03 at 5 32 15 PM](https://github.com/geode-sdk/geode/assets/133602771/d67b5d25-3a3c-4bc0-9f49-e555df0e5aba)

**Comment by altalk23** [comment]
Yes that is why the 1.0.0 installer is broken, it's fixed in 1.0.1

**Comment by Broccoliwagon** [comment]
> Yes that is how the 1.0.0 installer is broken, it's fixed in 1.0.1

Thanks, Ill try the 1.0.1 installer when it's released. Ill send an update when I do, but I'm guessing it should work.

**Comment by altalk23** [comment]
Alright, published 1.0.1

**Comment by Broccoliwagon** [comment]
Update: I installed 1.0.1, and everything is still there. The libraries, Geode files, but for some reason the game just refuses to use them. Are there any extra installation steps I must take?

**Comment by altalk23** [comment]
Fixed with 1.0.3 release.
