### ISSUE TITLE
Geode will not auto-update

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#202]
### Platform

Windows

### Geode Version

1.0.0-beta18

### Expected Behavior

I expected Geode to auto-update from my current version (listed above) to the latest release (1.0.0/1.0.1).

### Actual Behavior

Geode did not auto-update despite having the auto-update setting enabled.

![image](https://github.com/geode-sdk/geode/assets/76978184/8f1642c4-3a58-4f08-ba16-f27e327bc103)

### Steps to Reproduce

1. Open Geode on 1.0.0-beta18
2. No auto-updating occurs

**Comment by matcool** [comment]
someone correct me if im wrong, but i believe beta18 never actually had auto updating enabled

**Comment by TechStudent10** [comment]
> someone correct me if im wrong, but i believe beta18 never actually had auto updating enabled

It used to work before

**Comment by TechStudent10** [comment]
> we cant update beta 18 now lol

So just manually update to 1.0.0?

**Comment by matcool** [comment]
> > we cant update beta 18 now lol
> 
> So just manually update to 1.0.0?

yeah, i guess

**Comment by TechStudent10** [comment]
> > > we cant update beta 18 now lol
> > 
> > 
> > So just manually update to 1.0.0?
> 
> yeah, i guess

Installer did not work, but manually extracting the files works.

**Comment by matcool** [comment]
> > > > we cant update beta 18 now lol
> > > 
> > > 
> > > So just manually update to 1.0.0?
> > 
> > 
> > yeah, i guess
> 
> Installer did not work, but manually extracting the files works.

can you explain in what way?

**Comment by TechStudent10** [comment]
> > > > > we cant update beta 18 now lol
> > > > 
> > > > 
> > > > So just manually update to 1.0.0?
> > > 
> > > 
> > > yeah, i guess
> > 
> > 
> > Installer did not work, but manually extracting the files works.
> 
> can you explain in what way? and was it 1.0.1? because 1.0.0 mac installer is broken.

Correct, 1.0.1. It wouldn't let me through. I forgot what the exact error does but from what I can tell in #201 (the issue you're describing), it's the same thing (just on Windows this time). Geode errors then I'm booted into unmodded GD.

**Comment by cgytrus** [comment]
> > > > > > we cant update beta 18 now lol
> > > > > 
> > > > > 
> > > > > So just manually update to 1.0.0?
> > > > 
> > > > 
> > > > yeah, i guess
> > > 
> > > 
> > > Installer did not work, but manually extracting the files works.
> > 
> > 
> > can you explain in what way? and was it 1.0.1? because 1.0.0 mac installer is broken.
> 
> Correct, 1.0.1. It wouldn't let me through. I forgot what the exact error does but from what I can tell in #201 (the issue you're describing), it's the same thing (just on Windows this time). Geode errors then I'm booted into unmodded GD.

i thought i fixed that what
can you screenshot your gd folder

**Comment by TechStudent10** [comment]
> can you screenshot your gd folder

![image](https://github.com/geode-sdk/geode/assets/76978184/23844455-34b5-4081-a391-d9eec2cd8391)

**Comment by TechStudent10** [comment]
This is the correct one

**Comment by cgytrus** [comment]
> This is the correct/working one

thats not helpful.. i asked for the broken screenshot

**Comment by TechStudent10** [comment]
> > This is the correct/working one
> 
> thats not helpful.. i asked for the broken screenshot

Could've been more explicit ¯\_(ツ)_/¯

![image](https://github.com/geode-sdk/geode/assets/76978184/f2c6c8dc-3de4-4dd2-81d3-95e3fb5186ba)

(sorry for taking forever, had to get an unpatched version of GD)

This time, it shows the platform console (if you have it enabled) then just quits. From what I could see, the last line says `Entry Done` but I couldn't screenshot it because it happens in a split-second.
