### ISSUE TITLE
I can't launch when I install Geode

### ISSUE THREAD

**Issue by ethanapps** [geode-sdk/geode#204]
### Platform

MacOS

### Geode Version

v1.0.1

### Expected Behavior

Expected to be able to launch Geode
(I used to be able to)

### Actual Behavior

If I have Geode installed I can't launch GD

https://github.com/geode-sdk/geode/assets/12014157/1bfcc6b8-6a64-424a-808d-eb73b285a10b

### Steps to Reproduce

Idk it just started randomly happening

**Comment by ethanapps** [comment]
still happening with 1.0.2

**Comment by Sirsiraf** [comment]
same issue here i just installed the new version on a mac and gd won’t launch

**Comment by ethanapps** [comment]
fixed not by me but by the devs use this https://github.com/geode-sdk/geode/releases/tag/nightly

**Comment by altalk23** [comment]
yeah fixed with 1.0.3 will close the issue when i make the release
