### ISSUE TITLE
GD crashes when not playing but opened and trying to get back in

### ISSUE THREAD

**Issue by m1chael31** [geode-sdk/geode#209]
### Platform

Windows

### Geode Version

latest version

### Mods Installed

only the geode main mod

### Steps to Reproduce

i exited the game and tried to get back into the window but the game crashes

### Crash Report

[2023-08-17_13-33-36.log](https://github.com/geode-sdk/geode/files/12372157/2023-08-17_13-33-36.log)

**Comment by matcool** [comment]
can you consistently recreate the issue? can you give more detailed reproduction steps? i cant recreate it
