### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by marcelokula1** [geode-sdk/geode#210]
### Platform

Windows

### Geode Version

1.10

### Mods Installed

 editorcolab
 freewidnow
acbypass
demonlist-button
modmenutest
videoplayer
nongd
betterinfo
gdshare
restartkey
custom-keybinds
gmd-api
gd-platformer
reverse trigger

### Steps to Reproduce

i resize the window and i got back to main menu and change to fullscreen and i entered the create and it crashed my game

### Crash Report

[2023-08-18_19-09-03.log](https://github.com/geode-sdk/geode/files/12381546/2023-08-18_19-09-03.log)

**Comment by marcelokula1** [comment]
forgot to tell but i installed better edit and it don't work

**Comment by matcool** [comment]
please fill in the Mods Installed section

**Comment by marcelokula1** [comment]
Updated i think this is all that i got installed

**Comment by altalk23** [comment]
Sounds like a missing sprite issue, are you able to recreate in 1.3.0? there were some bugfixes related to that recently
