### ISSUE TITLE
Crystal Client crashes my game.

### ISSUE THREAD

**Issue by Honestyjsaua** [geode-sdk/geode#213]
### Platform

MacOS

### Geode Version

v1.10

### Mods Installed

crystal client v3.0.0

### Steps to Reproduce

Idk exactly how to reproduce it, but just try to play levels while using Crystal Client.

### Crash Report

After a while of using Geode with Crystal Client, every level i open crashes the game. Trying to disable Crystal client also crashes the game. The only way for me to play level is for me to get rid of Geode.

### Additional Information

idk

**Comment by altalk23** [comment]
you are supposed to report mod specific bugs to the mod author themselves, not to us
