### ISSUE TITLE
StartPosSwitcher is broken

### ISSUE THREAD

**Issue by ethanapps** [geode-sdk/geode#215]
### Platform

MacOS

### Geode Version

v1.1.0

### Mods Installed

Anticheat Bypass
Crystal Client
Geode
Nongd
StartPos Switcher

### Steps to Reproduce

Using startpos switcher in v1.1.0w

### Crash Report

[2023-08-20_09-30-22.log](https://github.com/geode-sdk/geode/files/12388277/2023-08-20_09-30-22.log)

### Additional Information

I think it crashes when using Geode v1.1.0 and Startpos Switcher(and maybe crystal client)

When i used Geode v1.0.3 it doesnt crash

**Comment by BoogieHasFun** [comment]
log states `It appears that the crash occurred while executing code from the "ninxout.crystalclient" mod.`. try using the mod without cystalclient

**Comment by ethanapps** [comment]
oh yeah it worked
