### ISSUE TITLE
Unwarranted lag while in levels.

### ISSUE THREAD

**Issue by xavwashere** [geode-sdk/geode#220]
### Platform

Windows

### Geode Version

v1.1.1

### Mods Installed

demonlist-button v1.0.0, GMD API v1.0.1, GDShare v1.0.0, Practice Music v1.0.4

### Expected Behavior

Game should run smoothly as it was like before installing Geode.

### Actual Behavior

High amounts of lag, worse than even on mobile.

### Steps to Reproduce

Install Geode
Enter a level
Profit

**Comment by altalk23** [comment]
Can't reproduce, are you certain Geode is the cause of it?

**Comment by xavwashere** [comment]
Hi, sorry for the late reply.
The lag started as soon as I installed Geode, but strangely, when I uninstalled and reinstalled GD to remove Geode, the lag remained.
But now it's mysteriously gone? This is quite strange.
