### ISSUE TITLE
every time i try to get on exit fullscreen (making my graphics better) makes my game crash >:(

### ISSUE THREAD

**Issue by cupgd1234** [geode-sdk/geode#223]
### Platform

Windows

### Geode Version

newest one

### Mods Installed

all of the gd share mods

### Expected Behavior

i expected to have it work but no

### Actual Behavior

crashed my fricking game

### Steps to Reproduce

exit fullscreen and two go to the create tab

**Comment by altalk23** [comment]
looks like a mod specific issue, we can't help much without a crashlog or any descriptive information anyway
