### ISSUE TITLE
Entire game crashing when entering a Non-Robtop Level

### ISSUE THREAD

**Issue by Nitr0h** [geode-sdk/geode#227]
### Platform

MacOS

### Geode Version

v1.2.0

### Mods Installed

nongd, crystal client, betteredit, circle tool, small additions, betterinfo

### Steps to Reproduce

- Have these mods enabled
- Open any level that isn't a Main Level (including your own)
- Instantly Crash

### Crash Report

[2023-09-04_21-53-22.log](https://github.com/geode-sdk/geode/files/12517925/2023-09-04_21-53-22.log)
[Geode 04 Sep 21.52.30.log](https://github.com/geode-sdk/geode/files/12517926/Geode.04.Sep.21.52.30.log)

**Comment by altalk23** [comment]
looks like a betteredit bug
