### ISSUE TITLE
whatever

### ISSUE THREAD

**Issue by stopq** [geode-sdk/geode#228]
### Platform

Windows

### Geode Version

v1.2.1

### Mods Installed

megahack, drawing utilities, editor collab, align to,  better info, capacity fix, nong gd, devtools, geode mouse api, better edit 5 alpha 7, custom keybinds, gdshare, hjfod gmd api, circle tool.

### Steps to Reproduce

I think its something to do with changing the color of an object cause its crashing when I do that

### Crash Report

[2023-09-06_21-26-53.log](https://github.com/geode-sdk/geode/files/12544576/2023-09-06_21-26-53.log)

**Comment by altalk23** [comment]
looks like a betteredit bug
