### ISSUE TITLE
My game crashed after downloading mod

### ISSUE THREAD

**Issue by SiliSpinoCobra** [geode-sdk/geode#229]
### Platform

MacOS

### Geode Version

v1.2.1

### Mods Installed

FPS Bypass v1.0.6
Geode v1.2.1

### Steps to Reproduce

By swiping to another app.

### Additional Information

This started after I installed Geode and FPS Bypass. It doesn't save any of my progress, even when I save my account.

**Comment by altalk23** [comment]
Update fps bypass to 1.0.7
