### ISSUE TITLE
Cannot build on Mac

### ISSUE THREAD

**Issue by MarioMastr** [geode-sdk/geode#231]
im trying to build gd share and then when it comes to the linking portion i always seem to get errors regarding it not having the correct architecture. this happens with other mods compatible with mac too

<img width="682" alt="Screenshot 2023-09-09 at 12 50 01" src="https://github.com/geode-sdk/cli/assets/84964352/78cce4e5-4fcc-46d0-85fd-7ca0833f844a">

**Comment by altalk23** [comment]
You need to either have set(CMAKE_OSX_ARCHITECTURES "x86_64") on the CMakeLists.txt or add -DCMAKE_OSX_ARCHITECTURES=x86_64 flag while configuring the cmake

**Comment by MarioMastr** [comment]
ok that worked thank you
