### ISSUE TITLE
I beat Shadow Temple and my game crashed :( (playing with mhv7)

### ISSUE THREAD

**Issue by LukaTV939** [geode-sdk/geode#232]
### Platform

Windows

### Geode Version

v1.3.0

### Mods Installed

I'm not going to mention every mod because I'm mad >:( , here's the mods folder instead https://www.mediafire.com/file/2pggwko9kjermjp/mods.zip/file

### Steps to Reproduce

beat the level and then the game crashes

### Crash Report

[2023-09-09_22-32-20.log](https://github.com/geode-sdk/geode/files/12566668/2023-09-09_22-32-20.log)

**Comment by altalk23** [comment]
try without megahack idk its a mod specific bug so its not very advisable to report it anyway

**Comment by altalk23** [comment]
Looking more into it sounds like a achievment failed to load since the current ccscene is null, might be a geode issue, needs testing

**Comment by LukaTV939** [comment]
I only now noticed that I have high capacity mode on while having the capacity fix mod on. I'll close this issue in a couple of days if that was the problem

**Comment by LukaTV939** [comment]
nvm the game still crashes, here's another crash log just in case 
[2023-09-14_11-37-29.log](https://github.com/geode-sdk/geode/files/12607328/2023-09-14_11-37-29.log)

**Comment by LukaTV939** [comment]
I only now realized what it is and I'm making a second issue for that.
It was not because of mods I installed

**Comment by altalk23** [comment]
Can you replicate the issue without megahack?
