### ISSUE TITLE
My game crashes alot

### ISSUE THREAD

**Issue by Xboy3998** [geode-sdk/geode#233]
### Platform

Windows

### Geode Version

v1.3.0

### Mods Installed

better info
custom keybinds
capacity fix
devtools
drawing utilities
mega hack
nongd
run info
texture loader
video player

### Steps to Reproduce

-First open the game
-Open a level
-Exit the level
-Open the level again or another one
-The crash happens
-Same for the editor

### Crash Report

[Geode 10 Sep 09.48.40.log](https://github.com/geode-sdk/geode/files/12567743/Geode.10.Sep.09.48.40.log)
[2023-09-10_09-51-29.log](https://github.com/geode-sdk/geode/files/12567744/2023-09-10_09-51-29.log)

**Comment by altalk23** [comment]
try disabling custom keybinds

**Comment by altalk23** [comment]
Checking again yes it is a custom keybinds issue, it calls the pushButton function while there is no valid baselayer instance
