### ISSUE TITLE
Undefined Symbol Errors

### ISSUE THREAD

**Issue by MarioMastr** [geode-sdk/geode#238]
### Your Question

cocos2d doesn't have a library in place on Mac, leading to undefined symbol errors like this one
<img width="682" alt="Screenshot 2023-09-12 at 17 20 47" src="https://github.com/geode-sdk/geode/assets/84964352/29d98f5d-ad54-4207-b71e-68d2195016dc">

**Comment by matcool** [comment]
go define it https://github.com/geode-sdk/geode/blob/main/bindings/Cocos2d.bro :+1:

**Comment by MarioMastr** [comment]
ok i did
<img width="1440" alt="Screenshot 2023-09-14 at 17 33 47" src="https://github.com/geode-sdk/geode/assets/84964352/786d6201-c70c-442e-9e34-ba55a55da688">

**Comment by altalk23** [comment]
you are supposed to find the offsets of them in the gd binary using smth like ghidra or ida not what that is. If you want to use cocos' source directly just put it into your own source file

**Comment by MarioMastr** [comment]
Is this going to be committed to the main branch? No. Do I plan to? No. This is purely local and nobody else will be affected by this. Let me do what I want on my local machine. Please and thank you.

**Comment by altalk23** [comment]
Keep rocking then
