### ISSUE TITLE
Crash while disabling/enabling a mod while looking at the author page (possibly a linux/proton experimental issue)

### ISSUE THREAD

**Issue by RandomVee** [geode-sdk/geode#239]
### Platform

Windows

### Geode Version

v1.3.1

### Mods Installed

  Loaded |  Enabled | [v1.3.1] geode.loader
  Loaded |  Enabled | [v1.3.0] cattodev.gatobot
  Loaded |  Enabled | [v7.1.1-beta.5] absolllute.megahack
Unloaded | Disabled | [v1.0.0] cgytrus.patcher
  Loaded |  Enabled | [v1.0.0] alphalaneous.separatedualicons
  Loaded |  Enabled | [v3.0.4] cvolton.betterinfo
  Loaded |  Enabled | [v1.0.2-beta] camila314.betterloading
  Loaded |  Enabled | [v1.0.0] cgytrus.solid-player-trail
  Loaded |  Enabled | [v1.0.6] fleym.nongd
  Loaded |  Enabled | [v1.0.1] geode.texture-loader
  Loaded |  Enabled | [v1.0.1] hjfod.gdshare
  Loaded |  Enabled | [v1.0.2] hjfod.gmd-api
  Loaded |  Enabled | [v1.0.5] mat.practice-music
  Loaded |  Enabled | [v1.0.1] mat.run-info
  Loaded |  Enabled | [v1.0.0] mat.song-search

### Steps to Reproduce

1) Open geometry dash, and go to the Geode menu (while having GDShare installed)
2) Go to your install mods and find a mod with an author name
3) Click on the author's name (gold text below the mod name, in this case HJfod)
4) Disable/enable any mod by clicking the checkbox
5) Crash.

### Crash Report

[2023-09-13_20-37-42.log](https://github.com/geode-sdk/geode/files/12603251/2023-09-13_20-37-42.log)

### Additional Information

Likely a wine/proton issue. Upon further testing it crashes with any mod that's enabled or disabled while checking the author's page. When the game starts again, the mod remains unchanged (still enabled or disabled)

**Comment by altalk23** [comment]
Finally an actual geode issue reported, will work on it now
