### ISSUE TITLE
Crash upon opening level.

### ISSUE THREAD

**Issue by Marblespoonkinda** [geode-sdk/geode#240]
### Platform

MacOS

### Geode Version

v1.3.1

### Mods Installed

BetterInfo
BetterLoading
Crystal Client
Drawing Utilities
Fullscreen Fix
nongd
RobTop Bot
Small Additions
Texture Loader

### Steps to Reproduce

I opened the game and tried to play stalemate by nox.

### Crash Report

[2023-09-14_10-23-46.log](https://github.com/geode-sdk/geode/files/12611668/2023-09-14_10-23-46.log)

### Additional Information

stalemate hates me. its literally only fucking stalemate.

**Comment by matcool** [comment]
try without betterloading

**Comment by altalk23** [comment]
@c314m betterloading :fire:
