### ISSUE TITLE
My game crashing again!

### ISSUE THREAD

**Issue by Xboy3998** [geode-sdk/geode#242]
### Platform

Windows

### Geode Version

v1.3.1

### Mods Installed

![image_2023-09-16_003800450](https://github.com/geode-sdk/geode/assets/125828514/ce3f9e6c-0d8d-4e4d-b8ab-0e4005361158)

### Steps to Reproduce

1) Open the game
2) Experience the crash

### Crash Report

[2023-09-16_00-36-22.log](https://github.com/geode-sdk/geode/files/12629183/2023-09-16_00-36-22.log)

[Geode 16 Sep 00.36.20.log](https://github.com/geode-sdk/geode/files/12629185/Geode.16.Sep.00.36.20.log)

### Additional Information

This is cause of libcocos, the game engine but i think it has to do with one of the mods.

**Comment by altalk23** [comment]
Vanilla gd save file bug, use a tool like [save file fix](https://github.com/WEGFan/Geometry-Dash-Savefile-Fix) to fix it
