### ISSUE TITLE
Using shortcut for hitbox viewer crashes the game (Crystal client)

### ISSUE THREAD

**Issue by yoncawave** [geode-sdk/geode#243]
### Platform

MacOS

### Geode Version

v1.3.1

### Mods Installed

Crystal client v4.0.0
GMD API v1.0.2
Scroll zoom v1.0.1
Texture loader v1.0.1

### Steps to Reproduce

1. Add a shortcut for hitboxes
2. Use shortcut

### Crash Report

[2023-09-16_10-22-35.log](https://github.com/geode-sdk/geode/files/12640072/2023-09-16_10-22-35.log)

### Additional Information

Switching it in mod menu is ok, the state before switching doesn't matter

**Comment by altalk23** [comment]
Crystal client issue, report it to its developer [ninxout](https://github.com/ninXout/Crystal-Client)
