### ISSUE TITLE
GD Crashes when I edit levels / Change level settings

### ISSUE THREAD

**Issue by Broccoliwagon** [geode-sdk/geode#245]
### Platform

MacOS

### Geode Version

1.3.3

### Steps to Reproduce

I created a level, and opening the settings just crashed my game 70% of the time.

### Additional Information

I've tried many things. For one, I deleted a lot of my copies of object-heavy levels as that has caused this issue for people in the past. No luck. I thought it was because it was overloading my RAM or CPU or something so I closed almost all applications, and it was still crashing. I do have 9 mods enabled that it wouldn't let me upload here, and I tried disabling every editor-related mod, but it's still crashing so I can't really use the editor right now.

**Comment by Broccoliwagon** [comment]
[2023-09-16_18-27-23.log](https://github.com/geode-sdk/geode/files/12641741/2023-09-16_18-27-23.log)

Btw I believe this is the crash log.

**Comment by FigmentBoy** [comment]
This appears to be caused by ninXout's Crystal Client, you can contact them at [their discord server](https://discord.gg/xV5dekWHTd).
