### ISSUE TITLE
crash when i entered to the icons menu

### ISSUE THREAD

**Issue by Abuigsito** [geode-sdk/geode#250]
### Platform

Windows

### Geode Version

v1.3.3

### Mods Installed

x | [v1.3.3] geode.loader
x | [v1.0.1] mat.run-info
x | [v7.1.1-beta.5] absolllute.megahack
x | [v1.0.2] hjfod.gmd-api
x | [v1.0.2] alphalaneous.separatedualicons
x | [v1.0.1] hjfod.gdshare
x | [v3.0.5] cvolton.betterinfo

### Steps to Reproduce

1) open the game
2) click to the icons menu
and crash 

### Crash Report

https://gist.github.com/Abuigsito/4a97cb98cf948dcab7b5450c51c635e5

### Additional Information

i have windows 7 (lol)

**Comment by altalk23** [comment]
Bug caused by Alphalaneous' separate dual icons mod, report it to them

**Comment by Alphatism** [comment]
:trollface:
