### ISSUE TITLE
IDs shifted in GJGarageLayer

### ISSUE THREAD

**Issue by Alphatism** [geode-sdk/geode#251]
### Platform

Windows

### Geode Version

v1.3.3

### Expected Behavior

The IDs to be assigned to the right elements.

### Actual Behavior

The IDs get shifted by one.
![image](https://github.com/geode-sdk/geode/assets/38200084/bfea6d52-dd7f-49be-867f-6b875e1ec028)

![image](https://github.com/geode-sdk/geode/assets/38200084/a308caa5-7b99-42a5-9b33-0f09113526c2)

### Steps to Reproduce

1. Be logged out
2. Change your display name in the garage
3. Leave and open the garage, you will see that all the element IDs are shifted

**Comment by altalk23** [comment]
fixed with (dd0179c), should be fixed in 1.3.5

**Comment by altalk23** [comment]
uhhh i think it's fixed, might need testing
