### ISSUE TITLE
Game crash on info button on 'mod requires x addons to function'

### ISSUE THREAD

**Issue by Explodingbill** [geode-sdk/geode#254]
### Platform

MacOS

### Geode Version

v1.3.4

### Mods Installed

cvolton.betterinfo v3.0.6
geode.devtools v1.2.2
geode.mouse-api v1.0.0
hjfod.gdshare v1.0.1
hjfod.gmd-api v1.0.2
mat.scroll-zoom v1.0.1
mat.song-search v1.0.0

### Steps to Reproduce

1) Find an addon in the download list that depends on another addon
2) When it comes up with the AlertLayer with the 'Info' and 'Download' buttons, press the Info button
3) the game crashes

### Crash Report

[Geode 20 Sep 15.58.33.log](https://github.com/geode-sdk/geode/files/12669120/Geode.20.Sep.15.58.33.log)

### Additional Information

some of the button names were incorrect when i descibed them because i forgor 💀

**Comment by altalk23** [comment]
Fixed with v1.3.5
