### ISSUE TITLE
Geode crashes when attempting to load a level using GDShare

### ISSUE THREAD

**Issue by superdude311** [geode-sdk/geode#255]
### Platform

Windows

### Geode Version

v1.3.4

### Mods Installed

Betterinfo v3.0.7
custom keybinds v1.1.2
demonlist-button v1.0.0
fps bypaass v1.0.4
fps shower v1.0.2
gmd api v1.0.2
gdshare v1.0.1
nongd v1.0.6
practice music v1.0.5

### Steps to Reproduce

I went to the build tab and level create screen, then clicked the load levels button. selected a level titled "Unamed 1.gmd" and the game crashed

### Crash Report

https://pastebin.com/Kmc0ADgy crash report
https://pastebin.com/tyfSkrBg log file

**Comment by altalk23** [comment]
Go report this issue to its developer Hjfod (though he no longer maintains his mods)
Make the issue on that repository someone will get to it eventually
