### ISSUE TITLE
amethyst crash report

### ISSUE THREAD

**Issue by steveco75** [geode-sdk/geode#259]
### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

crystal client v4.0

### Steps to Reproduce

1. open up any level
2. put on record in amethyst bot and 0.5x speed
3. play the level
4. get kicked out halfway through making the macro (i also want this to change)
5. record again
6. crash
(at least for me)

### Crash Report

[2023-09-23_23-02-57.log](https://github.com/geode-sdk/geode/files/12707755/2023-09-23_23-02-57.log)

**Comment by altalk23** [comment]
Go report this issue to its developer (ninxout) not us
