### ISSUE TITLE
Improper ::scene reimplementations

### ISSUE THREAD

**Issue by Cvolton** [geode-sdk/geode#26]
in bindings/GeometryDash.bro practically every layer has scene reimplemented like this

```cpp
static void scene(GJGameLevel* level) {
    auto pScene = cocos2d::CCScene::create();

    pScene->addChild(reinterpret_cast<cocos2d::CCNode*>(EditLevelLayer::create(level)));

    cocos2d::CCDirector::sharedDirector()->replaceScene(
        cocos2d::CCTransitionFade::create(.5f, pScene)
    );
}
```

The fact that it is reimplemented makes sense for a lot of functions, as the majority of ::scene calls are inlined (not all though, notable exception being LevelBrowserLayer, which exists on Windows but is reimplemented in here anyway)

The issue is though that by looking at the Android version we can gather the implementation doesn't exactly match the one in real GD, which is just this part:

```cpp
static cocos2d::CCScene* scene(GJGameLevel* level) {
    auto pScene = cocos2d::CCScene::create();

    pScene->addChild(reinterpret_cast<cocos2d::CCNode*>(EditLevelLayer::create(level)));

    return pScene;
}
```

the replaceScene call is then handled by the caller. I'm assuming the reason for this is that Rob sometimes uses replaceScene and sometimes he uses pushScene and wants to be able to switch between these 2 for individual button callbacks at will. No matter what the reason for Rob's decision about this is though, it is inconsistent with the code currently in here.

I would also advocate for calling the function directly whenever possible instead of reimplementations, however the behavior inconsistency would need to be fixed first for that.

**Comment by altalk23** [comment]
sounds like a gd.h legacy code to me 🙄 , no function in android calls replaceScene/pushScene, honestly i would prefer if the functions match and be 
```cpp
static CCScene* scene(GJGameLevel* level) {
    auto scene = CCScene::create();

    scene->addChild(EditLevelLayer::create(level));

    return scene;
}
``` 
(well there is also ones that set the scene enum too but we can add those)
