### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#260]
### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

betterinfo 3.0.7
custom keybinds 1.1.2
crystal client 4.0.0
editor collab 1.12.11 beta
nongd 1.0.6
rgb color input 1.0.2

### Steps to Reproduce

I press the 'save and play' button, and suddenly the game crashed less than 1 second.
I could see the level before the crash.

### Crash Report

[https://gist.github.com/BwompYes/3460d41186b5ff620736da4195432a2f](url)

**Comment by Fleeym** [comment]
@ninXout all yours

**Comment by altalk23** [comment]
crystal client issue report to its developer ninxout
