### ISSUE TITLE
gd crash

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#261]
### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

betterinfo 3.0.7
custom keybinds 1.1.2
crystal client 4.0.0
editor collab 1.12.11 beta
nongd 1.0.6
rgb color input 1.0.2

### Steps to Reproduce

I was recording a macro for my level showcase and I found an error in my level so I fixed it(the record button was still on while fixing).
And I came back to the level and I cleared the macro and started recording the macro again. And suddenly the game crashed. I remember I was pressing spacebar(because I'm a keyboard player), and no other keys.

### Crash Report

https://gist.github.com/BwompYes/af61865b52b2000c95027e194793bb63

**Comment by altalk23** [comment]
crystal client issue report to its developer ninxout
