### ISSUE TITLE
Geode Crash when seeing other mods

### ISSUE THREAD

**Issue by who-is-thiss** [geode-sdk/geode#263]
### Geode Issue

- [X] I confirm that this crash is directly related to Geode Loader.

### Platform

Windows

### Geode Version

v1.3.4

### Mods Installed

rlt.gd.platformer 1.0.0

### Steps to Reproduce

Open the mods download menu
Download the Cobalt Menu
Click on "View" when asked to see the other mods that will install with it
Crash occurs

### Crash Report

[2023-09-24_15-41-37.log](https://github.com/geode-sdk/geode/files/12709633/2023-09-24_15-41-37.log)

**Comment by altalk23** [comment]
ok yeah apparently i accidentally removed a nullptr check when adding multiple version support, should be fixed in 1.3.5
