### ISSUE TITLE
Game crashes becuase of quests

### ISSUE THREAD

**Issue by LukaTV939** [geode-sdk/geode#270]
### Geode Issue

- [ ] I confirm that this crash is directly related to Geode Loader.

### Platform

Windows

### Geode Version

v1.3.4

### Mods Installed

== Installed Mods ==
x | [v1.0.6] fleym.nongd
x | [v1.3.4] geode.loader
x | [v1.0.1] gdutilsdevs.gdutils
x | [v1.3.0] cattodev.gatobot
x | [v7.1.1-beta.5] absolllute.megahack
x | [v3.0.7] cvolton.betterinfo
x | [v1.0.1] fig.video_player
x | [v3.0.0-beta.3] fig.zbot
x | [v1.0.1] mat.scroll-zoom
x | [v1.1.2] geode.custom-keybinds
x | [v1.0.3] hjfod.gdshare
x | [v1.0.3] hjfod.gmd-api
x | [v1.0.0] mat.circle-tool
x | [v1.0.0] mat.song-search
x | [v1.0.2] mat.rgb-color-input
x | [v1.0.1] mat.run-info

### Steps to Reproduce

Beat any level that would complete a quest. [Streamable Video](https://streamable.com/9r65gp)

### Crash Report

https://gist.github.com/LukaTV939/9ede4b7aa5479a68f8610e3304a738ca

**Comment by altalk23** [comment]
Can you replicate the issue without megahack?

**Comment by LukaTV939** [comment]
> Can you replicate the issue without megahack?
> 

Tried to replicate without any mod and it didn't crash, but it was taking a while to process. Here's another video without any mods on https://streamable.com/wrpxd6 (weird processing happends at 1:23)

**Comment by altalk23** [comment]
Then sounds like one of your mods is the reason of the crash, most likely megahack since that is the only mod that I know of in the list that messes with the running scene
