### ISSUE TITLE
crash when entering level with crystal client

### ISSUE THREAD

**Issue by ShockedGaming** [geode-sdk/geode#271]
### Geode Issue

- [X] I confirm that this crash is directly related to Geode Loader.

### Platform

Windows

### Geode Version

1.3.4

### Mods Installed

ninxout.crystalclient.v4.0.1

### Steps to Reproduce

enter a level

### Crash Report

[Geode 29 Sep 21.59.28.log](https://github.com/geode-sdk/geode/files/12767893/Geode.29.Sep.21.59.28.log)

**Comment by cgytrus** [comment]
mod specific issue
