### ISSUE TITLE
wow another crash I wonder who has to work

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#272]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

betterinfo 3.0.7
crystal client 4.0.1
editor collab 1.12.13
globed 0.3.1
nongGd 1.0.6
rgb color input 1.0.2

### Steps to Reproduce

I playtested a level and went straight back to the editor. And then the game crashed.
I'm not sure what is the problem but it always happens.

(and why is the checkbox that says 'I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.' required?)

### Crash Report

https://gist.github.com/BwompYes/c90c5231dbd8b19e17b9a07cc004f339

**Comment by altalk23** [comment]
> (and why is the checkbox that says 'I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.' required?)
Because we deal with issues directly with Geode loader and not mods themselves.

This is technically a mod specific issue but it sounds interesting ill keep it up for now. Can you also send your log file too?

**Comment by altalk23** [comment]
Try this without editor collab and/or crystal client. If any of them fixes the issue I will close the issue and report them to their dev (me for editorcollab and ninxout for crystal client)
