### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#273]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

== Installed Mods ==
[v1.0.2] mat.rgb-color-input
[v0.3.1] dankmeme.globed
[v4.0.1] ninxout.crystalclient
[v3.0.7] cvolton.betterinfo
[v1.3.4] geode.loader
[v1.0.6] fleym.nongd
[v1.12.13-beta] alk.editorcollab
[v1.0.0] cgytrus.menu-shaders

I copied it from my crashlog

### Steps to Reproduce

I opened gd, and everything was fine.

all 8 mods were loaded successfully, and the game crashed while loading other features. I think it's because of the launcher.

### Crash Report

https://gist.github.com/BwompYes/fb63087a96bdbd0171edc78dd8b6cb32

**Comment by cgytrus** [comment]
menu shaders issue
