### ISSUE TITLE
again crash

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#274]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

1.3.4

### Mods Installed

== Installed Mods ==
x | [v1.0.2] mat.rgb-color-input
x | [v0.3.1] dankmeme.globed
x | [v3.0.7] cvolton.betterinfo
x | [v1.12.13-beta] alk.editorcollab
x | [v4.0.1] ninxout.crystalclient
x | [v1.0.6] fleym.nongd
x | [v1.3.4] geode.loader

### Steps to Reproduce

I was placing startposes to practice a 9 minutes level, and the game crashed.

### Crash Report

https://gist.github.com/BwompYes/a68eb068d178cb27cb3e0161f02a75ac

### Additional Information

I think this is likely caused by playing an XXL level.

**Comment by cgytrus** [comment]
my brother in christ please read the description of the checkbox you check open issues one the mod's specific issue trackers this is a crystal client issue

**Comment by iAndyHD3** [comment]
💀

**Comment by ninXout** [comment]
This seems to be an issue with the “Smart StartPos [BETA]” mod, please turn it off for now.
