### ISSUE TITLE
When You Save A macro your game crashes

### ISSUE THREAD

**Issue by Zeddish213** [geode-sdk/geode#279]
### Geode Issue

i have tried for a while still not fixed

### Platform

MacOS

### Geode Version

1.3.5

### Mods Installed

fps bypass, fps display, crystal client, run info

### Steps to Reproduce

just keep going to 100% macro runs and hit save over and over

### Crash Report

[2023-10-02_19-02-30.log](https://github.com/geode-sdk/geode/files/12782441/2023-10-02_19-02-30.log)

**Comment by Fleeym** [comment]
you should post Crystal related issues in the Crystal Client discord server

https://discord.gg/xV5dekWHTd
