### ISSUE TITLE
My game crashes too much

### ISSUE THREAD

**Issue by ansahtoby12** [geode-sdk/geode#289]
### Geode Issue

Geode Loader

### Platform

MacOS

### Geode Version

v1.3.5

### Mods Installed

alk.drawing-utilities.geode
alk.editorcollab.geode
alk.fps-shower.geode
alk.fullscreen-fix.geode
camila314.alignto.geode
camila314.demonlist-button.geode
dankmeme.globed.geode
hjfod.gdshare.geode
hjfod.gmd-api.geode
mat.circle-tool.geode
ninxout.crystalclient.geode

### Steps to Reproduce

1) Opening the Editor and then closing it then opening it again crashes the game for whatever reason
2) Trying to open the settings button (which changed bg/obj/song/speed/mode etc...) in the Editor

### Crash Report

[2023-10-09_21-22-16.log](https://github.com/geode-sdk/geode/files/12851808/2023-10-09_21-22-16.log)

### Additional Information

Im not sure why this is caused but please fix it as it is basically impossible to play gd with this glitch. Thanks so much. Also I have tried to uninstall geode and gd multiple times and it still didn't fix the problem.

**Comment by cgytrus** [comment]
please, fill out the template correctly.
