### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by python-nerd-3** [geode-sdk/geode#298]
### Your Question

Geode has just been a paperweight that significantly increases loading time and causes crashes. I need a method to uninstall it.

**Comment by Cvolton** [comment]
~~me when i use geode without using it for mods~~

Please state your Geode version and platform before we can point you to the correct uninstall instructions

**Comment by python-nerd-3** [comment]
v1.0.0

**Comment by Cvolton** [comment]
and platform? (windows, mac, android?)

also of note is that this is an outdated version of Geode at this point, so in the odd chance you would want to give Geode another shot, I recommend updating to the latest version, since most mods aren't available for 1.0.0

**Comment by python-nerd-3** [comment]
Windows

**Comment by Fleeym** [comment]
Remove geode.dll, XInput9_1_0.dll, GeodeUpdater.exe (if it exists) and the geode folder from your Geometry Dash folder
