### ISSUE TITLE
my gd crashed while im botting level

### ISSUE THREAD

**Issue by Imthecup** [geode-sdk/geode#300]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.5

### Mods Installed

Geode version 1.3.5 review
Thanks you guys for making amazing mod for GD
I can download mods, texture packs, etc...
But while I'm botting levels or turn on speedhack, it crashed immediately.
Hope you can help me about this!!!
P/s: sorry for my English mistake

### Steps to Reproduce

It crashed when I'm botting bloodbath and editing my levels

### Additional Information

It's look like crashed by speedhack or smth like that

**Comment by JOEYOCHO** [comment]
You have mods though I'd you are speed hacking and it only happens when you speed hack so how could it be a mod loader issue

**Comment by CattoDev** [comment]
This can only be a mod issue,
which mods are you using?
