### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Amongusasdo** [geode-sdk/geode#302]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.5

### Mods Installed

Crystal Client

### Steps to Reproduce

I did use a macro for deadlocked

### Crash Report

[Geode 15 Oct 11.59.12.log](https://github.com/geode-sdk/geode/files/12909874/Geode.15.Oct.11.59.12.log)

**Comment by Alphatism** [comment]
Crystal Client issue, please read the checkbox before checking it

**Comment by altalk23** [comment]
Please read the checkbox you just checked that says "NOT related to a mod"
