### ISSUE TITLE
I created a level, add some gameplay and the game crashed

### ISSUE THREAD

**Issue by hmh2010** [geode-sdk/geode#311]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v1.3.5

### Mods Installed

Anticheat bypass, betterinfo, crystal client, demonlist button, fps shower, gd utils, gmd api, gd share, globed, intergrated loquibot, nongd, startpos switcher, texture loader, volume scroll wheel

### Steps to Reproduce

1) I open the editor
2) Open the level that i'm working on
3) add some gameplay, decor
4) I saved the level by press the save and quit button
5) And it crashed.

### Crash Report

[2023-10-19_13-41-51.log](https://github.com/geode-sdk/geode/files/13038953/2023-10-19_13-41-51.log)

**Comment by Fleeym** [comment]
Does this crash happen every time you save and exit? If it does, try disabling globed or crystal client and see if the crash persists.

**Comment by hmh2010** [comment]
Yeah I'll do that
thanks!

**Comment by hmh2010** [comment]
I disable crystal client and it worked.
I think crystal client has a bug or sth

**Comment by Fleeym** [comment]
@ninXout you should take a look at this

**Comment by CattoDev** [comment]
This is obviously a mod issue though

**Comment by altalk23** [comment]
>  I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.
You should check out what you check

**Comment by hmh2010** [comment]
> > I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.
> 
> You should check out what you check

Yeah I'm sorry but when I check the check box, it says required

**Comment by CattoDev** [comment]
> > > I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.
> > 
> > You should check out what you check
> 
> Yeah I'm sorry but when I check the check box, it says required
> 

This is the exact reason it does this.
