### ISSUE TITLE
Update index in separate thread

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#313]
### Geode Version

1.3.4

### Related Problem

Geode takes a long time to update the index and it freezes the game sometimes

### Your Solution

Running the update method in a seperate thread might alieveate some of the issues. I think GitHub might be a bottleneck but that's out the scope of this issue.

**Comment by Netherbat** [comment]
I cannot understand why it was not this way from the beginning.

**Comment by altalk23** [comment]
its already in a separate thread

**Comment by matcool** [comment]
this issue is a bit old but whenever the index items are loaded the game gets a huge lagspike, since that loads in the main thread.
this will prob be fixed once we switch to the standalone server anyways

**Comment by TechStudent10** [comment]
> this issue is a bit old but whenever the index items are loaded the game gets a huge lagspike, since that loads in the main thread.
> this will prob be fixed once we switch to the standalone server anyways

yeah but imo this should remain open until the switch
