### ISSUE TITLE
Make the Geode options more accessible

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#314]
### Geode Version

1.3.4

### Your Solution

Pinning the Geode mod at the top would just be a nice QoL feature.

**Comment by matcool** [comment]
geode pinned at the top has been done ages ago, and new ui has a button specifically for geode settings

**Comment by TechStudent10** [comment]
> geode pinned at the top has been done ages ago, and new ui has a button specifically for geode settings

epic ((this issue is 8 months old))
