### ISSUE TITLE
Dual crash report

### ISSUE THREAD

**Issue by DavidoLuxzz** [geode-sdk/geode#316]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v1.3.5

### Mods Installed

alk.fullscreen-fix
hjfod.gmd-api
hjfod.gdshare
alk.small-additions
geode.texture-loader
ninxout.crystalclient

### Steps to Reproduce

1) Open Geometry Dash
2) Go to Create/My Levels where I have a copy of an level Stalemate (Insane Demon) (it happens also if I go directly to the level with search)
3) Playing level in practice mode until I am at the dual cube which is around 40% at the level
4) Crash :(

### Crash Report

[2023-10-22_13-27-10.log](https://github.com/geode-sdk/geode/files/13063165/2023-10-22_13-27-10.log)

### Additional Information

please fix this, this is my first insane demon

**Comment by dankmeme01** [comment]
It appears that the crash occurred while executing code from the "ninxout.crystalclient" mod. Please submit this crash report to its developer (ninXout) for assistance.
