### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by SkyIslandExplore** [geode-sdk/geode#326]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

== Installed Mods ==
x | [v1.3.6] geode.loader
x | [v1.12.13-beta] alk.editorcollab
x | [v1.0.0] nef.iconsave
x | [v1.0.2-beta] camila314.betterloading
x | [v1.1.0] geode.texture-loader
x | [v5.0.0-alpha.10] be_team.betteredit
x | [v2.2.5] alk.small-additions
x | [v1.0.0] balt.freewindow
x | [v1.1.0] be_team.editorapi
x | [v1.1.0] capeling.icon_profile
x | [v3.0.9] cvolton.betterinfo
x | [v1.0.5] mat.practice-music
x | [v0.4.2] dankmeme.globed
x | [v1.0.0] deathfuel.blink
x | [v1.2.3] fleym.nongd
x | [v1.0.2] gdutilsdevs.gdutils
x | [v1.2.2] geode.custom-keybinds
x | [v1.0.3] hjfod.gmd-api
x | [v1.2.3] geode.devtools
x | [v1.0.4] hjfod.gdshare
x | [v1.0.0] melody.antiantialttab
x | [v4.0.1] ninxout.crystalclient
x | [v1.5.2] tpdea.betterpause-Better

### Steps to Reproduce

1 : Saved Levels.
2 : choice a level and open it
3 : crash

### Crash Report

https://drive.google.com/drive/folders/1IIc6okKxGhm-yosJOx15ejmXIUR9XHKK?usp=sharing

**Comment by dankmeme01** [comment]
hello here's steps to fix :

- uninstall crystal client

**Comment by SkyIslandExplore** [comment]
I found ! The option : "Copy Song ID" crash the game with opening a level.
