### ISSUE TITLE
Geode crashed but IDK why

### ISSUE THREAD

**Issue by BwompYes** [geode-sdk/geode#329]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

1.3.6

### Mods Installed

== Installed Mods ==
x | [v1.0.0] n.level_pronouns
x | [v1.0.3] hjfod.volumescrollwheel
x | [v1.1.0] geode.texture-loader
  | [v1.0.2] mat.rgb-color-input
x | [v1.0.3] hjfod.gmd-api
x | [v4.0.1] ninxout.crystalclient
x | [v1.0.0] capeling.demons_in_garage
x | [v1.0.0] mat.circle-tool
x | [v1.0.0] camila314.song-randomizer
x | [v0.3.0-alpha] alk.drawing-utilities
x | [v3.0.9] cvolton.betterinfo
x | [v1.2.3] fleym.nongd
  | [v1.2.2] geode.custom-keybinds
x | [v1.0.1] cvolton.lists
x | [v1.3.6] geode.loader
x | [v1.0.4] hjfod.gdshare
  | [v1.0.2] gdutilsdevs.gdutils
x | [v1.0.4-beta.8] muhammadgames.bettermenu
x | [v1.1.0] capeling.icon_profile
x | [v1.0.13] alk.fps-bypass

### Steps to Reproduce

So if it happens when I try to open the level edit button for the 2nd time.

### Crash Report

crashlog: https://gist.github.com/BwompYes/f9646448bd3077d8f232709c96713359
log: https://gist.github.com/BwompYes/20c94cf1dd1888fde26905736e3cfa47

**Comment by Capeling** [comment]
Uninstall Crystal Client
