### ISSUE TITLE
Mod compiles but does not update

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#330]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.6

### Expected Behavior

Mod should compile and update. This means when I click the build button on the VSCode toolbar, the mod should fully recompile and I should get whatever new changes I've applied.

### Actual Behavior

Mod compiles fine, but when I open GD, an older version of the mod is still there. Uninstalling the mod and recompiling adds the mod back, but still an older version.

### Steps to Reproduce

1. Build mod
2. See results

### Additional Information

1. My CLI version is 2.6.1
2. This happened after I closed VSCode and opened it again.
3. Deleting the build folder fixes it for one build, after that the bug comes back

**Comment by TechStudent10** [comment]
<details><summary>Build log</summary>
<p>

[main] Building folder: Ambient 
[visual-studio] Patch Windows SDK path from C:\Program Files (x86)\Windows Kits\10\bin\x64 to C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64 for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat
[main] Configuring project: Ambient 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SC:/Users/moham/geode-mods/Ambient -Bc:/Users/moham/geode-mods/Ambient/build -G "Visual Studio 17 2022" -T host=x64 -A win32
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
[cmake] -- Found Geode: C:\Users\moham/geode/sdk
[cmake] -- Version: 1.3.6
[cmake] -- Found Geode CLI: C:/Users/moham/geode/geode.exe (version 2.6.1)
[cmake] -- CPM: Adding package json@ (a47f570)
[main] Configuring project: Ambient 
[cmake] -- CPM: Adding package fmt@9.1.0 (9.1.0)
[cmake] -- Module support is disabled.
[cmake] -- Version: 9.1.0
[cmake] -- Build type: 
[cmake] -- CXX_STANDARD: 20
[cmake] -- Required features: cxx_variadic_templates
[cmake] -- CPM: Adding package filesystem@3 (3e5b930)
[cmake] -- System name: Windows
[cmake] -- Compiler ID: MSVC
[cmake] -- CMAKE_CXX_COMPILE_FEATURES: cxx_std_98;cxx_template_template_parameters;cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates;cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates;cxx_std_17;cxx_std_20;cxx_std_23
[cmake] -- CPM: Adding package TulipHook@3423 (3423a29)
[cmake] C:/Users/moham/geode-mods/Ambient/build/cmake/CPM_0.36.0.cmake
[cmake] -- CPM: TulipHook: Adding package result@ (a97e66b)
[cmake] -- Setting up Ambient
[cmake] -- Configuring done (40.5s)
[cmake] -- Generating done (2.3s)
[cmake] -- Build files have been written to: C:/Users/moham/geode-mods/Ambient/build
[visual-studio] Patch Windows SDK path from C:\Program Files (x86)\Windows Kits\10\bin\x64 to C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64 for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat


</p>
</details>

**Comment by matcool** [comment]
thats the configure log not build log btw

**Comment by TechStudent10** [comment]
Oh shoot I reopened VSCode just now give me a min

**Comment by TechStudent10** [comment]
<details><summary>ACTUAL build log</summary>
<p>

[main] Building folder: Ambient 
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/moham/geode-mods/Ambient/build --config RelWithDebInfo --target ALL_BUILD -j 6 --
[build] MSBuild version 17.7.2+d6990bcfa for .NET Framework
[build] 
[build]   Checking File Globs
[build]   Performing build step for 'CodegenProject'
[build]   MSBuild version 17.7.2+d6990bcfa for .NET Framework
[build]   
[build]     Broma.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\geode\CodegenProject-prefix\src\CodegenProject-build\_deps\broma-build\RelWithDebInfo\Broma.lib
[build]     fmt.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\geode\CodegenProject-prefix\src\CodegenProject-build\_deps\fmt-build\RelWithDebInfo\fmt.lib
[build]     Codegen.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\geode\CodegenProject-prefix\src\CodegenProject-build\RelWithDebInfo\Codegen.exe
[build]   Performing install step for 'CodegenProject'
[build]   -- Up-to-date: C:/Users/moham/geode-mods/Ambient/build/geode/codegen/Codegen.exe
[build]   Completed 'CodegenProject'
[build]   GeodeFilesystemImpl.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\geode\RelWithDebInfo\GeodeFilesystemImpl.lib
[build]   fmt.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\_deps\fmt-build\RelWithDebInfo\fmt.lib
[build]   mat-json.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\_deps\json-build\RelWithDebInfo\mat-json.lib
[build]   GeodeCodegenSources.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\geode\RelWithDebInfo\GeodeCodegenSources.lib
[build]   Ambient.vcxproj -> C:\Users\moham\geode-mods\Ambient\build\RelWithDebInfo\techstudent10.ambient.dll
[build]   | Info | Zipping
[build]   | Done | Successfully packaged techstudent10.ambient.geode
[build]   | Done | Installed techstudent10.ambient.geode
[driver] Build completed: 00:00:15.039
[build] Build finished with exit code 0


</p>
</details>
