### ISSUE TITLE
Geode.dll crash

### ISSUE THREAD

**Issue by xavwashere** [geode-sdk/geode#331]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

Mega Hack v7 by Absolute (v7.1.1-beta.5)
Death Replay by dogotrigger (v1.1.1)
GDShare by HJfod (v1.0.4)
GMD API by HJfod (v1.0.3)
Lists by Cvolton (v1.0.1)
Geode (obv)

### Steps to Reproduce

1. Install a mod
2. Restart the game
3. obama gaming

### Crash Report

https://pastebin.com/hPXuJuPc (crash log)
https://pastebin.com/YHJUMYuw (latest log)

**Comment by altalk23** [comment]
have you installed geode using the installer? or are you loading geode with a separate mod loader/dll loader

**Comment by xavwashere** [comment]
I have installed Geode using the installer.

**Comment by xavwashere** [comment]
...

**Comment by xavwashere** [comment]
this wasn't completed...
