### ISSUE TITLE
Tried to install better edit it crashed durning the download

### ISSUE THREAD

**Issue by MegaFaresX** [geode-sdk/geode#332]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

No mods

### Steps to Reproduce

1): Open Gd with Geode
2): go to the download tab in Geode
3): install better edit (maybe others do but I didnt test yet)

### Crash Report

2023-11-08T22:16:12+0200
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.3.5
Installed mods: 1
Problems: 0

== Exception Information ==
Faulty Module: C:\Windows\System32\KERNELBASE.dll
Faulty Mod: <Unknown>
Exception Code: e06d7363 (<Unknown>)
Exception Flags: 1
Exception Address: 764D92B2 (KERNELBASE.dll + 1492b2 (RaiseException + 98))
Number Parameters: 3

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 1492b2 (RaiseException + 98)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 7e76 (CxxThrowException + 102)
 - C:\Windows\SYSTEM32\MSVCP140.dll + 162b4 (std::_Throw_Cpp_error + 52)
 - C:\Windows\SYSTEM32\MSVCP140.dll + 16277 (std::_Throw_C_error + 39)
 - E:\All Games\GD\Geode.dll + dd649 (geode::utils::web::AsyncWebRequest::send + 1289 | D:\a\geode\geode\loader\src\utils\web.cpp:523)
 - E:\All Games\GD\Geode.dll + 6baf2 (geode::Index::Impl::installNext + 4354 | D:\a\geode\geode\loader\src\loader\Index.cpp:741)
 - E:\All Games\GD\Geode.dll + 5a52e (`geode::Index::Impl::installNext'::`2'::<lambda_4>::operator()<std::monostate> + 1262 | D:\a\geode\geode\loader\src\loader\Index.cpp:778)
 - E:\All Games\GD\Geode.dll + 61bcb (`geode::utils::web::AsyncWebResult<std::monostate>::then'::`2'::<lambda_1>::operator() + 107 | D:\a\geode\geode\loader\include\Geode\utils\web.hpp:343)
 - E:\All Games\GD\Geode.dll + db49e (geode::utils::MiniFunctionState<``geode::utils::web::SentAsyncWebRequest::Impl::Impl'::`2'::<lambda_1>::operator()'::`2'::<lambda_4>,void>::call + 110 | D:\a\geode\geode\loader\include\Geode\utils\MiniFunction.hpp:28)
 - E:\All Games\GD\Geode.dll + f6aa3 (geode::Loader::Impl::executeGDThreadQueue + 291 | D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:677)
 - E:\All Games\GD\Geode.dll + 2f06f (geode::modifier::AsStaticFunction_update<FunctionQueue,void (__thiscall FunctionQueue::*)(float)>::Impl<void (__thiscall FunctionQueue::*)(float)>::function + 15 | D:\a\geode\geode\build\codegenned\Geode\modify\CCScheduler.hpp:46)
 - 013E34D7
 - E:\All Games\GD\libcocos2d.dll + ffb2d (cocos2d::CCDirector::levelForSceneInStack + 125)
 - E:\All Games\GD\GeometryDash.exe + 261175
 - E:\All Games\GD\GeometryDash.exe + 2621fd
 - C:\Windows\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00cfeee0
EBX: 19930520
ECX: 00000003
EDX: 00000000
EBP: 00cfef3c
ESP: 00cfeee0
EDI: 7422123c
ESI: 00000000
EIP: 764d92b2

== Installed Mods ==
x | [v1.3.5] geode.loader

**Comment by MegaFaresX** [comment]
Update It didnt crash with others just only when installing better edit

**Comment by dankmeme01** [comment]
you have geode v1.3.5, can you install v1.3.6 instead and post the crashlog if it still crashes?

**Comment by MegaFaresX** [comment]
Hold up I will check if I can update and gonna tell you what happnes

**Comment by MegaFaresX** [comment]
now it works thanks
