### ISSUE TITLE
crash geometry dash

### ISSUE THREAD

**Issue by BelmixYT** [geode-sdk/geode#333]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

== Installed Mods ==
x | [v1.0.5] mat.practice-music
x | [v1.3.5] geode.loader
x | [v1.0.4-beta.8] muhammadgames.bettermenu
x | [v4.0.1] ninxout.crystalclient
x | [v1.5.2] tpdea.betterpause-Better

### Steps to Reproduce

it throws a crash when I enter the create level

### Crash Report

2023-10-28T18:45:31+0200
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.3.5
Installed mods: 5
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 50E7789B (Geode.dll + 2789b (cocos2d::CCNode::getChildByID + 43 | D:\a\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:107))
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2789b (cocos2d::CCNode::getChildByID + 43 | D:\a\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:107)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 52b28
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 51b9e
 - 083709F7
 - 019307E6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 34b19 (CustomSongWidgetIDs::init + 73 | D:\a\geode\geode\loader\src\ids\CustomSongWidget.cpp:34)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 334f0 (geode::modifier::AsStaticFunction_init<CustomSongWidgetIDs,bool (__thiscall CustomSongWidgetIDs::*)(SongInfoObject *,LevelSettingsObject *,bool,bool,bool,bool,bool)>::Impl<bool (__thiscall CustomSongWidgetIDs::*)(SongInfoObject *,LevelSettingsObject *,bool,bool,bool,bool,bool)>::function + 48 | D:\a\geode\geode\build\codegenned\Geode\modify\CustomSongWidget.hpp:11)
 - 0193065F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 75543
 - 0193065F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 684cd
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 68160
 - 0193065F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 52263
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 51b70
 - 0193065F
 - 08512CFA
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\tpdea.betterpause-Better\tpdea.betterpause-Better.dll + b8db
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\tpdea.betterpause-Better\tpdea.betterpause-Better.dll + 700d
 - 1C8838CB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 6dc36
 - 1C8838CB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 38b18
 - 1C8838CB
 - 08373AD6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 6de30
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 6d57e
 - 08373937
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 25f992
 - 08501B16
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + 850f7
 - 08501977
 - 0850173E
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\ninxout.crystalclient\ninxout.crystalclient.dll + c7061
 - 085015A3
 - 085015A3
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c3f71 (cocos2d::CCEGLView::onGLFWKeyCallback + 337)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 111ade (cocos2d::CCPoint::unrotate + 7982)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 113436 (cocos2d::CCPoint::unrotate + 14470)
 - C:\WINDOWS\System32\USER32.dll + 32e03 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23be6 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 23557 (CallWindowProcW + 135)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3be09 (glDebugEntry + 3849)
 - C:\WINDOWS\System32\USER32.dll + 32e03 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23be6 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 224a5 (DispatchMessageW + 1221)
 - C:\WINDOWS\System32\USER32.dll + 21ff0 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 82bd0 (OverlayHookD3D3 + 121760)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1122d2 (cocos2d::CCPoint::unrotate + 10018)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c190b (cocos2d::CCApplication::run + 779)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 261175
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 008fea90
EBX: 668575d0
ECX: 00000000
EDX: 008feaec
EBP: 008fea9c
ESP: 008fea58
EDI: 00000000
ESI: 50e77870
EIP: 50e7789b

== Installed Mods ==
x | [v1.0.5] mat.practice-music
x | [v1.3.5] geode.loader
x | [v1.0.4-beta.8] muhammadgames.bettermenu
x | [v4.0.1] ninxout.crystalclient
x | [v1.5.2] tpdea.betterpause-Better

**Comment by ninXout** [comment]
Problem with Crystal Client please delete it for now
