### ISSUE TITLE
When I opened the editor it crashed

### ISSUE THREAD

**Issue by ShreyasMahesh** [geode-sdk/geode#335]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

23 mods

### Steps to Reproduce

I opened the editor that's all

### Additional Information

I don't know how this happened.

**Comment by cgytrus** [comment]
99.99% chance its a mod specific issue but cant see without a crash report
