### ISSUE TITLE
Geode is corrupting my save file on exit

### ISSUE THREAD

**Issue by nolemretaWxd** [geode-sdk/geode#336]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Steps to Reproduce

1) Open Geometry Dash
2) Close it
3) Try reopening it
4) Geode should crash

### Crash Report

Log: https://pastebin.com/PpyptkSY
Crash log: https://pastebin.com/vH86gHEc

**Comment by nolemretaWxd** [comment]
Checked save file hashes before and after launching GD and closing it, and Geode does in fact corrupt my save file each time the game is closed.
![image](https://github.com/geode-sdk/geode/assets/31414969/b53329ca-0977-44e5-838d-3dd06fb7a5b9)
![image](https://github.com/geode-sdk/geode/assets/31414969/ddf73c2b-6a11-4ec7-aab5-c05e0cbd6c27)
1st is before, and 2nd is after. File seems to be larger after closing the game, by 42 bytes

**Comment by cgytrus** [comment]
this is off-topic, but just an fyi, imhex has a diff tool that u can use if u go into tool and select diffing
![image](https://github.com/geode-sdk/geode/assets/30120687/fec5b429-680f-4971-b97f-0c0f5113b29d)

**Comment by cgytrus** [comment]
also your screenshots dont show the size what are you talking abt

**Comment by nolemretaWxd** [comment]
> also your screenshots dont show the size what are you talking abt

I can't reproduce a situation where broken CCGameManager.dat is 42 bytes larget, probably just opening the game caused some value to change.
However, I took a broken save file, and it was 44 509 096 bytes, then fixed it, and fixed file is 4 bytes larger
(Rozmiar is size, Rozmiar na dysku is size on disk)
![image](https://github.com/geode-sdk/geode/assets/31414969/19af6a36-3f5d-4c2d-b2f9-0a6a68b9d1eb)
![image](https://github.com/geode-sdk/geode/assets/31414969/e8a2cedf-3c41-4dd3-9a5e-169892b7d012)

Also thanks for showing diff tool in ImHex, here's a screenshot from it compairing broken to fixed save file
![image](https://github.com/geode-sdk/geode/assets/31414969/5bb2207d-fbb8-487b-93e2-092a356d43bf)
I would upload the save files, but I'm logged into my GD account on that save. I can log out so I'll have an empty broken and fixed save to upload.

**Comment by nolemretaWxd** [comment]
I've uninstalled Geode and GD is still corrupting my save file. I don't know what's the cause of this, and what corrupted my save file in the first place, GD or Geode

**Comment by Alphatism** [comment]
This is a GD bug that can happen when GD crashes instead of closing when you are closing the game

**Comment by nolemretaWxd** [comment]
I've uploaded my save into cloud and the issue seems to be fixed. Or just decrypting and encrypting the save helped with some corruption idk
