### ISSUE TITLE
Gd unexpected crash 

### ISSUE THREAD

**Issue by fabriziotq** [geode-sdk/geode#338]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

Loader Version: v1.3.6

### Mods Installed

== Installed Mods ==
x | [v1.0.0] n.level_pronouns
x | [v1.3.6] geode.loader
x | [v1.1.1] gdutilsdevs.gdutils
x | [v1.0.1] alphalaneous.integrated_loquibot
x | [v7.1.1-beta.5] absolllute.megahack
x | [v1.1.0] geode.texture-loader
x | [v5.0.0-alpha.10] be_team.betteredit
x | [v2.2.5] alk.small-additions
x | [v0.3.0-alpha] alk.drawing-utilities
  | [v1.0.3] alphalaneous.separatedualicons
x | [v1.1.0] be_team.editorapi
x | [v1.0.0] camila314.alignto
x | [v1.0.0] nef.iconsave
  | [v1.0.3-beta] camila314.betterloading
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.0.0] camila314.editor-hitbox-fix
x | [v1.0.0] capeling.demons_in_garage
x | [v1.1.0] capeling.icon_profile
x | [v1.3.0] cattodev.gatobot
x | [v1.0.0] cgytrus.patcher
x | [v3.0.9] cvolton.betterinfo
  | [v1.0.0] endrei.mappacksremover
x | [v1.0.2] cvolton.robtop_bot
x | [v1.2.3] fleym.nongd
x | [v1.0.1] mat.scroll-zoom
x | [v1.2.2] geode.custom-keybinds
x | [v1.0.3] hjfod.gmd-api
x | [v1.2.3] geode.devtools
  | [v1.0.0] geode.mouse-api
x | [v1.0.4] hjfod.gdshare
x | [v1.5.2] tpdea.betterpause-Better
x | [v1.0.3] hjfod.volumescrollwheel
  | [v1.0.1] rlt.gd-multiprofile-mod
x | [v1.0.1] iandyhd3.abbreviated_labels
x | [v1.0.0] mat.ffmt
  | [v1.0.0] iandyhd3.check_steam
x | [v1.0.0] kolyah35.clipboardfix
x | [v1.0.0] mat.circle-tool
x | [v1.0.0] mat.song-search
x | [v1.0.2] mat.rgb-color-input
x | [v1.0.1] mat.run-info
x | [v1.1.1] org.dogotrigger.deathreplay

### Steps to Reproduce

I entered to a level (slaughterhouse), I exited and approximately 10 seconds later, the game crashed.

### Crash Report

[2023-11-12_16-53-28.log](https://github.com/geode-sdk/geode/files/13329000/2023-11-12_16-53-28.log)

**Comment by cgytrus** [comment]
gdutils issue, report it to the developer
