### ISSUE TITLE
Crashing when trying to open the icon selection menu

### ISSUE THREAD

**Issue by PhoenixAceVFX** [geode-sdk/geode#339]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.6

### Mods Installed

== Installed Mods ==
x | [v1.3.6] geode.loader
x | [v7.1.1-beta.5] absolllute.megahack
x | [v1.0.3-beta] camila314.betterloading
x | [v2.2.5] alk.small-additions
x | [v1.0.3] alphalaneous.separatedualicons
x | [v1.1.0] be_team.editorapi
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.0.0] camila314.editor-hitbox-fix
x | [v1.1.0] capeling.icon_profile
x | [v3.0.9] cvolton.betterinfo
x | [v1.2.3] fleym.nongd
x | [v1.1.1] gdutilsdevs.gdutils
x | [v1.2.2] geode.custom-keybinds
x | [v1.0.3] hjfod.gmd-api
x | [v1.2.3] geode.devtools
x | [v1.0.0] geode.mouse-api
x | [v1.1.0] geode.texture-loader
x | [v1.0.4] hjfod.gdshare
x | [v1.5.2] tpdea.betterpause-Better
x | [v1.0.3] hjfod.volumescrollwheel
x | [v1.0.2] mat.rgb-color-input
x | [v1.0.4-beta.8] muhammadgames.bettermenu
x | [v1.1.1] org.dogotrigger.deathreplay

### Steps to Reproduce

Open the icon select, Game crashes instantly

### Crash Report

---------------------------
Geode Crashed
---------------------------
2023-11-14T17:13:44-0500
Whoopsies! An exception has occurred while running Geode.
It appears that the crash occurred while executing code from the "alphalaneous.separatedualicons" mod. Please submit this crash report to its developer (Alphalaneous) for assistance.

== Geode Information ==
Loader Version: v1.3.6
Installed mods: 23
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.separatedualicons\alphalaneous.separatedualicons.dll
Faulty Mod: alphalaneous.separatedualicons
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 1B5DA620 (alphalaneous.separatedualicons.dll + 2a620)
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.separatedualicons\alphalaneous.separatedualicons.dll + 2a620
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.separatedualicons\alphalaneous.separatedualicons.dll + 310d6
 - 030C1D8B
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 191e52
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + abe83 (cocos2d::CCMenuItem::activate + 35)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + aaf1d (cocos2d::CCMenu::ccTouchEnded + 29)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + 14672 (mouse::MouseEventFilter::handle + 978)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + 1706 (geode::EventFilter<mouse::MouseEvent>::getPool + 262)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 580ce (geode::DefaultEventListenerPool::handle + 78 | D:\a\geode\geode\loader\src\loader\Event.cpp:33)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5822e (geode::Event::postFromMod + 30 | D:\a\geode\geode\loader\src\loader\Event.cpp:91)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + 154c7 (json::Serialize<enum mouse::MouseButton>::to_json + 263)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + 10924 (mouse::Tooltip::show + 16772)
 - 1BAB0E0F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.devtools\geode.devtools.dll + 3634
 - 1BAB0E0F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + d8fb (mouse::Tooltip::show + 4443)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.mouse-api\geode.mouse-api.dll + ce77 (mouse::Tooltip::show + 1751)
 - 1BAB257B
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 111b29 (cocos2d::CCPoint::unrotate + 8057)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 113679 (cocos2d::CCPoint::unrotate + 15049)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 151800
 - C:\WINDOWS\System32\USER32.dll + 32e03 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23be6 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 23557 (CallWindowProcW + 135)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3be09 (glDebugEntry + 3849)
 - C:\WINDOWS\System32\USER32.dll + 32e03 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23be6 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 224a5 (DispatchMessageW + 1221)
 - C:\WINDOWS\System32\USER32.dll + 21ff0 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 82bd0 (OverlayHookD3D3 + 121760)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1122d2 (cocos2d::CCPoint::unrotate + 10018)
 - 09471349
 - 09471D4B
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 261175
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: b781f0dd
EBX: 00000004
ECX: b781f0dd
EDX: 00ff6bec
EBP: 005aee08
ESP: 005aedb4
EDI: 000001b0
ESI: ffffe78d
EIP: 1b5da620

== Installed Mods ==
x | [v1.3.6] geode.loader
x | [v7.1.1-beta.5] absolllute.megahack
x | [v1.0.3-beta] camila314.betterloading
x | [v2.2.5] alk.small-additions
x | [v1.0.3] alphalaneous.separatedualicons
x | [v1.1.0] be_team.editorapi
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.0.0] camila314.editor-hitbox-fix
x | [v1.1.0] capeling.icon_profile
x | [v3.0.9] cvolton.betterinfo
x | [v1.2.3] fleym.nongd
x | [v1.1.1] gdutilsdevs.gdutils
x | [v1.2.2] geode.custom-keybinds
x | [v1.0.3] hjfod.gmd-api
x | [v1.2.3] geode.devtools
x | [v1.0.0] geode.mouse-api
x | [v1.1.0] geode.texture-loader
x | [v1.0.4] hjfod.gdshare
x | [v1.5.2] tpdea.betterpause-Better
x | [v1.0.3] hjfod.volumescrollwheel
x | [v1.0.2] mat.rgb-color-input
x | [v1.0.4-beta.8] muhammadgames.bettermenu
x | [v1.1.1] org.dogotrigger.deathreplay

---------------------------
OK   
---------------------------

**Comment by PhoenixAceVFX** [comment]
found which mod was causing the crash already
separate dual icons was causing it

**Comment by Alphatism** [comment]
This issue is to do with not being logged into an account causing Geode to shift the IDs of elements in the icon menu. To fix, log into a GD account and then open the icon menu.
