### ISSUE TITLE
Crash when installing BetterEdit

### ISSUE THREAD

**Issue by Slooshie1** [geode-sdk/geode#340]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

None

### Steps to Reproduce

1. Freshly install Geometry Dash
2. Run Geode installer
3. Launch Geometry Dash
4. Find BetterEdit mod and click install
5. Crash

### Crash Report

[2023-11-14_19-46-42.log](https://github.com/geode-sdk/geode/files/13359850/2023-11-14_19-46-42.log)

**Comment by altalk23** [comment]
fixed in main (1.3.7)

**Comment by NathGaming532** [comment]
try to install the 4GB patch
