### ISSUE TITLE
Game crashes when deleting a level

### ISSUE THREAD

**Issue by Xboy3998** [geode-sdk/geode#342]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

![Screenshot 2023-11-16 214153](https://github.com/geode-sdk/geode/assets/125828514/77ebb2ee-70bb-4bf8-bc0e-8344ecf96ebf)
![Screenshot 2023-11-16 214201](https://github.com/geode-sdk/geode/assets/125828514/d47973fb-3f1b-4205-931d-eb09612e84d8)
![Screenshot 2023-11-16 214207](https://github.com/geode-sdk/geode/assets/125828514/697b101c-1a5c-4b16-9b86-243fa8cb27cb)
![Screenshot 2023-11-16 214213](https://github.com/geode-sdk/geode/assets/125828514/cda86339-ec0a-49fa-be96-b9b97075ef14)
![Screenshot 2023-11-16 214220](https://github.com/geode-sdk/geode/assets/125828514/e3434d36-6923-43e3-9713-c575a9a30ee9)
![Screenshot 2023-11-16 214226](https://github.com/geode-sdk/geode/assets/125828514/521ad4d7-aa89-4dfa-afb6-f36f4d3dda39)

### Steps to Reproduce

1. download or open an level page
2. delete the level or reopen it after being opened
3. repeat

### Crash Report

[2023-11-16_21-39-58.log](https://github.com/geode-sdk/geode/files/13383201/2023-11-16_21-39-58.log)
[Geode 16 Nov 21.41.14.log](https://github.com/geode-sdk/geode/files/13383203/Geode.16.Nov.21.41.14.log)

**Comment by cgytrus** [comment]
looks like a loquibot issue, report it to the developer of the mod.

**Comment by Alphatism** [comment]
I’ll look into it, I started having the same issue myself a few days ago

**Comment by cgytrus** [comment]
turned out to be a geode issue disguising as mod specific, thanks for the report!

**Comment by Xboy3998** [comment]
Have any of you found something that caused this? Can't play gd with this bug.

**Comment by Alphatism** [comment]
@Xboy3998 update the loquibot mod on the index, it should no longer cause this
