### ISSUE TITLE
Geode Error

### ISSUE THREAD

**Issue by Alenminasyan** [geode-sdk/geode#347]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

MegaHack v7.1.1-beta5, BetterPause v1.5.2, BetterInfo 3.0.10, BetterEdit v5.0.0-beta10, Custom Keybinds v1.2.2, Editor Hitbox Fix v1.0.0, Editor-API v1.1.0, ExtraIcons v1.0.2, FpsBypass v1.0.4, GMD API v1.0.3, Hide Pause v1.0.0, nongd v1.2.3, ProjectedStars v1.0.0, 
RGB Color Input v1.0.2, SongSearch v1.0.0, SeperateDualIcons v1.0.3, SmallAdditions v2.2.5, MenuShaders v1.1.0, Blink 1.0.0.

### Steps to Reproduce

I wanted to go in but the door in the lower right corner in the creator menuю I wanted to open the keys and the game crashes

### Crash Report

2023-11-20T23:12:15+0300
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.3.6
Installed mods: 26
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 004753A2 (GeometryDash.exe + 1553a2)
Number Parameters: 2

== Stack Trace ==
 - C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe + 1553a2
 - C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe + 154521
 - C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe + 4f64c
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + abe83 (cocos2d::CCMenuItem::activate + 35)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + aaf1d (cocos2d::CCMenu::ccTouchEnded + 29)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + f5919 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + bb37c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + c4046 (cocos2d::CCEGLView::onGLFWMouseCallBack + 198)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + c406e (cocos2d::CCEGLView::onGLFWMouseCallBack + 238)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + 111b29 (cocos2d::CCPoint::unrotate + 8057)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + 113679 (cocos2d::CCPoint::unrotate + 15049)
 - C:\Users\User\Desktop\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 151800 (MegaHackExt::SelectionBox::get + 704912)
 - C:\Windows\System32\USER32.dll + 448eb (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 2613c (CallWindowProcW + 2860)
 - C:\Windows\System32\USER32.dll + 2568f (CallWindowProcW + 127)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 3ea3e (glDebugEntry + 3614)
 - C:\Windows\System32\USER32.dll + 448eb (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 2613c (CallWindowProcW + 2860)
 - C:\Windows\System32\USER32.dll + 2528e (DispatchMessageW + 558)
 - C:\Windows\System32\USER32.dll + 25070 (DispatchMessageW + 16)
 - C:\Users\User\Desktop\Geometry Dash\libcocos2d.dll + 1122d2 (cocos2d::CCPoint::unrotate + 10018)
 - 04C41349
 - C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe + 261175
 - C:\Users\User\Desktop\Geometry Dash\GeometryDash.exe + 2621fd
 - C:\Windows\System32\KERNEL32.DLL + 16359 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a94 (RtlGetAppContainerNamedObjectPath + 228)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a64 (RtlGetAppContainerNamedObjectPath + 180)

== Register States ==
EAX: 00d3f0c8
EBX: 637eee11
ECX: 05fac298
EDX: 00000004
EBP: 00d3f1fc
ESP: 00d3effc
EDI: 00000003
ESI: 00000000
EIP: 004753a2

== Installed Mods ==
x | [v1.3.6] geode.loader
  | [v1.0.0] camila314.song-randomizer
x | [v1.0.0] alphalaneous.projectedstars
x | [v7.1.1-beta.5] absolllute.megahack
x | [v5.0.0-alpha.10] be_team.betteredit
x | [v3.0.10] cvolton.betterinfo
x | [v1.0.2] alphalaneous.extraicons
x | [v2.2.5] alk.small-additions
x | [v1.0.3] alphalaneous.separatedualicons
x | [v1.1.0] be_team.editorapi
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.0.0] camila314.editor-hitbox-fix
  | [v1.0.0] capeling.demons_in_garage
  | [v1.0.0] capeling.simple_icon_hack
x | [v1.0.5] mat.practice-music
  | [v1.0.2] cvolton.robtop_bot
x | [v1.0.0] deathfuel.blink
x | [v1.2.3] fleym.nongd
x | [v1.2.2] geode.custom-keybinds
x | [v1.0.4] hjfod.gdshare
x | [v1.0.3] hjfod.gmd-api
x | [v1.0.4] mat.fps-bypass
x | [v1.0.0] mat.song-search
x | [v1.0.2] mat.rgb-color-input
x | [v1.0.0] techstudent10.hidepause
x | [v1.5.2] tpdea.betterpause-Better

### Additional Information

I think this is because of the mega hack because a lot of things can fly out because of it

**Comment by FireMario211** [comment]
If it's a mod issue, then it isn't a Geode related issue.

**Comment by altalk23** [comment]
> If it's a mod issue, then it isn't a Geode related issue.
yeah
