### ISSUE TITLE
Remove "updating index"

### ISSUE THREAD

**Issue by AdyaGMD** [geode-sdk/geode#348]
### Geode Version

1.3.6

### Related Problem

sometimes the "updating index" stays on for a long time

### Your Solution

either remove it, or make it disappear when you're ingame, or only make it appear in the mod selection menu. I don't need to know if the index is being updated or not.

**Comment by iAndyHD3** [comment]
there should be an option to disable updating the index every single time you open the game. it's terrible

**Comment by altalk23** [comment]
added a timeout for 4 seconds in the main branch (1.3.7 probably)

**Comment by CattoDev** [comment]
im with andy on this one

**Comment by TechStudent10** [comment]
i'm with andy on this one too
