### ISSUE TITLE
https://disboard.org/es/server/849332828034039849 

### ISSUE THREAD

**Issue by Michitoxd** [geode-sdk/geode#350]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.6

### Mods Installed

s

### Steps to Reproduce

s

### Crash Report

literraly

### Additional Information

A

**Comment by TechStudent10** [comment]
what a nice issue we have here

**Comment by TheSillyDoggo** [comment]
![image](https://github.com/geode-sdk/geode/assets/95105680/ee673264-caad-4ee5-9afc-efd628324c4a)
