### ISSUE TITLE
geode dont found mods

### ISSUE THREAD

**Issue by NathGaming532** [geode-sdk/geode#351]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.6

### Actual Behavior

geode dont found mods 
![image](https://github.com/geode-sdk/geode/assets/151595720/851f3985-2192-4db7-8b61-4b8c0e98ade4)
, how do i fix it ?

### Steps to Reproduce

  i dont know, i just start geometry dash and geode dont found mods

**Comment by cgytrus** [comment]
what

**Comment by NathGaming532** [comment]
@cgytrus you dont know how to fix it ?

**Comment by CattoDev** [comment]
are you trying to load .dll files or smth?

**Comment by Cvolton** [comment]
the issue seems to be that the index didn't get downloaded properly - if you go into the `geode` folder inside the folder with your `GeometryDash.exe` and delete the `index` folder there, the issue should fix itself

**Comment by NathGaming532** [comment]
@Cvolton its doesen't work

**Comment by NathGaming532** [comment]
> are you trying to load .dll files or smth?

.ddl i think
