### ISSUE TITLE
Downloading BetterEdit through the in-game downloader crashes the game before it can install

### ISSUE THREAD

**Issue by circledeni** [geode-sdk/geode#352]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.6

### Mods Installed

None (only Geode itself)

### Steps to Reproduce

- Open GD with Geode installed
- Click Install on the BetterEdit v5.0.0 page through the in-game downloader
- before all files can install, the game crashes

### Crash Report

[2023-11-24_17-09-50.log](https://github.com/geode-sdk/geode/files/13460468/2023-11-24_17-09-50.log)

**Comment by Alphatism** [comment]
This is a known issue, a workaround is to download custom keybinds first, then BetterEdit

**Comment by matcool** [comment]
fixed in 1.3.7
