### ISSUE TITLE
geode dont found mods

### ISSUE THREAD

**Issue by NathGaming532** [geode-sdk/geode#353]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.7

### Expected Behavior

have mods

### Actual Behavior

geode dont found mods 
![20231124170801_1](https://github.com/geode-sdk/geode/assets/151595720/b73ce105-2acd-4ea5-ac71-93bf952f159f)

### Steps to Reproduce

i dont know.

**Comment by cgytrus** [comment]
dont close and re-create issues if you dont find a solution.

**Comment by NathGaming532** [comment]
> dont close and re-create issues if you dont find a solution.

ok sorry
