### ISSUE TITLE
ZBot crash

### ISSUE THREAD

**Issue by MrPurpleCat** [geode-sdk/geode#354]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v1.3.7

### Mods Installed

Run Info, Practice Music, Menu Shaders, Integrated Loquibot, GDutils, GMD API, Editor API, Demonlist-button, custom keybinds, better loading, betteredit, betterinfo

### Steps to Reproduce

1) install zBot
2) restart the game

**Comment by CattoDev** [comment]
Clearly a mod issue

**Comment by cgytrus** [comment]
bro clicked on the checkmark that clearly directly contradicts what the title says
