### ISSUE TITLE
Geode doesn't install on Steam Proton (Linux Steam Play)

### ISSUE THREAD

**Issue by CribonGarge** [geode-sdk/geode#355]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.7

### Expected Behavior

I run the geode installer, and it installs perfectly fine, works as expected. Maybe with some bugs here and there.

### Actual Behavior

Geode doesn't appear, even though the installer succeeded, and all the files are there. Geode should work (i think) because geometry dash does, and proton is so good (sometimes)!

### Steps to Reproduce

Install Steam Proton
Install Geometry Dash
Run Geode Installer.exe
Run GD
No Geode :sob:

### Additional Information

I am running this on a Chromebook Linux virtual machine (Crostini or smth, its official), my friend with a SteamDeck has the same problem. Do i need some sort of launch argument? I have tried manually adding the files aswell. Also geometry dash is steam deck playable.

**Comment by cgytrus** [comment]
try following these instructions
![image](https://github.com/geode-sdk/geode/assets/30120687/60ac3faf-b81f-48b1-9501-a4bf8d0e7d36)

**Comment by CribonGarge** [comment]
Thanks, it seems to be working as expected!
