### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by MrPurpleCat** [geode-sdk/geode#356]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v1.3.7

### Mods Installed

Better menu, BetterInfo, BetterLoading, Custom Keybinds, Demonlist, Editor api, better edit, fps bypass, fps shower, gdutils, run info

### Steps to Reproduce

1) go in the editor
2) press ESC and press resume
3) it randomly crashes ( not always )

### Crash Report

2023-11-27T19:11:05+0400
Whoopsies! An exception has occurred while running Geode.
It appears that the crash occurred while executing code from the "be_team.betteredit" mod. Please submit this crash report to its developer (BE Team) for assistance.

== Geode Information ==
Loader Version: v1.3.7
Installed mods: 20
Problems: 0

== Exception Information ==
Faulty Lib: /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib
Faulty Mod: be_team.betteredit
Instruction Address: 0x116224d3f
Signal Code: b (SIGSEGV: Segmentation Fault)

== Stack Trace ==
 - /usr/lib/system/libsystem_platform.dylib + 0x35ed: _sigtramp (in libsystem_platform.dylib) + 29
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc7d3f: std::__1::__function::__value_func<bool ()>::operator()() const (in be_team.betteredit.dylib) + 47
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc7375: std::__1::function<bool ()>::operator()() const (in be_team.betteredit.dylib) + 21
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc7324: VisibilityToggle::updateState() (in be_team.betteredit.dylib) + 68
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc6b2c: updateVisibilityTab() (in be_team.betteredit.dylib) + 396
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc6922: hook347<(anonymous namespace)::hook347Parent>::onResume(cocos2d::CCObject*) (in be_team.betteredit.dylib) + 34
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/be_team.betteredit/be_team.betteredit.dylib + 0xc672d: geode::modifier::AsStaticFunction_onResume<hook347<(anonymous namespace)::hook347Parent>, void (hook347<(anonymous namespace)::hook347Parent>::*)(cocos2d::CCObject*)>::Impl<void (hook347<(anonymous namespace)::hook347Parent>::*)(cocos2d::CCObject*)>::function(hook347<(anonymous namespace)::hook347Parent>*, cocos2d::CCObject*) (in be_team.betteredit.dylib) + 93
 - /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver + 0x22fa970: 0x112ed8970
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x1257d2: 0x0000000106a517d2 (in Geometry Dash) + 162
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x439038: 0x0000000106d65038 (in Geometry Dash) + 40
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x281be2: 0x0000000106badbe2 (in Geometry Dash) + 386
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x29e221: 0x0000000106bca221 (in Geometry Dash) + 81
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x3b11d4: 0x0000000106cdd1d4 (in Geometry Dash) + 196
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/Frameworks/Geode.dylib + 0x4a33e30: 0x10c857e30
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/Frameworks/Geode.dylib + 0x4a33e30: 0x10c857e30
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x1a17eb: -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] (in AppKit) + 424
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x1a1427: -[NSWindow(NSEventRouting) sendEvent:] (in AppKit) + 345
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x19fe01: -[NSApplication(NSEvent) sendEvent:] (in AppKit) + 345
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/geode.custom-keybinds/geode.custom-keybinds.dylib + 0xafb47: sendEvent(NSApplication*, objc_selector*, NSEvent*) (in geode.custom-keybinds.dylib) + 167
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x45a74e: -[NSApplication _handleEvent:] (in AppKit) + 65
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x2f7ad: -[NSApplication run] (in AppKit) + 623
 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit + 0x39a1: NSApplicationMain (in AppKit) + 817
 - /Users/timurmakar/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x19b4: 0x000000010692d9b4 (in Geometry Dash) + 52
 - 0x1: 0x1

== Register States ==
rax: 0x3f155556162cbb40
rbx: 0x7fc2f85a4140
rcx: 0x1a
rdx: 0x1162b2a88
rdi: 0x7fc2f858a100
rsi: 0x1162b2a90
rbp: 0x7ff7b95d2a10
rsp: 0x7ff7b95d2a00
r8: 0
r9: 0x98268b44
r10: 0xef6698bf
r11: 0xfffffffffffffff8
r12: 0x600002fd23a0
r13: 0x7fc313bc5a38
r14: 0x600002fdb390
r15: 0x600001d5c630
rip: 0x116224d3f
rflags: 0x10206
cs: 0x2b
fs: 0
gs: 0

== Installed Mods ==
  | [v1.0.2] alk.fps-shower
x | [v1.0.5] mat.practice-music
x | [v1.1.0] geode.texture-loader
x | [v1.0.3] hjfod.gmd-api
x | [v1.0.1] mat.run-info
x | [v1.1.0] be_team.editorapi
x | [v1.0.4-beta] camila314.betterloading
x | [v5.0.0-alpha.10] be_team.betteredit
x | [v1.0.0] camila314.demonlist-button
x | [v3.0.10] cvolton.betterinfo
x | [v1.0.2] alphalaneous.integrated_loquibot
x | [v1.2.2] geode.custom-keybinds
x | [v1.1.0] capeling.icon_profile
x | [v1.0.13] alk.fps-bypass
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.1.21] gdutilsdevs.gdutils
x | [v1.0.4-beta.9] muhammadgames.bettermenu
  | [v1.0.0] endrei.mappacksremover
x | [v1.0.1] cvolton.lists
x | [v1.3.7] geode.loader

**Comment by Capeling** [comment]
this is caused by betteredit, try removing it and seeing if the issue still occurs

**Comment by MrPurpleCat** [comment]
> this is caused by betteredit, try removing it and seeing if the issue still occurs

still crashes

**Comment by TheSillyDoggo** [comment]
Remove betterloading
