### ISSUE TITLE
Geometry Dash crashes after installing Geode

### ISSUE THREAD

**Issue by ABwebGamesFan** [geode-sdk/geode#357]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.7

### Mods Installed

None

### Steps to Reproduce

Step 1: Open the game

### Crash Report

There is no crash logs directory though there was a generic Windows error popup that said

"The procedure entry point ?resetSmoothFixCounter@CCDirector@cocos2d@@QAEXXZ could not be located in the dynamic link library D:\geode test\Geode.dll"

### Additional Information

I did change the exe name to something that wasn't GeometryDash.exe to see if it was an issue with my save file, though that didn't fix the issue.

**Comment by Alphatism** [comment]
You’re using an outdated version of the game (most likely pirated).

**Comment by matcool** [comment]
geode is only designed for gd 2.113, the latest version of the game
