### ISSUE TITLE
Can't type special characters ({, }, comma, full-stop etc) in a geode::InputNode

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/geode#359]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v1.3.7

### Expected Behavior

input the characters into the text box like { } or , .

### Actual Behavior

it didn't type. normal letters and numbers type

### Steps to Reproduce

select a geode::InputNode
press . on your keyboard
it doesn't type

**Comment by Cvolton** [comment]
does your filter include these characters?

**Comment by TheSillyDoggo** [comment]
closed due to me not doing what cvolton says. it was letting me type anything because i had character bypass in mega hack on so this is just a mistake on my end sorry
