### ISSUE TITLE
Geometry Dash Spin Offs In More Games

### ISSUE THREAD

**Issue by RetroWaveGaming** [geode-sdk/geode#364]
### Geode Version

1.3.7

### Related Problem

1. Can't Unlock The Bottom Row In The Second Page In The icon Kit. 2. The More Games Button Is Useless

### Your Solution

Rename The More Games Button To Say More Levels So Everyone Can Access The Spin Off Levels Or You Could Just Put The Spin Off Levels In The The Vault The Chamber Of Time And The Vault Of Secrets And Get Rid Of The More Games Button And Add Extra Slots Of Icons * Also Btw Im On Mac So Please Make It Compatable Sorry Im So Bossy *

**Comment by RetroWaveGaming** [comment]
Im Trying To Take This Down

**Comment by TechStudent10** [comment]
> Im Trying To Take This Down

![image](https://github.com/geode-sdk/geode/assets/76978184/02624233-d9f4-48fa-9451-e47583b3edd0)

Click on this close issue button

**Comment by RetroWaveGaming** [comment]
Oh Thanks
