### ISSUE TITLE
Geode Crashes when Opening the Editor

### ISSUE THREAD

**Issue by xendyex** [geode-sdk/geode#365]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v1.3.7

### Mods Installed

Abbreviated Labels
Better Menu
Blink
Better Info
Better Edit ( although this was disabled at the time )
Better Loading
Clipboard Fix
Custom Keybinds
Check Steam
DevTools
Demons In Garage
Demonlist Button
Editor Hitbox Fix
Editor API
GD Share
GMD API
GD Utils
Gradient Pages
Hide Pause
Icon Profile
Lists
Simple Patch Loader
Song Randomiser
Separate Dual Icons
Small Additions
Texture Loader

### Steps to Reproduce

1) Ubuntu 23.04 with Proton 8
2) Open GD with Geode
3) Open the editor ( any level, even blank )
4) Crashes

### Crash Report

http://xendy.co.uk/CrashLogs/2023-12-04_09-33-06.log
Downloads it.

Or Pastebin link here:
https://pastebin.com/1ubi7A9K

No, I have not altered it. I use xendyex as my acc name so it saves my leaking my name.

### Additional Information

This may be caused by a mod, however, I doubt it as without mods it crashes when I zoom in, and, the crash error is something to do with LibCocos.

**Comment by Fleeym** [comment]
Does the crash happen consistently? Also remove betterloading, its very unstable
