### ISSUE TITLE
Game Crash When "Download" Is Clicked

### ISSUE THREAD

**Issue by NewAlexGamer** [geode-sdk/geode#37]
when you click on the download section of the geode menu it just crashes
[2022-09-29_23-08-15.log](https://github.com/geode-sdk/geode/files/9679112/2022-09-29_23-08-15.log)
[2022-09-29_23-07-50.log](https://github.com/geode-sdk/geode/files/9679113/2022-09-29_23-07-50.log)

**Comment by HJfod** [comment]
logs seem to imply missing textures, have you installed all of the Geode textures?

**Comment by NewAlexGamer** [comment]
ok so i was about to write how i was about to write (yes this repetition is on purpose because that's what actually happened) the fact i was putting the geode.loader folder inside the gd resources and not inside the geode resources, but it still crashed
i am using mghv7 and following the instructions i loaded geode as a mod without XInput9_1_0.dll, opened the game and placed the geode.loader folder inside geode/resources, restarted the game and tested if the download tab was crashing again
sure enough i got this
[2022-09-29_23-21-13.log](https://github.com/geode-sdk/geode/files/9679172/2022-09-29_23-21-13.log)

**Comment by NewAlexGamer** [comment]
since using other mod loaders is a complete no go you should probably not include the instructions on how to install while having another mod loader

**Comment by altalk23** [comment]
where is that

**Comment by HJfod** [comment]
the instructions explicitly said "do not install alongside other mod loaders" in like 3 different ways and then said "if you still insist on doing that we will not help you when issues arise"

**Comment by NewAlexGamer** [comment]
guess i should read better next time, sorry for bothering you
