### ISSUE TITLE
create save and play crash

### ISSUE THREAD

**Issue by jugem718** [geode-sdk/geode#370]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

1.3.7

### Mods Installed

[v1.0.0] n.level_pronouns
x | [v1.3.7] geode.loader
x | [v1.0.0] deathfuel.blink
x | [v1.0.2] alk.fps-shower
x | [v5.0.0-alpha.10] be_team.betteredit
x | [v3.0.12] cvolton.betterinfo
x | [v1.0.5] alphalaneous.extraicons
x | [v2.2.5] alk.small-additions
x | [v1.0.1] mat.run-info
x | [v1.0.0] camila314.song-randomizer
x | [v1.0.0] alphalaneous.projectedstars
x | [v1.1.21] gdutilsdevs.gdutils
x | [v1.0.1] camila314.bezier
x | [v1.0.2] alphalaneous.integrated_loquibot
x | [v1.0.3] alphalaneous.separatedualicons
x | [v1.1.0] be_team.editorapi
x | [v1.0.0] nef.iconsave
x | [v1.0.4-beta] camila314.betterloading
x | [v1.0.0] iandyhd3.check_steam
x | [v1.0.0] camila314.demonlist-button
x | [v1.0.0] capeling.demons_in_garage
x | [v1.1.0] capeling.icon_profile
x | [v1.0.0] capeling.simple_icon_hack
x | [v1.0.1] cgytrus.8star-antianticheat
x | [v1.0.1] cvolton.lists
x | [v1.0.1] fig.video_player
x | [v1.2.3] geode.custom-keybinds
x | [v1.0.4] hjfod.gdshare
x | [v1.0.3] hjfod.gmd-api
x | [v1.5.3] tpdea.betterpause-Better
x | [v1.0.0] iandyhd3.custom_object_workshop
x | [v1.0.0] mat.circle-tool
x | [v1.0.4-beta.9] muhammadgames.bettermenu
x | [v1.0.0] o7moon.noglow
x | [v1.0.1] rlt.gd-multiprofile-mod

### Steps to Reproduce

save and play button cilck sometimes cresh

### Crash Report

Geometry Dash\geode\crashlogs

### Additional Information

does not exist

**Comment by Alphatism** [comment]
You posted the path to the crash report, not the actual crash report,

**Comment by Alphatism** [comment]
Also, remove BetterLoading, can guarantee this is causing issues.
