### ISSUE TITLE
Get rid of featured tab

### ISSUE THREAD

**Issue by matcool** [geode-sdk/geode#393]

**Comment by TechStudent10** [comment]
i agree with this, featured tab literally serves no purpose

**Comment by Fleeym** [comment]
Change it to modpacks :sunglasses:

**Comment by TechStudent10** [comment]
> Change it to modpacks 😎

Oh this is actually a good idea, change the featured tab to modpacks

**Comment by TheSillyDoggo** [comment]
#363

**Comment by sirbradinator** [comment]
I might fork it and add this for my first mod!!

**Comment by TheSillyDoggo** [comment]
Index is being rewritten with new ui so no point since it'll be useless
