### ISSUE TITLE
dont have it say Geode Crashed

### ISSUE THREAD

**Issue by Cvolton** [geode-sdk/geode#398]
### Geode Version

2.0.0

### Related Problem

the crash log says "Geode Crashed" "An exception was encountered while running Geode"

### Your Solution

imo it should say "Geometry Dash Crashed" "An exception was encountered while running Geometry Dash" because if it says Geode too much people are gonna blame Geode for the crashes because if the first thing they see is "Geode Crashed" they're gonna think it was Geode that crashed and seek running away immediately and boom now Geode evil :(((( and we don't want geode to be evil :((

**Comment by 0x1DEA** [comment]
I like the crash messages on jailbreaks based on Saurik's Cydia Substrate where upon entering safe mode the message says "MobileSubstrate DID NOT cause this this problem: it protected you from it."

Would that even be true? Does Geode have anything in place to crash as gracefully as possible? Idk if that would be possible but maybe one thing would be storing savedata in a crash directory if possible.

**Comment by cgytrus** [comment]
u cant rly crash gracefully like if smth went so wrong the game crashed its already too bad to continue running

**Comment by 8ightfold** [comment]
You can handle crashes if they actually happen in Geode

**Comment by kynex7510** [comment]
I propose to replace "Geode crashed" with "Geode dashed into a spike", it's more fitting, it's playful and belittles Geode involvement with horrible crashes that make people lose their savegames.
