### ISSUE TITLE
Compile Geode 2.0.0

### ISSUE THREAD

**Issue by JFIUG** [geode-sdk/geode#402]
### Your Question

How can i compile Geode. 2.0.0 for mac? 
i tried much times with that cmake folder but when it compiles it says an error <sub>(i</sub> <sup>don't</sup> <sub>remember <sup>it)</sup>

**Comment by TheSillyDoggo** [comment]
Mac is broken that's why there's no version's

**Comment by matcool** [comment]
geode 2.0.0 macos is missing many bindings, it is intentionally broken as no one has worked on it so far.

**Comment by JFIUG** [comment]
oh.
