### ISSUE TITLE
tulip hook crash

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/geode#408]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

a2e0408

### Geode Version

v2.0.0

### Mods Installed

i had no mods installed except for the basic mod:

```c++
#include <Geode/Geode.hpp>
#include <Geode/modify/MenuLayer.hpp>

using namespace geode::prelude;

class $modify(MenuLayer) {
	void onMoreGames(CCObject*) {
		FLAlertLayer::create("Geode", "Hello from my custom mod!", "OK")->show(); 
	} 
};
```

### Expected Behavior

Hook the function

### Actual Behavior

game crashes

### Steps to Reproduce

1) compile this mod
2) open gd
3) success (or not in this case)

**Comment by matcool** [comment]
Could not recreate the issue, code and built version here: https://github.com/matcool/insane-crash-geode-mod
