### ISSUE TITLE
multiple issues related to InputNode

### ISSUE THREAD

**Issue by dankmeme01** [geode-sdk/geode#411]
### Geode Version

v2.0.0

### Related Problem

The class `geode::InputNode` currently has at least two issues (one on Android):

1. On all platforms, the text is not scaled properly. As seen in the screenshot below, the text does not use the entire space of the input node.
2. On Windows, the method `InputNode::getString` will always return an empty string, even if there's some text in the input node.

![image](https://github.com/geode-sdk/geode/assets/42031238/1fb33774-83aa-4946-88ca-7dfd102df85b)

### Your Solution

i do not know as i am not a lead geode developer

**Comment by matcool** [comment]
only thing thats left rn is the hitbox being in the wrong location, and this is due to cctextinputnode ignoring anchor points :(

**Comment by altalk23** [comment]
can you test on latest

**Comment by matcool** [comment]
oh yeah this is all fixed now. i think

**Comment by dankmeme01** [comment]
thats right mat thank you
