### ISSUE TITLE
Latest nightly for 2.202 crashes the game when clicking on the geode button in the main menu

### ISSUE THREAD

**Issue by marthabo** [geode-sdk/geode#413]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0 nightly 1989483

### Steps to Reproduce

1) Click on the geode button in the main menu

### Crash Report

https://pastebin.com/6Dthnww7

**Comment by matcool** [comment]
already fixed, just hasnt been compiled with latest bindings.. besides, missing bindings crashes are quite boring
