### ISSUE TITLE
cancelling a mod installation makes it impossible to install the mod again

### ISSUE THREAD

**Issue by dankmeme01** [geode-sdk/geode#418]
### Geode Version

v2.0.0

### Related Problem

Steps to reproduce:

1. try to install a mod from the index
2. press "cancel" before the installation finishes
3. try to install the same mod again

The installation status will be stuck at "Starting install" and it will be impossible to install the said mod again until you restart the game.

### Your Solution

fix it imo

**Comment by eggonthebeat** [comment]
heyyyy

**Comment by dankmeme01** [comment]
i fixed it

**Comment by matcool** [comment]
where

**Comment by dankmeme01** [comment]
https://github.com/geode-sdk/geode/commit/2138579d14045f897fde51e976171c5b9d9510b1
