### ISSUE TITLE
Float input setting doesn't support decimals

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/geode#428]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Expected Behavior

be able to type decimals

### Actual Behavior

no decimals

### Steps to Reproduce

1) create a float type setting in a mod without a slider
2) write a number with a decimal
3) no decimal

**Comment by matcool** [comment]
fixed in beta.15
