### ISSUE TITLE
GD Crashes After Unistalling Geode

### ISSUE THREAD

**Issue by NoG4m3** [geode-sdk/geode#431]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0 beta 2

### Mods Installed

was using only index mods but i dont remember which

### Steps to Reproduce

1. i installed geode and everything worked fine, i installed some index mods and then closed the game and shut down the computer
2. the next day i tried to play GD but it just didnt open
3. i tried unistalling geode, i unistalled gd manually and convalidated game files, i deleted my savefile but GD still crashes

### Additional Information

i think this is caused by me having downloaded many index mods

**Comment by matcool** [comment]
geode cannot affect your game after you've uninstalled it. sounds like improper uninstallation

**Comment by NoG4m3** [comment]
sorry for disturbing you, arleady fixed it
