### ISSUE TITLE
GD won't launch

### ISSUE THREAD

**Issue by ThatMG393** [geode-sdk/geode#438]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android

### Geode Version

v2.0.0-beta.4

### Mods Installed

[v1.4.0] geode.texture-loader
[v1.1.0] capeling.icon_profile_2.2
[v1.2.12] gdutilsdevs.gdutils
[v1.1.2] firee.PrismMenu
[v4.0.0-alpha.5] cvolton.betterinfo
[v1.1.2] geode.node-ids
[v2.0.0-beta.4] geode.loader

### Steps to Reproduce

Just launch the game

### Crash Report

Crashlog: https://pastebin.com/BXjCEpFD
Log: https://pastebin.com/wFGkhMpN

**Comment by FireMario211** [comment]
sounds like the same tuliphook issue with BetterInfo

**Comment by ThatMG393** [comment]
@FireMario211 It's fixed but now it crashed when I opened saved levels

Logs:
```
Geode crashed!
Please submit this crash report to the developer of the mod that caused it.

== Geode Information ==
Loader Version: v2.0.0-beta.4
Loader Commit: c2f626b
Bindings Commit: 1df21db
Installed mods: 5
Problems: 0

== Installed Mods ==
x | [v1.1.0] capeling.icon_profile_2.2
x | [v1.2.12] gdutilsdevs.gdutils
x | [v1.4.0] geode.texture-loader
x | [v1.1.2] geode.node-ids
x | [v2.0.0-beta.4] geode.loader

== Crash Report (Logcat) ==
F/libc    ( 3379): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa4bcc2aa in tid 3440 (GLThread 446), pid 3379 (.geode.launcher)
F/DEBUG   ( 3454): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   ( 3454): Build fingerprint: 'samsung/a13xzh/a13x:14/UP1A.231005.007/A136BZHU5DWK7:user/release-keys'
F/DEBUG   ( 3454): Revision: '14'
F/DEBUG   ( 3454): ABI: 'arm'
F/DEBUG   ( 3454): Processor: '-1'
F/DEBUG   ( 3454): Timestamp: 2024-01-22 10:10:44.913200084+0800
F/DEBUG   ( 3454): Process uptime: 5s
F/DEBUG   ( 3454): Cmdline: com.geode.launcher
F/DEBUG   ( 3454): pid: 3379, tid: 3440, name: GLThread 446  >>> com.geode.launcher <<<
F/DEBUG   ( 3454): uid: 10657
F/DEBUG   ( 3454): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa4bcc2aa
F/DEBUG   ( 3454):     r0  ee12e400  r1  00000001  r2  00000000  r3  a4bcc2aa
F/DEBUG   ( 3454):     r4  ee12e400  r5  00000001  r6  00000000  r7  00000000
F/DEBUG   ( 3454):     r8  ee12e400  r9  c2ccf304  r10 00000006  r11 000013a2
F/DEBUG   ( 3454):     ip  c26ab718  sp  c2f80d70  lr  ee154619  pc  c26ab71e
F/DEBUG   ( 3454): 2 total frames
F/DEBUG   ( 3454): backtrace:
F/DEBUG   ( 3454):       #00 pc 0031371e  /data/app/~~w5U35bRc1ciBNnhWlqd9Lg==/com.robtopx.geometryjump-hcY622kjHp4SAJ7XgcRTdA==/lib/arm/libcocos2dcpp.so (GameManager::isIconUnlocked(int, IconType)+14) (BuildId: 368e9b7fbd840c0f45951d388885f4da7b66a057)
F/DEBUG   ( 3454):       #01 pc 00006617  <anonymous:ee14e000>
```

**Comment by altalk23** [comment]
not a geode issue

**Comment by Mystifyjackk** [comment]
its so bad I cant even play the game anymore, and i dont know how to delete geode and then reinstall all the mods and stuff.


2024-11-01T20:31:40-0500
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.9.0
Loader Commit: bd8387d
Bindings Commit: caeff54
Installed mods: 9
Problems: 2

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: Integrated Demonlist v1.6.3 (hiimjustin000.integrated_demonlist)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 5fe4c (RaiseException + 108)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 57689 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:411)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 2a0ee9 (matjson::Value::as_array + 73 | /home/runner/work/geode/geode/cpm-cache/json/7be1271964142fe09a9ce8136cda20080acc1e08/src/value.hpp:66)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + d2fe
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 121a4
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 12340
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 58b4
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 523c
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 7bb4b (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 154d83 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:275)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 8e5a2 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 6881d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 0000026FF69E4482 (Hook handler)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 0000026F8B181C82 (Hook handler)
 - 0000026F8B181C82 (Hook handler)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\Geode.dll + 29218a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Program Files (x86)\Steam\New folder\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af08 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000040
RBX: 0000000000000000
RCX: 0000026ff34e0de0
RDX: 0000000000000000
RBP: 0000000000000000
RSP: 000000bd628ffa30
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff950baaf08
R8:  0000000000000004
R9:  0000000000000000
R10: 000000bd628fe269
R11: 0000026ff35b0000
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.4] alphalaneous.click_after_frames
! | [v1.6.2] dankmeme.globed2
x | [v1.7.0] geode.devtools
x | [v3.9.0] geode.loader
x | [v1.15.0] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.6.3] hiimjustin000.integrated_demonlist
! | [v1.2.2] syzzi.click_between_frames
x | [v1.6.10] thesillydoggo.qolmod

**Comment by hiimjustin000** [comment]
https://youtu.be/vk0k57b_tD8
