### ISSUE TITLE
Geode dissappeared?

### ISSUE THREAD

**Issue by ark2000k** [geode-sdk/geode#441]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.6

### Mods Installed

BetterEdit, BetterInfo, Gradient Pages, Prism Menu

### Expected Behavior

Should be loading mods in, and having geode menu

### Actual Behavior

Mods and Geode menu not there

https://github.com/geode-sdk/geode/assets/123225182/e918c464-540b-4005-9ebf-9dc84ab3bd2d

### Steps to Reproduce

all i did was press launch

### Additional Information

This is on android; there was no android option above so I selected windows.

**Comment by ark2000k** [comment]
I tried clearing Geode's data and uninstalling, but it still doesnt have the mod menu when i reinstalled

**Comment by Fleeym** [comment]
GD got updated on Android today, make sure you are on the latest version

**Comment by ark2000k** [comment]
> GD got updated on Android today, make sure you are on the latest version

Just made sure, this still happens 

https://github.com/geode-sdk/geode/assets/123225182/251d4e49-14e3-4e0c-bb02-428b42145e57

**Comment by Fleeym** [comment]
I meant GD updates, not geode

**Comment by ark2000k** [comment]
Oh, my bad

Thank you! It works now!
