### ISSUE TITLE
Geometry Dash 2.205 came to mobile(im not kidding)and bcz of that i cant open Geode.

### ISSUE THREAD

**Issue by Stunteh** [geode-sdk/geode#442]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta6

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

**Comment by Stunteh** [comment]
It only says MacOS and Windows but im playing on mobile.

**Comment by TheSillyDoggo** [comment]
update geode

**Comment by Stunteh** [comment]
Same.Nothing happened.

**Comment by Stunteh** [comment]
Update on issue:Download tab says that the latest version is v2.0.0-beta6. When i download it,the file says v1.0.0-beta3.Thats like half of the download tab!And when i open the app and press launch,it says:"Unsupported Launcher".
