### ISSUE TITLE
Geode crash

### ISSUE THREAD

**Issue by TV46** [geode-sdk/geode#448]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

beta.7

### Steps to Reproduce

wait around on main menu for a bit or also try switching windows and sleeping pc.

### Crash Report

[Geode 24 Jan 19.07.29.log](https://github.com/geode-sdk/geode/files/14036396/Geode.24.Jan.19.07.29.log)

**Comment by altalk23** [comment]
that is not a crash report that is just the console log, and this log tells me everything is fine
