### ISSUE TITLE
Drag-scrolling in mod info is broken

### ISSUE THREAD

**Issue by Bituvo** [geode-sdk/geode#451]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.8

### Expected Behavior

Appropriate drag-scrolling behavior.

### Actual Behavior

Drag-scrolling is cancelled if your mouse moves too fast (the bar is very low).

### Steps to Reproduce

1. Click "View" on a mod listing.
2. Click and drag inside the mod info box to scroll it.
3. Observe

**Comment by altalk23** [comment]
can't recreate on android at least, lets see windows

**Comment by Bituvo** [comment]
Whar

**Comment by matcool** [comment]
this was already fixed in https://github.com/geode-sdk/bindings/commit/f7388c97c9064a0b4df205ab5be99c95f7dcfe41
and again in https://github.com/geode-sdk/bindings/commit/7d7b9260575497363ce302de4a8665461911ae56
are you compiling geode yourself? we cant recreate this.

**Comment by Bituvo** [comment]
No, I got it from the website.
