### ISSUE TITLE
Geode crash on Android

### ISSUE THREAD

**Issue by RzaIX** [geode-sdk/geode#455]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android (64 bit)

### Geode Version

Geode v2.0.0-beta.9

### Mods Installed

bitz.customprofiles, fleym.nongd, cvolton.betterinfo

### Steps to Reproduce

Every few minutes it crashes, in previous versions it worked fine

### Crash Report

[2024-01-25_11-02-05.log](https://github.com/geode-sdk/geode/files/14046670/2024-01-25_11-02-05.log)

**Comment by matcool** [comment]
windows or android? choose one..

**Comment by RzaIX** [comment]
Android

**Comment by Rustring** [comment]
Edit your main comment
