### ISSUE TITLE
Index loads absolutly nothing on macos

### ISSUE THREAD

**Issue by Eclipse-5214** [geode-sdk/geode#456]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v2.0.0-Beta-9

### Mods Installed

just geode

### Expected Behavior

show a list of mods

### Actual Behavior

nothing showed up

### Steps to Reproduce

download geode macos
go to download tab
<img width="1440" alt="Screenshot 2024-01-25 at 8 17 38 AM" src="https://github.com/geode-sdk/geode/assets/83417472/6299f003-bb4c-413b-8cb3-00133f325206">

**Comment by Weebifying** [comment]
> MacOS support!. Note that this is very new, things might crash and there are no mods for it still.

**Comment by matcool** [comment]
theres literally no mods for macos. thats it
