### ISSUE TITLE
Extend the mod description textbox downwards

### ISSUE THREAD

**Issue by Electrro** [geode-sdk/geode#458]
### Geode Version

v2.0.0-beta9

### Related Problem

![slika](https://github.com/geode-sdk/geode/assets/106490798/8ab73de7-f82a-4448-9216-227712d474a4)
there's some empty space down there

### Your Solution

extend the text box down:
-less scrolling
-more info

**Comment by Bigmancozmo** [comment]
There's a "report an issue" button under it on certain mods. 
![Screenshot_20240215_073645_Geode.jpg](https://github.com/geode-sdk/geode/assets/67850768/9b140ad2-9de1-44c6-bc60-b1d48ff12ff8)

**Comment by qimiko** [comment]
think it's safe to call this one fixed on the new index :)

![image](https://github.com/geode-sdk/geode/assets/25387744/bb076aae-d44c-41e0-ae68-167334ac54c6)
