### ISSUE TITLE
Geode Freezing on Mobile

### ISSUE THREAD

**Issue by Rustring** [geode-sdk/geode#460]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android (32bit copy of GD)

### Geode Version

2.0.0 Beta 9

### Actual Behavior

Everytime the game would launch it would freeze for a few seconds on updating index untill it says index is up to date

### Steps to Reproduce

Open the game on a 32 bit copy of geometry dash android

**Comment by matcool** [comment]
should be fixed in beta.10

**Comment by Rustring** [comment]
Yeah it's fixed now

**Comment by Rustring** [comment]
Also unzipping index takes way too long on Android

**Comment by matcool** [comment]
> Also unzipping index takes way too long on Android

Well at least its async now :-)
