### ISSUE TITLE
Text doesn't appear in text boxes in mod settings

### ISSUE THREAD

**Issue by BeatACVR** [geode-sdk/geode#462]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.10

### Expected Behavior

![image](https://github.com/geode-sdk/geode/assets/75857504/c624aa09-2fd4-498c-8303-600f7d274ee8)

A number appears in the text box (integer)

### Actual Behavior

![image](https://github.com/geode-sdk/geode/assets/75857504/17e23983-8672-4549-be3f-30fb6e2a4d14)

Text is invisible in the textbox after updating

### Steps to Reproduce

1) Look at the settings of a mod that has a textbox
2) No text appears in the textbox.

**Comment by matcool** [comment]
fixed in beta.11
