### ISSUE TITLE
installer should have experimental option to force install

### ISSUE THREAD

**Issue by matcool** [geode-sdk/geode#472]
delete all the dlls that are conflicting type of thing. warn the user though

**Comment by sirbradinator** [comment]
You could do that with a radar function to search for dlls and delete them and warn user. If a system warning comes up, it will abort.

**Comment by TheSillyDoggo** [comment]
> You could do that with a radar function to search for dlls and delete them and warn user. If a system warning comes up, it will abort.

We only need to remove mega hack DLLs and a few others not every dll

**Comment by sirbradinator** [comment]
But you also have stuff like gdmo and other free modding menus. It could list the folders and dlls that will be deleted and it can be modified
