### ISSUE TITLE
Proper handaling of outdated mods

### ISSUE THREAD

**Issue by Netherbat** [geode-sdk/geode#473]
### Geode Version

v2.0.0 beta 12

### Related Problem

Currently, if a mod cannot be loaded because it has been designed for an older version of geode, the warning "some mods failed to load" will be displayed with nothing else happening. 

The only way to remove these mods is to delete the .geode files manually

### Suggested Solution

a pop-up is displayed listing the incompatible mods and providing the option to delete or ignore the mods

**Comment by altalk23** [comment]
fixed with [d9c65b3](https://github.com/geode-sdk/geode/commit/d9c65b37eafb48490dcceb15af925f27415f9e68)
