### ISSUE TITLE
Fix android64 exceptions

### ISSUE THREAD

**Issue by matcool** [geode-sdk/geode#477]
apparently they work fine on mods, but not on geode itself

**Comment by qimiko** [comment]
i'm posting my backtrace sorry mat (it's inspiring)
![backtrace showing a crash from create_directories](https://github.com/geode-sdk/geode/assets/25387744/cab40ea2-4519-4d3d-8fca-2ed10358e1c1)

**Comment by DEADBUGGETE** [comment]
Where is download

**Comment by iHarouse** [comment]
there's an issue on geode rn, I use android 64 and the mods aren't loading ¯\_(ツ)_/¯

**Comment by matcool** [comment]
fixed in 3.0.0, by using c++_shared and a fix in the launcher itself
cfb682ef7999f90e8f01ef79ce611969dcd08f75
https://github.com/geode-sdk/android-launcher/commit/c61d65222942ff7dd7a53a70e48ae0e9be3d65be
