### ISSUE TITLE
Crash when exiting custom level - unknown if caused by mod

### ISSUE THREAD

**Issue by ClaytonTDM** [geode-sdk/geode#478]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.12

### Mods Installed

Only showing enabled mods, all mods are listed in the crash report
[v8.0.0-alpha.9] absolllute.megahack
[v1.1.0] adyagd.godlikefaces
[v1.0.1] alphalaneous.happy_textures
[v1.1.2] alphalaneous.projectedstars
[v1.0.5] bitz.customprofiles
[v1.0.2] blackholemx.nomoregames
[v1.1.2] capeling.demons_in_garage_2.2
[v1.1.1] capeling.icon_profile_2.2
[v1.0.1] colon.bumpscosity
[v4.0.0-alpha.9] cvolton.betterinfo
[v2.2.0] fleym.nongd
[v1.2.14] gdutilsdevs.gdutils
[v1.4.0] geode.devtools
[v2.0.0-beta.12] geode.loader
[v1.1.4] geode.node-ids
[v1.5.0] geode.texture-loader
[v1.0.4] hjfod.gdshare
[v1.0.1] hjfod.gmd-api
[v1.0.1] itzkiba.elegant_rankings
[v1.1.0] itzkiba.grandpa_demon
[v1.0.0] legowiifun.unlisted_objects_in_editor
[v1.1.3] mat.circle-tool
[v1.0.1] mat.draw-divide
[v1.0.2] mat.run-info
[v1.1.0] mat.scroll-zoom
[v1.0.3] n.level_pronouns
[v1.2.0-beta.3] org.dogotrigger.deathreplay
[v1.1.0] redlime.statchanges
[v1.2.0] sanes.daily-transfer
[v1.1.4] shineua.minecraft_splash
[v1.0.2] skyward.no_robtop_logo
[v2.2.0] techstudent10.discord_rich_presence
[v1.1.0] thesillydoggo.better_startpos_menu
[v1.0.0] thesillydoggo.entersearch
[v1.2.0] thesillydoggo.moretags
[v1.0.0] uproxide.geodedevelopers
[v1.0.0] weebify.coins_in_pause_menu
[v1.0.1] weebify.restartbtn
[v1.2.1] zilko.xdbot

### Steps to Reproduce

1. Go to a custom level
2. After playing for a while, double-tap Esc to exit (with transitions off)
3. Your game crashes right after loading the level page

### Crash Report

https://gist.github.com/ClaytonTDM/4007cfc768a6baab5a0c796b8875af11

### Additional Information

It's unknown if this is caused by a mod, because the stack trace contains both mod and non-mod instances. I'm reporting this here just to be safe.
The issue doesn't happen 100% of the time, it seems to be random.

**Comment by TheSillyDoggo** [comment]
39 mods :ned:
