### ISSUE TITLE
Enabling/disabling mods shouldn't affect anything until confirmed

### ISSUE THREAD

**Issue by Corsaka** [geode-sdk/geode#483]
### Geode Version

v.2.0.0-beta.4

### Related Problem

Clicking an enable/disable box on geode's mod browser will immediately remove that box and replace it with a restart prompt, even though nothing has happened to the mod yet. This prevents you from viewing the mod and enabling/disabling the mod again if you misclicked.

### Your Solution

It would make more sense if you could toggle whether mods will be enabled or disabled freely, and the restart prompt is only triggered by trying to return to the main menu. A pop-up of "You've made changes to your enabled mods. Do you want to restart now?" with a restart/cancel prompt would fit this well.

### Additional Information

Mainly a QoL thing. It kinda sucks that I can't view a mod after I've clicked disable, or if I misclick a disable button while trying to view a mod and then have to entirely restart my game twice to get it back. I'd prefer to Not do that.

**Comment by silvernull** [comment]
## I apologise in advance for my poor preview

Something like this perhaps would work?
Moving the restart option to a separate location, e.g. one of two pink options in the top right, that still allows us to press view on the mod and re-enable/disable it if we pressed on it accidentally so we do not need to restart additionally.

Or have to do it in the main menu with a button like Weebify's Restart Button mod.

I'm not sure what the ideal method to implement it would be.

![image](https://github.com/geode-sdk/geode/assets/80038133/0217fdff-87ca-403d-a9c8-8f54cb74129d)

**Comment by qimiko** [comment]
i think this is fixed?

![image](https://github.com/geode-sdk/geode/assets/25387744/a83ce397-ba90-4e23-a156-1c504d1ed8c9)
