### ISSUE TITLE
Make level: and mod: links work for about.md files

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/geode#486]
### Geode Version

v2.0.0-beta.14

### Related Problem

As specified in the Geode documentation on the MDTextArea class

> Note that links also have some special protocols. Use user:\<id> or user:\<name> to link to a GD account; level:\<id> to link to a GD level and mod:\<id> to link to another Geode mod.

currently only "user:" links work not "mod:", nor "level:" links.

### Your Solution

To be able to use "level:" and "mod:" links in game for MDTextArea.

### Additional Information

Currently, when you click "level:" or "mod:" links in Geometry Dash on a Mod's about.md (or a MDTextArea class), they go to Windows instead of going to the level or mod in the game. Windows asks what application you want open the link with, Geometry Dash is not listed and instead their is only one option, look for an app on the Microsoft Store.

**Comment by Corsaka** [comment]
For the additional: that's an OS level assignment of a default program to open .md (markdown) files. You don't want that because Geometry Dash isn't the only program that uses markdown, and trying to open non-GD-formatted files with GD will end poorly.

**Comment by cgytrus** [comment]
@Corsaka thats not about the md file, thats about clicking a level: or a mod: link *inside* of the game in an MDTextArea, not double-clicking a file in windows explorer.

**Comment by Corsaka** [comment]
...which attempts to open it as a markdown file.

**Comment by matcool** [comment]
idk what ur on brah this is just about the geode provided MDTextArea, which has special tags already like user: to open the profile of an account. this has nothing to do with windows file assignment

**Comment by coopeeo** [comment]
fixed in #664
