### ISSUE TITLE
Geode Crash

### ISSUE THREAD

**Issue by MasterGamerY** [geode-sdk/geode#488]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

V.2.0.0-Beta.15

### Mods Installed

x | [v1.0.2] abb2k.backup
x | [v1.0.3] adam_729.deathmarkers
x | [v1.0.0] adyagd.ingamelistmod
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.0] arkane.dl-team-icons
x | [v1.0.4] b1rtek.gddlintegration
x | [v1.3.1] beat.click-sound
x | [v1.1.2] capeling.demons_in_garage_2.2
x | [v1.1.4] capeling.icon_profile_2.2
  | [v1.1.3] cdc.more-hints
x | [v4.0.0-alpha.12] cvolton.betterinfo
  | [v1.0.2] dogotrigger.roulette
x | [v1.0.1] ekv.hidePauseMenuHack
x | [v1.0.0] ekv.save_on_level_page
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.3.2] elohmrow.death_tracker
x | [v1.0.3] firee.GoldenBest
  | [v1.3.2] firee.PrismMenu
x | [v2.2.4] fleym.nongd
x | [v1.2.14] gdutilsdevs.gdutils
x | [v2.0.0-beta.15] geode.loader
x | [v1.2.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.0.4] hjfod.gdshare
x | [v1.0.1] hjfod.gmd-api
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.0.0] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.0] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.2] mat.run-info
x | [v2.3.0] maxnu.gd_mega_overlay
x | [v1.0.4-beta.12] muhammadgames.bettermenu
x | [v1.0.3] n.level_pronouns
x | [v1.1.2] oatmealine.nlw_integration
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.6.1] prevter.openhack
x | [v1.1.0] redlime.statchanges
x | [v1.2.0] sanes.daily-transfer
x | [v1.2.1] shineua.minecraft_splash
x | [v1.0.0] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
x | [v1.0.0] thesillydoggo.entersearch
x | [v1.2.0] thesillydoggo.moretags
x | [v1.6.1] undefined0.gdtweaks
x | [v1.0.1] uproxide.geodedevelopers
  | [v1.1.0] weebify.jumpscare
x | [v1.0.2] weebify.restartbtn
x | [v1.3.4] zilko.xdbot

### Steps to Reproduce

Whenever you try to exit a level, the game crashes.

### Crash Report

[2024-02-04_20-30-49.log](https://github.com/geode-sdk/geode/files/14159415/2024-02-04_20-30-49.log)

**Comment by MasterGamerY** [comment]
Is the game crashing due to a specific mod? If so, which one?

**Comment by InsomniaGaming** [comment]
For more info, the mods I found that could crash the game this way are GD Utils, Prism Menu, Hide Pause Menu Hack, Click Sound, More Tags, StartPos Switcher, and XDBot.

**Comment by MasterGamerY** [comment]
I turned off Click Sound and it seems to work fine now. Closing, thank you!

**Comment by InsomniaGaming** [comment]
Actually, it probably depends on how many active mods you have. It appeared as if you had 45 mods active, which might have been the mod limit.

**Comment by Derlop47285** [comment]
Geode also crashed 2.207
