### ISSUE TITLE
Restrart Button Wierd Location

### ISSUE THREAD

**Issue by Rustring** [geode-sdk/geode#490]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v2.0.0-beta.15

### Mods Installed

Look here
![Screenshot_20240205_183621](https://github.com/geode-sdk/geode/assets/155897302/6fcbc7ba-80ef-40c9-a2aa-f07e99d128a5)

### Expected Behavior

Restart button should be on its regular place

### Actual Behavior

Restart button is on the top right
![Screenshot_20240205_183249](https://github.com/geode-sdk/geode/assets/155897302/479c4c2a-7e06-4082-8e29-dee0d431e1ec)

### Steps to Reproduce

Go in the game and check the restart button

**Comment by matcool** [comment]
your ass is Not on macos. update nodeids

**Comment by Rustring** [comment]
> your ass is Not on macos. update nodeids

I was changing it they don't allow anything other than MacOS or Windows

**Comment by matcool** [comment]
youre running the windows version of the game through wine. select windows

**Comment by Rustring** [comment]
I've changed it now
