### ISSUE TITLE
Unzipping index on Android 

### ISSUE THREAD

**Issue by Entibrine** [geode-sdk/geode#492]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

V2.0.0-beta.16

### Expected Behavior

Expected to get all mods listed after unzipping index.

### Actual Behavior

Keeps on repeating "unzipping index..." Over and over after 5+ minutes.

### Steps to Reproduce

1) open geode
2) launch GD
3) click the geode button
4) click the "download" tab

### Additional Information

I do not know if this is a device issue or something directly related to geode. A short time ago I could still see the mods, but after one geode update, it just repeats unzipping index forever.

**Comment by Potatosei** [comment]
same problem here but with updating local cache 
![Screenshot (171)](https://github.com/geode-sdk/geode/assets/140474345/2c1d748d-1f43-4b1d-8d0f-591776ab4ef0)

**Comment by gdcolo7** [comment]
doesn't work on a fresh android install, now i have to download mods manually :((
