### ISSUE TITLE
geode::InputNode sets you to the start when clicking it

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/geode#498]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

>= 2.0.0

### Expected Behavior

clicking it should set the selection to where the cursor is

### Actual Behavior

Sets you to the start of the text input field instead of where you click (what 2.2 does)

### Steps to Reproduce

Click on any geode::InputNode

**Comment by matcool** [comment]
Yeah

**Comment by TheSillyDoggo** [comment]
also with input node you can click it when it isn't visible

**Comment by matcool** [comment]
> also with input node you can click it when it isn't visible

fixed in bf43946dafca5705e0a60e1f9e5c71be62a0e684

**Comment by dankmeme01** [comment]
should've been fixed already some time ago
