### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by RealFX-Code** [geode-sdk/geode#499]
### Geode Version

latest

### Related Problem

I recently installed Debian Sid on my pc, And geode doesn't work anymore under proton. This was an issue with MegaHack too, so it seems to be an issue with Proton.

### Your Solution

I'd love a workaround of some sorts for linux users, I'm not entirely sure how to do that myself.

**Comment by Cvolton** [comment]
see #190

**Comment by RealFX-Code** [comment]
> see #190

Thanks, I'll check that out.
Sorry I didn't see that before.
