### ISSUE TITLE
Geode Gives an error but im playing GD 2.205 but Geode Lastest Requires 2.200

### ISSUE THREAD

**Issue by enessmr** [geode-sdk/geode#500]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

Developer Realese or 16_Beta2

### Mods Installed

nothing

### Expected Behavior

idk in title

### Actual Behavior

in Title.

### Steps to Reproduce

IN TITLE.

**Comment by matcool** [comment]
Good one

**Comment by Cvolton** [comment]
download the newest version of the launcher from https://geode-sdk.org/install

**Comment by enessmr** [comment]
here is the reveal
![Ekran görüntüsü 2024-02-09 225827](https://github.com/geode-sdk/geode/assets/136172887/3a69dc1e-5ce2-4023-92fc-3022f732daa9)

**Comment by enessmr** [comment]
but its the lastest

**Comment by matcool** [comment]
Error clearly shows youre on 2.200 while we only support 2.204. Lol!

**Comment by enessmr** [comment]
;-;

**Comment by enessmr** [comment]
but
i hav an idea

**Comment by enessmr** [comment]
ok,i cannot say it because it was pirating is bad.
