### ISSUE TITLE
Android 5 can't read Geode APK Properly

### ISSUE THREAD

**Issue by SevenworksDev** [geode-sdk/geode#502]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

v2.0.0-beta.16

### Expected Behavior

For the Android 5.0.1 Package Manager to be able to read the APK properly and be prompted to install it.

### Actual Behavior

Recieve a Package Manager "There was a problem parsing this package." error.

### Steps to Reproduce

1) Download Geode 32bit for Android
2) Run the APK with Package Manager

### Additional Information

I don't know if this is an AndroidManifest.xml issue or something since I'm not too experienced with android app development. If this is intentional then this is unfair since Geometry Dash has a minimum compatibilty of Android 5.0+ so it would at least make sense for Geode to support it as well. 😎😎

**Comment by matcool** [comment]
we intentionally only support android 6+. Get a new phone.
