### ISSUE TITLE
Game freezes when unlocking the phone after suspension and trying to play a level.

### ISSUE THREAD

**Issue by fedew04** [geode-sdk/geode#503]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.16

### Mods Installed

GDUtils, Golden Best, Jukebox, Node IDs, Run Info (anyways, this happens with no mods)

### Expected Behavior

I should be able to play levels after unlocking my phone.

### Actual Behavior

When I leave the phone AFK on the pause menu of a level and the phone enters suspension, after unlocking the phone the game "works" until I try to resume the level, then the game permanently freezes and you have to force close it. If you press the menu button, it does send you to the menu, but after clicking play on any level the game freezes. The same happens if the phone enters suspension while on the main menu; trying to play any level after unlocking the phone freezes the game.

### Steps to Reproduce

1) Open the main menu
2) Leave the phone AFK until its suspended (or manually lock the phone)
3) Unlock the phone and try to play any level

or

1) Open the pause menu inside a level
2) Leave the phone AFK until its suspended (or manually lock the phone)
3) Unlock the phone and try to resume the level

**Comment by matcool** [comment]
this is more of a https://github.com/geode-sdk/android-launcher issue than geode itself
