### ISSUE TITLE
Geode Installer crashes when attempting to open

### ISSUE THREAD

**Issue by delusionss** [geode-sdk/geode#505]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.16-win

### Mods Installed

null

### Steps to Reproduce

1) Open Geode Installer
2) Watch it attempt to open and crash

### Crash Report

null

**Comment by matcool** [comment]
pretty unhelpful reproduce steps because most people simply dont get that
