### ISSUE TITLE
geode loader not doing anything and corrupting mods

### ISSUE THREAD

**Issue by uhokay4** [geode-sdk/geode#509]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

beta 17

### Expected Behavior

expected for geode updater to close itself and then open geometry dash

### Actual Behavior

geode updater opens but stays open, and when closed corrupts mods because not unzipped correctly

### Steps to Reproduce

1. start geometry dash
2. open geode menu
3. update mods
4. click restart
5. geode loader stays open

**Comment by VoxelDoesCode** [comment]
That's happening to me, too. NodesID doesn't unzip properly somehow, and when I try to reinstall, the popup for GeodeUpdater.exe doesn't close.
