### ISSUE TITLE
Geode crashes when trying to load mods

### ISSUE THREAD

**Issue by VeryRandomGitHubPerson** [geode-sdk/geode#510]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

Last version of this issue posted

### Mods Installed

Geode launcher

### Steps to Reproduce

1. Open GD
2. Open mods or cant be the causing
3. wait to load mods
4. Game crashes!

### Additional Information

i dont know why this happens, i play in a windows 8 with a win10 OP. supports 2 drives and a Micro-sd spot. if someone know why, write in someplace im so new in github

**Comment by od3f** [comment]
I need help too! I keep having to uninstall and reinstall Geode and each time i install GD Mega Overlay or any mod, It just crashes for absolutely no reason!

**Comment by AliixGD** [comment]
Hi, im just having this issue now. did u ever sort it and if so how? thanks
