### ISSUE TITLE
infinite downloading 100% in download new mods

### ISSUE THREAD

**Issue by Gre4ka43** [geode-sdk/geode#515]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.18

### Mods Installed

GD mega overlay v2.4.6

### Expected Behavior

I expected to download mods in GD

### Actual Behavior

![image](https://github.com/geode-sdk/geode/assets/159810104/e4ec5377-3e0f-4ae6-ba6c-aa52c9de4355)

### Steps to Reproduce

idk because after I download mod. it happens again and again

**Comment by Zixil245** [comment]
did you solve the problem?

**Comment by wllstn** [comment]
what did you do to fix it? i have the same poblem
