### ISSUE TITLE
Unofficial Linux Support?

### ISSUE THREAD

**Issue by skyler948** [geode-sdk/geode#520]
### Your Question

Does anyone know a method to use geode on linux? I have tried installing it with the latest version of wine (9.1 (Staging)) and using the same version of proton that GD is using on steam (5.0-10), the installer opens and it installs, but geode does not work upon opening the game.

**Comment by Rajala1404** [comment]
Tried the same but within the Steam Prefix and have the same problem

**Comment by Rajala1404** [comment]
Just add WINEDLLOVERRIDES="XInput9_1_0.dll=n,b" %command% to your  Start options then it should work.
I use Arch btw
![image](https://github.com/geode-sdk/geode/assets/115874847/b03c97d6-4052-4518-ab2e-38fa85395adc)

**Comment by skyler948** [comment]
Yep, that did it. Thank you! (I'm not on arch btw ;))
