### ISSUE TITLE
Geode crashes upon launch

### ISSUE THREAD

**Issue by NewHubWhoDis** [geode-sdk/geode#521]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.19

### Steps to Reproduce

1) Open Geode

### Crash Report

https://pastebin.com/BeBrYsY6

### Additional Information

The Android model was a Samsung Galaxy S9.

**Comment by Breelandthecat** [comment]
i had this once on windows 11 but its very rare for me

**Comment by Breelandthecat** [comment]
I'm not sure though. Since im on pc and android uses a seperate app, It might not be the same.

For me it crashed upon loading geometry dash.

And for you, I Think it was upon opening the geode app?

**Comment by Breelandthecat** [comment]
I Could try giving alternate assistance though. idk.

Does the regular geometry dash open?

**Comment by selenium2106** [comment]
I also have that same problem on my Samsung galaxy S8, I even reinstalled geometry dash but it didn't work

**Comment by Frikistone** [comment]
I think the geode is not compatible with devices with exynos processor... It's most likely because of that and I think it's irreparable. So we're left without geode until the Italian apk mod comes out

**Comment by JOEYOCHO** [comment]
Tf no I have exynos (pixel 6a)

**Comment by Frikistone** [comment]
JOEYOCHO not you xd, The message referred to Selenium2106 and NewHubWhodis who have samsung and probably have exynos processor (or have snapdragon, I don't know) but on my s8+ it's already been resolved

**Comment by NewHubWhoDis** [comment]
Just tried running Geode on a Samsung Galaxy A34 and it launches, so this is definitely my phone.

**Comment by selenium2106** [comment]
In the new update the bug that caused it to fail on phones with an Exynos processor was finally fixed, it works perfectly on my Samsung S8
