### ISSUE TITLE
Geode crash on launch on Android

### ISSUE THREAD

**Issue by 5x9x7x2x7x9** [geode-sdk/geode#524]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v1.3.0

### Mods Installed

None

### Steps to Reproduce

1) Install Geode 
2) Launch Geometry Dash
3) Crash

### Crash Report

https://pastebin.com/raw/vT2KZY2R

### Additional Information

I am using a Samsung Galaxy A51

**Comment by selenium2106** [comment]
I have that problem too, I thought it was geometry dash, but it wasn't, I even reinstalled it and it didn't work. I'm just waiting for a solution for this problem
