### ISSUE TITLE
Bruh this sucks

### ISSUE THREAD

**Issue by Benbenfamgd** [geode-sdk/geode#525]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

1.20beta:19

### Mods Installed

Every mobile mod

### Steps to Reproduce

I just opened it

### Crash Report

The crash is when I open the game it crashes instantly

### Additional Information

I dont know how this happens

**Comment by TechStudent10** [comment]
1. can't tell you how to fix without a crash log
2. If you have all mobile mods that's probably the issue

**Comment by matcool** [comment]
someone didnt read the checkbox they were ticking
