### ISSUE TITLE
can u make geode for ios and apple phones

### ISSUE THREAD

**Issue by RapidosElite** [geode-sdk/geode#528]
### Geode Version

idk

### Related Problem

can u make geode for ios and apple phones please

### Your Solution

idk

### Additional Information

can u add geode for ios moblie and phones?

**Comment by RapidosElite** [comment]
please

**Comment by TripleBaconn** [comment]
will never happen, iOS can't use .dll files, which are required for geode to work.

**Comment by FireMario211** [comment]
> will never happen, iOS can't use .dll files, which are required for geode to work.

you don't quite understand how geode works lol
there's also .dylibs

**Comment by FireMario211** [comment]
> please

when someone makes it work, yes

**Comment by TripleBaconn** [comment]
> > will never happen, iOS can't use .dll files, which are required for geode to work.
> 
> you don't quite understand how geode works lol there's also .dylibs

rlly i was just being simple, iOS just sucks for mod/custom app compatibility.

**Comment by RapidosElite** [comment]
i know how geode works  im not dumb

**Comment by RapidosElite** [comment]
and i want geode for moblie

**Comment by JOEYOCHO** [comment]
Get icreate if you need mods

**Comment by RapidosElite** [comment]
i know
