### ISSUE TITLE
With MegaHack V8, the game Does not load 12 mods

### ISSUE THREAD

**Issue by enessmr** [geode-sdk/geode#534]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0 beta19

### Expected Behavior

idk

### Actual Behavior

IDK

### Steps to Reproduce

IDK

### Additional Information

there is %50 percent checkbox

**Comment by enessmr** [comment]
mod and geode loader

**Comment by TechStudent10** [comment]
uhh how did you get the errors?

what mods you have installed?

**Comment by enessmr** [comment]
I forgor 💀💀💀💀

**Comment by enessmr** [comment]
the game crashed and i installed PERFECT GD AND GEODE

**Comment by enessmr** [comment]
COMING PHOTO

**Comment by enessmr** [comment]
i just changed to wifi cuz... bro my isp changed to fiber

**Comment by enessmr** [comment]
but good
