### ISSUE TITLE
Multiple QOL Features

### ISSUE THREAD

**Issue by sinc0s** [geode-sdk/geode#536]
### Geode Version

v2-Beta 20

### Your Solution

- 'Update All' Button (manually updating every mod is very inconvenient)
- View new changelogs before updating
- Cancel updating/view mod info instead of just a 'restart' button (very frequent annoyance)
- Download counts and sorting by most/least downloaded (when possible)
- Simply add the best/most popular mods to featured tab for now (Betteredit, Globed, maybe Mega Hack with an external download to absolute's site?)
- Support externally paid mods on the index

**Comment by dankmeme01** [comment]
pretty sure all of those have been added by now, so closing
