### ISSUE TITLE
Game crashing before getting to main menu

### ISSUE THREAD

**Issue by fancythedeveloper** [geode-sdk/geode#54]
### Platform

Windows

### Geode Version

0.4.7

### Steps to Reproduce

1) Open the game
2) It freezes then crashes right before the bar fills up completely

### Crash Report

[2022-10-15_02-16-21.log](https://github.com/geode-sdk/geode/files/9791296/2022-10-15_02-16-21.log)
[Geode 15 Oct 02.16.17.log](https://github.com/geode-sdk/geode/files/9791298/Geode.15.Oct.02.16.17.log)

### Additional Information

I tried removing any mods I had installed on Geode, but even with 0 mods, it still kept crashing

**Comment by fancythedeveloper** [comment]
I should mention that, after renaming the XInput DLL so that it stops loading Geode, the game launched as normal.

**Comment by HJfod** [comment]
It appears that it crashed because it tried to set IDs to controller stuff. Do you have a controller plugged in?

**Comment by fancythedeveloper** [comment]
> It appears that it crashed because it tried to set IDs to controller stuff. Do you have a controller plugged in?

Pretty sure not
