### ISSUE TITLE
Improve error message for mod dependency version mismatch

### ISSUE THREAD

**Issue by tastyForReal** [geode-sdk/geode#542]
### Geode Version

v2.0.0-beta.12

### Your Solution

A mod (e.g., [`bitz.customprofiles`](https://github.com/iArtie/CustomProfiles)) that depends on another mod (e.g., [`geode.node-ids`](https://github.com/geode-sdk/NodeIDs)) may not load even if the dependency meets the version requirement. Selecting a specific version of the dependency (e.g., [`geode.node-ids`](https://github.com/geode-sdk/NodeIDs) version `v1.1.4`) may resolve the issue.

The current error message is confusing for users and can be improved. For example, it could suggest that the developer of [`bitz.customprofiles`](https://github.com/iArtie/CustomProfiles) update the version requirement for [`geode.node-ids`](https://github.com/geode-sdk/NodeIDs) if there are compatibility changes.

### Screenshots

![image](https://github.com/geode-sdk/geode/assets/40455776/30164f24-2f2f-4aed-8d79-7e38c6a7eb2f)
![image](https://github.com/geode-sdk/geode/assets/40455776/bc4e7307-5e1a-4cfd-8fbd-ac9cab426d94)
![image](https://github.com/geode-sdk/geode/assets/40455776/a65ee5a6-f7d5-442b-a455-262d1b8ba65e)

A more informative error message would explain that the developer of [`bitz.customprofiles`](https://github.com/iArtie/CustomProfiles) needs to update the version requirement for [`geode.node-ids`](https://github.com/geode-sdk/NodeIDs). It could also suggest that users report the issue to the developer if they are not the developer of [`bitz.customprofiles`](https://github.com/iArtie/CustomProfiles).

An improved error message could be:
```
The version of `geode.node-ids` is not compatible with `bitz.customprofiles`. This is likely due to breaking changes in `geode.node-ids`. Please report this issue to the developer of `bitz.customprofiles` and request that they update the version requirement for `geode.node-ids`.
```

### Additional Information

[Geode 18 Feb 17.29.31.log](https://github.com/geode-sdk/geode/files/14322105/Geode.18.Feb.17.29.31.log)

**Comment by Cvolton** [comment]
current messages look like this, update your geode btw, that's what the error you're getting is about
![image](https://github.com/geode-sdk/geode/assets/5721187/99eaea96-673c-4548-9bc6-a705fa03912d)

**Comment by Cvolton** [comment]
the version requirement for customprofiles is fine, the mod just doesn't load because Node IDs itself didn't load

**Comment by tastyForReal** [comment]
> the error you're getting actually means that Node IDs is for a newer version of Geode than what you have, unfortunately the version of Geode you have didn't have the version checks working properly - this is also fixed in later releases

I see now. Thanks.
