### ISSUE TITLE
Geometry Dash not working

### ISSUE THREAD

**Issue by Gorejda** [geode-sdk/geode#544]
### Your Question

writes that Geometry Dash was not found
![Screenshot_20240218-172151](https://github.com/geode-sdk/geode/assets/160407283/7cbde85c-77d4-4b55-b725-871855858036)

**Comment by altalk23** [comment]
![Screen Shot 2024-02-18 at 17 27 23](https://github.com/geode-sdk/geode/assets/45172705/88431888-1164-411a-8de6-5438b400fd5a)

**Comment by Gorejda** [comment]
I have a phone bro

**Comment by Gorejda** [comment]
but it works for everyone except for me on my phone
