### ISSUE TITLE
I was making a mod for geode, when it finishes, I decided to try the mod, but after compiling it and building the .dll file, I get this error "Modified class not recognized, please include <Geode/modify/ClassName.hpp> to be able to use it." How do I fix it or what do I have to do?

### ISSUE THREAD

**Issue by ElParaguasXD** [geode-sdk/geode#555]
### Geode Issue

- [ ] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

a674b97

### Geode Version

2.00-beta.20

### Mods Installed

None

### Expected Behavior

What I thought was going to happen is that I could try the mod but it didn't happen

### Actual Behavior

This is what happens when I compile the .dll file

![Animation](https://github.com/geode-sdk/geode/assets/98687237/51f01f0d-276f-4ed3-871e-c2b474978e2c)

### Steps to Reproduce

I don't know, I installed everything but I get this error

**Comment by BlackHoleMX12892** [comment]
Do what the error says

**Comment by matcool** [comment]
u ppl need to stop putting everything as the issue title :sob: also just read the error
