### ISSUE TITLE
Mod download ends with crash (by geode mod downloader)

### ISSUE THREAD

**Issue by GDenisC** [geode-sdk/geode#56]
### Platform

Windows

### Geode Version

v0.4.4 alpha

### Mods Installed

Geode, DevTools

### Steps to Reproduce

1. just download mod by geode menu
2. wait for 99% binary
3. crash

### Crash Report

[2022-10-21_14-08-53.log](https://github.com/geode-sdk/geode/files/9836539/2022-10-21_14-08-53.log)

### Additional Information

and lol what is last-crashed with 0 bytes size
![image](https://user-images.githubusercontent.com/92527725/197135511-6f31e352-a345-4e69-bcf4-0953f28e2c62.png)

**Comment by GDenisC** [comment]
Geode v0.5.0 fixed it lmao

**Comment by altalk23** [comment]
mmm yes love it when reports of old versions
