### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rayomz** [geode-sdk/geode#560]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

1.3.2

### Mods Installed

Beat.click.sound.geode geode.node-ids.geode

### Steps to Reproduce

It literally just bug in the geode mod i literally have 2 mods and it crashes

### Crash Report

Idk

### Additional Information

Idk why

**Comment by FireMario211** [comment]
if its related to a geode mod, its not related to geode itself 👍 
Also no crash logs doesn't help us, and the steps to reproduce you gave isn't helpful either.

**Comment by matcool** [comment]
most unhelpful crash report
