### ISSUE TITLE
Dylibs

### ISSUE THREAD

**Issue by GreatNateDev** [geode-sdk/geode#569]
### Geode Version

Newest

### Related Problem

Are the dylibs arm64 or arm64e because I’m trying to use azula on iOS to fuse them to the geometry dash ipa file to see if geode will work

### Your Solution

Arm 64 or nah

**Comment by matcool** [comment]
you cannot put a square in the circle hole

**Comment by matcool** [comment]
you cannot put a square in the circle hole

**Comment by GreatNateDev** [comment]
> you cannot put a square in the circle hole

I see

**Comment by GreatNateDev** [comment]
Predicted :)
