### ISSUE TITLE
Let me use it on ios

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [geode-sdk/geode#572]
### Geode Version

Most recent version

### Your Solution

Let us use it on ios

### Additional Information

Let us use geode on ios

**Comment by RayDeeUx** [comment]
your best bet is convincing tim cook to allow iphones to dualboot into android (real)

**Comment by ImmediateMurderProfessionals** [comment]
the fuck is tim cook?

**Comment by RayDeeUx** [comment]
http://en.m.wikipedia.org/wiki/Tim_Cook

**Comment by qimiko** [comment]
#528
