### ISSUE TITLE
Terminal Freeze

### ISSUE THREAD

**Issue by DozerGaming** [geode-sdk/geode#573]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

Geode 2.0.0, AutoCheckpoint 1.1.0, Auto Priority To High 1.0.1, Better Menu 2.0.1,  BetterPause 1.6.2, BetterInfo 4.0.0,  Boring Delay Info 1.0.0, Click Sounds 1.5.1, GDDL Integration 1.1.2, Globed 1.2.5, Golden Best 1.0.3, Grandpa Demon 1.1.0, Mega hack Pro 8.0.0, Minecraft Splash 1.2.1, More Settings 1.2.0, Node IDs 1.7.1, Run Info 1.0.2.

### Steps to Reproduce

I tried to update mods many times in succession.

### Additional Information

Geode still technically works, but most of the mods don't load or work because the terminal refuses to update.

**Comment by cursefroge** [comment]
Please explain what actually happens. Are you saying GeodeUpdater doesn't update after you tried to update a lot?

**Comment by matcool** [comment]
stale
