### ISSUE TITLE
(Windows) How do I build a Geode Mod 

### ISSUE THREAD

**Issue by Rustring** [geode-sdk/geode#581]
### Your Question

I'm stuck right now I have the following dependencies

1) Visual Studio (Desktop development with C++ workload included)
2) CMake
3) Geode CLI

I first try to use cmake gui but I get this error
![Untitled](https://github.com/geode-sdk/geode/assets/155897302/9fde7ce6-61d8-451d-b9d6-a95faa6e987e)

I third try to use VSCode but the CMake: Select a kit doesn't exist, I have the CMake tools extension installed

So I don't know what to do

**Comment by Rustring** [comment]
I Used

       cmake -B build -A win32

And got this error

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- Found Geode: C:\Users\User\Documents\Geode
-- Version: 2.0.0, tag: beta.21 (type: Beta, number: 21)
-- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
-- CPM: Adding package bindings@ (main)
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:2934 (message):
  error: could not find git for clone of bindings-populate
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:4445 (_ep_add_download_command)
  CMakeLists.txt:29 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!

CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1702 (message):
  CMake step for bindings failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1854:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1854 (cmake_language)
  build/cmake/CPM_0.38.7.cmake:1010 (FetchContent_Populate)
  build/cmake/CPM_0.38.7.cmake:804 (cpm_fetch_package)

**Comment by Rustring** [comment]
Using Cmake gui gives me these errors

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:2934 (message):
  error: could not find git for clone of bindings-populate
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:4445 (_ep_add_download_command)
  CMakeLists.txt:29 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!

CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1702 (message):
  CMake step for bindings failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1854:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FetchContent.cmake:1854 (cmake_language)
  C:/Users/M/Documents/Cmake/cmake/CPM_0.38.7.cmake:1010 (FetchContent_Populate)
  C:/Users/M/Documents/Cmake/cmake/CPM_0.38.7.cmake:804 (cpm_fetch_package)
  C:/Users/M/Documents/Geode/CMakeLists.txt:76 (CPMAddPackage)


Configuring incomplete, errors occurred!

**Comment by matcool** [comment]
https://docs.geode-sdk.org/getting-started/cpp-stuff all is covered here, which you clearly didnt follow

**Comment by Rustring** [comment]
I hate the fact that git saves the day also why you closed the issue as not planned
