### ISSUE TITLE
CONSTANT RANDOM CRASHES

### ISSUE THREAD

**Issue by GlassesCatandsteve** [geode-sdk/geode#582]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.21

### Mods Installed

hi , i wanna clarify that no matter which mods i have installed it still hapens , i have many many mods and i dont wanna spend 30 minutes listing them and their versions , if this is like very important (youll see why i thinm it isnt in the description) make a comment about it .

### Steps to Reproduce

well , you kinda cant

### Crash Report

some logs were deleted as i had to fix some other things , so it isnt many .
[2024-03-02_12-00-49.log](https://github.com/geode-sdk/geode/files/14472658/2024-03-02_12-00-49.log)
[2024-03-02_13-25-48.log](https://github.com/geode-sdk/geode/files/14472659/2024-03-02_13-25-48.log)
[2024-03-02_20-08-39.log](https://github.com/geode-sdk/geode/files/14472660/2024-03-02_20-08-39.log)
[2024-03-03_11-56-57.log](https://github.com/geode-sdk/geode/files/14472661/2024-03-03_11-56-57.log)
[2024-03-03_12-07-34.log](https://github.com/geode-sdk/geode/files/14472662/2024-03-03_12-07-34.log)

### Additional Information

my game randomly crashes 5 - 10 times a day , wiping most session progress , it isnt at specific events , so i cant tell how to reproduce or something , all the logs say that the faulty mod is unknown , but this is getting way too annoying .

**Comment by TheSillyDoggo** [comment]
"I have many many mods" you've answered your own problem, not a geode crash.

**Comment by TheSillyDoggo** [comment]
Also one of them is bad allocation install 4gb patch

**Comment by Alphalaneous** [comment]
Looking at these logs, I suspect GDDL integration as a potential issue here. 

As for my second suspect, I believe it could be xdbot but I cannot verify, just best to try with and without and see if anything changes

**Comment by Faisalkhan2266** [comment]
![Screenshot_20240309_135714_Geode](https://github.com/geode-sdk/geode/assets/159558539/390ecf26-35e4-4673-81f1-ad0fd9422069)


This also happen to me as well. Here is the file log

**Comment by MTSyntho** [comment]
me too :(

**Comment by matcool** [comment]
stale

**Comment by Faisalkhan2266** [comment]
This mail was 5-6 Month's old but this issue did got resolved. Damn it took
you guys very long time to response.
