### ISSUE TITLE
Download Page Not Loading

### ISSUE THREAD

**Issue by Sus1568** [geode-sdk/geode#583]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.21

### Expected Behavior

I Expected To Get A List Of Mods Like In This Video:
![Screenshot 2024-03-03 160652](https://github.com/geode-sdk/geode/assets/162032260/bf15703e-2432-4976-9c7f-c61e33f6a5ce)

### Actual Behavior

But Instead Of The Picture In The Category Above I Got This:
![Screenshot 2024-03-03 160853](https://github.com/geode-sdk/geode/assets/162032260/c6cb43c5-c124-42a4-b6a3-389cca107532)

### Steps to Reproduce

I Just Installed Geode Now, And Wanted To Download Mods, I Dont Know What Happened.

**Comment by kyleF9** [comment]
You can either:

1. Restart the game, and play levels before pressing the geode button/entering the index.

2. You cant download mods on the geode site, you need to go to the creators github site and download the mods manually, you can go to #new-mods and scroll up to find some mods, then press the mod creators name, itll take you to their github which you can find their uploaded mods, after finding their mod, you wanna scroll down till you see "Released" then press the version number. Scroll down till you see (for example) "modcreatorsuser.modname.geode", then move that downloaded file to the geode folder, then find mods folder (btw if it shows an error please view it and see whats wrong. It could need another mod.)

3. Alternative way for paragraph 2, you could go to the official geode mods website to find mods. You can also see if it supports your device. After finding the mod you want, go to the tab "Tags & Links" (press it), after, press the "Repository" button. It'll take you to the github mod page immediately. Next, scroll down until you see "Releases", and press the version number that has "Latest" next to it. You might have to scroll down to see a .geode file. Install ONLY the .geode file (should be at the top, right under "Assets") Next, move this to the geode folder, and the mods folder.

**Comment by Sus1568** [comment]
> You can either:
> 
> 1. Restart the game, and play levels before pressing the geode button/entering the index.
> 2. You cant download mods on the geode site, you need to go to the creators github site and download the mods manually, you can go to #new-mods and scroll up to find some mods, then press the mod creators name, itll take you to their github which you can find their uploaded mods, after finding their mod, you wanna scroll down till you see "Released" then press the version number. Scroll down till you see (for example) "modcreatorsuser.modname.geode", then move that downloaded file to the geode folder, then find mods folder (btw if it shows an error please view it and see whats wrong. It could need another mod.)
> 3. Alternative way for paragraph 2, you could go to the official geode mods website to find mods. You can also see if it supports your device. After finding the mod you want, go to the tab "Tags & Links" (press it), after, press the "Repository" button. It'll take you to the github mod page immediately. Next, scroll down until you see "Releases", and press the version number that has "Latest" next to it. You might have to scroll down to see a .geode file. Install ONLY the .geode file (should be at the top, right under "Assets") Next, move this to the geode folder, and the mods folder.

helped me very much thanks!
