### ISSUE TITLE
Geode doesn't show up when opening Geometry Dash (Wine on MacOS)

### ISSUE THREAD

**Issue by FeliReta** [geode-sdk/geode#584]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v2.0.0-beta.21

### Expected Behavior

I installed Geode SDK on WineSkin on my MacOS (Intel version) to get the mods that are not available on MacOS.
<img width="1280" alt="Captura de pantalla 2024-03-03 a las 18 53 53" src="https://github.com/geode-sdk/geode/assets/162047626/8d319628-4623-4feb-87fc-c36443f0a25d">

### Actual Behavior

When I open Geometry Dash via Steam the Geode button that is supposed to show up in the main menu doesn't.
<img width="1280" alt="Captura de pantalla 2024-03-03 a las 19 08 12" src="https://github.com/geode-sdk/geode/assets/162047626/dccfe923-9ca0-484b-9ddb-848512353a16">

### Steps to Reproduce

1. I installed Steam though Wine on my MacBook.
2. I installed Geometry Dash in Steam on Wine.
3. I downloaded GeodeSDK installer, copied it inside the Wine C:\ and opened it though Wine.
4. I installed GeodeSDK inside GD folder "C:\ProgramFilesx64\Steam\steamapps\common\GeometryDash"
5. I launched Geometry Dash on Steam via Wine

**Comment by BNTFryingPan** [comment]
on linux, you have to add a library override in winecfg or an environment variable for `xinput9_1_0` for geode to work. have you tried doing this?

**Comment by Rustring** [comment]
Try adding "WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%" to your steam launch options

**Comment by BNTFryingPan** [comment]
> Try adding "WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%" to your steam launch options

this wont work, as steam itself is running inside wine

**Comment by Rustring** [comment]
Add xinput as a dependency, I am on Linux where you use winetricks or bottles, idk how you do it on MacOS

**Comment by RoootTheFox** [comment]
You pretty much do the same thing on macOS - set GD's launch options *inside* Steam to `WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%` (its inside Properties for Geometry Dash)

also, note that this isn't a bug that's related to Geode, if you need support you should join the Discord server, as GitHub isn't really the place for that.

**Comment by Rustring** [comment]
> > Try adding "WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%" to your steam launch options
> 
> this wont work, as steam itself is running inside wine

**Comment by RoootTheFox** [comment]
is there any way you can run `winecfg`? If yes, please do that and set a library override for xinput9_1_0

**Comment by Rustring** [comment]
Yeah I am saying the same thing

**Comment by davttd** [comment]
I use crossover and i set lib overwrite and force it to use native xinput but this seems to crash for me

**Comment by MadSlimDude** [comment]
> > is there any way you can run `winecfg`? If yes, please do that and set a library override for xinput9_1_0
> 
> Yeah I am saying the same thing

How do I run it if I'm using Whiskey? I use whiskey which automatically installs wine for me so I don't really know how to do this

**Comment by chubbybear0924** [comment]
How to change launch options on win

**Comment by koedash** [comment]
I have the same isue but on windows 10

**Comment by RoootTheFox** [comment]
Geode isn't updated yet! please be patient

**Comment by R4vy50n** [comment]
i triyed to put WINEDLLOVERRIDES="xinput9_1_0=n,b" %command% but noq the gd doesnt even open

**Comment by R4vy50n** [comment]
how do you solve that in windows 10?

**Comment by koedash** [comment]
I think it a problem with gd itself because i try to re install geode and it still doesn't show up

**Comment by Betito23** [comment]
> I think it a problem with gd itself because i try to re install geode and it still doesn't show up

Yeah i tried that too but wouldnt work

**Comment by RadishTheVeg671** [comment]
I tried on my windows and it still dosent show up with the geode thing
