### ISSUE TITLE
Mods unable to load (Now it's every mod I download)

### ISSUE THREAD

**Issue by MinuetedKira** [geode-sdk/geode#585]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

Geode v2.0.0, Globed v3.0.0, Node ID's v1.7.1, Autocheckpoint 1.1.0

### Expected Behavior

Globed and Node IDs should load normally when starting Geometry dash, that leading to autocheckpoints loading normally

### Actual Behavior

Every mod I download/update have and an error saying "Failed unzipping" and when clicking more it says "unable to delete temp dir: Access is denied"
![image](https://github.com/geode-sdk/geode/assets/162059272/30204f2d-20a6-4eca-b8c8-d98c182fb214)
![image](https://github.com/geode-sdk/geode/assets/162059272/66fe8075-562c-409e-9668-c47ac1362c02)

### Steps to Reproduce

Just download any mod

**Comment by Denyscrasav4ik** [comment]
maybe try reinstaling everything also temp dir stands for temporary directory
I think it creates it to install mod and convert it to geode format also i dont contribute with geode so idk what it is

**Comment by PurpleProg** [comment]
same problem here

**Comment by PurpleProg** [comment]
i just deleted the entire unziipped folder and Voila it worked again
IDK why did it work but it did

**Comment by matcool** [comment]
stale, reopen if needed

**Comment by Alyssya-GD** [comment]
for me it just stays on prepareing download
Any recommendations on how i could fix this?
