### ISSUE TITLE
I dont know why my geode says "a geometry dash update is required" can someone help me?

### ISSUE THREAD

**Issue by SuscraftTT** [geode-sdk/geode#587]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

Version 1.3.2

### Mods Installed

XDBOT
Globed
Prism Menu
Same dual color

### Additional Information

Well... i tried this step everytime. 1. I download geometry dash 2.205 by soluble gd. 2.then i download geode sdk. 3. After the download done,i open geode and it says "a geometry dash update is required". Can someone fix that word for me?!

**Comment by qimiko** [comment]
not a geode bug. don't install weird pirated versions of the game and expect support
