### ISSUE TITLE
Use tarball instead of zip archive for the index

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/geode#588]
### Geode Version

version agnostic

### Related Problem

Unzipping the index takes too long

### Your Solution

Use a tarball (`.tar.xz`) instead of a zip archive to speed up the extraction 

### Additional Information

tar is available on ALL platforms
tar doesn't need to be manually installed on non-officially supported platforms (such as Linux and BSD)
tarballs are much faster to extract than zip archives (this is based on actual benchmarks)
tarballs are less lossy than the zip format

**Comment by BNTFryingPan** [comment]
just for the record, `.tar.xz` is a `.xz` *compressed* `.tar` tarball, as a tarball is just a uncompressed bundle of files. `.xz` is a format that is optimized for compression ratio, so it is smaller, but can take longer to compress. i havent dont any benchmarking myself, but wikipedia says that `.xz` decompresses slower than gzip (`.gz`), so some testing of that might be good if a switch is considered.

> tar doesn't need to be manually installed on non-officially supported platforms (such as Linux and BSD)
this is irrelevant. geode needs to run on windows natively, and requiring users to install software just to use the built-in mod browser would be a downgrade from the current experience. it is possible for geode to include either a library or just its own implementation of one of these formats, but it would also use that when running through wine/proton on linux.

> tarballs are less lossy than the zip format
what? no like seriously, this literally does not make sense. `.zip` is literally a lossless compression format, just like `.png` is for images.

**Comment by RoootTheFox** [comment]
i said this again: `zstd` would imo a much better fit
however i'm pretty sure with the new index this won't be needed at all anymore.

**Comment by TheBearodactyl** [comment]
> just for the record, `.tar.xz` is a `.xz` _compressed_ `.tar` tarball, as a tarball is just a uncompressed bundle of files. `.xz` is a format that is optimized for compression ratio, so it is smaller, but can take longer to compress. i havent dont any benchmarking myself, but wikipedia says that `.xz` decompresses slower than gzip (`.gz`), so some testing of that might be good if a switch is considered.
> 
> > tar doesn't need to be manually installed on non-officially supported platforms (such as Linux and BSD)
> 
> this is irrelevant. geode needs to run on windows natively, and requiring users to install software just to use the built-in mod browser would be a downgrade from the current experience. it is possible for geode to include either a library or just its own implementation of one of these formats, but it would also use that when running through wine/proton on linux.
> 
> > tarballs are less lossy than the zip format
> 
> what? no like seriously, this literally does not make sense. `.zip` is literally a lossless compression format, just like `.png` is for images.

i know, i was just giving the more commonly used extension lol

**Comment by matcool** [comment]
> tar is available on ALL platforms

the tar command line utility is only available on windows 10+, however that is completely irrelevant because we would just use it as a library compiled into geode, not as an external process.
> tarballs are less lossy than the zip format

this is invalid

> use `tar.xz` instead of `zip`

technically speaking we could only use `tar.gz`, since that is what https://github.com/geode-sdk/mods/tarball/main returns

besides, this will all become irrelevant when new index..
since that is relatively close, its kinda pointless to switch the existing zip extraction code to use some tar.gz supporting library
