### ISSUE TITLE
Crashes that happens randomly

### ISSUE THREAD

**Issue by EnzoZenphroi** [geode-sdk/geode#592]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v1.3.2

### Steps to Reproduce

As the titles said, it happens randomly.
Even when not a single action was done, it still crashes.

### Crash Report

[Crash 2024-03-06 15.42.40.dmp](https://github.com/geode-sdk/geode/files/14507471/Crash.2024-03-06.15.42.40.dmp)
[Geode 2024-03-06 15.42.40.log](https://github.com/geode-sdk/geode/files/14507474/Geode.2024-03-06.15.42.40.log)

### Additional Information

At first i speculated it to be caused by a mod but after turning them all off, it still occures.

**Comment by qimiko** [comment]
this was the curl crash, which was fixed in beta 22 (about 3 days after this issue was made)
