### ISSUE TITLE
How to set geode sdk variable on Linux

### ISSUE THREAD

**Issue by Rustring** [geode-sdk/geode#594]
### Your Question

I've tried to run "geode sdk install" many times and have restarted the terminal and computer many times still the geode sdk variable is not set

My Distro: Arch Linux x64 (Got Geode CLI from the AUR) with KDE 6.0

**Comment by RoootTheFox** [comment]
If you're looking into developing mods, you're better off dualbooting Windows (or using a KVM).
If you *really* want to use Linux, `export GEODE_SDK="path"` for your current terminal session, and [good luck](https://gist.github.com/matcool/abb65ee59ded3766717c673014c3a2a7).

**Comment by Rustring** [comment]
The only reason I am using linux is because windows is dualbooted on a slow hard drive, and I don't want to visualize as my SSD's storage is around 256GB and GD doesn't work on windows (for me) so it is annoying changing operating systems as windows takes 1 minute to boot

**Comment by Rustring** [comment]
I followed the guide and got this

-- "LLVM_VER" not set, leaving blank
-- "CLANG_VER" not set, leaving blank
-- "LLVM_PATH" not set, leaving blank
CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:123 (message):
  CMake variable SPLAT_DIR must point to a folder containing the xwin splat.
Call Stack (most recent call first):
  build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:7 (project)


CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:128 (message):
  Cannot find Windows.h
Call Stack (most recent call first):
  build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:7 (project)


-- The CXX compiler identification is Clang 16.0.6 with MSVC-like command-line
-- Check for working CXX compiler: /usr/bin/clang-cl
CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:123 (message):
  CMake variable SPLAT_DIR must point to a folder containing the xwin splat.
Call Stack (most recent call first):
  /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/CMakeScratch/TryCompile-uCdftp/CMakeLists.txt:5 (project)


CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:128 (message):
  Cannot find Windows.h
Call Stack (most recent call first):
  /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/CMakeScratch/TryCompile-uCdftp/CMakeLists.txt:5 (project)


CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!

**Comment by Rustring** [comment]
I give up I'm using windows for compiling mods :(

**Comment by TheBearodactyl** [comment]
```bash
export GEODE_SDK="absolute/path/to/the/sdk/"
```

or with `fish`:
```fish
set -x GEODE_SDK "absolute/path/to/the/sdk/"
```

**Comment by Rustring** [comment]
> I followed the guide and got this
> 
> -- "LLVM_VER" not set, leaving blank -- "CLANG_VER" not set, leaving blank -- "LLVM_PATH" not set, leaving blank CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:123 (message): CMake variable SPLAT_DIR must point to a folder containing the xwin splat. Call Stack (most recent call first): build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include) CMakeLists.txt:7 (project)
> 
> CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:128 (message): Cannot find Windows.h Call Stack (most recent call first): build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include) CMakeLists.txt:7 (project)
> 
> -- The CXX compiler identification is Clang 16.0.6 with MSVC-like command-line -- Check for working CXX compiler: /usr/bin/clang-cl CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:123 (message): CMake variable SPLAT_DIR must point to a folder containing the xwin splat. Call Stack (most recent call first): /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include) /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/CMakeScratch/TryCompile-uCdftp/CMakeLists.txt:5 (project)
> 
> CMake Error at /home/lolno/toolchain/clang-cl-msvc.cmake:128 (message): Cannot find Windows.h Call Stack (most recent call first): /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include) /home/lolno/Downloads/GDModHack-main/build/CMakeFiles/CMakeScratch/TryCompile-uCdftp/CMakeLists.txt:5 (project)
> 
> CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile): Failed to configure test project build system. Call Stack (most recent call first): CMakeLists.txt:7 (project)
> 
> -- Configuring incomplete, errors occurred!

But I get another problem noe

**Comment by Rustring** [comment]
> If you're looking into developing mods, you're better off dualbooting Windows (or using a KVM). If you _really_ want to use Linux, `export GEODE_SDK="path"` for your current terminal session, and [good luck](https://gist.github.com/matcool/abb65ee59ded3766717c673014c3a2a7).

@RoootTheFox I'm using github actions to build my mods, it's much (10x) quicker and I can build it for multiple platforms easily.
