### ISSUE TITLE
"CMake: Select a Kit:" or any of those "CMake:" wont appear in vscode

### ISSUE THREAD

**Issue by THEDERP655129** [geode-sdk/geode#599]
### Your Question

I downloaded CMake and CMake tools but for some reason this what I get
![image](https://github.com/geode-sdk/geode/assets/83438557/029c579c-25db-4bdd-a3de-d57bee833c3b)
How can I fix this

**Comment by Rustring** [comment]
Make sure you have Visual Studio 2022, Git and Geode CLI installed

**Comment by THEDERP655129** [comment]
@Rustring  

When I go to manage configurations to look for "RelWithDebInfo" on Visual Studio 2022 this is what I get
![image](https://github.com/geode-sdk/geode/assets/83438557/15323134-6c25-431f-a7c5-4515d3b7c49c)
And I cant find any "Tool Kit" as well

**Comment by MarioMastr** [comment]
make sure that the folder you're currently working in has a valid cmakelists.txt file in it

**Comment by THEDERP655129** [comment]
> make sure that the folder you're currently working in has a valid cmakelists.txt file in it

I do have cmakelists.txt in the project folder but how can I tell if its valid?
