### ISSUE TITLE
Empty update response

### ISSUE THREAD

**Issue by Vexomalia** [geode-sdk/geode#601]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

APK says V.1.3.2

### Mods Installed

It is not related to mods.

### Steps to Reproduce

You can't reproduce.

### Crash Report

[Crash 2024-03-07 17.50.59.dmp](https://github.com/geode-sdk/geode/files/14527467/Crash.2024-03-07.17.50.59.dmp)

### Additional Information

Anytime i open Geode, it starts up normally and works up until it checks the index for the mods, then it just crashes. The application logs always say "Failed to fetch updates Empty response". If there's anything in the crashlogs that explain it, please tell me since i don't have an app to view the dmp files. :(

**Comment by matcool** [comment]
stale, reopen if needed
