### ISSUE TITLE
Rewrite it in Rust.

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/geode#602]
### Geode Version

version agnostic.

### Related Problems

1. Geode and the mods it powers often crash due to memory problems. This is not just a problem with unsafe code, but also the language the code is written in being inherently unsafe (C++).

2. At this point in time, Geode does not have seamless IDE support. Right now, there's multiple steps just to get an IDE to find the headers, one of them requiring you to build the SDK yourself (e.g. for the headers in the `binding` directory), and another requiring you to build the mod you're working on. This takes up a good chunk of time that could've been spent writing code.

3. C++ code is inherently cluttered, making it a nightmare to read. This makes writing mods not nearly as beginner friendly as it could and should be. Like seriously, at first glance, do these look any different to you?: 
```cpp
int* hi = 5;
int *hi = 5;
```

### Your Solutions

Rust solves all of these problems.
1. It's built to be memory safe and efficient. You don't need manual memory management (it's automatically handled for you), and it doesn't require a garbage collector due to the borrow checker. This (mostly) solves the problem of memory related crashes.
2. With `rust-analyzer`, all you would need to do to have seamless IDE support is to run `cargo add geode-sdk` in a new crate directory, and BOOM! You've got a `geode` mod with full IDE support, all with a single command
3. Rust code is very high level and tidy, making it very nice to read and write with. This makes it very beginner friendly, and gives a nice little head start for anyone who's trying to learn how to mod GD. The readability also gives a nice little bonus of being much easier to debug, as this makes it easier to understand what the hell is going on the the code. Also, with how rust projects are structured, you don't need to have separate `.cpp` and `.h` files. You've just got `.rs` files, and this makes it much easier to understand what files have what in them.
4. (bonus) Rust can very easily interop with C++, so you would still be able to use the `cocos` and `fmod` libraries.

### Additional Information

I know this is a very big request, and would take a lot of time to do, but i hope y'all at least consider it. I think doing this would have a very positive impact on GD modding, and would improve the experience of everyone using Geode.

**Comment by TheBearodactyl** [comment]
just realized how many times i said "nice little" lmfao

**Comment by Cvolton** [comment]
ok im assigning you to make a pr that does the whole thing

**Comment by TheBearodactyl** [comment]
> ok im assigning you to make a pr that does the whole thing

i take this as a challenge, and I accept

**Comment by DexterHill0** [comment]
Be warned it's not as easy as you think. i've attempted it with @FlowVix [here](https://github.com/DexterHill0/jah) but it's not that nice. Automatically generating bindings for Geode as a whole doesn't seem possible (or at least it wasn't then and I dont think it's changed since then), so you need to generate them for cocos alone. But unlike 2.1, there is now no standalone modified cocos headers for 2.2 (that I know of) and the ones inside Geode pull in many other headers from Geode itself, making bindings very difficult.

Theres also the fact that bindings are very low level and messy. Lots of raw pointers and lots of void pointers to many C++ std types. CXX helps to an extent, since it implements some cross compatibility for types like `std::vector`, but there are also many types that aren't implemented (such as `std::map`, hence our own implementation of CXX (`stdty`) for jah), which are required to work.
Then there is the issue of having to write high-level apis for the low-level bindings which would take a while. There is potential in something like [autocxx](https://github.com/google/autocxx), but I didn't have any luck with it, and you are still stuck with the issue of limited implementations of C++ standard types.
There may potential in just using `CXX` alone and writing functions and structs that map to ones in Geode but it would have to be experimented with.

Once all of that is figured out, you still need to work out how to replicate the behaviour of things like `$execute`, `$modify` and so forth. 

Not to put you off just thought I'd share my progress on it....

**Comment by TheBearodactyl** [comment]
> Be warned it's not as easy as you think. i've attempted it with @FlowVix [here](https://github.com/DexterHill0/jah) but it's not that nice. Automatically generating bindings for Geode as a whole doesn't seem possible (or at least it wasn't then and I dont think it's changed since then), so you need to generate them for cocos alone. But unlike 2.1, there is now no standalone modified cocos headers for 2.2 (that I know of) and the ones inside Geode pull in many other headers from Geode itself, making bindings very difficult.
> 
> Theres also the fact that bindings are very low level and messy. Lots of raw pointers and lots of void pointers to many C++ std types. CXX helps to an extent, since it implements some cross compatibility for types like `std::vector`, but there are also many types that aren't implemented (such as `std::map`,  hence our own implementation of CXX (`stdty`) for jah), which are required to work. Then there is the issue of having to write high-level apis for the low-level bindings which would take a while. There is potential in something like [autocxx](https://github.com/google/autocxx), but I didn't have any luck with it, and you are still stuck with the issue of limited implementations of C++ standard types. There may potential in just using `CXX` alone and writing functions and structs that map to ones in Geode but it would have to be experimented with.
> 
> Once all of that is figured out, you still need to work out how to replicate the behaviour of things like `$execute`, `$modify` and so forth.
> 
> Not to put you off just thought I'd share my progress on it....

that's why macros and https://crates.io/crates/libc exist

**Comment by DexterHill0** [comment]
> that's why macros and https://crates.io/crates/libc exist

Macros, yes, we used macros to modify some of the output bindings but some of the issues still pertain like raw pointers.
I'm not sure how libc would help seeing as its the C standard library, and not the C++ standard library.

**Comment by TheBearodactyl** [comment]
> > that's why macros and https://crates.io/crates/libc exist
> 
> Macros, yes, we used macros to modify some of the output bindings but some of the issues still pertain like raw pointers. I'm not sure how libc would help seeing as its the C standard library, and not the C++ standard library.

sorry, should've added https://crates.io/crates/cxx

**Comment by TheBearodactyl** [comment]
> > sorry, should've added https://crates.io/crates/cxx
> 
> I mean yeah, I mentioned CXX originally. It's probably the most plausible way, but again, the issue of limited standard types exist. Also the fact that you would have to write bindings manually for the entirety of cocos headers.

I wouldn't actually, someone actually wrote bindings to Rob's version of cocos2d in rust: https://crates.io/crates/rcocos2d-sys

**Comment by RoootTheFox** [comment]
> > > sorry, should've added https://crates.io/crates/cxx
> > 
> > 
> > I mean yeah, I mentioned CXX originally. It's probably the most plausible way, but again, the issue of limited standard types exist. Also the fact that you would have to write bindings manually for the entirety of cocos headers.
> 
> I wouldn't actually, someone already wrote bindings to Rob's version of cocos2d in rust: https://crates.io/crates/rcocos2d-sys

that version is 2 years old

**Comment by TheBearodactyl** [comment]
> > > > sorry, should've added https://crates.io/crates/cxx
> > > 
> > > 
> > > I mean yeah, I mentioned CXX originally. It's probably the most plausible way, but again, the issue of limited standard types exist. Also the fact that you would have to write bindings manually for the entirety of cocos headers.
> > 
> > 
> > I wouldn't actually, someone already wrote bindings to Rob's version of cocos2d in rust: https://crates.io/crates/rcocos2d-sys
> 
> that version is 2 years old

fair, although i could probably update it pretty easily, as the basis of what i need is already there

**Comment by RoootTheFox** [comment]
well, good luck then

**Comment by acaruso-xx** [comment]
You should never be allowed near a computer ever again.

**Comment by matcool** [comment]
nice joke

**Comment by TheBearodactyl** [comment]
> nice joke

not a joke.

**Comment by TheBearodactyl** [comment]
> You should never be allowed near a computer ever again.

who even are you?

**Comment by TheBearodactyl** [comment]
> well, good luck then

thanks, gonna need it :D

**Comment by FlowVix** [comment]
we should go one step further and rewrite GD in rust

**Comment by TheBearodactyl** [comment]
> we should go one step further and rewrite GD in rust

@FlowVix https://github.com/opstic/gdclone

**Comment by TechStudent10** [comment]
if you pull this off

you have my applause

**Comment by HJfod** [comment]
I want to add here that the Geode lead dev team is filled with Rustaceans who write everything they can in Rust (see [Geode CLI](https://github.com/geode-sdk/cli),or [Geode server](https://github.com/geode-sdk/server), or [the Geode docs genner](https://github.com/HJfod/flash)). Also, Hyperdash had some of its core components written in Rust so we were aware of the idea of using the language years ago when Geode started.

This is all to say that if the idea of making Geode use Rust had even the slightest bit of sanity behind it, **we would've done it already**. There are a lot of good reasons we have not and almost certainly never will.
