### ISSUE TITLE
geode crashes randomly, android64

### ISSUE THREAD

**Issue by Lanalanita** [geode-sdk/geode#603]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0 beta 21

### Mods Installed

globed 1.3.1

### Steps to Reproduce

nothing specific, just use geode

### Crash Report

[Crash_2024-03-07_20.44.24.dmp](https://github.com/geode-sdk/geode/files/14533370/Crash_2024-03-07_20.44.24.dmp)

### Additional Information

https://github.com/geode-sdk/geode/assets/108598436/4dacedfe-f66c-4fd9-9976-3b4a5ac790ff

galaxy a34
android 14

**Comment by matcool** [comment]
stale, reopen if needed
