### ISSUE TITLE
Needed gd update bug

### ISSUE THREAD

**Issue by Snowuw** [geode-sdk/geode#604]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### SDK commit

.

### Geode Version

1.3.2

### Mods Installed

.

### Expected Behavior

Fix bug pls

### Actual Behavior

Somehow it doesn't allow me to launch gd because It needed gd update even though I already did install the latest version of 2.2.13 or 2.205

### Steps to Reproduce

.

### Additional Information

.

**Comment by RoootTheFox** [comment]
Did you install Geometry Dash through the Google Play Store?

**Comment by Snowuw** [comment]
No I didn't, I installed it through apk

**Comment by RoootTheFox** [comment]
Then that's your issue, try another one that is up to date and isn't modified by some sketchy 3rd-party website.

**Comment by Hamx1111** [comment]
Can you show any links of recent ones?
I probably need it too.
