### ISSUE TITLE
"Tags" filter menu bug

### ISSUE THREAD

**Issue by zipatton** [geode-sdk/geode#606]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.21

### Mods Installed

BetterEdit v6.3.3, Betterinfo v4.1.2, Compact Editor Menus v1.1.0, Custom Keybinds v1.5.2, DevTools v1.5.1, GDTweaks v1.9.2, GMD API v1.0.5, Level Info in Pause Menu v1.0.3, Level Info v1.2.1, Level Thumbnails v1.0.1, More Settings Button v1.2.0, Node IDs v1.7.1, Restart Buttons v1.1.1, Texture Loader v1.5.0

### Expected Behavior

The "Tags" menu should start from the top to bottom.
![20240308125102_1](https://github.com/geode-sdk/geode/assets/155669622/75a1d28b-9ac6-4146-bbc0-a84b775b6244)

### Actual Behavior

The "Tags" menu starts at the bottom of the list.
![20240308125305_1](https://github.com/geode-sdk/geode/assets/155669622/5851462f-c05f-4ed4-b38f-f4a1de46e3ca)

### Steps to Reproduce

Open the Geode mod page, and just go to the tags filter button.

### Additional Information

_I do not have the ability to record any footage._

**Comment by qimiko** [comment]
fixed on new index :slightly_smiling_face: no more lists

![image](https://github.com/geode-sdk/geode/assets/25387744/de6deee8-aa6f-4177-8085-7518abb9292e)
