### ISSUE TITLE
Feature Outline

### ISSUE THREAD

**Issue by zipatton** [geode-sdk/geode#607]
### Geode Version

v2.0.0-beta.21

### Related Problem

Feature Glow/Outline is not centered on the mod icon.

### Your Solution

Have it be located in the middle of where the mod icon container would be.

### Additional Information

_Tried to find where the feature glow was located in the node tree thing to try and center it manually for an example, but I couldn't find where it was located._

**Comment by TeahersAreStupid1234** [comment]
![image](https://github.com/geode-sdk/geode/assets/59105483/0ed638a4-f544-4d5e-860e-0984387d7e48)
heres an image for people who need it
literally unplayable btw

**Comment by qimiko** [comment]
fixed on new index

![image](https://github.com/geode-sdk/geode/assets/25387744/9f3c4534-b0c0-44cf-be41-22b8d78cc439)
