### ISSUE TITLE
hello world mod crashes GD instantly

### ISSUE THREAD

**Issue by Fleeym** [geode-sdk/geode#61]
### Platform

Windows

### Geode Version

v0.6.1

### Mods Installed

- devtools v0.0.5
- fps bypass v1.0.0
- the basic mod generated with `geode new`

### Steps to Reproduce

1. Install the SDK and loader
2. Create new mod with `geode new`
3. Compile mod
4. Launch GD

### Crash Report

https://pastebin.com/HJtyqAt2 - crashlog
Last log in geode/log is empty

### Additional Information

I'm guessing I did something wrong while installing the SDK, no other idea why this happens.

**Comment by iAndyHD3** [comment]
Have you tried to remove the other mods to see if it's some issue related to them?

**Comment by Fleeym** [comment]
yep, it's definetly the mod that I compile that crashes the game

**Comment by matcool** [comment]
seems like youre compiling in debug, you have to compile in either release or relwtihdebinfo, otherwise std::string and other stl containers will crash

**Comment by Fleeym** [comment]
yeah, that was it. thanks a lot!
