### ISSUE TITLE
when I go to download to find mods without typing ANYTHING is says no mods found

### ISSUE THREAD

**Issue by AabidPlaysYT** [geode-sdk/geode#610]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0 beta 21

### Expected Behavior

![image_2024-03-09_173735693](https://github.com/geode-sdk/geode/assets/160798931/b48f4865-94d9-431b-a5b4-2f00c587750d)

### Actual Behavior

![image_2024-03-09_173811206](https://github.com/geode-sdk/geode/assets/160798931/807fad29-af54-41ba-8f15-85199bfa3fdc)

### Steps to Reproduce

I dont know

**Comment by cloudskies13** [comment]
reopen geode, this happens to me too

**Comment by NoteEveryFriday** [comment]
Happens to me but restarting dont work
