### ISSUE TITLE
Gd crash when completing a level / new best

### ISSUE THREAD

**Issue by Epix62** [geode-sdk/geode#612]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v1.3.2

### Mods Installed

A lot

### Steps to Reproduce

Get a new best

### Crash Report

13:42:14 INFO  [Main] [Geode]: Running Geode v2.0.0-beta.22
13:42:14 INFO  [Main] [Geode]: Setting up internal mod
13:42:14 INFO  [Main] [Geode]: Setting up loader
13:42:14 DEBUG [Main] [Geode]:   Loading launch arguments
13:42:14 DEBUG [Main] [Geode]:   Setting up crash handler
13:42:14 DEBUG [Main] [Geode]:   Loading hooks
13:42:14 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::fullPathForFilename hook at 0x700eed29bc for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::sharedFileUtils hook at 0x700eed6e70 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled FMOD::System::init hook at 0x705af9c3b8 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled FMOD::ChannelControl::setVolume hook at 0x705af8f20c for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled __dynamic_cast hook at 0x700f09a54c for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::getUserObject hook at 0x700ee98920 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::setUserObject hook at 0x700ee98e08 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled LevelPage::onPlay hook at 0x700eb86934 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled LoadingLayer::init hook at 0x700e9c27c4 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x700e9c1b08 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled MenuLayer::init hook at 0x700e9c0454 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled ProfilePage::getUserInfoFinished hook at 0x700ecdaa2c for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled AchievementNotifier::willSwitchToScene hook at 0x700e8ee930 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled AppDelegate::trySaveGame hook at 0x700e9bb3a8 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled FileOperation::getFilePath hook at 0x700ef0cd14 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled cocos2d::CCScheduler::update hook at 0x700ee805f0 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled CCTextInputNode::ccTouchBegan hook at 0x700e9a4240 for geode.loader
13:42:14 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x700e9c1b08 for geode.loader
13:42:14 DEBUG [Main] [Geode]:   Setting up directories
13:42:15 INFO  [Main] [Geode]:   Refreshing mod graph
13:42:15 DEBUG [Main] [Geode]:     Queueing mods
13:42:15 DEBUG [Main] [Geode]:       Searching /storage/emulated/0/Android/media/com.geode.launcher/game/geode/mods
13:42:15 DEBUG [Main] [Geode]:         Found cvolton.betterinfo.geode
13:42:15 DEBUG [Main] [Geode]:           id: cvolton.betterinfo
13:42:15 DEBUG [Main] [Geode]:           version: v4.1.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found m336.levelinfo.geode
13:42:15 DEBUG [Main] [Geode]:           id: m336.levelinfo
13:42:15 DEBUG [Main] [Geode]:           version: v1.2.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found mat.run-info.geode
13:42:15 DEBUG [Main] [Geode]:           id: mat.run-info
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.2
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found nytelyte.wave_trail_drag_fix.geode
13:42:15 DEBUG [Main] [Geode]:           id: nytelyte.wave_trail_drag_fix
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.4
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found ml5.treasure-checklist.geode
13:42:15 DEBUG [Main] [Geode]:           id: ml5.treasure-checklist
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found weebify.restartbtn.geode
13:42:15 DEBUG [Main] [Geode]:           id: weebify.restartbtn
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found hjfod.gdshare.geode
13:42:15 DEBUG [Main] [Geode]:           id: hjfod.gdshare
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.5
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found cdc.level_thumbnails.geode
13:42:15 DEBUG [Main] [Geode]:           id: cdc.level_thumbnails
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found xanii.youtubers.geode
13:42:15 DEBUG [Main] [Geode]:           id: xanii.youtubers
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.4
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found hjfod.gmd-api.geode
13:42:15 DEBUG [Main] [Geode]:           id: hjfod.gmd-api
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.5
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found elsai.easing_preview.geode
13:42:15 DEBUG [Main] [Geode]:           id: elsai.easing_preview
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.0
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found zilko.xdbot.geode
13:42:15 DEBUG [Main] [Geode]:           id: zilko.xdbot
13:42:15 DEBUG [Main] [Geode]:           version: v1.5.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found cvolton.misc_bugfixes.geode
13:42:15 DEBUG [Main] [Geode]:           id: cvolton.misc_bugfixes
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found hjfod.betteredit.geode
13:42:15 WARN  [Main] [Geode]:           settings.pinch-to-zoom contains unknown key "platforms"
13:42:15 WARN  [Main] [Geode]:           settings.grid-size-controls contains unknown key "platforms"
13:42:15 WARN  [Main] [Geode]:           settings.show-grid-on-size-change contains unknown key "platforms"
13:42:15 DEBUG [Main] [Geode]:           id: hjfod.betteredit
13:42:15 DEBUG [Main] [Geode]:           version: v6.3.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found coopeeo.hideplus.geode
13:42:15 DEBUG [Main] [Geode]:           id: coopeeo.hideplus
13:42:15 DEBUG [Main] [Geode]:           version: v1.2.0
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found hiimjustin000.integrated_demonlist.geode
13:42:15 DEBUG [Main] [Geode]:           id: hiimjustin000.integrated_demonlist
13:42:15 DEBUG [Main] [Geode]:           version: v1.4.2
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found tastyforreal.google-translate.geode
13:42:15 DEBUG [Main] [Geode]:           id: tastyforreal.google-translate
13:42:15 DEBUG [Main] [Geode]:           version: v2024.229.0
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found elsai.copyright_remover_for_main_levels.geode
13:42:15 DEBUG [Main] [Geode]:           id: elsai.copyright_remover_for_main_levels
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found shineua.geometrize2gd.geode
13:42:15 DEBUG [Main] [Geode]:           id: shineua.geometrize2gd
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found geode.node-ids.geode
13:42:15 DEBUG [Main] [Geode]:           id: geode.node-ids
13:42:15 DEBUG [Main] [Geode]:           version: v1.7.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found dankmeme.globed2.geode
13:42:15 DEBUG [Main] [Geode]:           id: dankmeme.globed2
13:42:15 DEBUG [Main] [Geode]:           version: v1.3.2
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found thesillydoggo.comment_emojis.geode
13:42:15 DEBUG [Main] [Geode]:           id: thesillydoggo.comment_emojis
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.0-beta.5
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found geode.texture-loader.geode
13:42:15 DEBUG [Main] [Geode]:           id: geode.texture-loader
13:42:15 DEBUG [Main] [Geode]:           version: v1.5.0
13:42:15 DEBUG [Main] [Geode]:           early: yes
13:42:15 DEBUG [Main] [Geode]:         Found undefined0.autocheckpoint.geode
13:42:15 DEBUG [Main] [Geode]:           id: undefined0.autocheckpoint
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found fleym.nongd.geode
13:42:15 DEBUG [Main] [Geode]:           id: fleym.nongd
13:42:15 DEBUG [Main] [Geode]:           version: v2.5.2
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found beat.click-sound.geode
13:42:15 DEBUG [Main] [Geode]:           id: beat.click-sound
13:42:15 DEBUG [Main] [Geode]:           version: v1.7.1
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found gdutilsdevs.gdutils.geode
13:42:15 DEBUG [Main] [Geode]:           id: gdutilsdevs.gdutils
13:42:15 DEBUG [Main] [Geode]:           version: v1.2.16
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found mat.circle-tool.geode
13:42:15 DEBUG [Main] [Geode]:           id: mat.circle-tool
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found elsai.brightness_mod.geode
13:42:15 DEBUG [Main] [Geode]:           id: elsai.brightness_mod
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found cdc.more-hints.geode
13:42:15 DEBUG [Main] [Geode]:           id: cdc.more-hints
13:42:15 DEBUG [Main] [Geode]:           version: v1.1.4
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found firee.GoldenBest.geode
13:42:15 DEBUG [Main] [Geode]:           id: firee.GoldenBest
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.3
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:         Found firee.PrismMenu.geode
13:42:15 DEBUG [Main] [Geode]:           id: firee.PrismMenu
13:42:15 DEBUG [Main] [Geode]:           version: v1.5.0
13:42:15 DEBUG [Main] [Geode]:           early: yes
13:42:15 DEBUG [Main] [Geode]:         Found relative.advanced_song_search.geode
13:42:15 WARN  [Main] [Geode]:           [relative.advanced_song_search/v1.0.0/mod.json] contains unknown key "links"
13:42:15 DEBUG [Main] [Geode]:           id: relative.advanced_song_search
13:42:15 DEBUG [Main] [Geode]:           version: v1.0.0
13:42:15 DEBUG [Main] [Geode]:           early: no
13:42:15 DEBUG [Main] [Geode]:     Populating mod list
13:42:15 DEBUG [Main] [Geode]:       cvolton.betterinfo v4.1.3
13:42:15 DEBUG [Main] [Geode]:       m336.levelinfo v1.2.1
13:42:15 DEBUG [Main] [Geode]:       mat.run-info v1.0.2
13:42:15 DEBUG [Main] [Geode]:       nytelyte.wave_trail_drag_fix v1.1.4
13:42:15 DEBUG [Main] [Geode]:       ml5.treasure-checklist v1.1.1
13:42:15 DEBUG [Main] [Geode]:       weebify.restartbtn v1.1.1
13:42:15 DEBUG [Main] [Geode]:       hjfod.gdshare v1.0.5
13:42:15 DEBUG [Main] [Geode]:       cdc.level_thumbnails v1.0.1
13:42:15 DEBUG [Main] [Geode]:       xanii.youtubers v1.0.4
13:42:15 DEBUG [Main] [Geode]:       hjfod.gmd-api v1.0.5
13:42:15 DEBUG [Main] [Geode]:       elsai.easing_preview v1.0.0
13:42:15 DEBUG [Main] [Geode]:       zilko.xdbot v1.5.3
13:42:15 DEBUG [Main] [Geode]:       cvolton.misc_bugfixes v1.0.1
13:42:15 DEBUG [Main] [Geode]:       hjfod.betteredit v6.3.3
13:42:15 DEBUG [Main] [Geode]:       coopeeo.hideplus v1.2.0
13:42:15 WARN  [Main] [Hide+]:         Encountered unknown setting "LevelSearchLayer-section" while loading settings
13:42:15 WARN  [Main] [Hide+]:         Encountered unknown setting "creatorlayer-section" while loading settings
13:42:15 WARN  [Main] [Hide+]:         Encountered unknown setting "menulayer-section" while loading settings
13:42:15 WARN  [Main] [Hide+]:         Encountered unknown setting "hideplus-section" while loading settings
13:42:15 DEBUG [Main] [Geode]:       hiimjustin000.integrated_demonlist v1.4.2
13:42:15 DEBUG [Main] [Geode]:       tastyforreal.google-translate v2024.229.0
13:42:15 DEBUG [Main] [Geode]:       elsai.copyright_remover_for_main_levels v1.0.3
13:42:15 DEBUG [Main] [Geode]:       shineua.geometrize2gd v1.1.3
13:42:15 DEBUG [Main] [Geode]:       geode.node-ids v1.7.1
13:42:15 DEBUG [Main] [Geode]:       dankmeme.globed2 v1.3.2
13:42:15 DEBUG [Main] [Geode]:       thesillydoggo.comment_emojis v1.0.0-beta.5
13:42:15 DEBUG [Main] [Geode]:       geode.texture-loader v1.5.0
13:42:15 DEBUG [Main] [Geode]:       undefined0.autocheckpoint v1.0.1
13:42:15 DEBUG [Main] [Geode]:       fleym.nongd v2.5.2
13:42:15 DEBUG [Main] [Geode]:       beat.click-sound v1.7.1
13:42:15 WARN  [Main] [Click Sounds]:  Encountered unknown setting "clicksound-section" while loading settings
13:42:15 WARN  [Main] [Click Sounds]:  Encountered unknown setting "releasesound-section" while loading settings
13:42:15 WARN  [Main] [Click Sounds]:  Encountered unknown setting "test-click-btn" while loading settings
13:42:15 WARN  [Main] [Click Sounds]:  Encountered unknown setting "misc-section" while loading settings
13:42:15 WARN  [Main] [Click Sounds]:  Encountered unknown setting "test-release-btn" while loading settings
13:42:15 DEBUG [Main] [Geode]:       gdutilsdevs.gdutils v1.2.16
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "credit-buttons" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "credits-section" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "misc-section" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "test-notification" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "notification-appearance-section" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "notification-section" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "notification-placement-section" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "notificationPlacement" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "spotifyApp" while loading settings
13:42:15 WARN  [Main] [GDUtils]:       Encountered unknown setting "spotify-section" while loading settings
13:42:15 DEBUG [Main] [Geode]:       mat.circle-tool v1.1.3
13:42:15 DEBUG [Main] [Geode]:       elsai.brightness_mod v1.0.3
13:42:15 DEBUG [Main] [Geode]:       cdc.more-hints v1.1.4
13:42:15 DEBUG [Main] [Geode]:       firee.GoldenBest v1.0.3
13:42:15 DEBUG [Main] [Geode]:       firee.PrismMenu v1.5.0
13:42:15 WARN  [Main] [Prism Menu]:    Encountered unknown setting "values" while loading settings
13:42:15 DEBUG [Main] [Geode]:       relative.advanced_song_search v1.0.0
13:42:15 DEBUG [Main] [Geode]:     Building mod graph
13:42:15 DEBUG [Main] [Geode]:       firee.GoldenBest
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       cdc.more-hints
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       elsai.brightness_mod
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       mat.circle-tool
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       gdutilsdevs.gdutils
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       beat.click-sound
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       fleym.nongd
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       firee.PrismMenu
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       undefined0.autocheckpoint
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       geode.texture-loader
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       thesillydoggo.comment_emojis
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       cvolton.betterinfo
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:         cvolton.misc_bugfixes
13:42:15 DEBUG [Main] [Geode]:       shineua.geometrize2gd
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       elsai.copyright_remover_for_main_levels
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       hiimjustin000.integrated_demonlist
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       coopeeo.hideplus
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       dankmeme.globed2
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       mat.run-info
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       hjfod.gmd-api
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       nytelyte.wave_trail_drag_fix
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       zilko.xdbot
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       geode.loader
13:42:15 DEBUG [Main] [Geode]:       weebify.restartbtn
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       xanii.youtubers
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       tastyforreal.google-translate
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       hjfod.gdshare
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         hjfod.gmd-api
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       hjfod.betteredit
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       cvolton.misc_bugfixes
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       elsai.easing_preview
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       ml5.treasure-checklist
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42:15 DEBUG [Main] [Geode]:       relative.advanced_song_search
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       m336.levelinfo
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       geode.node-ids
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:       cdc.level_thumbnails
13:42:15 DEBUG [Main] [Geode]:         geode.loader
13:42:15 DEBUG [Main] [Geode]:         geode.node-ids
13:42

I cant do with the crash i cant copy n paste cus its 2 big

### Additional Information

I think its caused by getting a new best

**Comment by cursefroge** [comment]
Can you upload the full crash log to [a Pastebin service](https://pb.envs.net/)? The stacktrace isn't shown here.

**Comment by matcool** [comment]
stale, reopen if needed
