### ISSUE TITLE
gd crashes when changing any graphics settings besides texture quality

### ISSUE THREAD

**Issue by LandonIsE** [geode-sdk/geode#613]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.22

### Mods Installed

I have robtop jumpscare, geode node, custom keybinds & globed, but none of them were enabled.

### Steps to Reproduce

Change resolution & change to fullscreen (fullscreen takes time for it to crash though), but not when changing texture quality.

### Crash Report

2024-03-10T12:25:59-0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.22
Loader Commit: d90bfdd
Bindings Commit: 179edb2
Installed mods: 5
Problems: 0

== Exception Information ==
Faulty Module: C:\WINDOWS\SYSTEM32\d3d11.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 675B19D6 (d3d11.dll + 919d6 (D3D11CreateDeviceForD3D12 + 790))
Number Parameters: 2

== Stack Trace ==
 - C:\WINDOWS\SYSTEM32\d3d11.dll + 919d6 (D3D11CreateDeviceForD3D12 + 790)
 - C:\WINDOWS\SYSTEM32\d3d11.dll + 92a26 (D3D11On12CreateDevice + 54)
 - C:\ProgramData\obs-studio-hook\graphics-hook32.dll + 4517
 - C:\ProgramData\obs-studio-hook\graphics-hook32.dll + 45cb
 - C:\ProgramData\obs-studio-hook\graphics-hook32.dll + 432a
 - C:\ProgramData\obs-studio-hook\graphics-hook32.dll + 494e
 - C:\ProgramData\obs-studio-hook\graphics-hook32.dll + 4f29
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 9d67cb (DrvSetCallbackProcs + 1957515)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 9d8651 (DrvSetCallbackProcs + 1965329)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 97fcb7 (DrvSetCallbackProcs + 1602423)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 789d98 (DllMain + 7631416)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 78777c (DllMain + 7621660)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 78c50d (DllMain + 7641517)
 - C:\WINDOWS\System32\DriverStore\FileRepository\u0400566.inf_amd64_5e4d397bddb6fe15\B400392\atioglxx.dll + 1a55125 (eglGetProcAddress + 477717)
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 00000003
ECX: 0a219738
EDX: 00000001
EBP: 2318ca4c
ESP: 2318c994
EDI: 00000000
ESI: 00000000
EIP: 675b19d6

== Installed Mods ==
  | [v1.1.0] dankmeme.globed2
  | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.22] geode.loader
  | [v1.4.0] geode.node-ids
  | [v1.2.1] n.robtop-jumpscare

### Additional Information

Most likely caused by the robtop jumpscare mod, which even then doesn't make entirely sense since the mod is disabled.

**Comment by LandonIsE** [comment]
Update: the game doesn't crash anymore. Very weird.

**Comment by elnexreal** [comment]
iirc the problem is related to graphic things, try updating your graphics drivers

**Comment by matcool** [comment]
stale, reopen if needed
