### ISSUE TITLE
Random crash that has something to do with the file igxelpicd32.dll

### ISSUE THREAD

**Issue by relaxingOcean** [geode-sdk/geode#617]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.00 beta 22

### Mods Installed

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v0.1.4] acaruso.slope
x | [v1.1.2] adam_729.deathmarkers
x | [v1.1.1] adyagd.godlikefaces
x | [v1.2.8] alphalaneous.deathlink
  | [v1.3.6] alphalaneous.integratedloquibot
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.7.1] beat.click-sound
  | [v1.0.6] bitz.customprofiles
x | [v1.0.3] bitz.moregames
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.2] capeling.soggy-mod
x | [v1.0.0] capeling.usable_explorers
x | [v1.0.1] cdc.level_thumbnails
  | [v1.1.4] cdc.more-hints
x | [v1.0.1] coderqc.gdswearfilter
x | [v1.3.1] creatorcreepy.unixsync
x | [v1.0.0] creo.color_unlock_hack
x | [v4.1.3] cvolton.betterinfo
x | [v1.1.0] cvolton.misc_bugfixes
x | [v1.3.2] dankmeme.globed2
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.3] elsai.brightness_mod
x | [v1.0.3] elsai.copyright_remover_for_main_levels
x | [v1.0.3] firee.GoldenBest
  | [v1.5.0] firee.PrismMenu
x | [v2.5.2] fleym.nongd
x | [v1.2.16] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.0] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v6.3.3] hjfod.betteredit
x | [v1.0.1] itzkiba.elegant_rankings
  | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.0] itzkiba.id_hyperlinks
x | [v1.0.0] izzy.i_hate_you_top_lists
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v0.1.8] lexi.visiblecheckpoints
  | [v1.0.1] mat.draw-divide
x | [v1.0.1] mat.max-window
x | [v1.0.2] mat.run-info
x | [v1.0.0-beta.9] minemaker0430.gddp_integration
x | [v1.1.1] ml5.treasure-checklist
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.0.1] n.friends
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v2.1.0] prevter.openhack
x | [v1.1.0] raydeeux.likebaitexterminator
x | [v1.1.1] redlime.statchanges
x | [v1.0.1] relative.advanced_song_search
x | [v1.1.0] relative.custom_endscreen_text
x | [v0.1.2] rooot.custom-gamemode-colors
x | [v1.2.4] shineua.minecraft_splash
x | [v1.0.5] sofabeddd.colored_icon_kit
x | [v1.0.3] sofabeddd.geometry_dash
  | [v0.1.1] suntle.compactendscreen
x | [v2024.229.0] tastyforreal.google-translate
x | [v1.0.1] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.0.0-beta.5] thesillydoggo.comment_emojis
x | [v1.6.9] thesillydoggo.entersearch
x | [v2.2.4] TheSillyDoggo.GradientPages
x | [v1.0.3] thesillydoggo.icon_kit_switcher
  | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.6.6] tpdea.betterpause-Better
x | [v1.1.3] undefined0.autocheckpoint
x | [v1.11.0] undefined0.gdtweaks
  | [v1.1.1] undefined0.minecraft_menu
x | [v1.1.0] uproxide.autosong
x | [v1.0.1] uproxide.more_difficulties
x | [v4.0.0] user95401.mainlevelseditor
x | [v1.0.4] weebify.coins_in_pause_menu
  | [v1.0.1] weebify.randomizecreatorlayer-geode
x | [v1.0.0] xanii.freaky_mode
x | [v1.0.4] xanii.youtubers
x | [v1.5.3] zilko.xdbot

### Steps to Reproduce

Probably happens randomly (first two times happened with exiting the level "I hate this level" and then while inside the level "Globed Palace")

### Crash Report

https://pastebin.com/w878HAaF

**Comment by matcool** [comment]
stale, reopen if needed
