### ISSUE TITLE
Platformer Checkpoints Not Working

### ISSUE THREAD

**Issue by sheepdotcom** [geode-sdk/geode#618]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.22

### Expected Behavior

Activating a checkpoint in platformer mode should respawn you at the checkpoint when dying.

### Actual Behavior

Activating a checkpoint in platformer mode then respawning causes you to respawn at the start of the level instead of the checkpoint.

### Steps to Reproduce

1) Activate Checkpoint
2) Die and Respawn

### Additional Information

This issue happens even in safe mode and when all mods are disabled. Does not occur on android64 though.

**Comment by RayDeeUx** [comment]
please check your pause settings and make sure `disable checkpoints` is off
