### ISSUE TITLE
'Higher Rate Limit'

### ISSUE THREAD

**Issue by FlutterFlakesGD** [geode-sdk/geode#622]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

Geode 2.0.0 Beta,21 (

### Mods Installed

Had 20 mods installed, uninstalled all mods to see if the problem would fix.

### Expected Behavior

Geode would load normally, the download section would load as normal.

### Actual Behavior

Geode had a message about a 'failed request' and 'get a higher rate limit'. Mod downloader can't load and only shows a spinning wheel (I have a small aspect ratio, I can't show the full error). 
![image](https://github.com/geode-sdk/geode/assets/163170939/3b9a8ddd-563a-4cb4-aa32-6dc833c9c2db)

### Steps to Reproduce

Unsure how to reproduce the bug.

**Comment by RoootTheFox** [comment]
This isn't a Geode issue, but GitHub.
This will be fixed with the new index.
