### ISSUE TITLE
crashes randomly

### ISSUE THREAD

**Issue by youmustp** [geode-sdk/geode#623]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.22

### Mods Installed

x | [v1.3.2] dankmeme.globed2
x | [v2.5.2] fleym.nongd
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.0] geode.node-ids

### Steps to Reproduce

its random

### Crash Report

[2024-03-13_16-51-57.log](https://github.com/geode-sdk/geode/files/14581880/2024-03-13_16-51-57.log)
[Geode 2024-03-13 16.36.58.log](https://github.com/geode-sdk/geode/files/14581883/Geode.2024-03-13.16.36.58.log)

**Comment by HappyAlexRomania** [comment]
PLZ FIX THIS I LOST 2 FREAKING HOURS OF WORK BECAUSE OF THIS

**Comment by matcool** [comment]
stale, reopen if needed
