### ISSUE TITLE
Mod count (Downloaded and Available)

### ISSUE THREAD

**Issue by zipatton** [geode-sdk/geode#626]
> ### Geode Version
>
> v2.0.0-beta.22

### Suggestion

It would be a nice addition if the browser told you how many mods there are and how many you have installed.

**Comment by qimiko** [comment]
fixed on new index :3 (check the installed tab for installed mod counts)

![image](https://github.com/geode-sdk/geode/assets/25387744/cb6f6b21-d3ce-4dc0-8b17-22332e2530fd)
