### ISSUE TITLE
I CANT SEE ANY MODS

### ISSUE THREAD

**Issue by SomeGDPerson123** [geode-sdk/geode#627]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0 beta-22

### Mods Installed

Happened with mods and no mods.

### Expected Behavior

Expected to see every mod in the download tab.

### Actual Behavior

"No mods found"

### Steps to Reproduce

IT HAPPENED RANDOMLY

### Additional Information

this is all i have. i tried everything. uninstalling mods. uninstalling geode with keeping data. uninstalling geode with deleting data.

**Comment by SomeGDPerson123** [comment]
DISREGARD THIS BUG, I FIXED IT BY REINSTALLING THE GAME AND THE MODLOADER

**Comment by SomeGDPerson123** [comment]
PLEASE SOMEONE HELP ME

**Comment by chubbybear0924** [comment]
Same thing foundmy geode loader no having a mod folder when I downloaded it maybe the executible is missing files
