### ISSUE TITLE
 Crash after deleting checkpoint

### ISSUE THREAD

**Issue by mottyan1991** [geode-sdk/geode#629]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta.22

### Mods Installed

== Installed Mods ==
x | [v1.0.1] colon.gold_user_coins
x | [v1.0.0] creo.color_unlock_hack
x | [v1.0.0] creo.music_unlock_hack
x | [v1.0.2] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.0.0] izzy.practice_sync
x | [v0.1.9] lexi.visiblecheckpoints
x | [v1.0.1] mat.max-window
x | [v1.0.2] mat.run-info
x | [v2.8.5] maxnu.gd_mega_overlay
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.0.0] polsk.pause_settings
x | [v2.1.0] prevter.openhack
x | [v1.0.2] relative.account_statuses
x | [v1.1.3] shineua.geometrize2gd
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.5.4] zilko.xdbot

### Steps to Reproduce

crash after delete 2~4 times checkpoint
https://github.com/geode-sdk/geode/assets/163700174/dd3f3e12-7858-44ce-9612-9fae026b81e9

![スクリーンショット 2024-03-17 111651](https://github.com/geode-sdk/geode/assets/163700174/b669fd05-eb61-41e3-b7dc-97490b7a957a)

### Crash Report

2024-03-16T19:04:48+0900
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.22
Loader Commit: d90bfdd
Bindings Commit: 179edb2
Installed mods: 20
Problems: 0

== Exception Information ==
Faulty Module: D:\Geometry.Dash\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 6C69A370 (libcocos2d.dll + 6a370 (cocos2d::CCObject::release + 0))
Number Parameters: 2

== Stack Trace ==
 - D:\Geometry.Dash\libcocos2d.dll + 6a370 (cocos2d::CCObject::release + 0)
 - D:\Geometry.Dash\libcocos2d.dll + 63c73 (cocos2d::CCArray::removeLastObject + 19)
 - D:\Geometry.Dash\geode\unzipped\lexi.visiblecheckpoints\lexi.visiblecheckpoints.dll + 20a2d
 - D:\Geometry.Dash\geode\unzipped\lexi.visiblecheckpoints\lexi.visiblecheckpoints.dll + 183fe
 - 03AB16D7
 - D:\Geometry.Dash\GeometryDash.exe + 3bf943
 - D:\Geometry.Dash\libcocos2d.dll + 9bf09 (cocos2d::CCKeyboardDispatcher::dispatchKeyboardMSG + 153)
 - 01932BA6
 - 019329CF
 - D:\Geometry.Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 9b554
 - 019329CF
 - D:\Geometry.Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 6ef24
 - 019329CF
 - D:\Geometry.Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 56204
 - 019329CF
 - D:\Geometry.Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 1dea4
 - 019329CF
 - D:\Geometry.Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + b294
 - 019329CF

== Register States ==
EAX: 18efab28
EBX: 00000000
ECX: 8803c200
EDX: 19f99738
EBP: 0073ef54
ESP: 0073ef48
EDI: ffffffff
ESI: 18efadb0
EIP: 6c69a370

== Installed Mods ==
x | [v1.0.1] colon.gold_user_coins
x | [v1.0.0] creo.color_unlock_hack
x | [v1.0.0] creo.music_unlock_hack
x | [v1.0.2] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.0.0] izzy.practice_sync
x | [v0.1.9] lexi.visiblecheckpoints
x | [v1.0.1] mat.max-window
x | [v1.0.2] mat.run-info
x | [v2.8.5] maxnu.gd_mega_overlay
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.0.0] polsk.pause_settings
x | [v2.1.0] prevter.openhack
x | [v1.0.2] relative.account_statuses
x | [v1.1.3] shineua.geometrize2gd
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.5.4] zilko.xdbot

**Comment by Prevter** [comment]
1. "I confirm that this crash is NOT related to a mod but directly to Geode Loader itself." is made for a reason
2. Disable "VisibleCheckpoints" and try again

**Comment by mottyan1991** [comment]
> 1. "I confirm that this crash is NOT related to a mod but directly to Geode Loader itself." is made for a reason
> 2. Disable "VisibleCheckpoints" and try again

doing this fix that. thank you prevter
