### ISSUE TITLE
gd crashing whenever you upen it

### ISSUE THREAD

**Issue by swirlyboii** [geode-sdk/geode#630]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

no mods

### Steps to Reproduce

i opened gd and it crashed

### Crash Report

the error was (0xc000007b)

**Comment by Reprisent** [comment]
I happen, before it crashes, see which mod appears on the game loading screen, then go to the game files and delete the mod, then you can download it again

**Comment by matcool** [comment]
stale, reopen if needed
