### ISSUE TITLE
geode crashing when opening editor

### ISSUE THREAD

**Issue by RandomGDPlyr** [geode-sdk/geode#631]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Steps to Reproduce

when i was trying to open editor, it literally crashed for no reason. i'm getting so mad and im here for like 3 HOURS just to find how to fix this crash
![Captura de tela 2024-03-17 165606](https://github.com/geode-sdk/geode/assets/163772274/7cb757a5-b2ab-41c7-8037-810e1e6b0d4d)

**Comment by matcool** [comment]
stale, reopen if needed
