### ISSUE TITLE
Editor Bug

### ISSUE THREAD

**Issue by GorariaNS** [geode-sdk/geode#632]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.22

### Mods Installed

abb2k.backup.geode
capeling.gamemode_picker.geode
cdc.level_thumbnails.geode
cvolton.betterinfo.geode
cvolton.misc_bugfixes.geode
dankmeme.globed2.geode
fleym.nongd.geode
geode.node-ids.geode
geode.texture-loader.geode
hjfod.betteredit.geode
thesillydoggo.comment_emojis.geode
tpdea.betterpause-Better.geode
weebify.high-graphics-android.geode
zilko.xdbot.geode

### Expected Behavior

When play testing in the level editor, I expected to die to the spikes to test if something is too off balance.

### Actual Behavior

When touching the spike, It didn't make my icon die. Rather it just did nothing like I just turn on "No Touch"

### Steps to Reproduce

To see it happen is easy. How you get it is the hard part and the one I don't understand.

If you wanna see it, you gotta go in the editor, place a spike or something similar, and click the play test button on your left.

### Additional Information

This bug isn't present in vanilla GD nor when I actually play the level. I also haven't messed with anything else like enable "ignore damage" or "no touch"

Furthermore, it's also universal across all my levels. It also only affects spikes, saws, or anything like them. Other objects like pads, blocks, etc. work just fine.

**Comment by dankmeme01** [comment]
globed bug, not geode
