### ISSUE TITLE
MSVC unordered_map ABI breakage

### ISSUE THREAD

**Issue by kynex7510** [geode-sdk/geode#633]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

whatever is the latest as of writing this

### Expected Behavior

Work.

### Actual Behavior

Crash.

### Steps to Reproduce

Any access to unordered_map.

**Comment by dankmeme01** [comment]
fixed in #636
