### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by InfernuZGD** [geode-sdk/geode#64]
### Platform

Windows

### Geode Version

v0.6.1

### Steps to Reproduce

1) Have Megahack
2) Instail geode
3) Press new 5 button on main screen
4) Crash

### Crash Report

[2022-11-03_21-26-15.log](https://github.com/geode-sdk/geode/files/9932488/2022-11-03_21-26-15.log)

### Additional Information

Probably megahack issue

**Comment by altalk23** [comment]
> Have Megahack

> Mods made using traditional methods, such as GD Hacker Mode or BetterEdit v4 are unfortunately never going to be supported by Geode.

I am sorry to inform you that we are not responsible for any crashes that occur that happens when other "traditional" mods are loaded
