### ISSUE TITLE
Geode crashing when purchasing a path

### ISSUE THREAD

**Issue by CyanEight** [geode-sdk/geode#646]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta.22

### Mods Installed

== Installed Mods ==
x | [v1.1.1] adyagd.godlikefaces
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.1.2] capeling.main_level_pages
x | [v1.0.1] cdc.level_thumbnails
  | [v1.0.1] coderqc.gdswearfilter
x | [v1.3.1] creatorcreepy.unixsync
x | [v1.3.2] dankmeme.globed2
  | [v1.3.1] elsai.a_daily_shop
x | [v1.0.3] firee.GoldenBest
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.3.1] m336.levelinfo
x | [v1.0.2] mat.run-info
x | [v1.0.0-beta.10] minemaker0430.gddp_integration
x | [v1.1.1] ml5.treasure-checklist
x | [v1.0.0] rynat.better_unlock_info
x | [v1.2.5] shineua.minecraft_splash
x | [v1.0.5] sofabeddd.colored_icon_kit
x | [v1.0.3] sofabeddd.geometry_dash
x | [v1.0.0-beta.5] thesillydoggo.comment_emojis
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.0.1] uproxide.more_difficulties
x | [v1.0.2] weebify.separate_dual_icons
x | [v1.5.4] zilko.xdbot

### Steps to Reproduce

1) From the main menu, go to the Create tab
2) Click the Paths button
3) Purchase a path

### Crash Report

Crashlog:
https://pastebin.com/PNvKASMX
Log:
https://pastebin.com/6WCMEhSv

**Comment by Prevter** [comment]
"Better Unlock Info" crash most likely

**Comment by TheSillyDoggo** [comment]
☑️ I confirm I am NOT reading the checkbox and am just going to blame mod crashes on geode itself

**Comment by CyanEight** [comment]
nvm how do i delete this

**Comment by CyanEight** [comment]
should've looked into the crashlog before assuming it was bc of geode. thanks prevter!
