### ISSUE TITLE
Game is not starting up

### ISSUE THREAD

**Issue by jerkylettuce59** [geode-sdk/geode#647]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0 b21

### Mods Installed

~ | [v1.1.1] adyagd.godlikefaces
~ | [v1.2.8] alphalaneous.deathlink
~ | [v1.8.0] beat.click-sound
~ | [v1.0.3] bitz.moregames
~ | [v1.0.5] capeling.gamemode_picker
~ | [v1.0.2] capeling.soggy-mod
  | [v1.0.1] cdc.level_thumbnails
~ | [v1.0.1] cj_link.fakemoderator
~ | [v1.3.1] creatorcreepy.unixsync
  | [v1.0.0] creo.music_unlock_hack
~ | [v1.3.6] dankmeme.globed2
~ | [v2.5.2] fleym.nongd
~ | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.21] geode.loader
x | [v1.8.1] geode.node-ids
~ | [v6.3.3] hjfod.betteredit
~ | [v1.0.5] hjfod.gdshare
~ | [v1.0.5] hjfod.gmd-api
~ | [v1.1.0] itzkiba.grandpa_demon
~ | [v1.0.0] mat.reference-image
~ | [v1.0.2] mat.run-info
~ | [v2.8.7] maxnu.gd_mega_overlay
  | [v2.0.4-beta.1] muhammadgames.bettermenu
~ | [v1.1.0] sofabeddd.colored_icon_kit
~ | [v1.0.1] thesillydoggo.animatedprofiles
~ | [v1.0.0-beta.5] thesillydoggo.comment_emojis
~ | [v2.2.4] TheSillyDoggo.GradientPages
x | [v1.6.8] tpdea.betterpause-Better

### Steps to Reproduce

I do not know how to reproduce the crash; it happened naturally

### Crash Report

[2024-03-27_15-56-38.log](https://github.com/geode-sdk/geode/files/14773889/2024-03-27_15-56-38.log)

**Comment by qimiko** [comment]
if you still have this issue, it seems to be a graphics drivers/gpu problem. please verify that you're on the latest (and correct!) drivers for your gpu
