### ISSUE TITLE
Crash when press X in Practice Mode after update to beta.22

### ISSUE THREAD

**Issue by MessiInter** [geode-sdk/geode#649]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v2.0.0-beta.22

### Mods Installed

abb2k.backup
alphalaneous.playercolorselect
alphalaneous.projectedstars
bitz.moregames
capeling.colored_level_info_bg
capeling.gamemode_picker
capeling.usable_explorers
cdc.level_thumbnails
cdc.more-hints
cj_link.fakemoderator
coopeeo.customname
coopeeo.hideplus
cvolton.betterinfo
cvolton.misc_bugfixes
dankmeme.globed2
elohmrow.death_tracker
elsai.a_daily_shop
firee.GoldenBest
fleym.nongd
gdutilsdevs.gdutils
geode.custom-keybinds
geode.node-ids
geode.texture-loader
hjfod.betteredit
hjfod.gdshare
hjfod.gmd-api
hjfod.quick-volume-controls
itzkiba.elegant_rankings
itzkiba.formatted_platformer_time
itzkiba.id_hyperlinks
khronophobia.more_settings_button
legowiifun.unlisted_objects_in_editor
lexi.visiblecheckpoints
mat.circle-tool
mat.reference-image
mat.scroll-zoom
maxnu.gd_mega_overlay
n.level_pronouns
nytelyte.wave_trail_drag_fix
polsk.level_quests
prevter.openhack
raydeeux.camerashadertoggles
raydeeux.controlvanillasfx
relative.advanced_song_search
shineua.geometrize2gd
shineua.minecraft_splash
slammy333.save_button
sofabeddd.colored_icon_kit
spaghettdev.gd-roulette
tastyforreal.google-translate
thesillydoggo.animatedprofiles
thesillydoggo.entersearch
TheSillyDoggo.GradientPages
thesillydoggo.icon_kit_switcher
tpdea.betterpause-Better
tpdea.sceneswitcher
tpdea.scroll_any_input
uproxidedevelopers
weebify.coins_in_pause_menu
weebify.level_info_in_pause_menu
weebify.restartbtn
xanii.youtubers

### Steps to Reproduce

1. Start Geometry Dash
2. Play a level
3. Change to Practice Mode
4. Press X to remove checkpoint(s)
5. Geometry Dash Crashed

### Crash Report

[2024-03-30_16-47-27.log](https://github.com/geode-sdk/geode/files/14811470/2024-03-30_16-47-27.log)
[Geode 2024-03-30 16.30.30.log](https://github.com/geode-sdk/geode/files/14811471/Geode.2024-03-30.16.30.30.log)

### Additional Information

This is likely caused by the Geode loader because in v2.0.0-beta.21 everything is normal but after beta.21 update, it crashes when press X in Practice Mode, and I don't install new mods after the update

**Comment by RayDeeUx** [comment]
you claim to use macos and yet openhack is in your installed mods

let's think about that for a moment
