### ISSUE TITLE
My geometry dash does not open under any circumstances and with the geode it causes a crash

### ISSUE THREAD

**Issue by San3k1** [geode-sdk/geode#651]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Mods Installed

0

### Steps to Reproduce

As far as I remember, I accidentally launched Geometry Dash and pressed Ctrl + Alt + F4 because I have a program installed that works like lt F4 but closes everything using the task manager using this combination. And I think that because I did this while loading mods or something else caused an error. But the whole problem is that I can’t launch Geometry Dash in principle and I don’t know what to do

### Crash Report

2024-04-01T08:08:03+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.23
Loader Commit: b3c0c9f
Bindings Commit: a4c775b
Installed mods: 1
Problems: 0

== Exception Information ==
Faulty Module: C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 72757DD2 (LIBCOC~1.DLL + 117dd2 (cocos2d::CCPoint::unrotate + 12434))
Number Parameters: 2

== Stack Trace ==
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 117dd2 (cocos2d::CCPoint::unrotate + 12434)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c764b (cocos2d::CCEGLView::onGLFWError + 139)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 1157bf (cocos2d::CCPoint::unrotate + 2687)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 11983e (cocos2d::CCPoint::unrotate + 19198)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 118f5f (cocos2d::CCPoint::unrotate + 16927)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 117a91 (cocos2d::CCPoint::unrotate + 11601)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 1172ba (cocos2d::CCPoint::unrotate + 9594)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + 116327 (cocos2d::CCPoint::unrotate + 5607)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c8006 (cocos2d::CCEGLView::setupWindow + 54)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c7240 (cocos2d::CCEGLView::initWithRect + 160)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c70af (cocos2d::CCEGLView::initWithFullScreen + 159)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c6aa4 (cocos2d::CCEGLView::createWithFullScreen + 100)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\GEOMET~1.EXE + 5b1cd
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\LIBCOC~1.DLL + c4b1a (cocos2d::CCApplication::run + 26)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\GEOMET~1.EXE + 3c12d8
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\Geode.dll + 172764 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - C:\PROGRA~2\Steam\STEAMA~1\common\GEOMET~1\GEOMET~1.EXE + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 20099 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67b6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67b3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00000000
EBX: 012ff2dc
ECX: 01558e24
EDX: 0892389c
EBP: 012fb080
ESP: 012fb080
EDI: 0155eb0c
ESI: 0892bc48
EIP: 72757dd2

== Installed Mods ==
x | [v2.0.0-beta.23] geode.loader

### Additional Information

I don't know what to add
![GeometryDash_FYszMBcOwA](https://github.com/geode-sdk/geode/assets/165631134/02e8438f-e5b8-4bb7-8070-e2b00c9fdce5)

**Comment by qimiko** [comment]
not a geode issue! check your gpu drivers and/or restart your computer

**Comment by San3k1** [comment]
> not a geode issue! check your gpu drivers and/or restart your computer
Thank you so much
