### ISSUE TITLE
GD crashes when pressing save/save and play/save and exit

### ISSUE THREAD

**Issue by sjmlouie** [geode-sdk/geode#652]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.23

### Mods Installed

[v1.1.4] adyagd.ingamelistmod
x | [v1.5.0] egg.icon_hack
  | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.23] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.4.4] hiimjustin000.integrated_demonlist
x | [v1.0.0] izzy.practice_sync
x | [v1.0.2] mat.run-info
x | [v2.8.7] maxnu.gd_mega_overlay
x | [v1.1.1] ninkaz.blending_glow
  | [v1.1.0] techstudent10.button_sfx
x | [v2.2.4] TheSillyDoggo.GradientPages

### Steps to Reproduce

GD crashes when pressing save/save and play/save and exit

### Crash Report

2024-04-01T19:05:27+0900
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.23
Loader Commit: b3c0c9f
Bindings Commit: a4c775b
Installed mods: 12
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_alloc("bad allocation")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 149542 (RaiseException + 98)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 19339 (CxxThrowException + 78)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 5da6a (fcloseall + 34608)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 624c7 (CCContentManager::addDictDS + 471)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 61f9d (DS_Dictionary::~DS_Dictionary + 445)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 6257d (CCContentManager::addDictDS + 653)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + d15e9 (pugi::xml_document::save_file + 329)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + d163d (pugi::xml_document::save_string + 29)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 771fd (DS_Dictionary::saveRootSubDictToString + 77)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 76c04 (DS_Dictionary::saveRootSubDictToCompressedFile + 420)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 47624
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + a2c56
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + a2cb4
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)

== Register States ==
EAX: 00fce6d0
EBX: 00000000
ECX: 00000003
EDX: 00000000
EBP: 00fce728
ESP: 00fce6d0
EDI: 00fce778
ESI: 66fcc7fc
EIP: 75eb9542

== Installed Mods ==
x | [v1.1.4] adyagd.ingamelistmod
x | [v1.5.0] egg.icon_hack
  | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.23] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.4.4] hiimjustin000.integrated_demonlist
x | [v1.0.0] izzy.practice_sync
x | [v1.0.2] mat.run-info
x | [v2.8.7] maxnu.gd_mega_overlay
x | [v1.1.1] ninkaz.blending_glow
  | [v1.1.0] techstudent10.button_sfx
x | [v2.2.4] TheSillyDoggo.GradientPages

### Additional Information

idk

**Comment by qimiko** [comment]
seems like an out of memory, you might want to install the [4gb patch](https://ntcore.com/?page_id=371). but, not a geode issue.

**Comment by LDYgdPlayer** [comment]
i have the same issue, and it seems to be a bug of gd itself.
i tried deleting all the mods, deleting geode itself, refreshing my account, 4gb patch with none of them working.

idk how to fix it maybe wait for rob to release a new update


this is my crash log, it says level api by cvolton is the problem but no it isnt
[2025-05-31_20-06-36.log](https://github.com/user-attachments/files/20533242/2025-05-31_20-06-36.log)
