### ISSUE TITLE
game crashes every time i click something

### ISSUE THREAD

**Issue by TheBonOdori** [geode-sdk/geode#653]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta.23

### Steps to Reproduce

I was messing around with texture packs to change my difficulty faces and when i tried to boot up the game and click on the play button, the game crashed immediatly

### Crash Report

[2024-04-01_21-40-57.log](https://github.com/geode-sdk/geode/files/14830081/2024-04-01_21-40-57.log)

**Comment by RoootTheFox** [comment]
can you reproduce this crash without *any* mods installed?

**Comment by TheBonOdori** [comment]
how do uninstall mods without the game being opened?

**Comment by RoootTheFox** [comment]
hold SHIFT while starting the game, that'll enable safe mode

**Comment by TheBonOdori** [comment]
i tried it and it didnt work??

**Comment by RoootTheFox** [comment]
hold it while pressing start in steam until you get this popup
![image](https://github.com/geode-sdk/geode/assets/78933889/5bfd0575-32d3-4c8c-a016-109a7fbdd104)

this should pop up before gd opens

**Comment by TheBonOdori** [comment]
the crash still happened though and in the logs, the faulty file is Geode.dll

**Comment by TheBonOdori** [comment]
it happens every time i click the icon menu, the play button and custom levels button

**Comment by RoootTheFox** [comment]
your texture pack messed up `GJ_gradientBG.png` - verify file integrity in steam and try again

**Comment by RoootTheFox** [comment]
right click gd and go to properties
![image](https://github.com/geode-sdk/geode/assets/78933889/0249f464-e2e3-4620-8ccb-cb333c989a72)

then go to installed files and click "verify integrity of game files"
![image](https://github.com/geode-sdk/geode/assets/78933889/c0f93e0e-8473-42f3-9604-5632996a593e)

**Comment by TheBonOdori** [comment]
alright (cool niko cursor)

**Comment by RoootTheFox** [comment]
does the crash still happen?

**Comment by TheBonOdori** [comment]
thank you th game works properly now but none of the texture pack files work now

**Comment by RoootTheFox** [comment]
yeah, as i stated previously, its sadly an issue with your texture pack - not with Geode

**Comment by TheBonOdori** [comment]
ok thank you for helping me :)
