### ISSUE TITLE
Fifaxx

### ISSUE THREAD

**Issue by Fifaop** [geode-sdk/geode#657]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### SDK commit

Bb

### Geode Version

Bnn

### Mods Installed

Vv

### Expected Behavior

Bb

### Actual Behavior

Vb

### Steps to Reproduce

Vv

### Additional Information

Gh

**Comment by Weebifying** [comment]
amen

**Comment by dankmeme01** [comment]
this is true
