### ISSUE TITLE
downloadable mod list and featured list say "no mods found" (restarting didn't fix)

### ISSUE THREAD

**Issue by Waffffelz** [geode-sdk/geode#659]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.23

### Mods Installed

elsai.a_daily_shop v1.3.1, grian.art_importer v1.1.0, beat.click_sound v1.8.0, geode.custom_keybinds v1.5.2, acaruso.slope v0.1.6, capeling.gamemode_picker v1.0.5, maxnu.gd_mega_overlay v2.8.7, n.level_pronouns v1.0.4, geode.node_ids v1.8.1, zilko.xdbot v1.5.5

### Expected Behavior

Expected to see a list of mods when clicking the Download tab on the Geode mod menu.

### Actual Behavior

![Screenshot (90)](https://github.com/geode-sdk/geode/assets/166131636/64bb1f82-92cc-4443-9b43-4ba659a320bf)
There were no mods on the Download page.

### Steps to Reproduce

1) I opened the game and clicked the Geode button.
2) I clicked on the Download tab and waited for it to finish extracting.
3) Nothing happened after "Updating Local Cache"
4) When I left and came back it said "No mods found"

**Comment by altalk23** [comment]
just reopen the game bad internet sometimes does that
