### ISSUE TITLE
does not load levels

### ISSUE THREAD

**Issue by TEDrome** [geode-sdk/geode#660]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

V2.0.0-beta.23

### Expected Behavior

load the levels
![Screenshot_20240406_001541_Geode](https://github.com/geode-sdk/geode/assets/166196362/0ab5a1bd-01c3-4ade-9ea9-e4db1d2b747d)

### Actual Behavior

I was looking at the mod but then I couldn't play
![Screenshot_20240406_001940_Geometry Dash](https://github.com/geode-sdk/geode/assets/166196362/e4414f6f-940d-4bcc-bcd4-5f282ddb627e)

### Steps to Reproduce

I didn't touch anything

### Additional Information

They used to load me but now no more

**Comment by TEDrome** [comment]
Pls help me

**Comment by Samuca012013RBLXGD** [comment]
Bad for you, but even bad for me, i cant open the download due to Family Link and my mom didnt got the solicitation 😔
