### ISSUE TITLE
Some mods don't have github link

### ISSUE THREAD

**Issue by eye-wave** [geode-sdk/geode#661]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.23

### Expected Behavior

show the github icon when viewing the mod preview

### Actual Behavior

repo link is not there

### Steps to Reproduce

open some mods in the mod browser like
- GDShare
- Run Info

### Additional Information

in `mods-v2/mod/version/entry.json` there is a download link to the binaries and most of the time its from github releases. 
Therefore i don't see the need to hide github button, especially for mods that are featured. I feel like users should have the freedom to take a look at the mod source before actually installing it.

**Comment by eye-wave** [comment]
i wasn't sure if this was intentional or not. I was initially going to mark it as question not a bug

**Comment by altalk23** [comment]
github button is provided from the mod.json (specifically the repository key) which is not a mandatory key (maybe it will be later it is somethig discussed before though). thats why those mods are midding them cause they dont have it in their mod.json. not a bug, just the mod devs (even us!) being lazy.
