### ISSUE TITLE
No version for Samsung :(

### ISSUE THREAD

**Issue by Samuca012013RBLXGD** [geode-sdk/geode#662]
### Geode Version

v2.0.1

### Related Problem

No download for Samsung Galaxy A14

### Your Solution

If I could be an dev of Geode I would launch for Samsung

### Additional Information

I will follow Geode if you all launch for Samsung

**Comment by Samuca012013RBLXGD** [comment]
Not just Samsung Galaxy A14, you can all release on other devices

**Comment by dankmeme01** [comment]
samsung runs android, there already is an android version of geode.

**Comment by Samuca012013RBLXGD** [comment]
Wait what, well i have family link and my mom didnt get the notification to permit it 😐 so can you fix that as well, too?!?!?!

**Comment by enessmr** [comment]
Well it's possible to install on Redmi note 6 pro.

**Comment by enessmr** [comment]
a 2018 phone
