### ISSUE TITLE
cant update game and geode is made for 2.204

### ISSUE THREAD

**Issue by AWVR777** [geode-sdk/geode#663]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta.23

### Expected Behavior

geode to load.

### Actual Behavior

dialogue box: "geode is made for geometry dash 2.204. please update your game."

### Steps to Reproduce

Open geometry dash 2.200

### Additional Information

It is impossible for me to update the game in any way other than to replace files directly in file explorer or write the code myself (which I can't do)

**Comment by RoootTheFox** [comment]
simple: update to 2.204 ~ geode does NOT EXIST FOR 2.200 and neither do mods.

**Comment by AWVR777** [comment]
do you have the gae files for 2.204

**Comment by RoootTheFox** [comment]
yes: https://store.steampowered.com/app/322170/Geometry_Dash/

**Comment by AWVR777** [comment]
didnt work

**Comment by AWVR777** [comment]
hold on lemme try something

**Comment by AWVR777** [comment]
darn i gotta wait a day

**Comment by AWVR777** [comment]
can you just email the files containing the necessary thing for 2.204 to convert without using steam

**Comment by RoootTheFox** [comment]
Add to cart > View cart > Continue to payment > Enter your payment details > Continue > follow instructions

hope that helps!

**Comment by AWVR777** [comment]
cant use steam at all.

**Comment by qimiko** [comment]
this sounds suspiciously like not a geode bug

**Comment by AWVR777** [comment]
bruh

**Comment by hiimjustin000** [comment]
Are you region locked or you just can't pay?

**Comment by AWVR777** [comment]
dont have money

**Comment by AWVR777** [comment]
but i have the game

**Comment by AWVR777** [comment]
also doing this on a school laptop  (i emailed myself gd for pc)

**Comment by AWVR777** [comment]
so steam website is blocked

**Comment by AWVR777** [comment]
ima just wait until i can use my phone again

**Comment by AWVR777** [comment]
see if that works

**Comment by RoootTheFox** [comment]
my guy github is not a chat platform or a personal notebook where you can talk to yourself 😭

**Comment by elnexreal** [comment]
lmao tf is this

**Comment by AWVR777** [comment]
the thread is closed stop comments
