### ISSUE TITLE
Add an "update all" button

### ISSUE THREAD

**Issue by Kevin11git** [geode-sdk/geode#668]
### Geode Version

v2.0.0-BETA.23

### Related Problem

it's annoying when I get a lot of updates to mods and I have to update them one by one, so why not add an update all button that updates every mod that has one.

### Your Solution

Just add an "Update all" button in the mods section similar to how the modrinth launcher has one
![image](https://github.com/geode-sdk/geode/assets/90834642/c654d05e-f7fb-406d-b0a2-6370703aa8c8)

**Comment by qimiko** [comment]
see also: #620 #559 #523 

but yes, this is coming soon (tm)
https://twitter.com/geode_sdk/status/1772932163513545204
