### ISSUE TITLE
Can I install Geode alongside another mod-loader (say, QuickLDR)?

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#67]
### Your Question

(sorry if this question has been answered somewhere. I know that Geode doesn't support traditional mods, but I'm not sure about mod-loaders)

Hello Geode team (mostly HJfod, ig)! I am thinking about building a new Geometry Dash mod. On the one side, Geode makes development wayyy easier compared to traditional methods. But on the other side, my problem lies that if Geode isn't compatible with other mod-loaders, then I wouldn't be getting the same amount of users I would be getting using a traditional method.

So, can I/my potential users of my mod use/install another mod-loader alongside Geode? Again, sorry if this answered somewhere in an FAQ somewhere. If you can't use another mod-loader alongside Geode, what's the reason?

**Comment by poweredbypie** [comment]
I'm fairly certain this has been answered in the Geode server somewhere, but no. Without heavy modification, you can't use Geode alongside another modloader. This is intentional because we want to unify the modding scene so that everyone can develop on the same platform.

**Comment by TechStudent10** [comment]
Hm okay.


Do you see any point in developing a Geode mod now if it breaks compatibility with other mod loaders?

**Comment by poweredbypie** [comment]
Yes, of course. You can be one of the first to contribute to the future of GD modding and indirectly spread the word! Most users aren't extremely fixed on using a certain mod loader yet, after all!

**Comment by HJfod** [comment]
The reason Geode doesn't have users right now is because it doesn't have any mods, which of course can be helped by making mods for it :)

If you'd be interested in reading a more detailed explanation as to why Geode won't support other modloaders, [we have a dedicated page for that in our docs](https://geode-sdk.github.io/docs/#/docs/info/whatisgeode?id=what-about-non-geode-mods)

**Comment by TechStudent10** [comment]
> Yes, of course. You can be one of the first to contribute to the future of GD modding and indirectly spread the word! Most users aren't extremely fixed on using a certain mod loader yet, after all!

Ah alright.

> The reason Geode doesn't have users right now is because it doesn't have any mods, which of course can be helped by making mods for it :)

Yeah that totally makes sense. I'm thinking about making a sort-of Geode marketplace kind of thing where mod makers can upload their Geode mods and users can download them, for free of course.

**Comment by TechStudent10** [comment]
Well that answers my question. Thanks guys!

**Comment by HJfod** [comment]
> Yeah that totally makes sense. I'm thinking about making a sort-of Geode marketplace kind of thing where mod makers can upload their Geode mods and users can download them, for free of course.

We have a ready-made solution for this already, the [mods repo](https://github.com/geode-sdk/mods). Any Geode modder can publish their mods there, and users can install them in-game :)

**Comment by TechStudent10** [comment]
> > Yeah that totally makes sense. I'm thinking about making a sort-of Geode marketplace kind of thing where mod makers can upload their Geode mods and users can download them, for free of course.
> 
> We have a ready-made solution for this already, the [mods repo](https://github.com/geode-sdk/mods). Any Geode modder can publish their mods there, and users can install them in-game :)

Ah okay
