### ISSUE TITLE
geode question

### ISSUE THREAD

**Issue by rubiidev18alt** [geode-sdk/geode#671]
### Your Question

How can I modify the android geode apk to have it install geode somewhere else/on a gdps? I'm currently want to put it on geekrus gdps 
(package:com.mathieu.geekrusgdps0 Launcher:com.mathieu.geekrusgdps0.GeometryJump)
AND make a clone of the geode 32 bit android apk for that gdps. (if it's possible, you can do it, I'm lazy.)

**Comment by qimiko** [comment]
not a geode issue unfortunately
