### ISSUE TITLE
mods not showing up

### ISSUE THREAD

**Issue by cartoonistgamer** [geode-sdk/geode#672]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Expected Behavior

i expected new mods to load after it was done loading new mods

### Actual Behavior

no mods showed up because the loading wasn't finished?

### Steps to Reproduce

i waited and went to my already installed mods and then went back & no mods showed up.

**Comment by altalk23** [comment]
your internet is bad so close and reopen, and new index should change that as well
