### ISSUE TITLE
Game crashes when on download mods/featured mods menu

### ISSUE THREAD

**Issue by Transmissionn** [geode-sdk/geode#676]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.23

### Steps to Reproduce

Go onto the geode menu, click on download or featured tab so that it starts loading, when it gets to 100% the game crashes. If I exit the menu before it reaches 100%, nothing happens and when I go back it just restarts the download.
![image](https://github.com/geode-sdk/geode/assets/90855674/c7b7a9ea-0565-43e1-9125-acd401f2f21f)

### Crash Report

https://gist.github.com/Transmissionn/a9645a725c58f08e236573ddd3e38512

### Additional Information

This happens whether I have mods installed, disabled, or removed completely. I've tried reinstalling both GD and geode and it still happens. The first case I could find of me getting this crash was on the 21st March 2024, and its been happening ever since.

**Comment by altalk23** [comment]
this looks like youre missing some resources
go verify the files from steam and try it again

**Comment by Transmissionn** [comment]
Just verified resources and it still happens. Logs are here: https://gist.github.com/Transmissionn/68b6cff27be2a7b4cf961afac034f639
I put my installed mods back into the folder since last time but the actual crash popup says the same thing as before so I don't think it should make a difference.
Do you know what specifically is missing, and if I can reinstall it manually? As it could just be steam verifying isn't working for some reason.

**Comment by Transmissionn** [comment]
Found the issue, somehow every folder in \geode\index\v0\geode-sdk-mods-fd1eb60\mods-v2 got corrupted so it was impossible to edit/delete them. I renamed the geometry dash folder and reinstalled and it works again, not sure what caused that to happen as nothing else in my files is corrupted but its fine now.
