### ISSUE TITLE
Impossible to launch geode on latest nightly ver. (even with safe mode enabled)

### ISSUE THREAD

**Issue by HotKentang** [geode-sdk/geode#682]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

Nightly-a84d49a

### Steps to Reproduce

Step 1. Open & launch geode on android64
Done

### Crash Report

[Crash 2024-04-11 07.03.59.dmp](https://github.com/geode-sdk/geode/files/14939077/Crash.2024-04-11.07.03.59.dmp)

### Additional Information

This is me getting that crash & trying to see if the crash still works if I launch geode with safe mode on

https://github.com/geode-sdk/geode/assets/161263883/ed6ccef4-0576-49a5-ae90-44567be4f74e

**Comment by dankmeme01** [comment]
Can you try again on the latest nightly and confirm whether this still happens or not? We have 2 ideas as to what could cause it and we tried to fix the 1st cause, so it would be great to know if that helped at all.

**Comment by HotKentang** [comment]
> Can you try again on the latest nightly and confirm whether this still happens or not? We have 2 ideas as to what could cause it and we tried to fix the 1st cause, so it would be great to know if that helped at all.

Unfortunately, it still happened as you can see in the video. It usually works before these updates in question btw

(*Yes I have updated my geode nightly to the latest ver.*)


https://github.com/geode-sdk/geode/assets/161263883/62b80889-557f-47ba-b954-1a83d53fca26

**Comment by HotKentang** [comment]
For now I had just revert back into using the non-nightly version of geode and it worked, idk what causes it but idk if other players have experienced this kinda stuff too.


https://github.com/geode-sdk/geode/assets/161263883/08638e5a-5ef8-4145-b457-eec82c2fa53a

**Comment by altalk23** [comment]
can you try again in like 10 minutes when the next nightly releases?

**Comment by HotKentang** [comment]
> can you try again in like 10 minutes when the next nightly releases?

I was sleeping when responding to that sorry lol, anyway ty for releasing the new nightly version but it didn't work again rip. Mb for responding an hour later i'm such a busy mf.


https://github.com/geode-sdk/geode/assets/161263883/14365fa1-f300-4b6a-859d-80c89856e36a

[Crash 2024-04-11 20.06.50.dmp](https://github.com/geode-sdk/geode/files/14946524/Crash.2024-04-11.20.06.50.dmp)

**Comment by HotKentang** [comment]
oh no
[Crash 2024-04-12 07.31.33.dmp](https://github.com/geode-sdk/geode/files/14952643/Crash.2024-04-12.07.31.33.dmp)

https://github.com/geode-sdk/geode/assets/161263883/dc7ce640-03e1-47d2-b168-91be4f6ac19a

(ig i'll just using the non-nightly ver. for now)
