### ISSUE TITLE
Multiple android geode copies for gdps's that launch a modified gd based on gd package name in a option

### ISSUE THREAD

**Issue by rubiidev18alt** [geode-sdk/geode#683]
### Geode Version

nightly a84d49a

### Related Problem

For this question: How can I modify the android geode apk to have it install geode somewhere else/on a gdps? I'm currently want to put it on geekrus gdps
(package:com.mathieu.geekrusgdps0 Launcher:com.mathieu.geekrusgdps0.GeometryJump)
AND make a clone of the geode 32 bit android apk for that gdps. (if it's possible, you can do it, I'm lazy.)

### Your Solution

try to modify the 32 bit apk to act like the question. it might be a bit complicated

### Additional Information

idk

**Comment by rubiidev18alt** [comment]
> Supporting GDPSes isn't a priority right now, sadly. We are open to contributions though :)

oh alrighty, thanks for the reply! hope you can do this in the future!

**Comment by qimiko** [comment]
this is more relevant for [the launcher](https://github.com/geode-sdk/android-launcher), but there's currently no plans for this functionality

what _might_ happen is a way to have multiple profiles and then you just use some mod to switch the gd base url. hopefully coming at some point
