### ISSUE TITLE
Rarely crashing whenever I die

### ISSUE THREAD

**Issue by Rust-NeoShiny** [geode-sdk/geode#692]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

x | [v1.0.5] abb2k.backup
x | [v1.1.3] adam_729.deathmarkers
x | [v1.1.2] adyagd.godlikefaces
  | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.8.0] beat.click-sound
x | [v1.0.4] bitz.moregames
x | [v1.0.2] blueblock6.cleanstartpos
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.4] capeling.soggy-mod
x | [v1.0.3] cdc.level_thumbnails
x | [v1.0.2] colon.gold_user_coins
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.7] cvolton.betterinfo
x | [v1.1.2] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.5.0] egg.icon_hack
  | [v1.3.1] elsai.a_daily_shop
x | [v1.0.1] elsai.easing_preview
x | [v1.0.3] firee.GoldenBest
x | [v2.7.1] fleym.nongd
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.23] geode.loader
x | [v1.8.1] geode.node-ids
x | [v1.1.0] grian.art_importer
x | [v1.4.4] hiimjustin000.integrated_demonlist
x | [v6.3.3] hjfod.betteredit
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.1] jojo989.geometwy_dash
x | [v1.0.3] kart.heartattack
x | [v1.3.1] m336.levelinfo
x | [v1.1.3] mat.circle-tool
x | [v1.0.2] mat.run-info
  | [v1.0.1] n.friends
x | [v1.0.4] n.level_pronouns
x | [v2.2.2] prevter.openhack
x | [v1.1.0] raydeeux.disturbingnewbests
x | [v1.1.1] raydeeux.wholesomeendtexts
x | [v1.2.8] shineua.minecraft_splash
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v1.0.8] syzzi.click_between_frames
x | [v2024.229.0] tastyforreal.google-translate
x | [v1.0.0-beta.7] thesillydoggo.comment_emojis
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.0.0] uproxide.accupracatt
x | [v1.1.0] uproxide.more_difficulties
x | [v1.0.1] viper.guwude
x | [v1.0.2] weebify.congregation_jumpscare
x | [v1.3.1] weebify.jumpscare
x | [v1.0.3] xanii.flashlight
x | [v1.0.0] xanii.super_expert
x | [v1.5.4] zilko.xdbot

### Steps to Reproduce

Crash in either normal or practice mode, its about a 0.7-ish percent chance, or around every 150 attempts

### Crash Report

https://docs.google.com/document/d/1KP__s3ii9Q6_Hfj5E3uV1Xfedsq1AaUenweyU1x5d14/edit?usp=sharing

### Additional Information

I doubt this is caused by mods due to the fact this has been happening ever since i installed geode, when i had maybe, 10 mods. The frequency has not changed either at all.

**Comment by Alphalaneous** [comment]
Jumpscare mod
