### ISSUE TITLE
Cannot touch

### ISSUE THREAD

**Issue by rocholojavinar** [geode-sdk/geode#697]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### SDK commit

c3c72df

### Geode Version

v2.0.0-beta.24

### Mods Installed

fleym.nongd v2.7.1, relative.advanced_song_search v1.0.1, TheSillyDoggo.Cheats v1.3.5

### Expected Behavior

Expected to produce can't touch by consuming QOLMod.

### Actual Behavior

Produced one mod but I can't touch.

### Steps to Reproduce

1) I can't touch!

### Additional Information

This is likely caused by "Can't touch" because bug

**Comment by dankmeme01** [comment]
don't entirely understand the issue, but it is probably the fault of QOLMod, not Geode.
