### ISSUE TITLE
My game doesn't work

### ISSUE THREAD

**Issue by ZebeANomalies** [geode-sdk/geode#699]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

[v1.3.7] dankmeme.globed2
[v0.0.3] flafy.autonong
[v2.7.1] fleym.nongd
[v1.5.2] geode.custom-keybinds
[v2.0.0-beta.24] geode.loader
[v1.9.1] geode.node-ids
[v1.0.9] syzzi.click_between_frames
[v1.1.2] TheSillyDoggo.StartposSwitcher
[v1.6.8] tpdea.betterpause-Better

### Steps to Reproduce

I entered the game but it doesn't work and gives me this
![스크린샷 2024-04-16 233939](https://github.com/geode-sdk/geode/assets/161597189/e3e8f652-6aaa-4771-a68a-f36f331f96aa)

### Crash Report

crashlogs

2024-04-17T23:20:13+0900
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.24
Loader Commit: d7c3d4a
Bindings Commit: 3ba1039
Installed mods: 9
Problems: 0

== Exception Information ==
C++ Exception: class std::system_error("대상 멀티바이트 코드페이지에 유니코드 문자의 매핑이 없습니다.")
Faulty Mod: <Unknown>
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 1498b2 (RaiseException + 98)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 7e96 (CxxThrowException + 102)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 3c91 (jukebox::setActiveSong + 11233)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 197ef (jukebox::setActiveSong + 100159)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 1d9e6 (jukebox::setActiveSong + 117046)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 17c65 (jukebox::setActiveSong + 93109)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 9b57 (jukebox::setActiveSong + 35495)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\fleym.nongd\fleym.nongd.dll + 18034 (jukebox::setActiveSong + 94084)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5f373 (geode::DefaultEventListenerPool::handle + 67)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 9d406 (geode::log::vlogImpl + 278)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 905e6 (geode::Loader::getLaunchFlag + 33238)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 905f4 (geode::Loader::getLaunchFlag + 33252)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 94ce2 (geode::Loader::getLaunchFlag + 51410)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 9391f (geode::Loader::getLaunchFlag + 46351)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 503e2 (geode::SettingValueSetter<bool>::operator= + 35282)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 1754a4 (geode::stl::operatorDelete + 2420)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 6be3b (RtlInitializeExceptionChain + 107)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bdbf (RtlClearBits + 191)

== Register States ==
EAX: 010fefd0
EBX: 19930520
ECX: 00000003
EDX: 00000000
EBP: 010ff02c
ESP: 010fefd0
EDI: 56e15cc4
ESI: 010ff070
EIP: 76f298b2

== Installed Mods ==
~ | [v1.3.7] dankmeme.globed2
~ | [v0.0.3] flafy.autonong
o | [v2.7.1] fleym.nongd
~ | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.24] geode.loader
x | [v1.9.1] geode.node-ids
~ | [v1.0.9] syzzi.click_between_frames
~ | [v1.1.2] TheSillyDoggo.StartposSwitcher
x | [v1.6.8] tpdea.betterpause-Better

latest log

23:20:10 INFO  [Main] [Geode]: Running Geode v2.0.0-beta.24 in Geometry Dash v2.204
23:20:10 INFO  [Main] [Geode]: Setting up internal mod
23:20:10 INFO  [Main] [Geode]: Setting up loader
23:20:10 DEBUG [Main] [Geode]:   Loading launch arguments
23:20:10 DEBUG [Main] [Geode]:   Setting up crash handler
23:20:10 DEBUG [Main] [Geode]:   Loading hooks
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::fullPathForFilename hook at 0x5c0d0f40 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::sharedFileUtils hook at 0x5c0d9770 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCMenuItem::activate hook at 0x5c0be1e0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCMenu::ccTouchEnded hook at 0x5c0bd260 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled FMOD::System::init hook at 0x5bdd2530 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled FMOD::ChannelControl::setVolume hook at 0x5bd4b180 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::getUserObject hook at 0x5c1231f0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::setUserObject hook at 0x5c0715a0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled LevelPage::onPlay hook at 0x72c080 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled LoadingLayer::init hook at 0x736370 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x736bd0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled MenuLayer::init hook at 0x73b450 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled ProfilePage::getUserInfoFinished hook at 0x7b1db0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled AchievementNotifier::willSwitchToScene hook at 0x4dc200 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled AppDelegate::trySaveGame hook at 0x51b790 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled cocos2d::CCScheduler::update hook at 0x5c116db0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled CCTextInputNode::ccTouchBegan hook at 0x4f04f0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x736bd0 for geode.loader
23:20:10 DEBUG [Main] [Geode]:   Setting up directories
23:20:10 INFO  [Main] [Geode]:   Refreshing mod graph
23:20:10 DEBUG [Main] [Geode]:     Queueing mods
23:20:10 DEBUG [Main] [Geode]:       Searching C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\mods
23:20:10 DEBUG [Main] [Geode]:         Found dankmeme.globed2.geode
23:20:10 DEBUG [Main] [Geode]:           id: dankmeme.globed2
23:20:10 DEBUG [Main] [Geode]:           version: v1.3.7
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found flafy.autonong.geode
23:20:10 WARN  [Main] [Geode]:           dependencies.0 contains unknown key "required"
23:20:10 DEBUG [Main] [Geode]:           id: flafy.autonong
23:20:10 DEBUG [Main] [Geode]:           version: v0.0.3
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found fleym.nongd.geode
23:20:10 DEBUG [Main] [Geode]:           id: fleym.nongd
23:20:10 DEBUG [Main] [Geode]:           version: v2.7.1
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found geode.custom-keybinds.geode
23:20:10 DEBUG [Main] [Geode]:           id: geode.custom-keybinds
23:20:10 DEBUG [Main] [Geode]:           version: v1.5.2
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found geode.node-ids.geode
23:20:10 DEBUG [Main] [Geode]:           id: geode.node-ids
23:20:10 DEBUG [Main] [Geode]:           version: v1.9.1
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found syzzi.click_between_frames.geode
23:20:10 DEBUG [Main] [Geode]:           id: syzzi.click_between_frames
23:20:10 DEBUG [Main] [Geode]:           version: v1.0.9
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found TheSillyDoggo.StartposSwitcher.geode
23:20:10 DEBUG [Main] [Geode]:           id: TheSillyDoggo.StartposSwitcher
23:20:10 DEBUG [Main] [Geode]:           version: v1.1.2
23:20:10 DEBUG [Main] [Geode]:           early: no
23:20:10 DEBUG [Main] [Geode]:         Found tpdea.betterpause-Better.geode
23:20:10 DEBUG [Main] [Geode]:           id: tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:           version: v1.6.8
23:20:10 DEBUG [Main] [Geode]:           early: yes
23:20:10 DEBUG [Main] [Geode]:     Populating mod list
23:20:10 DEBUG [Main] [Geode]:       dankmeme.globed2 v1.3.7
23:20:10 DEBUG [Main] [Geode]:       flafy.autonong v0.0.3
23:20:10 DEBUG [Main] [Geode]:       fleym.nongd v2.7.1
23:20:10 DEBUG [Main] [Geode]:       geode.custom-keybinds v1.5.2
23:20:10 DEBUG [Main] [Geode]:       geode.node-ids v1.9.1
23:20:10 DEBUG [Main] [Geode]:       syzzi.click_between_frames v1.0.9
23:20:10 DEBUG [Main] [Geode]:       TheSillyDoggo.StartposSwitcher v1.1.2
23:20:10 DEBUG [Main] [Geode]:       tpdea.betterpause-Better v1.6.8
23:20:10 DEBUG [Main] [Geode]:     Building mod graph
23:20:10 DEBUG [Main] [Geode]:       geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:       fleym.nongd
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:       geode.loader
23:20:10 DEBUG [Main] [Geode]:       tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:         geode.node-ids
23:20:10 DEBUG [Main] [Geode]:       dankmeme.globed2
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:         geode.custom-keybinds
23:20:10 DEBUG [Main] [Geode]:       flafy.autonong
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:         fleym.nongd
23:20:10 DEBUG [Main] [Geode]:       TheSillyDoggo.StartposSwitcher
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:       syzzi.click_between_frames
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:         geode.custom-keybinds
23:20:10 DEBUG [Main] [Geode]:       geode.custom-keybinds
23:20:10 DEBUG [Main] [Geode]:         geode.loader
23:20:10 DEBUG [Main] [Geode]:     Loading early mods
23:20:10 DEBUG [Main] [Geode]:       geode.node-ids v1.9.1
23:20:10 DEBUG [Main] [Geode]:         Unzip
23:20:10 DEBUG [Main] [Geode]:         Same hash detected, skipping unzip
23:20:10 DEBUG [Main] [Geode]:         Load
23:20:10 DEBUG [Main] [Geode]:         Loading binary for mod geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled ChallengeNode::init hook at 0x51db30 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled ChallengesPage::createChallengeNode hook at 0x51d190 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled ChallengesPage::init hook at 0x51c560 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled CharacterColorPage::init hook at 0x51ea50 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled CommentCell::loadFromComment hook at 0x544490 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled CreatorLayer::init hook at 0x52f550 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled CustomizeObjectLayer::init hook at 0x5364a0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled CustomizeObjectLayer::toggleVisible hook at 0x539780 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled DailyLevelNode::init hook at 0x5596c0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled DailyLevelPage::init hook at 0x5576d0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled EditLevelLayer::init hook at 0x55c8e0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled EditorPauseLayer::init hook at 0x560020 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled EditorUI::init hook at 0x564260 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled EndLevelLayer::customSetup hook at 0x5a74f0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled EndLevelLayer::showLayer hook at 0x5a8c20 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled FLAlertLayer::init hook at 0x4f0f60 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJCommentListLayer::create hook at 0x6c7dc0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJDropDownLayer::init hook at 0x696700 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJGarageLayer::init hook at 0x6af250 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJGarageLayer::setupPage hook at 0x6b1d70 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJListLayer::create hook at 0x6b8930 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GJScoreCell::loadFromScore hook at 0x5465b0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GameToolbox::addBackButton hook at 0x501910 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GameToolbox::addRThumbScrollButton hook at 0x5019c0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GauntletNode::init hook at 0x648740 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GauntletSelectLayer::init hook at 0x646cf0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled GauntletSelectLayer::setupGauntlets hook at 0x647b90 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled InfoLayer::init hook at 0x6e8810 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled InfoLayer::setupCommentsBrowser hook at 0x6eb670 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LeaderboardsLayer::init hook at 0x6edc60 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelAreaInnerLayer::init hook at 0x6f11e0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelBrowserLayer::init hook at 0x6f2e60 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelCell::loadCustomLevelCell hook at 0x53da60 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelCell::loadFromLevel hook at 0x53d8b0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelCell::loadLocalLevelCell hook at 0x5404d0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelEditorLayer::init hook at 0x6f9a70 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelInfoLayer::init hook at 0x7116a0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelInfoLayer::setupPlatformerStats hook at 0x713a90 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelInfoLayer::setupProgressBars hook at 0x713e20 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelInfoLayer::updateLabelValues hook at 0x716d20 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelLeaderboard::init hook at 0x718060 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelPage::create hook at 0x728f30 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelPage::updateDynamicPage hook at 0x729a80 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelSearchLayer::init hook at 0x720f10 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled LevelSelectLayer::init hook at 0x727d00 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled MoreOptionsLayer::init hook at 0x771630 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled OptionsLayer::customSetup hook at 0x7702d0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::customSetup hook at 0x7789f0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::init hook at 0x79c4a0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::setupHasCompleted hook at 0x79ce40 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayerObject::init hook at 0x7824c0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled ProfilePage::init hook at 0x7ad080 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled ProfilePage::loadPageFromUserInfo hook at 0x7adda0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled RewardsPage::init hook at 0x7b67f0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled SecretRewardsLayer::init hook at 0x7bb6b0 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled SetGroupIDLayer::init hook at 0x7d0d80 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:         Enabled UILayer::init hook at 0x87ec10 for geode.node-ids
23:20:10 DEBUG [Main] [Geode]:       tpdea.betterpause-Better v1.6.8
23:20:10 DEBUG [Main] [Geode]:         Unzip
23:20:10 DEBUG [Main] [Geode]:         Same hash detected, skipping unzip
23:20:10 DEBUG [Main] [Geode]:         Load
23:20:10 DEBUG [Main] [Geode]:         Loading binary for mod tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::create hook at 0x778940 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::keyDown hook at 0x77a310 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onEdit hook at 0x77a020 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onNormalMode hook at 0x779ed0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onPracticeMode hook at 0x779e60 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onRestart hook at 0x779f80 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onRestartFull hook at 0x779fd0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::onResume hook at 0x779f30 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PauseLayer::tryQuit hook at 0x77a170 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::addObject hook at 0x7a19b0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::init hook at 0x79c4a0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::levelComplete hook at 0x79db60 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled PlayLayer::showNewBest hook at 0x79edc0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled GJBaseGameLayer::update hook at 0x67b780 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled MoreOptionsLayer::addToggle hook at 0x7725f0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled GameOptionsLayer::create hook at 0x6d3050 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled GJOptionsLayer::addToggleInternal hook at 0x6c6350 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled GJOptionsLayer::init hook at 0x6c5f80 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CustomSongWidget::updateSongInfo hook at 0x554b80 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CustomSongWidget::updateSongObject hook at 0x554280 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CCScrollLayerExt::ccTouchCancelled hook at 0x4e83e0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CCScrollLayerExt::ccTouchEnded hook at 0x4e81c0 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CCScrollLayerExt::ccTouchMoved hook at 0x4e8410 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled CCScrollLayerExt::scrollLayer hook at 0x4e8550 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled InfoLayer::onClose hook at 0x6eb200 for tpdea.betterpause-Better
23:20:10 DEBUG [Main] [Geode]:         Enabled GJGameLevel::savePercentage hook at 0x5d3d70 for tpdea.betterpause-Better
23:20:10 INFO  [Main] [Geode]:     Took 0.072s. Continuing next frame...
23:20:10 DEBUG [Main] [Geode]: Setting up IPC
23:20:10 DEBUG [Main] [Geode]:   IPC set up
23:20:10 INFO  [Main] [Geode]: Starting loader update check
23:20:10 INFO  [Main] [Geode]: Entry took 0.092s
23:20:13 INFO  [Main] [Geode]: Continuing mod graph refresh...
23:20:13 DEBUG [Main] [Geode]:   Loading mods
23:20:13 DEBUG [Main] [Geode]:     tpdea.betterpause-Better v1.6.8
23:20:13 INFO  [Main] [Geode]: Continuing mod graph refresh...
23:20:13 DEBUG [Main] [Geode]:   Loading mods
23:20:13 DEBUG [Main] [Geode]:     fleym.nongd v2.7.1
23:20:13 DEBUG [Mod Unzip] [Geode]:  Unzip
23:20:13 DEBUG [Mod Unzip] [Geode]:  Same hash detected, skipping unzip
23:20:13 DEBUG [Main] [Geode]:       Load
23:20:13 DEBUG [Main] [Geode]:       Loading binary for mod fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled CustomSongWidget::init hook at 0x552c20 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled CustomSongWidget::updateMultiAssetInfo hook at 0x555a60 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled CustomSongWidget::updateSongInfo hook at 0x554b80 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled CustomSongWidget::updateSongObject hook at 0x554280 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled CustomSongWidget::updateWithMultiAssets hook at 0x5556f0 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled LevelInfoLayer::init hook at 0x7116a0 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled MenuLayer::init hook at 0x73b450 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled MusicDownloadManager::getSongInfoObject hook at 0x743cb0 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled MusicDownloadManager::onGetSongInfoCompleted hook at 0x742d00 for fleym.nongd
23:20:13 DEBUG [Main] [Geode]:       Enabled MusicDownloadManager::pathForSong hook at 0x744070 for fleym.nongd

### Additional Information

The Korean one says "The target multicom code page does not have a unique code indication."

**Comment by RayDeeUx** [comment]
update your jukebox mod
