### ISSUE TITLE
controller movement not workin

### ISSUE THREAD

**Issue by d0re0** [geode-sdk/geode#703]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Mods Installed

custom keybinds

### Expected Behavior

the controller movement buttons to work

### Actual Behavior

they dont actually work

### Steps to Reproduce

use a controller

**Comment by matcool** [comment]
stale, reopen if needed
