### ISSUE TITLE
Crashing Caused by QOLmod 1.3.8 Update

### ISSUE THREAD

**Issue by LuckAbsence13** [geode-sdk/geode#716]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.25

### Mods Installed

QOLmod v1.3.8 

### Steps to Reproduce

1) Opening any level in the "Create" section, exiting out of it, and the game immediately crashes upon opening the level again. 
2) Opening any level in general or via the editor (by pressing "Save and play") causes the game to crash instantaneously, but only on condition that there is a hack from the mod enabled. 

### Crash Report

[Crash 2024-04-23 15.03.01.dmp](https://github.com/geode-sdk/geode/files/15076945/Crash.2024-04-23.15.03.01.dmp)
[Crash 2024-04-23 15.02.01.dmp](https://github.com/geode-sdk/geode/files/15076946/Crash.2024-04-23.15.02.01.dmp)
[Crash 2024-04-23 14.58.37.dmp](https://github.com/geode-sdk/geode/files/15076947/Crash.2024-04-23.14.58.37.dmp)
[Crash 2024-04-23 14.58.17.dmp](https://github.com/geode-sdk/geode/files/15076948/Crash.2024-04-23.14.58.17.dmp)

### Additional Information

I am highly convinced that this bug was very likely, if not certainly, caused by some type of error that had come along with the new QOLmod update, which was launched just recently. I assume so because, prior to the update, the bug or any other bugs of similar nature never occured for me; it is only after the update that I started experiencing this issue. I would be extremely grateful if you fixed the aforesaid bug as soon as possible.

**Comment by RoootTheFox** [comment]
This is *not* a Geode issue - read the checkbox that you ticked. This is an issue with QOLMod, not Geode. Apart from that; QOLMod got updated a few minutes ago, you might wanna check if that update fixes your crash.
