### ISSUE TITLE
Crashed while opening

### ISSUE THREAD

**Issue by rocholojavinar** [geode-sdk/geode#717]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

v2.0.0-beta.24

### Mods Installed

fleym.nongd v2.7.1, relative.advanced_song_search v1.0.1, TheSillyDoggo.Cheats v1.3.8

### Steps to Reproduce

1) I did crashed while pressed the play button

**Comment by Fleeym** [comment]
Cam you send your latest crashlog? You can find it in Android/media/com.geode.launcher/game/crashlogs
