### ISSUE TITLE
Bro why crash

### ISSUE THREAD

**Issue by HuuVuong0912** [geode-sdk/geode#720]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

all the mods

### Steps to Reproduce

I restart my game after beating a level

### Crash Report

wth

### Additional Information

BRO PLS FIX

**Comment by Alphalaneous** [comment]
Please actually list the mods, secondly, please send a crash report. No one can help you without this information. This is likely a mod causing the crash and not Geode itself. If you are to send the information asked of you, help would be given.

**Comment by iristraa** [comment]
wait this guy is vietnamese lemme translate it

@HuuVuong0912 ông ơi, game crash thì ông cho tui xin danh sách mod của ông nha, gửi thêm cái crash log nữa (gửi file mới nhất nha ông)
![image](https://github.com/geode-sdk/geode/assets/84076556/bea010a7-7495-438e-80e6-6bf6c1abba96)
