### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SEBASPRO666** [geode-sdk/geode#722]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### SDK commit

Si

### Geode Version

Si

### Mods Installed

Papalota

### Expected Behavior

Naaaaa

### Actual Behavior

No se

### Steps to Reproduce

Hice1

### Additional Information

Jajs

**Comment by RayDeeUx** [comment]
as a macos user i can confirm that i cannot reproduce the issue sebaspro666 is experiencing
