### ISSUE TITLE
Installer Bugs for Geometry Dash version 2.2

### ISSUE THREAD

**Issue by Ramses610** [geode-sdk/geode#733]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v.2.0.0-beta.25

### Mods Installed

BetterEdit v6.3.3, Click Between Frames v1.0.9, Globed v1.3.7

### Expected Behavior

The mods will work as they normally do.

### Actual Behavior

The mods show an error sign, and do not work.

### Steps to Reproduce

I started up Geometry Dash, and the mods showed that there were some errors.

### Additional Information

I do not know how this was caused, there were no mods that needed to be updated, and i haven't done anything weird on the game. I just started up the game.

**Comment by TheSillyDoggo** [comment]
You have to install the mods these mods depend on so get node ids and custom keybinds
