### ISSUE TITLE
Zoink texture pack prevents loader from working 

### ISSUE THREAD

**Issue by Nukey2** [geode-sdk/geode#734]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

V2.0.0.beta.25

### Steps to Reproduce

I was using an texture pack for the original game and then geode loader codes doesn't match with the main game

### Additional Information

This is caused by zoink texture pack

**Comment by heavyutils** [comment]
Has nothing to do with geode. Invalid spritesheets WILL ALWAYS crash the game.

**Comment by cursefroge** [comment]
In addition to @heavyutils's comment, please attach a crash report in the future.
