### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Kar182004** [geode-sdk/geode#735]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Steps to Reproduce

i installed a lot of mods

### Crash Report

2024-05-01T20:20:30+0400
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "polsk.ratinginfo" mod. Please submit this crash report to its developers (polsk) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.25
Loader Commit: 20dc3c9
Bindings Commit: 2eb85b0
Installed mods: 24
Problems: 7

== Exception Information ==
Faulty Module: C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\polsk.ratinginfo\polsk.ratinginfo.dll
Faulty Mod: polsk.ratinginfo
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 69523445 (polsk.ratinginfo.dll + 3445)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\polsk.ratinginfo\polsk.ratinginfo.dll + 3445
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\polsk.ratinginfo\polsk.ratinginfo.dll + 2e73
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\m336.levelinfo\m336.levelinfo.dll + 1aeb
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\m336.levelinfo\m336.levelinfo.dll + 1a7f
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\fleym.nongd\fleym.nongd.dll + 14073 (jukebox::setActiveSong + 77763)
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\fleym.nongd\fleym.nongd.dll + 13ef3 (jukebox::setActiveSong + 77379)
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\geode\unzipped\cvolton.misc_bugfixes\cvolton.misc_bugfixes.dll + 21a73
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 2515d7
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + f87df
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 80f4a
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + ae203 (cocos2d::CCMenuItem::activate + 35)
 - C:\Users\LENOVO\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)

== Register States ==
EAX: 0000000f
EBX: 1a11ada0
ECX: 00000000
EDX: 10daf998
EBP: 00cfec08
ESP: 00cfeb58
EDI: 00000000
ESI: 00cfeb58
EIP: 69523445

== Installed Mods ==
  | [v1.1.0] artoree.enhanced_menu
x | [v1.0.4] bitz.moregames
! | [v1.0.4] cdc.level_thumbnails
! | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v2.7.1] fleym.nongd
x | [v1.5.6] geode.custom-keybinds
x | [v2.0.0-beta.25] geode.loader
  | [v1.9.1] geode.node-ids
! | [v6.3.3] hjfod.betteredit
! | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.1.0] itzkiba.grandpa_demon
! | [v1.2.0] khronophobia.more_settings_button
x | [v1.3.2] m336.levelinfo
x | [v1.0.3] mat.run-info
x | [v1.1.0] polsk.ratinginfo
x | [v2.3.0] prevter.openhack
x | [v1.0.9] syzzi.click_between_frames
x | [v1.6.9] thesillydoggo.entersearch
x | [v1.1.2] TheSillyDoggo.StartposSwitcher
! | [v1.0.3] weebify.level_info_in_pause_menu
! | [v1.0.0] xanii.level_ratings

**Comment by Alphalaneous** [comment]
> Faulty Mod: polsk.ratinginfo

Not a geode crash, the rating info mod looks to be causing a crash
