### ISSUE TITLE
creator corrupted

### ISSUE THREAD

**Issue by bigdude153** [geode-sdk/geode#737]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

V2.00beta.25

### Mods Installed

Main level editor

### Expected Behavior

Expected it to show a button to add levels to the main levels

### Actual Behavior

I downloaded the mod and my online levels all said 'killbot easy 2' and had sweet dreams as the song

### Steps to Reproduce

I downloaded the mod and my online levels all said 'killbot easy 2' and had sweet dreams as the song
![Screenshot_20240502-162336_Geode](https://github.com/geode-sdk/geode/assets/168757258/be09902b-9406-4dc8-9dde-4ef3cc4be553)

**Comment by qimiko** [comment]
mod issue! talk to the mod developer
