### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Alex213128** [geode-sdk/geode#738]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0

### Mods Installed

texture loader v1.5.0, UnixSync v1.3.1, Save On Level Page v1.0.0, Node IDs v1.9.1, Globed v1.3.7, GD Mega Overlay v2.10.0, Custom Keybinds v1.5.6, Click Sounds v1.8.0, Click betweens Frames v1.0.9, Better Edit v6.3.3

### Steps to Reproduce

I Was Plaiyng A Level Then After 20 minutes it crashed btw i was in globed

**Comment by YellowCat98** [comment]
the geode loader only loads mods brother 😭😭😭
