### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by YanderYT** [geode-sdk/geode#741]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.25

### Mods Installed

 | [v1.3.7] dankmeme.globed2
 | [v1.5.0] egg.icon_hack
| [v1.0.1] elnexreal.auto_priority
| [v1.5.2] geode.custom-keybinds 
 | [v2.0.0-beta.25] geode.loader
 | [v1.9.1] geode.node-ids
 | [v6.3.5] hjfod.betteredit
 | [v1.0.5] hjfod.gdshare
| [v1.0.5] hjfod.gmd-api
 | [v1.0.0] mat.reference-image
 | [v2.2.2] prevter.openhack

### Steps to Reproduce

So i go to a very big level that i copied in my created levels( which is yangire) Theres 343K objects. If i add a strt position so i can practice in parts,i press save and play and my level is completely gone and when i alt + f4 my geometry dash opens the crash folder cause apparently it crashed.

### Crash Report

[2024-05-05_17-31-33.log](https://github.com/geode-sdk/geode/files/15214643/2024-05-05_17-31-33.log)

### Additional Information

I dont know what causes this.

**Comment by StupidIdiot1033** [comment]
it might be betteredit

**Comment by RB-999** [comment]
Game crashes on my device too. Maybe it is because node ids is not optimized for new Geode version

**Comment by matcool** [comment]
stale, reopen if needed
