### ISSUE TITLE
Official songs and sfx no longer working

### ISSUE THREAD

**Issue by SaltyAutumn** [geode-sdk/geode#742]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

V2.0.0-Beta.25

### Mods Installed

A Daily Shop v1.3.1
Better Info v4.1.10
Better Edit v6.3.5
Better Pause v1.6.8
Better Unlock Info  v1.1.0
Change Font 19 v1.0.0
Clean StartPos v 1.0.2
Emojis in Comments v 1.0.0
Google Translate v2024.229.0
Icon Save 2.2 v1.0.3
Jukebox v2.7.1
Level Thumbnails v1.0.4
Misc Bugfixes v1.1.4
Minecraft Splash v 1.3.1
Node IDs v1.9.1
Prism Menu v1.6.4
Run Info v1.0.3
Soggy Mod v1.0.5
Treasure Checklist v1.2.0

### Expected Behavior

Playing levels that use the official RobTop level songs actually play the songs, entering any room that changes the music such as treasure rooms or shops plays their respective music, dying plays the usual crash noise, pressing play on a level makes the usual noise, warning orbs/stars/keys/etc makes the usual sound, opening a chest makes the usual sound

### Actual Behavior

literally none of those noises are playing. the only sounds my game can make are the menu theme and whatever songs I download from online levels. and there's option to download the RobTop songs either :(

### Steps to Reproduce

im... not sure how to reproduce it.. it just started happening out of nowhere and nothing I've tried has worked to solve the issue! 

### Additional Information

I know it's not a phone issue because when I open default GD it works like usual, but opening Geode presents these issues. I will note that downloaded sfx from levels that use them do also work like usual, while it's the in-game sounds that don't

**Comment by qimiko** [comment]
might be a launcher issue? if you can, would you be able to go into the launcher settings, tap "view application logs" and then press "save to" in the top right menu. and then send the file here
