### ISSUE TITLE
Se me crashea por que estoy en niveles que quiero jugar

### ISSUE THREAD

**Issue by Verdesitopromax** [geode-sdk/geode#743]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

2.0.0 beta 25

### Mods Installed

Tenia 4 mods y se me crasheo de una

### Steps to Reproduce

Fui a jugar un nivel y se me crasheo

### Crash Report

https://github.com/geode-sdk/geode/issues/new?template=crash-report.yml

### Additional Information

En un mod ahí mucho bug y lag y es globed porfa ayuda

**Comment by Oukgd** [comment]
ami me pasa lo mismo tengo muchos mods pero cuando jugar un nivel cualquiera  en medio del nivel se me crashea díganme por qué se crashea
