### ISSUE TITLE
GD crashes when I open the level edit

### ISSUE THREAD

**Issue by therickypro31** [geode-sdk/geode#744]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.25

### Mods Installed

geode.loader v2.0.0-beta25, geode.texture-loader v1.5.0, prevter.openhack v2.3.0

### Steps to Reproduce

1. When i play a level, i press esc key
2. then i  click into the level edit
3. The game crashes

### Crash Report

[2024-05-07_12-20-21.log](https://github.com/geode-sdk/geode/fi
[Geode 2024-03-27 12.54.47.log](https://github.com/geode-sdk/geode/files/15234146/Geode.2024-03-27.12.54.47.log)
les/15234142/2024-05-07_12-20-21.log)

### Additional Information

this is likely caused by some mods but i dont know

**Comment by Gh053d413x** [comment]
I am having the exact same problem, here is my crash issue: https://github.com/geode-sdk/geode/issues/763

**Comment by CRPyR** [comment]
turn off no wave trail pulse

**Comment by matcool** [comment]
stale, reopen if needed
