### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by frenchfrysays3** [geode-sdk/geode#752]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0 beta 26

### Mods Installed

Did not get a chance to check

### Steps to Reproduce

I started up geometry Dash

**Comment by Alphalaneous** [comment]
Firstly, horrible issue report, normally, no one would be able to help you with such little information. But we know GD MegaOverlay had a bug that causes GD to not start. 

Hold shift when launching GD, this will open it in safe mode, then update GD MegaOverlay

**Comment by frenchfrysays3** [comment]
ok thx!

**Comment by enessmr** [comment]
thx

**Comment by enessmr** [comment]
i have this issue tho its modrealated
