### ISSUE TITLE
Renevant

### ISSUE THREAD

**Issue by faisxg** [geode-sdk/geode#753]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Steps to Reproduce

Every time I try loading into the original copy of Renevant specifically, it crashes.

### Crash Report

[Geode 2024-05-10 17.14.43.log](https://github.com/geode-sdk/geode/files/15276701/Geode.2024-05-10.17.14.43.log)
[2024-05-10_17-13-19.log](https://github.com/geode-sdk/geode/files/15276702/2024-05-10_17-13-19.log)

**Comment by faisxg** [comment]
It also crashes when I try to view my deaths through the death tracker mod..

**Comment by dankmeme01** [comment]
it does look like a death tracker issue judging by the crashlog, not a Geode issue.
