### ISSUE TITLE
Crash 10/05/24

### ISSUE THREAD

**Issue by MatthaMMM** [geode-sdk/geode#754]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Mods Installed

~ | [v1.0.5] abb2k.backup
~ | [v1.1.2] adyagd.godlikefaces
~ | [v1.3.3] bigmancozmo.hide_profile_button
~ | [v1.0.4] bitz.moregames
~ | [v1.0.2] blueblock6.cleanstartpos
~ | [v1.0.0] capeling.usable_explorers
~ | [v1.0.4] cdc.level_thumbnails
~ | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
~ | [v1.3.1] elnexreal.copy_song_id
~ | [v1.5.7] geode.custom-keybinds
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
~ | [v6.3.5] hjfod.betteredit
~ | [v1.1.1] itzkiba.formatted_platformer_time
~ | [v1.1.0] itzkiba.grandpa_demon
~ | [v1.2.0] khronophobia.more_settings_button
~ | [v1.1.3] mat.circle-tool
~ | [v1.0.3] mat.run-info
o | [v2.10.0] maxnu.gd_mega_overlay
~ | [v1.0.4] n.level_pronouns
~ | [v1.1.0] raydeeux.camerashadertoggles
~ | [v1.2.0] raydeeux.likebaitexterminator
x | [v1.0.0] raydeeux.nolevelrefresh
~ | [v1.0.1] relative.advanced_song_search
x | [v1.1.0] sofabeddd.colored_icon_kit
~ | [v1.0.3] sofabeddd.geometry_dash
~ | [v1.0.9] syzzi.click_between_frames
~ | [v2.2.4] TheSillyDoggo.GradientPages
~ | [v1.2.0] thesillydoggo.moretags
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.2.2] undefined0.autocheckpoint
~ | [v1.0.0] uproxide.accupracatt
~ | [v1.1.0] uproxide.autosong
~ | [v1.3.0] uproxide.more_difficulties
~ | [v1.1.3] weebify.coins_in_pause_menu
~ | [v1.0.2] xiyxs.confirmpracticerestart

### Steps to Reproduce

I just tried to load Geometry Dash

### Crash Report

[2024-05-10_17-24-41.log](https://github.com/geode-sdk/geode/files/15277545/2024-05-10_17-24-41.log)

**Comment by RayDeeUx** [comment]
hold shift while opening geometry dash to enter safe mode

then update GDMO

**Comment by MatthaMMM** [comment]
> hold shift while opening geometry dash to enter safe mode
> 
> then update GDMO

Does GDMO mean Geometry Dash Mega Overlay?

**Comment by HenrySck075** [comment]
> Does GDMO mean Geometry Dash Mega Overlay?

yes
