### ISSUE TITLE
Typing too fast in the downloads tab causes the game to freeze and become unresponsive

### ISSUE THREAD

**Issue by ItsDaCreeper** [geode-sdk/geode#757]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Expected Behavior

Typing without the game freezing and becoming unresponsive

### Actual Behavior

The game freezes and becomes unresponsive.

### Steps to Reproduce

1) Type fast in the search bar in the download tab
2) If it doesn't freeze the game, try again a few more times
3) The game should freeze and give a blank screen, and you can't tab out (at least in my case). Windows will eventually say the program is not responding, then you can close the game.

### Additional Information

- This also happens if you backspace too quickly as well.
- This happens regardless of having mods installed or not.
- The game doesn't crash, it just stays unresponsive until you close it.

**Comment by NexusSfan** [comment]
For me when I type too fast in "Installed", it completely crashes.

**Comment by matcool** [comment]
stale, reopen if needed
