### ISSUE TITLE
Global Cheat Indicator

### ISSUE THREAD

**Issue by sphericle** [geode-sdk/geode#761]
### Geode Version

2.0.0

### Related Problem

Some mods do not have cheat indicators, making it hard to detect unfair advantages (ex. click between frames)

### Your Solution

Modders could mark settings in their mods as “cheats” and the cheat indicator could appear if any settings marked as cheats are active.

**Comment by RayDeeUx** [comment]
good in concept, poor in practice. there'll always be a loophole (either already there by nature or pried open by brute force) to avoid detection or falsify such results

this is why anticheat detection/disallowed mod detection is always a constant battle for minecraft multiplayer servers—you can easily change mod IDs, edit the raw `.jar` (in this case, `.geode`) binary, or just outright make your own bootleg mod containing the same cheat
