### ISSUE TITLE
Game Crashes when opening editor

### ISSUE THREAD

**Issue by Gh053d413x** [geode-sdk/geode#763]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta.26

### Mods Installed

![image](https://github.com/geode-sdk/geode/assets/100062083/b8dae6f7-3547-4007-8448-ff0287a4f08e)
![image](https://github.com/geode-sdk/geode/assets/100062083/7132f2a4-5a77-4386-9615-6d3dd1104ce8)
![image](https://github.com/geode-sdk/geode/assets/100062083/04769d10-01c6-4086-b089-f836082b8233)
![image](https://github.com/geode-sdk/geode/assets/100062083/6a4ea46b-a49f-402d-ac77-9d4dc7ec05ad)
![image](https://github.com/geode-sdk/geode/assets/100062083/fff4dc76-dbf6-4351-baf9-e818762c7a7f)
![image](https://github.com/geode-sdk/geode/assets/100062083/4f9accc3-753a-440d-868f-04031b791b46)
![image](https://github.com/geode-sdk/geode/assets/100062083/bca00955-3c7b-4b6f-aff3-b3f4806e9716)
![image](https://github.com/geode-sdk/geode/assets/100062083/c1001d0d-7423-4062-8b35-c6d300b67c94)
![image](https://github.com/geode-sdk/geode/assets/100062083/da2cc91b-26bf-46b8-ae63-4752a5660174)
![image](https://github.com/geode-sdk/geode/assets/100062083/3e5622b1-8dca-4a4e-88bf-91d38d8c3d11)
![image](https://github.com/geode-sdk/geode/assets/100062083/9cc4d7be-a338-4b5a-8d72-8db8363c2754)
![image](https://github.com/geode-sdk/geode/assets/100062083/e25c91fa-a170-4189-9d43-79942553ed1c)
![image](https://github.com/geode-sdk/geode/assets/100062083/fb11ddbf-b431-469f-a34a-d6d88edd8998)

### Steps to Reproduce

![image](https://github.com/geode-sdk/geode/assets/100062083/0fb5cbbd-688f-4bd3-a897-0dddec187f77)
![image](https://github.com/geode-sdk/geode/assets/100062083/c7260730-c9d8-4ffc-bdcf-2677c16f2829)
![image](https://github.com/geode-sdk/geode/assets/100062083/d6bf31fd-fdd0-40ab-960a-72fe687bfe0c)
![image](https://github.com/geode-sdk/geode/assets/100062083/d0d777e8-df06-4271-b0f6-e518986fe0aa)
![image](https://github.com/geode-sdk/geode/assets/100062083/52fb5b65-e06f-45a9-8a27-34d0f9e5a371)

### Crash Report

2024-05-13T21:02:42-0600
Why did you do that?

== Geode Information ==
- Working Directory: D:\Programs\Steam\steamapps\common\Geometry Dash
- Loader Version: v2.0.0-beta.26 (Geometry Dash v2.204)
- Loader Commit: 2857ecf
- Bindings Commit: d35e301
- Installed Mods: 57 (Loaded: 52/52)
- 4GB Patch: Patched
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 6120)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: GeometryDash.exe+0x1F7AB3 (GJGroundLayer::updateGround01Color+0x3)
- Exception Flags: 0x0
- Exception Parameters: 0x0, 0x13C
- Access Violation Type: Read
- Access Violation Address: 0x0000013C
- Protect: PAGE_NOACCESS (0x1)
- State: MEM_FREE (0x10000)
- Type: Unknown (0x0)

== Stack Trace ==
- GeometryDash.exe+0x1F7AB3 (GJGroundLayer::updateGround01Color+0x3)
- 0x0FE50E36
- bitz.moregames.dll+0x3E6BE
- Geode.dll+0x3FE300 (tulip::hook::Handler::incrementIndex+0x110)
└ D:\a\geode\geode\cpm-cache\tuliphook\9344f239f71e7949e1a8e23135c8eab0d52b6309\src\Handler.cpp:144
- 0x0F730463
- GeometryDash.exe+0x9BD9A (EditButtonBar::loadFromItems+0x42a)
- GeometryDash.exe+0x9B963 (EditButtonBar::init+0x83)
- GeometryDash.exe+0x9B896 (EditButtonBar::create+0xb6)
- GeometryDash.exe+0xAF471
- GeometryDash.exe+0xA518D (EditorUI::init+0xf2d)
- 0x04A71076
- geode.node-ids.dll+0x26EE1 (<0x26d00>+0x1e1)
- geode.custom-keybinds.dll+0x150D1
- 0x04A70C97
- 0x04A82D7E
- geode.node-ids.dll+0x51AC7 (<0x51960>+0x167)
- raydeeux.moveaudiovisualizer.dll+0x54CD (<0x5470>+0x5d)
- raydeeux.moveaudiovisualizer.dll+0x5333 (<0x51d0>+0x163)
- GeometryDash.exe+0x2399A2 (LevelEditorLayer::scene+0x22)
- libcocos2d.dll+0xAE203 (cocos2d::CCMenuItem::activate+0x23)
- libcocos2d.dll+0xAD27D (cocos2d::CCMenu::ccTouchEnded+0x1d)

== Register States ==
- EAX: 770000CC (SHELL32.dll+0x1200CC (Shell_NotifyIconW+0x6f6c))
- EBX: 00000000 (0i | 0u)
- ECX: 00000000 (0i | 0u)
- EDX: 00000000 (0i | 0u)
- ESI: 22891508 (-> 0xF47)
- EDI: 00000000 (0i | 0u)
- EBP: 00CFE7FC (-> 0xCFE84C -> 0x60257D20 -> Geode.dll+0x87D20 (geode::Loader::takeNextMod+0x0))
- ESP: 00CFE7FC (-> 0xCFE84C -> 0x60257D20 -> Geode.dll+0x87D20 (geode::Loader::takeNextMod+0x0))
- EIP: 00237AB3 (GeometryDash.exe+0x1F7AB3 (GJGroundLayer::updateGround01Color+0x3))
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 0 
- SF: 0 | TF: 0 | ZF: 0 

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.3] adam_729.deathmarkers
x | [v1.2.10] alphalaneous.deathlink
x | [v1.0.4] alphalaneous.hide
  | [v1.0.0] bigmancozmo.skip_editor_save_confirm
x | [v1.0.4] bitz.moregames
x | [v1.0.5] capeling.gamemode_picker
x | [v1.0.1] capeling.hide_main_menu_ui
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.1.3] capeling.main_level_pages
x | [v1.2.1] coopeeo.hideplus
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.2.0-beta.8] dogotrigger.deathreplay
x | [v1.0.3] dogotrigger.level_history
x | [v1.5.0] egg.icon_hack
  | [v1.1.1] ekv.hidePauseMenuHack
x | [v1.3.1] elnexreal.copy_song_id
x | [v1.0.1] elsai.easing_preview
x | [v0.0.3] flafy.autonong
x | [v2.7.1] fleym.nongd
x | [v1.5.7] geode.custom-keybinds
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.2.0] grian.art_importer
  | [v6.3.5] hjfod.betteredit
x | [v1.0.5] hjfod.gmd-api
x | [v1.0.1] hjfod.quick-volume-controls
x | [v1.1.0] iristraa.spinoffsubtitles
x | [v1.1.0] itzkiba.better_progression
x | [v1.1.0] itzkiba.id_hyperlinks
x | [v1.0.0] izzy.i_hate_you_top_lists
x | [v1.2.0] khronophobia.more_settings_button
x | [v1.0.1] mat.max-window
x | [v1.0.0-beta.19] minemaker0430.gddp_integration
  | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.0.0] naxrin.progress_bar_color
x | [v1.0.4] nytelyte.garage_utilities
x | [v1.2.0] prevter.bettercrash
x | [v2.3.0] prevter.openhack
x | [v1.1.0] raydeeux.camerashadertoggles
x | [v1.0.0] raydeeux.moveaudiovisualizer
x | [v1.0.0] riley.nogrounds
x | [v1.1.1] rynat.better_unlock_info
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v1.0.3] sofabeddd.geometry_dash
x | [v0.1.0] sse2.gj-music-manager
x | [v1.0.1] thesillydoggo.dialogue_handler
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.0.0] uproxide.accupracatt
x | [v1.1.0] uproxide.autosong
x | [v1.0.0] user95401.window-name
  | [v1.0.2] viper.gamemode_only
x | [v1.0.1] xiyxs.recolored_music_library_songs
x | [v1.0.0] zilko.literal_level_lengths

== Stack Allocations ==
- 0xCFE7FC: 00CFE84C (-> 0x60257D20 -> Geode.dll+0x87D20 (geode::Loader::takeNextMod+0x0))
- 0xCFE800: 0FE50E36 (0x0FE50E36)
- 0xCFE804: 770000CC (SHELL32.dll+0x1200CC (Shell_NotifyIconW+0x6f6c))
- 0xCFE808: 523159DD (bitz.moregames.dll+0x1B59DD (<0x1b5980>+0x5d))
- 0xCFE80C: 00000000 (0i | 0u)
- 0xCFE810: 770000CC (SHELL32.dll+0x1200CC (Shell_NotifyIconW+0x6f6c))
- 0xCFE814: A2BAE7E0 (2730158048i | 2730158048u)
- 0xCFE818: 00000000 (0i | 0u)
- 0xCFE81C: 1A5B9830 (-> 0x610932F4 -> 0x6101BBC0 -> libcocos2d.dll+0xABBC0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0xCFE820: 1A5B9830 (-> 0x610932F4 -> 0x6101BBC0 -> libcocos2d.dll+0xABBC0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0xCFE824: 22891514 (-> 0xF4A)
- 0xCFE828: 22891508 (-> 0xF47)
- 0xCFE82C: 00000001 (1i | 1u)
- 0xCFE830: 00CFE800 (-> 0xFE50E36 -> 0x0FE50E36)
- 0xCFE834: 00000000 (0i | 0u)
- 0xCFE838: 00000000 (0i | 0u)
- 0xCFE83C: 00000000 (0i | 0u)
- 0xCFE840: 00CFE964 (-> 0xCFE9C8 -> 0xCFEBDC -> 0xCFECBC -> 0xCFED38 -> 0xCFEE5C -> 0xCFEED8 -> 0xCFEF68 -> 0xCFF008 -> 0xCFF078 -> 0xCFF0AC -> 0xCFF11C -> 0xCFF314 [...])
- 0xCFE844: 523BD281 (bitz.moregames.dll+0x25D281 (<0x25c392>+0xeef))
- 0xCFE848: FFFFFFFF (4294967295i | 4294967295u)
- 0xCFE84C: 60257D20 (Geode.dll+0x87D20 (geode::Loader::takeNextMod+0x0))
- 0xCFE850: 5219E6BE (bitz.moregames.dll+0x3E6BE)
- 0xCFE854: F80000CC (4160749772i | 4160749772u)
- 0xCFE858: 1A5B9830 (-> 0x610932F4 -> 0x6101BBC0 -> libcocos2d.dll+0xABBC0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0xCFE85C: 00000019 (25i | 25u)
- 0xCFE860: 00CFE904 (-> 0xCFE970 -> 0xCFE98C -> 0xCFE9D4 -> 0xCFEBE8 -> 0xCFEC60 -> 0xCFECD4 -> 0xCFED50 -> 0xCFED70 -> 0xCFEE68 -> 0xCFEEF0 -> 0xCFEF80 -> 0xCFF028 [...])
- 0xCFE864: 1A5B9830 (-> 0x610932F4 -> 0x6101BBC0 -> libcocos2d.dll+0xABBC0 (cocos2d::CCCopying::copyWithZone+0x0))
- 0xCFE868: 040000FF (&"")
- 0xCFE86C: 000000CC (204i | 204u)
- 0xCFE870: 21FD2C88 (-> 0x44B3E4 -> 0x401742 -> GeometryDash.exe+0x3C1742 (<0x3c1710>+0x32))
- 0xCFE874: 00F15DC8 (&"")
- 0xCFE878: 00000001 (1i | 1u)

### Additional Information

I suspect it has to do with Geode itself but if I am wrong than you can let me know why and which mod causes that

**Comment by qimiko** [comment]
it is definitely a mod issue. you have 50 mods installed. if you get this issue in safe mode (hold shift when starting game) or with no mods enabled, then feel free to reopen the issue and post the new crashlog
