### ISSUE TITLE
Crash On Startup (EXCEPTION_ACCESS_VIOLATION (0xC0000005))

### ISSUE THREAD

**Issue by Alltoupload** [geode-sdk/geode#765]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0-beta-26

### Mods Installed

x | [v1.0.0] acaruso.horn
x | [v1.1.2] adyagd.godlikefaces
x | [v1.0.1] alphalaneous.playercolorselect
x | [v1.0.3] alphalaneous.random_tab
x | [v1.8.0] beat.click-sound
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.0.1] cj_link.fakemoderator
  | [v1.0.2] colon.bumpscosity
x | [v2.0.3] colon.gd_in_2019
x | [v1.0.2] colon.gold_user_coins
x | [v4.1.10] cvolton.betterinfo
x | [v1.0.0] cvolton.compact_lists
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.0.3] dogotrigger.level_history
x | [v1.0.0] ekv.save_on_level_page
x | [v1.0.3] elsai.copyright_remover_for_main_levels
x | [v1.0.1] elsai.easing_preview
x | [v1.6.4] firee.PrismMenu
x | [v2.7.1] fleym.nongd
x | [v1.5.7] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.2.0] grian.art_importer
x | [v1.0.5] hiimjustin000.more_object_info
x | [v6.3.5] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
! | [v1.1.0] itzkiba.better_progression
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.id_hyperlinks
x | [v1.0.3] korshun.quickaccess
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.3] mat.run-info
x | [v2.11.1] maxnu.gd_mega_overlay
x | [v1.0.0] nyakofox.channelviewer
x | [v1.0.4] nytelyte.garage_utilities
x | [v1.2.5] nytelyte.wave_trail_drag_fix
x | [v1.1.0] polsk.ratinginfo
x | [v1.2.0] prevter.bettercrash
x | [v2.3.0] prevter.openhack
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.1.2] raydeeux.disturbingnewbests
x | [v1.1.2] raydeeux.erysedits
x | [v1.0.0] riley.nogrounds
x | [v1.0.0] shadyiscool.shadypause
x | [v1.2.0] shineua.geometrize2gd
x | [v1.3.1] shineua.minecraft_splash
x | [v1.0.2] slammy333.save_button
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v0.1.0] sse2.gj-music-manager
  | [v1.0.0] statuszer0.ultra_ldm
  | [v1.0.9] syzzi.click_between_frames
x | [v1.1.0] techstudent10.button_sfx
x | [v1.0.1] thesillydoggo.blur_bg
x | [v1.0.0-beta.8] thesillydoggo.comment_emojis
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.0.0] tpdea.checkpoint_switcher
x | [v1.0.3] undefined0.buttoneasing
x | [v1.3.0] undefined0.editormusic
x | [v1.12.3] undefined0.gdtweaks
x | [v1.1.1] undefined0.minecraft_menu
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.3.0] uproxide.more_difficulties
x | [v5.0.0] user95401.mainlevelseditor
  | [v1.0.1] weebify.randomizecreatorlayer-geode
x | [v1.1.2] weebify.restartbtn
x | [v1.0.0] xanii.level_ratings
x | [v1.0.2] xanii.pitch_shifter
  | [v1.0.0] zilko.better_screenshots
x | [v1.1.0] zilko.custom_labels
x | [v1.0.0] zilko.literal_level_lengths
x | [v1.0.1] zsa.percentage-bugfix

### Steps to Reproduce

Startup not in Safe Mode (I hate Safe Mode)
That's it

### Crash Report

2024-05-16T07:48:01+0100
Would you like a cupcake?

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash
- Loader Version: v2.0.0-beta.26 (Geometry Dash v2.204)
- Loader Commit: 2857ecf
- Bindings Commit: d35e301
- Installed Mods: 76 (Loaded: 70/71)
- 4GB Patch: Patched
- Problems: 1
Type: PresentIncompatibility
Mod: itzkiba.better_progression
Message: zilko.better_screenshots

== Exception Information ==
- Thread Information: "Main" (ID: 20104)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: firee.PrismMenu.dll+0xFCF75
- Exception Flags: 0x0
- Exception Parameters: 0x0, 0xFFFFFFD8
- Access Violation Type: Read
- Access Violation Address: 0xFFFFFFD8
- Protect: PAGE_READONLY | PAGE_WRITECOPY | PAGE_NOCACHE (0x69570A0A)
- State: MEM_RESERVE | MEM_FREE (0x29656578)
- Type: MEM_IMAGE | MEM_MAPPED | MEM_PRIVATE (0x6F466874)

== Stack Trace ==
- firee.PrismMenu.dll+0xFCF75
- firee.PrismMenu.dll+0xF2C8D (<0xf27e0>+0x4ad)
- firee.PrismMenu.dll+0x9D236 (<0x9d1a0>+0x96)
- firee.PrismMenu.dll+0x5DE16 (<0x5dd90>+0x86)
- 0x005B2DCB
- cvolton.misc_bugfixes.dll+0x2436D
- cvolton.misc_bugfixes.dll+0x1DB52
- 0x005B2DCB
- cvolton.misc_bugfixes.dll+0x1067D (<0xfa90>+0xbed)
- 0x005B2DCB
- cvolton.misc_bugfixes.dll+0xB470 (<0xa570>+0xf00)
- 0x005B2DCB
- cvolton.misc_bugfixes.dll+0x3607
- 0x005B2DCB
- prevter.openhack.dll+0xF89B2 (openhack::hooks::MenuLayerHook::init+0x32)
- 0x005B2DCB
- geode.texture-loader.dll+0x12182 (<0x12150>+0x32)
- geode.texture-loader.dll+0x1088B (<0x10870>+0x1b)
- 0x005B2DCB
- undefined0.gdtweaks.dll+0xE0CF
- 0x005B2DCB
- undefined0.minecraft_menu.dll+0x1B6A
- 0x005B2DCB
- beat.click-sound.dll+0xA51A (<0xa4d0>+0x4a)
- 0x005B2DCB
- GeometryDash.exe+0x276B0A (LoadingLayer::loadingFinished+0x2a)
- 0x103329AB
- dankmeme.globed2.dll+0x38002 (<0x37dc0>+0x242)
- dankmeme.globed2.dll+0x367CB (<0x367b0>+0x1b)
- 0x103329AB
- 0x005B2D89
- 0x005B29AB
- Geode.dll+0x4459C (CustomLoadingLayer::loadAssets+0x14c)
└ D:\a\geode\geode\loader\src\hooks\LoadingLayer.cpp:214
- 0x005B29AB
- libcocos2d.dll+0x8F484 (cocos2d::CCActionInterval::step+0xb4)
- libcocos2d.dll+0x91564 (cocos2d::CCActionManager::update+0x74)
- libcocos2d.dll+0x106E02 (cocos2d::CCScheduler::update+0x52)
- 0x01310416
- 0x01310037
- maxnu.gd_mega_overlay.dll+0x652A6 (setupStartPos+0x686)
- 0x01310037
- maxnu.gd_mega_overlay.dll+0x44B56 (cocos2d::CCString::createWithFormat+0x1576)
- 0x01310037
- zilko.custom_labels.dll+0x1DAC6 (<0x1dab0>+0x16)
- 0x01310037
- 0x01310037
- 0x103335C9
- 0x103331EB
- GeometryDash.exe+0x3C12D8 (<0x3c10f0>+0x1e8)
- Geode.dll+0x1765C4 (gdMainHook+0x214)
└ D:\a\geode\geode\loader\src\platform\windows\main.cpp:59
- GeometryDash.exe+0x3C267E (<0x3c1710>+0xf6e)
- KERNEL32.DLL+0x1FCC9 (BaseThreadInitThunk+0x19)
- ntdll.dll+0x67CBE (RtlGetAppContainerNamedObjectPath+0x11e)
- ntdll.dll+0x67C8E (RtlGetAppContainerNamedObjectPath+0xee)

== Register States ==
- EAX: 00000000 (0i | 0u)
- EBX: 30C3FD18 (-> 0x1)
- ECX: 00000000 (0i | 0u)
- EDX: 00000000 (0i | 0u)
- ESI: 0056E160 (&"")
- EDI: FFFFFFD8 (4294967256i | 4294967256u)
- EBP: 0056E5D0 (-> 0x56E7B8 -> 0x56E814 -> 0x56E864 -> 0x56E8C0 -> 0x56E928 -> 0x56E974 -> 0x56E9D0 -> 0x56EA4C -> 0x56EAA8 -> 0x56EAC8 -> 0x56EB24 -> 0x56EB58 [...])
- ESP: 0056E160 (&"")
- EIP: 6F99CF75 (firee.PrismMenu.dll+0xFCF75)
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 1 
- SF: 1 | TF: 0 | ZF: 0 

== Installed Mods ==
x | [v1.0.0] acaruso.horn
x | [v1.1.2] adyagd.godlikefaces
x | [v1.0.1] alphalaneous.playercolorselect
x | [v1.0.3] alphalaneous.random_tab
x | [v1.8.0] beat.click-sound
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.0.1] cj_link.fakemoderator
  | [v1.0.2] colon.bumpscosity
x | [v2.0.3] colon.gd_in_2019
x | [v1.0.2] colon.gold_user_coins
x | [v4.1.10] cvolton.betterinfo
x | [v1.0.0] cvolton.compact_lists
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.0.3] dogotrigger.level_history
x | [v1.0.0] ekv.save_on_level_page
x | [v1.0.3] elsai.copyright_remover_for_main_levels
x | [v1.0.1] elsai.easing_preview
x | [v1.6.4] firee.PrismMenu
x | [v2.7.1] fleym.nongd
x | [v1.5.7] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.2.0] grian.art_importer
x | [v1.0.5] hiimjustin000.more_object_info
x | [v6.3.5] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
! | [v1.1.0] itzkiba.better_progression
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.id_hyperlinks
x | [v1.0.3] korshun.quickaccess
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.3] mat.run-info
x | [v2.11.1] maxnu.gd_mega_overlay
x | [v1.0.0] nyakofox.channelviewer
x | [v1.0.4] nytelyte.garage_utilities
x | [v1.2.5] nytelyte.wave_trail_drag_fix
x | [v1.1.0] polsk.ratinginfo
x | [v1.2.0] prevter.bettercrash
x | [v2.3.0] prevter.openhack
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.1.2] raydeeux.disturbingnewbests
x | [v1.1.2] raydeeux.erysedits
x | [v1.0.0] riley.nogrounds
x | [v1.0.0] shadyiscool.shadypause
x | [v1.2.0] shineua.geometrize2gd
x | [v1.3.1] shineua.minecraft_splash
x | [v1.0.2] slammy333.save_button
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v0.1.0] sse2.gj-music-manager
  | [v1.0.0] statuszer0.ultra_ldm
  | [v1.0.9] syzzi.click_between_frames
x | [v1.1.0] techstudent10.button_sfx
x | [v1.0.1] thesillydoggo.blur_bg
x | [v1.0.0-beta.8] thesillydoggo.comment_emojis
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.0.0] tpdea.checkpoint_switcher
x | [v1.0.3] undefined0.buttoneasing
x | [v1.3.0] undefined0.editormusic
x | [v1.12.3] undefined0.gdtweaks
x | [v1.1.1] undefined0.minecraft_menu
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.3.0] uproxide.more_difficulties
x | [v5.0.0] user95401.mainlevelseditor
  | [v1.0.1] weebify.randomizecreatorlayer-geode
x | [v1.1.2] weebify.restartbtn
x | [v1.0.0] xanii.level_ratings
x | [v1.0.2] xanii.pitch_shifter
  | [v1.0.0] zilko.better_screenshots
x | [v1.1.0] zilko.custom_labels
x | [v1.0.0] zilko.literal_level_lengths
x | [v1.0.1] zsa.percentage-bugfix

== Stack Allocations ==
- 0x56E160: 00000000 (0i | 0u)
- 0x56E164: 00000030 (48i | 48u)
- 0x56E168: 00000110 (272i | 272u)
- 0x56E16C: 00000008 (8i | 8u)
- 0x56E170: 30C3FD18 (-> 0x1)
- 0x56E174: 00000000 (0i | 0u)
- 0x56E178: 00000000 (0i | 0u)
- 0x56E17C: 00000000 (0i | 0u)
- 0x56E180: 00000001 (1i | 1u)
- 0x56E184: 30CFC788 (-> 0x30D008F8 -> 0x2F62C9A8 -> 0x31184A80 -> 0x30DA7FA8 -> 0x13300C0 -> 0x15192A8 -> 0x95DAD10 -> 0x951D3A8 -> 0x4A4D2F8 -> 0x90DA468 -> 0x87BF6B8 -> 0x87EDF60 [...])
- 0x56E188: 000000BC (188i | 188u)
- 0x56E18C: 00000000 (0i | 0u)
- 0x56E190: 00000001 (1i | 1u)
- 0x56E194: 00000000 (0i | 0u)
- 0x56E198: 00000000 (0i | 0u)
- 0x56E19C: 00000000 (0i | 0u)
- 0x56E1A0: 30C3FD44 (-> 0xFFFFFFD8)
- 0x56E1A4: 00000000 (0i | 0u)
- 0x56E1A8: 00000000 (0i | 0u)
- 0x56E1AC: 00000000 (0i | 0u)
- 0x56E1B0: 00000000 (0i | 0u)
- 0x56E1B4: 00000000 (0i | 0u)
- 0x56E1B8: 30CFC900 (&"")
- 0x56E1BC: 00000002 (2i | 2u)
- 0x56E1C0: 2F5B1868 (&"rGrabHovered")
- 0x56E1C4: 00000000 (0i | 0u)
- 0x56E1C8: 00000000 (0i | 0u)
- 0x56E1CC: 00000000 (0i | 0u)
- 0x56E1D0: 046EFE44 (&"A")
- 0x56E1D4: 00000000 (0i | 0u)
- 0x56E1D8: 00000000 (0i | 0u)
- 0x56E1DC: 00000000 (0i | 0u)

**Comment by TheSillyDoggo** [comment]
I confirm that this crash is NOT related to Geode Loader but a mod.

**Comment by TheSillyDoggo** [comment]
try disabling prism
