### ISSUE TITLE
Problema: informe de fallo

### ISSUE THREAD

**Issue by Verdesitopromax** [geode-sdk/geode#769]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

1.3.2

### Mods Installed

V 2.0.0 -beta.25

### Steps to Reproduce

Entre al menú cuando de la nada se me crasheo

### Crash Report

Crash 2024-05-17 18.13.21.7z

### Additional Information

Geode loader

**Comment by frenchfrysays3** [comment]
i have the same issue

**Comment by Its-Aleplay** [comment]
I have a problem with the "node ids" mod, it tells me that it cannot load its binary, could you help me with that? 
![Uploading Screenshot_20240623-140944.jpg…]()
