### ISSUE TITLE
Cannot touch in editor

### ISSUE THREAD

**Issue by rocholojavinar** [geode-sdk/geode#771]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

v2.0.0-beta.26

### Expected Behavior

I can touch in the editor

### Actual Behavior

If you open editor, it cannot touch.

### Steps to Reproduce

1) Fix that you can't touch.

**Comment by HenrySck075** [comment]
wheres the steps to reproduce
