### ISSUE TITLE
Pressing Geode button crashes the game

### ISSUE THREAD

**Issue by WiktorProj** [geode-sdk/geode#773]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Mods Installed

x | [v1.1.3] adam_729.deathmarkers
x | [v1.0.0] bigmancozmo.skip_editor_save_confirm
x | [v1.0.2] colon.bumpscosity
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.5.7] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.2.0] grian.art_importer
x | [v6.3.5] hjfod.betteredit
x | [v1.1.0] itzkiba.better_progression
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.1.0] polsk.ratinginfo
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.3.0] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v1.0.2] slammy333.save_button
x | [v1.0.3] sofabeddd.geometry_dash
x | [v2024.229.0] tastyforreal.google-translate
x | [v1.1.2] TheSillyDoggo.StartposSwitcher
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.1.0] uproxide.autosong
x | [v1.0.0] viper.project-oppenheimer
x | [v1.0.0] xanii.level_ratings
x | [v1.0.4] xanii.youtubers
x | [v1.0.1] zeozeozeo.zcblive
x | [v1.0.0] zilko.literal_level_lengths
x | [v0.1.2] zohnannor.dark_mode

### Steps to Reproduce

1) Pressed the geode button

### Crash Report

2024-05-18T21:02:00+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.26
Loader Commit: 2857ecf
Bindings Commit: d35e301
Installed mods: 33
Problems: 0

== Exception Information ==
C++ Exception: class std::invalid_argument("invalid stoi argument")
Faulty Mod: <Unknown>
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 1498b2 (RaiseException + 98)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 7e96 (CxxThrowException + 102)
 - C:\Windows\SYSTEM32\MSVCP140.dll + 2d0df (std::_Xinvalid_argument + 31)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.better_progression\itzkiba.better_progression.dll + ae0f (Request::generateNewTotalEXP + 1487)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.better_progression\itzkiba.better_progression.dll + 4806 (BP_CCDirector::willSwitchToScene + 38)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.better_progression\itzkiba.better_progression.dll + 47dd (geode::modifier::AsStaticFunction_willSwitchToScene<BP_CCDirector,void (__thiscall BP_CCDirector::*)(cocos2d::CCScene *)>::Impl<void (__thiscall BP_CCDirector::*)(cocos2d::CCScene *)>::function + 13)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 9006a (cocos2d::CCSequence::update + 170)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 900ab (cocos2d::CCSequence::update + 235)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 8f4a2 (cocos2d::CCActionInterval::step + 210)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 91564 (cocos2d::CCActionManager::update + 116)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 106e02 (cocos2d::CCScheduler::update + 82)
 - 01920416
 - 0C312DA9
 - 0C3129CB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 1765c4 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 6be3b (RtlInitializeExceptionChain + 107)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bdbf (RtlClearBits + 191)

== Register States ==
EAX: 0064f920
EBX: 19930520
ECX: 00000003
EDX: 00000000
EBP: 0064f978
ESP: 0064f920
EDI: 6bb71a1c
ESI: 01553ef0
EIP: 770998b2

== Installed Mods ==
x | [v1.1.3] adam_729.deathmarkers
x | [v1.0.0] bigmancozmo.skip_editor_save_confirm
x | [v1.0.2] colon.bumpscosity
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.5.7] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.2.0] grian.art_importer
x | [v6.3.5] hjfod.betteredit
x | [v1.1.0] itzkiba.better_progression
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.1.0] polsk.ratinginfo
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.3.0] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v1.0.2] slammy333.save_button
x | [v1.0.3] sofabeddd.geometry_dash
x | [v2024.229.0] tastyforreal.google-translate
x | [v1.1.2] TheSillyDoggo.StartposSwitcher
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.1.0] uproxide.autosong
x | [v1.0.0] viper.project-oppenheimer
x | [v1.0.0] xanii.level_ratings
x | [v1.0.4] xanii.youtubers
x | [v1.0.1] zeozeozeo.zcblive
x | [v1.0.0] zilko.literal_level_lengths
x | [v0.1.2] zohnannor.dark_mode

### Additional Information

I have a new PC now, that's probably the issue...

**Comment by hiimjustin000** [comment]
Did this happen before?

**Comment by hiimjustin000** [comment]
Here's a better question: Are you logged in to your Geometry Dash account?

**Comment by Fleeym** [comment]
Yeah this is a crash related to Better Progression, report it to Kiba

**Comment by WiktorProj** [comment]
Ok.
