### ISSUE TITLE
2024-05-20T14:29:05.156537514 [W/.geode.launche]: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults

### ISSUE THREAD

**Issue by Verdesitopromax** [geode-sdk/geode#777]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

1.3.3

### Mods Installed

![XRecorder_20052024_143306](https://github.com/geode-sdk/geode/assets/165613600/3c67c35b-5ec2-48fa-90f7-25051e940764)

### Steps to Reproduce

Ejemplo:1 Hice reportar al mod de crash porque me molesta mucho eso 

### Crash Report

2024-05-20T14:29:05.156537514 [W/.geode.launche]: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults

### Additional Information

Esto puede pasarles a más a muchos y Ami entonces ayuda

**Comment by BenicioAdder** [comment]
![Screenshot_20240524_143608_Dev Tools Pro.jpg](https://github.com/geode-sdk/geode/assets/168354879/7e4e5c53-584a-4540-b23b-983f8a214ddd)

![Screenshot_20240524_143630_Dev Tools Pro.jpg](https://github.com/geode-sdk/geode/assets/168354879/5f95cb22-02fa-4741-b593-9d6e9ae0f3d2)
