### ISSUE TITLE
Image in LocalModInfoLayer doesn't scale to game graphics

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/geode#779]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

2857ecf

### Geode Version

v2.2.0 beta26

### Mods Installed

Not related to this issue ig

### Expected Behavior

I expect to add a title image for my self-made mod and the image perfectly fits the display like this:
![image](https://github.com/geode-sdk/geode/assets/94737247/ce890c34-d089-41b0-aa08-73d087a7319d)

### Actual Behavior

When it looks perfect in high graphics, it looks too giant in HD graphics and mobile:
![image](https://github.com/geode-sdk/geode/assets/94737247/16faaba1-e67c-4699-9d91-cc95930dec13)

But if I resize the image to fit the hd graphics, it looks tiny in UHD.

### Steps to Reproduce

As shown above.
Any image can reproduce this.

### Additional Information

There should be an auto-resize-fit-thing for images in LocalModInfoLayer

**Comment by hiimjustin000** [comment]
Did you put the image in the resources folder?

**Comment by Naxrin** [comment]
> Did you put the image in the resources folder?
> 
> If you want to put an image in `about.md`, you have to put the image in the resources folder, and then reference the image by putting, for example, `![Image](naxrin.rgb_icons/(image).png)`

ok it works thanks!
I‘ve not ever noticed only images in resources folder scale to graphics, since many other mods directly put images in root directory
But anyway, how can I put a link in about.md to make both in-game popup and mod desc in webpage can properly display the image?
e.g.:
![image](https://github.com/geode-sdk/geode/assets/94737247/523d1303-79c7-4c2b-90be-b116085b58fe)

**Comment by rocholojavinar** [comment]
![IMG](https://img.youtube.com/vi/T866AS3mB9M/maxresdefault.jpg)
