### ISSUE TITLE
for some reason there is no icon in the menu

### ISSUE THREAD

**Issue by pbroYT** [geode-sdk/geode#783]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

latest

### Mods Installed

none i tried reinstalling gd

### Expected Behavior

to show the icon and work

### Actual Behavior

does not show the icon

### Steps to Reproduce

idk

**Comment by MaTTzCZ** [comment]
Same problem here, It ocured after upgrading to Windows 11

**Comment by ratuser1** [comment]
> [если вы недавно обновили GD ](https://github.com/geode-sdk/geode/issues/827)

thanks

**Comment by Cebberi** [comment]
Yeah! me too... i just recently updated it... that might be the problem (contact the discord cuz i dont have a discord)

**Comment by Cappy13** [comment]
it's because of the 2.206 update

**Comment by Djspac3** [comment]
same

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/CyD8hAjj8L8/maxresdefault.jpg)

**Comment by Djspac3** [comment]
just was thinking what if as a temp fix (and a sucky compatibility fix for old as heck mods) the installer could just change the version installed like just reinstall old vers?
