### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by JuegosDeMarcos** [geode-sdk/geode#785]
### Geode Version

Ver 2.0.0 beta 26

### Related Problem

Podrían sacar el crasheo constante que hay en el Geode porque cada vez que tocó un botón el juego me saca instantaneamente,porfa,me harían un gran favor si sacan el crasheo constante

### Your Solution

Revisar el código aver si llegan a encontrar un error,talvez por eso me saca

### Additional Information

Solo eso

**Comment by Cristian12mt12** [comment]
> ### Versión Geoda
> Versión 2.0.0 beta 26
> 
> ### Problema relacionado
> Podrían sacar el crasheo constante que hay en el Geode porque cada vez que tocó un botón el juego me saca instantáneamente, porfa,me harían un gran favor si sacan el crasheo constante
> 
> ### Tu solución
> Revisar el código aver si llegan a encontrar un error,talvez por eso me saca
> 
> ### información adicional
> solo eso

Gracias

**Comment by hiimjustin000** [comment]
Cuál es tu sistema operativo?

**Comment by JuegosDeMarcos** [comment]
Aver aver,ahora bien lo que me pasa es que los mods,no se me descargan
porque me faltan otros mods que “supuestamente”NO EXISTEN,¿Solución?
