### ISSUE TITLE
i lost my progress because this crash

### ISSUE THREAD

**Issue by gdERA-94** [geode-sdk/geode#786]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Steps to Reproduce

i opened discord app and gd crashed

### Crash Report

i do have it but idk how to paste it here

### Additional Information

is there any way i can recover my data?

**Comment by HenrySck075** [comment]
1. unless you do have the crash report dialog show up when reentering (assuming that you did not have any actual crashes before), thats not a crash
2. 
![Screenshot_20240524_084559_Adblock Browser](https://github.com/geode-sdk/geode/assets/111231428/f890464b-c18b-414c-8dbe-05dd5c4e9be7)

**Comment by heavyutils** [comment]
Womp womp.
Go and vent to Discord instead. This isn't Geode's fault.

**Comment by enessmr** [comment]
Lose ur progress? Don't worry! There is a Save file in ur gaem! TRy to serach ur AppDAta folder! Then the save file appears.
Not working? Go to steam/steamapps/Geometry Dash and serach all folders.

**Comment by matcool** [comment]
stale, reopen if needed
