### ISSUE TITLE
Restarted my phone

### ISSUE THREAD

**Issue by BenicioAdder** [geode-sdk/geode#788]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

**Android64**

### Geode Version

**2.0.0-beta26**

### Steps to Reproduce

**I did open the app but it restarted my phone**

### Crash Report

**I just litterally launched geode and now it restarted my phone because i dont even know what happened, and that's the problem.**

### Additional Information

**Can someone fix it? Idk**

**Comment by MuhammedEmirArtan** [comment]
Holy bro, if I was you, I won't prefer to open Geode again bc. it can corrupt system files with it (small chance.)

**Comment by RoootTheFox** [comment]
it can't - it literally doesn't have permissions to do that.

**Comment by MuhammedEmirArtan** [comment]
> it can't - it literally doesn't have permissions to do that.

No, I know it oesnt have permissions to do that, but like turning off the phone immediately can damage RAM or data. There is a small possibility for that.

**Comment by RoootTheFox** [comment]
Android apps do not have permissions to restart your phone. It simply can't be done.

**Comment by BenicioAdder** [comment]
I'm scared to restart my phone or, btw bootloop.

**Comment by RoootTheFox** [comment]
if your phone is bootlooping, that is 100% *NOT* related to Geode.
Geode does not modify any system files or start on boot and therefore can't cause bootloops.

**Comment by BenicioAdder** [comment]
> Try clearing the Geode app cache or doing any system updates (I've never heard of this before lol, this is all I can think of). If you don't mind loosing any data, reinstalling Geode or in settings clicking "View Application Logs" may help diagnose the issue.

>hi

>test

I made this for no reason

**Comment by BenicioAdder** [comment]
> Try clearing the Geode app cache or doing any system updates (I've never heard of this before lol, this is all I can think of). If you don't mind loosing any data, reinstalling Geode or in settings clicking "View Application Logs" may help diagnose the issue.

How do I check?🤔
