### ISSUE TITLE
I cannot select objects in the editor

### ISSUE THREAD

**Issue by Rampage28** [geode-sdk/geode#789]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.26

### Mods Installed

hjfod.betteredit.geode

### Expected Behavior

Selecting objects in the editor

### Actual Behavior

I installed the last geode version, an after that, when going to the editor, i cannot select most of the objects by any means:
![Screenshot_20240525-002258_Geode](https://github.com/geode-sdk/geode/assets/167664671/2f2dc917-c802-4710-bdf9-451e9827afd8)
![Screenshot_20240525-002304_Geode](https://github.com/geode-sdk/geode/assets/167664671/3bb51eca-72c8-4b79-a236-f1c122c7064f)

### Steps to Reproduce

I do not have any idea

### Additional Information

The only editor mod that i had was betteredit, but was disabled, and was an older version of it

**Comment by Rampage28** [comment]
Also, this is very bad because i am a creator, and i need to be able to build levels lmao.
Also i cannot switch startpos because of this

**Comment by RayDeeUx** [comment]
check your delete tab and make sure the filter is set to "none"

**Comment by Rampage28** [comment]
> check your delete tab and make sure the filter is set to "none"

That was not the problem, but something similar, thanks for the help
