### ISSUE TITLE
Everytime I use the editor and press save and play the game crashes

### ISSUE THREAD

**Issue by Wowsoiyoiu** [geode-sdk/geode#794]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

V2.0.0

### Mods Installed

Click Between frames, Custom keybinds, Globed, Gmd Api, Jukebox, Megahack, and Node Ids

### Steps to Reproduce

It started randomly when I was trying to buff blast processing. I made some buffs and when I tried to play it the game simply crashed and my progress was lost. I tried doing the same thing again but it crashed again.

### Crash Report

2024-05-11T09:31:00-0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.26
Loader Commit: 2857ecf
Bindings Commit: d35e301
Installed mods: 5
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_alloc("bad allocation")
Faulty Mod: <Unknown>
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 1498b2 (RaiseException + 98)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 19339 (CxxThrowException + 78)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 5da6a (fcloseall + 34608)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 624c7 (CCContentManager::addDictDS + 471)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 61f9d (DS_Dictionary::~DS_Dictionary + 445)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 72f59 (DS_Dictionary::addBoolValuesToMapForKeySpecial + 761)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + ec843 (cocos2d::ZipUtils::encryptDecrypt + 131)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + ec2ba (cocos2d::ZipUtils::compressString + 234)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 76c1c (DS_Dictionary::saveRootSubDictToCompressedFile + 444)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 47624
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 5b8bd
 - 03403E16
 - 03403A37
 - D:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 4e4bb (geode::modifier::AsStaticFunction_trySaveGame<SaveLoader,void (SaveLoader::*)(bool) __attribute__((thiscall))>::Impl<void (SaveLoader::*)(bool) __attribute__((thiscall))>::function + 27 | D:\a\geode\geode\build\bindings\bindings\Geode\modify\AppDelegate.hpp:95)
 - 03403A37
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - D:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 1765c4 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6be3b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bdbf (RtlClearBits + 191)

== Register States ==
EAX: 008feb90
EBX: 00000000
ECX: 00000003
EDX: 00000000
EBP: 008febe8
ESP: 008feb90
EDI: 008fec38
ESI: 50d8c7fc
EIP: 74da98b2

== Installed Mods ==
x | [v8.0.0-alpha.134] absolllute.megahack
x | [v1.3.7] dankmeme.globed2
x | [v1.5.7] geode.custom-keybinds
x | [v2.0.0-beta.26] geode.loader
x | [v1.0.9] syzzi.click_between_frames

### Additional Information

This was probably caused by the modloader trying to run with low computer storage. It might be caused because when I say an update prompt I Ignored it. And the update might have downloaded corruptedly.

**Comment by hiimjustin000** [comment]
Install 4gb patch https://ntcore.com/4gb-patch/
