### ISSUE TITLE
Player Trail sometimes doesn't work

### ISSUE THREAD

**Issue by imsimonster** [geode-sdk/geode#795]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v.2.0.0-beta.27

### Expected Behavior

trail apperas after orbs and portals, in the ship, ufo, wave, swing, etc.

### Actual Behavior

trail doesnt appear sometimes (in all levels)
in very long levels (like Eon) the trail completely breaks and doesnt appear at all

### Steps to Reproduce

blank geode with mods/apis disabled 
i use the fire player trail but all trails dont work
play eon or any other level and the trail should be inconsistent or completely gone (it is not like the og trail cutting)

### Additional Information

i dont know what causes this, i disabled all mods and apis and it still doesnt appear so i guess its related to geode itself

**Comment by matcool** [comment]
have you checked vanilla? i really doubt this is geode

**Comment by imsimonster** [comment]
i didnt think it was vanilla because there was no update to it and it worked fine

**Comment by imsimonster** [comment]
so now i checked and it also doesnt work on vanilla, thank you
still think this is weird because there was no gd update
