### ISSUE TITLE
Menu Unloading

### ISSUE THREAD

**Issue by ThisIsKenLe** [geode-sdk/geode#803]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android32

### Geode Version

v2.0.0

### Expected Behavior

Expected menu to load

### Actual Behavior

Menu not loaded

### Steps to Reproduce

1) Launched Geode
2) Index updates

**Comment by matcool** [comment]
?
