### ISSUE TITLE
Force all mod IDs to lowercase internally

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/geode#804]
### Geode Version

v2.0.0

### Related Problem

When new index drops, mod IDs with capitals in the name will break, this will cause issues with duplicated mods when the id changes to lowercase.

### Your Solution

Change the code that gets mod IDs to run toLower on the mod id so that EpicDeveloper.EpicMod is considered the same as epicdeveloper.epicmod and the geode client can update them correctly without the two mods interfering

### Additional Information

This should be done because some people didn't know that capital letters were being banned cuz nowhere on the docs said it was banned.

**Comment by Fleeym** [comment]
This will be implemented with the supersede system
