### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Rubensillo19** [geode-sdk/geode#811]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### SDK commit

Jugar 

### Geode Version

2.2

### Mods Installed

Muchos 

### Expected Behavior

Jugar 

### Actual Behavior

Jugar 

### Steps to Reproduce

Jugar 

### Additional Information

Jugar

**Comment by heavyutils** [comment]
2.206 bug. Wait for fix.

**Comment by reyesmarangelantonio-art** [comment]
Cuando escribí geometry dash en un comentario si doy a espacio aparece try y con estas si pongo espacio aparece ests
