### ISSUE TITLE
Ss

### ISSUE THREAD

**Issue by Rubensillo19** [geode-sdk/geode#812]
### Geode Version

Ifk 

### Related Problem

Icjc

### Your Solution

Jcjc

### Additional Information

Lcic

**Comment by Rubensillo19** [comment]
Lviiff

**Comment by heavyutils** [comment]
Guys I can translate it:

Title: Shapeshifter
Geode Version: I forked
Related Problem: I completed Jumping Circles
Your Solution: Joe couldn't jump circles
Additional Information: Losers can, I can
