### ISSUE TITLE
geode crashed when clicking save and play or save and exit button

### ISSUE THREAD

**Issue by othmanwu67** [geode-sdk/geode#813]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.27

### Mods Installed

x | [v1.8.0] beat.click-sound
x | [v1.0.5] capeling.soggy-mod
x | [v1.3.7] dankmeme.globed2
x | [v1.5.9] geode.custom-keybinds
x | [v2.0.0-beta.27] geode.loader
x | [v1.11.0] geode.node-ids

### Steps to Reproduce

i was on the editor but when i click save and play and save and exit button, IT CRASHES.

### Crash Report
[Geode 2024-06-01 09.06.29.log](https://github.com/user-attachments/files/15520866/Geode.2024-06-01.09.06.29.log)

== Installed Mods ==
x | [v1.8.0] beat.click-sound
x | [v1.0.5] capeling.soggy-mod
x | [v1.3.7] dankmeme.globed2
x | [v1.5.9] geode.custom-keybinds
x | [v2.0.0-beta.27] geode.loader
x | [v1.11.0] geode.node-ids

### Additional Information

caused by unknown (how)

**Comment by JustHackedTV** [comment]
From your logs, looks like its a mod issue, and not a Geode issue.

From my experience, its probably BetterEdit, also BetterInputs had some issues loading some stuff in the settings, but not sure what may be causing it.
