### ISSUE TITLE
Geode Version

### ISSUE THREAD

**Issue by nbieberitz** [geode-sdk/geode#817]
### Your Question

How can I check the Geode Version currently installed, and how do I update to the latest version?

**Comment by Ki07-coder** [comment]
Open your game files, go to the geode folder and there shouls be a file called something like "geode updates" which lets you update geode. To see the installed version, you can simply check in the geode menu ingame

**Comment by GhostBuster145** [comment]
> Open your game files, go to the geode folder and there shouls be a file called something like "geode updates" which lets you update geode. To see the installed version, you can simply check in the geode menu ingame

I tried that but the file doesn't work.

**Comment by ManifestJW** [comment]
Didn't the new update for GD break Geode?

**Comment by GhostBuster145** [comment]
I am not sure

**Comment by LimeGradient** [comment]
The new GD update did break geode

**Comment by AClon314** [comment]
> Didn't the new update for GD break Geode?

Seems the new GD update break geode (Linux Proton)

**Comment by KillerCraftYT** [comment]
> > Didn't the new update for GD break Geode?
> 
> Seems the new GD update break geode (Linux Proton)

yea it did

**Comment by KillerCraftYT** [comment]
> > Didn't the new update for GD break Geode?
> 
> Seems the new GD update break geode (Linux Proton)

i think we need to wait for geode 2.0.0-beta28 which hopefully will fix are issues honestly i hope it comes soon because i cant live without betteredit

**Comment by GhostBuster145** [comment]
I agree!

**Comment by GhostBuster145** [comment]
Is geode even going to be updated?

**Comment by RoootTheFox** [comment]
no geode will never be updated it's dead
(this is a JOKE but please just be patient and wait!!)

**Comment by GhostBuster145** [comment]
Will it really be updated?

**Comment by GhostBuster145** [comment]
If so, I hope it will be soon. I can wait

**Comment by RoootTheFox** [comment]
yes. just wait, asking for when it's gonna be updated won't make it faster.

**Comment by GhostBuster145** [comment]
Good. As long as it will be updated, I can be patient.
