### ISSUE TITLE
Geode don't add geode to my game

### ISSUE THREAD

**Issue by STGamer24YT** [geode-sdk/geode#818]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

I don't know

### Mods Installed

![imagen_2024-06-01_172447594](https://github.com/geode-sdk/geode/assets/129440436/51773e1c-2d65-4fd4-8856-2a34fda7f3fd)

### Expected Behavior

Have geode button and Geode mods

### Actual Behavior

Nothing. Literally nothing happens, is just vanilla GD

### Steps to Reproduce

1. Uninstall and reinstall Geode (probably)
2. Open GD

### Additional Information

Hopefully you can identify the error and help me to fix it

**Comment by altalk23** [comment]
2.206 means Geode will stop working until it is updated 👍

**Comment by STGamer24YT** [comment]
> 2.206 means Geode will stop working until it is updated 👍

Oh thanks. I was scared xD
