### ISSUE TITLE
Geode not starting

### ISSUE THREAD

**Issue by Ki07-coder** [geode-sdk/geode#819]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.21

### Mods Installed

![image](https://github.com/geode-sdk/geode/assets/101982256/fea840a8-9395-4462-a503-2894e03ad09d)
should be the latest version of all of them

### Expected Behavior

I expected geode to normally start just as it always did previously

### Actual Behavior

Geometry Dash started, but Geode did not. I did not hold shift when starting GD.
It worked perfectly fine a few hours before, now it didn't.

### Steps to Reproduce

1) Simply start GD and watch Geode not start up (no geode button in the menu and no mods)

### Additional Information

I tried running the Geode updater file to make sure I am on the latest version but it did absolutely nothing.

**Comment by Ki07-coder** [comment]
It worked perfectly fine a few hours ago, now it does not.

**Comment by RoootTheFox** [comment]
first of all, your geode is outdated

but the actual reason geode doesn't load is because GD updated to 2.206 - wait for Geode and mods to update (you will likely need to reinstall geode through the installer)

**Comment by Ki07-coder** [comment]
> first of all, your geode is outdated
> 
> but the actual reason geode doesn't load is because GD updated to 2.206 - wait for Geode and mods to update (you will likely need to reinstall geode through the installer)

I just ran the installer again and it changed absolutely nothing

**Comment by Purpl3GuyGD** [comment]
I have the same problem right now

**Comment by Osmiauw** [comment]
have same rn

**Comment by RoootTheFox** [comment]
first of all, this issue is closed

also, leaving "i have the same problem" type of comments is very spammy, don't do that

**Comment by iampoopy908** [comment]
SHUT THE FUCK UP ROOTTHEFOX NO ONE LIKES YOU NERD

**Comment by RoootTheFox** [comment]
alright then! thats a pretty rude comment !
