### ISSUE TITLE
Geode doesn't load

### ISSUE THREAD

**Issue by AndyMan34Git** [geode-sdk/geode#822]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

I can't check

### Expected Behavior

Geode is supposed to load, including all of my mods

### Actual Behavior

Geode, nor anything related to it loads into the game

### Steps to Reproduce

I have no idea what's causing this

### Additional Information

I did just update my computer, though I don't think that has anything to do with it. The game did update to a new version (I think) so that might have something to do with it.

**Comment by KillerCraftYT** [comment]
same :(
