### ISSUE TITLE
Geode Menu not showing up | Windows launched on Steam

### ISSUE THREAD

**Issue by msavgd** [geode-sdk/geode#826]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

?

### Geode Version

v2.0.0

### Expected Behavior

![image_2024-06-02_041812700](https://github.com/geode-sdk/geode/assets/171464865/42bb3ae0-9d5f-4344-bc83-c4cf7880dd94)

### Actual Behavior

![Geometry Dash Screenshot 2024 06 02 - 04 18 18 04](https://github.com/geode-sdk/geode/assets/171464865/63a35fff-dc99-4a4c-ab12-ea25796d7e02)

### Steps to Reproduce

1. Close GD
2. Download Geode
3. Open GD
4. See it's not there so i close GD
5. Uninstall and Reinstall GD
6. Download Geode again and not there
7. delete geode and download it via run as administrator and still not there

**Comment by R4vy50n** [comment]
its becouse of the new update of gd 2.206, and geode doesnt has an update for that update
