### ISSUE TITLE
geode not working

### ISSUE THREAD

**Issue by 1hysteriia** [geode-sdk/geode#827]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

latest

### Mods Installed

???

### Expected Behavior

geode should load

### Actual Behavior

it just doesnt load

### Steps to Reproduce

1. load the game
2. geode doesnt load

### Additional Information

i reinstalled the game and geode, but still, it doesnt work

**Comment by TheSillyDoggo** [comment]
Geode does not support 2.206 yet.

**Comment by 1hysteriia** [comment]
good to know

**Comment by Djspac3** [comment]
yep
UHGFGGGG
