### ISSUE TITLE
Geometry dash 2.206 Not Working

### ISSUE THREAD

**Issue by Cebberi** [geode-sdk/geode#828]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v.2.0.0

### Mods Installed

41 (i dont remember)

### Expected Behavior

Load it in the bottom

### Actual Behavior

Not Loading

### Steps to Reproduce

New Geometry Dash Update

### Additional Information

![20240602111538_1](https://github.com/geode-sdk/geode/assets/158165005/e35d76a7-6533-434a-bc59-febfb0a0169f)
![20240602111545_1](https://github.com/geode-sdk/geode/assets/158165005/7238b4bf-d199-4a7e-b76f-9ab46c2f4f8d)

**Comment by Cebberi** [comment]
In the Additional Informations there is no:
Image 1: No Geode's Resources Loading Thing
Image 2: No Geode/Globed Button

**Comment by ThunderAxolotl** [comment]
Wait for geode to be updated for 2.206

**Comment by coopeeo** [comment]
The Geode Team (or other people) have to commit bindings for Geometry Dash version 2.206 for each platform, also making Geode work for Windows as now RobTop has made the program with the 64-bit architecture, as well as making Geode available for Macs on Apple Silicon as now that's released. (I can't remember if the last one is true but whatever.)
