### ISSUE TITLE
Modes not loading

### ISSUE THREAD

**Issue by Coolboycoolis** [geode-sdk/geode#831]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v1.3.4

### Mods Installed

Node id's, globed, prism menu, and gamemode swapper

### Expected Behavior

I expected for just a normal session of me playing GD

### Actual Behavior

I can't upload screen shots for some reason but this is all I have 
![Screenshot_20240602_122736_Geode](https://github.com/geode-sdk/geode/assets/169610777/4ee2f440-cc8e-454d-8be9-c6903a5c0035)

### Steps to Reproduce

I just logged on and out of nowhere my mods had a red exclamation mark next to the checkbox

### Additional Information

When I logged on tp geode on the homescreen it said "this version is not compatible" when I clearly is

**Comment by Kingminer7** [comment]
For the last time. Geode is NOT updated for 2.206 yet. The update released yesterday.

**Comment by Fleeym** [comment]
We're working on porting Geode to 2.206, please have patience :)
