### ISSUE TITLE
It doesn’t load, buddy

### ISSUE THREAD

**Issue by heavyutils** [geode-sdk/geode#834]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Expected Behavior

Geode to load normally.

### Actual Behavior

Game didn’t start.

### Steps to Reproduce

Load game with geode.

**Comment by iNUCi** [comment]
2.206 buddy

**Comment by matcool** [comment]
![image](https://github.com/geode-sdk/geode/assets/26722564/7b821634-c480-4b7a-bfc2-dc1d6e2cc367)
please read
