### ISSUE TITLE
Primary color of project/logo

### ISSUE THREAD

**Issue by uncenter** [geode-sdk/geode#836]
### Your Question

What is the primary/brand color of this project? Someone requested your logo to be added to Simple Icons at https://github.com/simple-icons/simple-icons/issues/10808, and I'm working on adding it in but we are stuck on what color to go with! 😅

Input would be appreciated at https://github.com/simple-icons/simple-icons/pull/10822#discussion_r1581030263 :)

**Comment by heavyutils** [comment]
What?

**Comment by uncenter** [comment]
Thankfully one of your lead developers already responded at the issue in question. I'll close this.

> You can go to the website or use color pick and then you'll get a feel of it.

Sorry but... no?? The whole point of this question is what is considered the *primary* color of Geode and it is clearly not just one here.

![Screenshot 2024-06-04 at 05 50 28 (Arc)](https://github.com/geode-sdk/geode/assets/47499684/432e0500-156d-4e1b-b234-887543a28d89)
