### ISSUE TITLE
Mods problem loading

### ISSUE THREAD

**Issue by rocholojavinar** [geode-sdk/geode#839]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### SDK commit

6510df7

### Geode Version

v2.0.0-beta.27

### Expected Behavior

Mods have been loaded

### Actual Behavior

Yesterday, mods were problems loading.

### Steps to Reproduce

I did the mods activated, but it was problem loading.

**Comment by iNUCi** [comment]
GD was updated to 2.206 and geode doesn't fully work with it yet

**Comment by PP09PetyaDecryptor** [comment]
yeee u need to wait
