### ISSUE TITLE
geode doesn't work

### ISSUE THREAD

**Issue by RUSLAN404100** [geode-sdk/geode#846]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0 beta 27

### Expected Behavior

I expected the geode to work. for example a new button in the menu

### Actual Behavior

Geode doesn't work as if I didn't download it
![Безымянныкцуей](https://github.com/geode-sdk/geode/assets/99784749/3cf1532d-973f-431a-8809-1813b2afcdad)

### Steps to Reproduce

I reinstalled Windows, it worked before

### Additional Information

Perhaps the geode does not work because it does not have the Windows Runtime it needs. As I said, I reinstalled Windows. Before downloading the Geometry dash, (not geode), it gave an error saying that there was no file, so I downloaded it from the Internet. Perhaps this also prevents it from working

**Comment by rocholojavinar** [comment]
![IMG](https://img.youtube.com/vi/kPMLbSXM97U/maxresdefault.jpg)

**Comment by heavyutils** [comment]
> ![IMG](https://img.youtube.com/vi/kPMLbSXM97U/maxresdefault.jpg)

Turi ip ip ip

**Comment by heavyutils** [comment]
> > ###
> 
> 
> 
> yes

Revert.

https://www.makeuseof.com/how-to-downgrade-steam-games/
