### ISSUE TITLE
Geode crashes on Android 64-bit, even on safemode

### ISSUE THREAD

**Issue by ActualHamish** [geode-sdk/geode#857]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v1.3.4

### Steps to Reproduce

1) Pressed the 'launch' button on the geode app
2) When the progress bar gets to roughly halfway, geode will crash.

### Crash Report

No trace of a crashlog

### Additional Information

I have tried this on a different Android 64-bit and the same issue persisted.

**Comment by cute-funny-cats-meow** [comment]
probably 2.206

**Comment by ActualHamish** [comment]
Worked perfectly fine on update day and the past 4 days. It's just now the issue is happening

**Comment by cute-funny-cats-meow** [comment]
> Worked perfectly fine on update day and the past 4 days. It's just now the issue is happening

idk then, you should use vanilla gd for now and check if that fixes the problem.

**Comment by Kingminer7** [comment]
Open settings and disable nightly release channel, then press check for updates.

**Comment by ActualHamish** [comment]
Tysm!!!
