### ISSUE TITLE
Geode not loading

### ISSUE THREAD

**Issue by frenchfrysays3** [geode-sdk/geode#864]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

latest

### Mods Installed

no mods

### Expected Behavior

for geode to load

### Actual Behavior

geode did not load

### Steps to Reproduce

I started up geometry dash, and the geode logo was not there

**Comment by Fleeym** [comment]
Geode is temporarily unavailable for 2.206, please be patient while we port it.
