### ISSUE TITLE
geode nightly doenst work

### ISSUE THREAD

**Issue by BaoIsCoding** [geode-sdk/geode#870]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

e910645

### Steps to Reproduce

I clicked GD,and it crashed

### Crash Report

[2024-06-08_18-04-01.log](https://github.com/user-attachments/files/15747656/2024-06-08_18-04-01.log)

**Comment by CNLover3** [comment]
It's been happening to me too since yesterday

**Comment by cipiar** [comment]
> Try the latest nightly version: https://github.com/geode-sdk/geode/releases

thanks i will try it since its a new commit. Also small question will it not be able to load if i have a texture pack like icedcave bcs i do

**Comment by cipiar** [comment]
> > Try the latest nightly version: https://github.com/geode-sdk/geode/releases
> 
> thanks i will try it since its a new commit. Also small question will it not be able to load if i have a texture pack like icedcave bcs i do

about that it did load but the button doesnt show up but its clickable

**Comment by BaoIsCoding** [comment]
i know but i done
