### ISSUE TITLE
GD crashes when opening the Geode menu

### ISSUE THREAD

**Issue by wind40** [geode-sdk/geode#873]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.0.0 Alpha

### Mods Installed

[cant retrieve because no crash window popped up]

### Steps to Reproduce

 - Installed Geode 3.0.0 Alpha to get mods back
 - Open Geode (works)
 - Close it for a while, then open again
 - GD crashes
 - Decide to install it with VS runtime
 - GD crashes again
 - Uninstall it altogether again
 - Install Geode without VS runtime
 - Open GD (works)
 - Open Geode menu
 - Menu does not show
 - GD freezes for about 2 seconds then crashes
 - No crash window

**Comment by hiimjustin000** [comment]
Download the [resources](https://github.com/geode-sdk/geode/releases/download/v3.0.0-alpha.1/resources.zip) and extract them to `Geometry Dash/geode/resources/geode.loader`

**Comment by DawningAgain** [comment]
@hiimjustin000 i am having the same problem. I did what you said and it still has the same problems.

**Comment by hiimjustin000** [comment]
Show me crashlog

**Comment by DawningAgain** [comment]
it crashes but it doesnt give me crashlog, even when i look in my crashlog folder nothing new is in there

**Comment by DawningAgain** [comment]
ok wait I just found something
if i have no mods in my mods folder it lets me go in there?

**Comment by hiimjustin000** [comment]
Yes it does

**Comment by DawningAgain** [comment]
yeah wait i tried something
without mods it works
with some mods it works
therefore it probably is a mod that is causing the issue and not geode
@wind40 whats ur mods folder?

**Comment by DawningAgain** [comment]
nvm i found it its the Texture Loader mod
i do not think this is a geode thing?

**Comment by Fernanfloo1234** [comment]
Quiero jugar online
