### ISSUE TITLE
geode not loading

### ISSUE THREAD

**Issue by cipiar** [geode-sdk/geode#874]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### SDK commit

3ab7077

### Geode Version

Pre-release commit 3ab7077

### Mods Installed

gamemode picker,globed,icon_hack,custom keybinds,node ids, texture loader,unlisted objects in editor,openhack and click between frames
![mod screenshot](https://github.com/geode-sdk/geode/assets/168566558/bc7b5461-0f87-4c2c-a028-914da92b9540)

### Expected Behavior

expected it to open and load normally(the version supported 2.206)

### Actual Behavior

gave an error code thats 1114

### Steps to Reproduce

install pre-release build and open the game and it gave the error code 1114

### Additional Information

i have icedcave texture pack along with the icons and menu icons with futura ui
![geode errror code](https://github.com/geode-sdk/geode/assets/168566558/e9473696-c31a-4d55-aee3-eafa993f7b4f)

**Comment by cipiar** [comment]
i tryed to open geometry dash with geode installed it just gave me an error code 1114, what is causing it?

**Comment by mastergamer2710** [comment]
idk i have som proplem

**Comment by cipiar** [comment]
> idk i have som proplem

you are having the same problem?

**Comment by ImLegiitXD** [comment]
i try the same thing, but it doesnt gives me a error.
it just doesnt load

**Comment by cipiar** [comment]
> i try the same thing, but it doesnt gives me a error. it just doesnt load

in that case which build are you using with geode? im using nightly

**Comment by DawningAgain** [comment]
i believe texture loading mod has some problems, so maybe remove it from your folders and try again? that a lot of my issues with geode not working correctly

**Comment by matcool** [comment]
update your visual c++ redistributables: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by cipiar** [comment]
i already had the newest one and it now works since i changed commit version to the newest
