### ISSUE TITLE
Safe Mode For Windows

### ISSUE THREAD

**Issue by DragosDobrican** [geode-sdk/geode#878]
### Geode Version

V2.0.0-Beta.27

### Related Problem

I'm always frustrated because I can't use safe mode on my computer, I can only use safe mode on my phone.

### Your Solution

Adding a shortcut to safe mode on the desktop to enable/disable safe mode, there should be something like this for mobile but it's in the geode APK instead of a widget

**Comment by DragosDobrican** [comment]
but I can't even OPEN geometry dash and i don't wanna uninstall geode

**Comment by Denyscrasav4ik** [comment]
try holding shift while launching the game

**Comment by DragosDobrican** [comment]
> try holding shift while launching the game

Will this work if I'm launching with steam?

**Comment by Denyscrasav4ik** [comment]
It should

**Comment by DragosDobrican** [comment]
it doesn't work :(

**Comment by chaicken** [comment]
for me it works by pressing shift
