### ISSUE TITLE
Geode not working on Linux

### ISSUE THREAD

**Issue by Rustring** [geode-sdk/geode#879]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Linux (Windows GD)

### Geode Version

Latest dev build at the time

### Mods Installed

None 

### Expected Behavior

Geode opens like in 2.204 (2.0.0-beta.7)

![Screenshot_20240609_025912](https://github.com/geode-sdk/geode/assets/155897302/97858da5-6185-41b2-aac3-2c3c6c5b0d6c)

### Actual Behavior

Geode doesn't work on 2.206 (3.0.0-alpha.1)

![Screenshot_20240609_030130](https://github.com/geode-sdk/geode/assets/155897302/1e0ff0ce-ccf2-4089-9646-8a0ec06cc944)

### Steps to Reproduce

Put `WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%` in steam's launch options on Linux and launch GD 2.206 on the latest build of Geode

**Comment by dankmeme01** [comment]
launch option has changed, it is now `WINEDLLOVERRIDES="xinput1_4=n,b`

**Comment by Rustring** [comment]
That doesn't wrok

**Comment by dankmeme01** [comment]
what happens instead? is there any popup indicating an error?

make sure you've extracted all the necessary files, your game folder should have a `Geode.dll` and an `XInput1_4.dll` from the latest alpha release

**Comment by Rustring** [comment]
> what happens instead? is there any popup indicating an error?
> 
> make sure you've extracted all the necessary files, your game folder should have a `Geode.dll` and an `XInput1_4.dll` from the latest alpha release

GD Launches w/o Geode and I reinstalled it and it still doesn't work

**Comment by simpansoftware** [comment]
Can confirm that GD launches without geode but no errors

**Comment by ItsFrocat** [comment]
For me GD launches with Geode with this: "WINEDLLOVERRIDES="XInput1_4=n,b" %command%" launch option.

**Comment by Rustring** [comment]
> For me GD launches with Geode with this: "WINEDLLOVERRIDES="XInput1_4=n,b" %command%" launch option.

It works thank you

**Comment by macisgreat** [comment]
neither work for me.
[2024-06-23_09-12-52.log](https://github.com/user-attachments/files/15944984/2024-06-23_09-12-52.log)
[2024-06-23_09-14-41.log](https://github.com/user-attachments/files/15944986/2024-06-23_09-14-41.log)

**Comment by Acemany** [comment]
> Update: i fixed it
But how?
