### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by MalikHw** [geode-sdk/geode#890]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.0.0-alpha2

### Mods Installed

No mod

### Expected Behavior

i expect that the internet in gme will work

### Actual Behavior

but it didnt

### Steps to Reproduce

i am on linux,
wine is working normally
and other wine apps has internet only gd after installing geode

**Comment by Tamarindo-XD** [comment]
can you update the alpha without downloading the installers all the time?

**Comment by MalikHw** [comment]
NO
maybe bcz the xinput library has been changed
bcz xinput9_1_0 works fine with geode 2.0.0 GD 2.204 but the alpha uses xinput1_4 which made the issue
