### ISSUE TITLE
Add iOS Support

### ISSUE THREAD

**Issue by Foxiseminger** [geode-sdk/geode#898]
### Geode Version

3.0.0 alpha 2

### Your Solution

iOS Support

### Additional Information

This is likely possible by getting a 2.206 IPA and modding it.

**Comment by hiimjustin000** [comment]
Apple's restrictions are too harsh for something like a mod loader to happen. It could work, but only if you had every mod pre-installed.

It is possible, though, but there are a lot of hoops and loops to jump over. iCreate Pro is simple, since it is just one mod, but for Geode, it is way more difficult.

**Comment by Foxiseminger** [comment]
then how did you do it on android?

**Comment by iNUCi** [comment]
> then how did you do it on android?

android is a lot more open and allows doing this kind of stuff easily

**Comment by Foxiseminger** [comment]
ok cuz i have an iPhone and I really want geode on my iPhone (iOS 18). Also I already tried iCreate Pro, it has a 24-hour limit, and i do not want to spend money on a product key.

**Comment by iNUCi** [comment]
> ok cuz i have an iPhone and I really want geode on my iPhone (iOS 18). Also I already tried iCreate Pro, it has a 24-hour limit, and i do not want to spend money on a product key.

shoulda bought an android

**Comment by Foxiseminger** [comment]
lol

**Comment by Foxiseminger** [comment]
i got an idea: Have all the mods already preinstalled, and be able to just choose which ones to enable.

**Comment by HJfod** [comment]
I mean we could consider having distributions of Geode with a bunch of popular mods preinstalled. Not sure if we feel like maintaining that as that would kind of make us responsible for mods, but maybe.

**Comment by Foxiseminger** [comment]
ok

**Comment by ImmediateMurderProfessionals** [comment]
> I mean we could consider having distributions of Geode with a bunch of popular mods preinstalled. Not sure if we feel like maintaining that as that would kind of make us responsible for mods, but maybe.

This is unrelated but are you the same HJfod from the sonic wave remix

**Comment by ImmediateMurderProfessionals** [comment]
> i got an idea: Have all the mods already preinstalled, and be able to just choose which ones to enable.

Good idea
