### ISSUE TITLE
Cannot build any mods

### ISSUE THREAD

**Issue by XEN486** [geode-sdk/geode#907]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0-beta.1

### Expected Behavior

Expected to build by using "geode build"

### Actual Behavior

During "Creating library", it started spewing error LNK2019 and "warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'".
Build failed with xenon2028.testmod.dll : fatal error LNK1120: 305 unresolved externals

### Steps to Reproduce

1) I created a new project with "geode new"
2) I set the version to 2.206 (this also happened with 2.204)
3) I built the example mod generated

**Comment by hiimjustin000** [comment]
What IDE do you use?

**Comment by XEN486** [comment]
visual studio 2022

**Comment by hiimjustin000** [comment]
Change the arch in `CMakeSettings.json` from `msvc_x86` to `msvc_x64`

**Comment by XEN486** [comment]
I couldn't find CMakeSettings.json but turns out if I first create a project with geode new but open it with VS (without doing geode build) it compiles fine. I don't know why "geode build" makes it not want to work

**Comment by hiimjustin000** [comment]
Okay, I think I know the problem now.
Update your CLI, please.

**Comment by XEN486** [comment]
updating the CLI fixed it! I just checked and the winget version (what I was using before) is out of date, it's on version 2.11.0 instead of the latest 3.0.1. I installed the scoop version instead which is actually up to date and it works!
