### ISSUE TITLE
Setup showing Boost agreement of 2003

### ISSUE THREAD

**Issue by Real3rr0r** [geode-sdk/geode#912]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

latest ver you have uploaded

### Mods Installed

No mods

### Expected Behavior

2024 agreement

### Actual Behavior

2003 agreement

### Steps to Reproduce

1 open the installer
2 select your language
3 then next 
4 then agreement will show

### Additional Information

Nothing I just wanted to update you

**Comment by matcool** [comment]
the boost license has not changed since 2003.
