### ISSUE TITLE
My game keeps crashing and I have no idea why

### ISSUE THREAD

**Issue by Polarsame** [geode-sdk/geode#914]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

most recent as of 6/17/2024

### Mods Installed

geode.node-ids

gdutilsdevs.gdutils

### Steps to Reproduce

I installed geode, got like 3 mods, restarted and then it crashed.

### Crash Report

2024-06-17T12:48:53-0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.0.0-alpha.2
Loader Commit: 341c735
Bindings Commit: 35be98f
Installed mods: 3
Problems: 0

== Exception Information ==
Faulty Module: C:\WINDOWS\SYSTEM32\ntdll.dll
Faulty Mod: <Unknown>
Exception Code: c0000139 (<Unknown>)
Exception Flags: 129
Exception Address: 00007FF9AA27F90D (ntdll.dll + 10f90d (RtlRaiseStatus + 61))
Number Parameters: 0
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 10f90d (RtlRaiseStatus + 61)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + c1c5 (RtlGetPersistedStateLocation + 3493)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + b94c8 (EtwLogTraceEvent + 34488)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 24c54 (RtlImageNtHeaderEx + 916)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 2c8d8 (LdrControlFlowGuardEnforced + 1480)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 10b0f (RtlQueryPerformanceCounter + 591)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 114f0 (RtlQueryPerformanceCounter + 3120)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 112bf (RtlQueryPerformanceCounter + 2559)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 28db4 (RtlImageRvaToSection + 484)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 190ac (RtlUnicodeToCustomCPN + 1020)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 2a73a (LdrLoadDll + 250)
 - C:\WINDOWS\System32\KERNELBASE.dll + 2b5a2 (LoadLibraryExW + 370)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll + 9e623 (OverlayHookD3D3 + 157331)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll + 9eafb (OverlayHookD3D3 + 158571)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 22865c (geode::Mod::Impl::loadPlatformBinary + 156 | D:\a\geode\geode\loader\src\platform\windows\ModImpl.cpp:77)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + a1691 (geode::Mod::Impl::loadBinary + 481 | D:\a\geode\geode\loader\src\loader\ModImpl.cpp:404)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 7f794 (geode::Loader::Impl::loadModGraph::<lambda_0>::operator() + 132 | D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:423)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 8488c (geode::utils::MiniFunctionState<`lambda at D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:494:37',void>::call + 76 | D:\a\geode\geode\loader\include\Geode\utils\MiniFunction.hpp:29)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 83192 (geode::Loader::Impl::executeMainThreadQueue + 242 | D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:823)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5e6ed (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | D:\a\geode\geode\build\bindings\bindings\Geode\modify\CCScheduler.hpp:115)
 - 000001E9BDDF3C9B
 - 00000000003F0CC8
 - C:\WINDOWS\System32\USER32.dll + 25a51 (GetKeyState + 145)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d4374 (cocos2d::CCPoint::unrotate + 18020)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 22ed6a (gdMainHook + 554 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:124)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: ffffffffc0000101
RCX: 0000003c1797d278
RDX: 0000000000000000
RBP: 0000003c1797deb0
RSP: 0000003c1797d810
RDI: 000001e9cd3bb1d8
RSI: 00000000c0000101
RIP: 00007ff9aa27f90d
R8:  0000000000000000
R9:  0000000000000000
R10: 0000000000000000
R11: 0000000000000000
R12: 00007ff9512efb4e
R13: 0000000000000000
R14: 0000000000000003
R15: 0000000000000003

== Installed Mods ==
o | [v1.3.0-alpha.14] gdutilsdevs.gdutils
x | [v3.0.0-alpha.2] geode.loader
x | [v1.12.0] geode.node-ids

### Additional Information

When will megahack be updated?

**Comment by iNUCi** [comment]
The most recent version is beta 1 not alpha 2

**Comment by Polarsame** [comment]
> The most recent version is beta 1 not alpha 2

oh. i didnt know. oops
