### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by BlackGreen342** [geode-sdk/geode#918]
### Geode Issue

- [ ] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### SDK commit

v2.0.0-beta.27

### Geode Version

v1.3.4

### Mods Installed

Downloading Globed, did not load the pack

### Expected Behavior

Confused

### Actual Behavior

It supposed to download the pack

### Steps to Reproduce

I did try to Uninstalled geode and installed UT back and it is still not available

### Additional Information

It will not work on other mods as well

**Comment by zkayns** [comment]
ok if your listening to 2pac and you already have 2 packs you cant get more packs because his name is 2pac like the rapper 2pac
![image](https://github.com/geode-sdk/geode/assets/80561998/bead86cd-213d-46eb-a3ae-d80da389e5fe)

**Comment by matcool** [comment]
what
