### ISSUE TITLE
Geode completely breaks GD.

### ISSUE THREAD

**Issue by AzuraTheRagdoll** [geode-sdk/geode#919]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0-beta.1

### Mods Installed

[v1.1.2] TheSillyDoggo.StartposSwitcher
[v1.0.6] abb2k.backup
[v1.0.2] acaruso.pride
[v1.1.3] alphalaneous.ezclipboard
[v1.3.7] alphalaneous.happy_textures
[v1.1.1] alphalaneous.hide
[v1.4.3] alphalaneous.integratedloquibot
[v1.2.3] alphalaneous.projectedstars
[v1.1.3] alphalaneous.random_tab
[v1.1.7] b1rtek.gddlintegration
[v1.0.1] bitz.darkmode_v4
[v1.0.4] bitz.moregames
[v1.1.4] capeling.icon_profile_2.2
[v1.0.0] capeling.usable_explorers
[v1.0.4] cdc.level_thumbnails
[v1.0.1] cdc.statuses
[v1.2.0] cgytrus.menu-shaders
[v2.0.1] cgytrus.smooth-particles
[v1.5.2] coopeeo.customname
[v4.2.0-alpha.3] cvolton.betterinfo
[v1.2.0-alpha.3] cvolton.misc_bugfixes
[v1.0.1] elsai.easing_preview
[v1.0.6] firee.goldenbest
[v0.1.2] flafy.autonong
[v2.9.0] fleym.nongd
[v1.5.9] geode.custom-keybinds
[v3.0.0-alpha.2] geode.loader
[v1.12.0] geode.node-ids
[v1.6.0-beta.3] geode.texture-loader
[v1.2.0] grian.art_importer
[v1.3.9-beta.1] hiimjustin000.better_icon_randomizer
[v1.0.5-beta.1] hiimjustin000.demons_in_between
[v1.4.9] hiimjustin000.integrated_demonlist
[v1.0.8-beta.1] hiimjustin000.more_object_info
[v1.0.2-beta.1] hiimjustin000.na_demon
[v6.4.3] hjfod.betteredit
[v1.3.0] hjfod.bettersave
[v1.0.5] hjfod.gdshare
[v1.1.0] hjfod.gmd-api
[v1.2.0-alpha.2] itzkiba.better_progression
[v1.3.4] m336.levelinfo
[v1.0.3] mat.max-window
[v1.0.0] mat.reference-image
[v1.0.0-beta.21] minemaker0430.gddp_integration
[v1.1.1] mishpro.comments_in_pause_menu
[v1.2.0] ml5.treasure-checklist
[v2.0.4-beta.3] muhammadgames.bettermenu
[v1.4.0-beta.1] oatmealine.ids_integration
[v1.4.0-beta.2] oatmealine.nlw_integration
[v1.5.0-beta.2] omgrod.garage_plus
[v1.1.0] polsk.ratinginfo
[v1.4.1] prevter.bettercrash
[v2.3.2] prevter.openhack
[v1.1.2] raydeeux.disturbingnewbests
[v1.0.1] relative.advanced_song_search
[v0.1.7] rooot.custom-gamemode-colors
[v1.1.2] rynat.better_unlock_info
[v1.2.0] shineua.geometrize2gd
[v2024.229.0] tastyforreal.google-translate
[v2.11.0] techstudent10.discord_rich_presence
[v1.6.2-beta] terma.ambienticons
[v1.0.0-beta.8] thesillydoggo.comment_emojis
[v1.4.4-beta.5] thesillydoggo.qolmod
[v1.1.1] uproxide.autosong
[v1.4.2] uproxide.more_difficulties
[v1.3.0] uproxide.user_reviews
[v6.0.0-beta.7] user95401.mainlevelseditor
[v1.0.1] viper.guwude
[v1.1.3-beta.2] weebify.restartbtn
[v1.1.0-beta.3] weebify.separate_dual_icons
[v1.0.0] xanii.level_ratings
[v1.2.1-beta.1] ziegenhainy.xxlify
[v1.0.1] zsa.percentage-bugfix

### Steps to Reproduce

1) Install Geode (any version above v2.0.0-beta.27)
2) Run Geometry Dash (either through Steam, or the .exe file)

### Crash Report

https://pastebin.com/AApPUYNb

### Additional Information

Geode made Geometry Dash unopenable, and the only way to fix that issue was to uninstall Geode.

**Comment by FireMario211** [comment]
maybe dont have a bunch of mods installed. Also if you read the crash log, it looks to be related to qolmod

If you really wanted to report a Geode issue, **make sure all mods are disabled**

**Comment by OmgRod** [comment]
it also seems to be you use 2.206 but have mods made for 2.204 so maybe thats why. did you try transferring mods from 2.204 to 2.206? it could be that if so.
