### ISSUE TITLE
Error 193

### ISSUE THREAD

**Issue by ThisIsNotFroxX** [geode-sdk/geode#922]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.27

### Steps to Reproduce

opening the game

### Crash Report

![Captura de pantalla 2024-06-17 231537](https://github.com/geode-sdk/geode/assets/173212121/761b51dd-f2ab-4ba1-a5a3-19d8a0c86ce9)

### Additional Information

idk why it happens, in other pc it works, but it doesn't work on mine

**Comment by Aworldc** [comment]
same issue with v3.0.0

**Comment by Aworldc** [comment]
solved it, need to close gd while intalling
