### ISSUE TITLE
Geode is preventing the startup of my geometry dash

### ISSUE THREAD

**Issue by GDMonarch** [geode-sdk/geode#923]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0 beta.1

### Steps to Reproduce

delete all files exept resources then reinstall

**Comment by zkayns** [comment]
ok right so basically deleting the game files makes the game not start
![image](https://github.com/geode-sdk/geode/assets/80561998/449b11e1-c8d1-45df-b59a-677387e5736d)

**Comment by Nebularzz** [comment]
you have to be trolling
