### ISSUE TITLE
Geometry Dash does not even open when Geode is installed

### ISSUE THREAD

**Issue by AcePainiteGD** [geode-sdk/geode#929]
### Geode Issue

- [ ] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0-beta.2

### Mods Installed

syzzi.click_between_frames v1.10.0
alphalaneous.happy_textures v1.3.7
i forgot the rest

### Steps to Reproduce

1) Open Geometry Dash
2) Does not open
3) Uninstall Geode
4) Geometry Dash opens
5) Install latest beta version of Geode
6) Does not open
7) This shit worked yesterday why today no work
8) Give up

### Crash Report

No crashlog and empty log file

**Comment by susigreg** [comment]
geode does that to me

**Comment by GDMonarch** [comment]
my geode made gd stop working totally stop making shit devs

**Comment by RoootTheFox** [comment]
> stop making shit devs

how about YOU make Geode better if the devs are making shit??
can YOU make Geode better? if not, be nice to them and dont leave unnecessary comments on issues.

As for the issue: @AcePainiteGD @susigreg can you give more details?
as in, GD version, Geode version, operating system/platform and how the crash happens (does GD open at all, do you get a crashlog, etc)

**Comment by AcePainiteGD** [comment]
> > stop making shit devs
> 
> how about YOU make Geode better if the devs are making shit?? can YOU make Geode better? if not, be nice to them and dont leave unnecessary comments on issues.
> 
> As for the issue: @AcePainiteGD @susigreg can you give more details? as in, GD version, Geode version, operating system/platform and how the crash happens (does GD open at all, do you get a crashlog, etc)

No crashlogs and GD does not even launch, background process opens and peaces out 5 seconds later

**Comment by iNUCi** [comment]
> > > stop making shit devs
> > 
> > 
> > how about YOU make Geode better if the devs are making shit?? can YOU make Geode better? if not, be nice to them and dont leave unnecessary comments on issues.
> > As for the issue: @AcePainiteGD @susigreg can you give more details? as in, GD version, Geode version, operating system/platform and how the crash happens (does GD open at all, do you get a crashlog, etc)
> 
> No crashlogs and GD does not even launch, background process appears and peaces out 5 seconds later

sounds like a lack of visual c++ redistributable https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by AcePainiteGD** [comment]
> > > stop making shit devs
> > 
> > 
> > how about YOU make Geode better if the devs are making shit?? can YOU make Geode better? if not, be nice to them and dont leave unnecessary comments on issues.
> > As for the issue: @AcePainiteGD @susigreg can you give more details? as in, GD version, Geode version, operating system/platform and how the crash happens (does GD open at all, do you get a crashlog, etc)
> 
> No crashlog and GD does not even launch, background process appears and peaces out 5 seconds later

[Geode 2024-06-20 19.53.04.log](https://github.com/user-attachments/files/15914281/Geode.2024-06-20.19.53.04.log)
the log file is also empty

**Comment by cgytrus** [comment]
there is not

**Comment by RoootTheFox** [comment]
yeah silly me forget that Geode logs stuff while initializing, and it only sets up the crash handler during initialization so it *can't* log a crash, my bad

**Comment by AcePainiteGD** [comment]
> is there a `_geode_early_error.txt` file in the game folder?

no

**Comment by AcePainiteGD** [comment]
> > > As for the issue: @AcePainiteGD @susigreg can you give more details? as in, GD version, Geode version, operating system/platform and how the crash happens (does GD open at all, do you get a crashlog, etc)
> > 
> > 
> > No crashlogs and GD does not even launch, background process appears and peaces out 5 seconds later
> 
> sounds like a lack of visual c++ redistributable https://aka.ms/vs/17/release/vc_redist.x64.exe

ok c++ was broken so i repaired it, it opens again. thank you kind stranger
