### ISSUE TITLE
Geode says it's in version 0.6.99999999 when attempting to install an incompatible mod 

### ISSUE THREAD

**Issue by Tiago1257** [geode-sdk/geode#93]
### Platform

Windows

### Geode Version

v0.6.1

### Mods Installed

alk.editorcollab v1.3.0, mat.scroll-zoom 1.0.0, hjfod.devtools v0.0.5, mat.practice-music v1.0.1, com.mat.fps-bypass v1.0.0

(failed to load, can't check id or versions): acbypass, demonlist-button, noclip

### Expected Behavior

Expected version to show up as 0.6.1 or 0.7.0.

### Actual Behavior

Version showed up as 0.6.99999999
![image](https://user-images.githubusercontent.com/84469804/205455058-0aa18579-5010-4787-ad82-e46ef44294d1.png)

### Steps to Reproduce

1) Manually install acbypass, demonlist-button or noclip by camila314
2) Open the game, a pop-up saying some mods failed to load should come up
3) Open the Geode menu
4) Press "Info" on any of the mods that failed to load

### Additional Information

could be because of how different operating systems handle numbers? unsure

**Comment by altalk23** [comment]
Fixed in 0.7.0 already
But thank you
