### ISSUE TITLE
Gd is not working because of geode trust me even with latest action realese

### ISSUE THREAD

**Issue by GDMonarch** [geode-sdk/geode#932]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0 beta

### Mods Installed

latest action release

### Steps to Reproduce

delete files then reinstall

### Additional Information

problem with geode

**Comment by cursefroge** [comment]
well it is a devel version
