### ISSUE TITLE
Missing texture on top right while viewing mods

### ISSUE THREAD

**Issue by LumerGD120** [geode-sdk/geode#942]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### SDK commit

1f5ebf9

### Geode Version

3.0.0-beta.5

### Mods Installed

![Screenshot_2024-06-22-17-12-11-71](https://github.com/geode-sdk/geode/assets/147040389/4393942e-d82d-4844-975e-5c1bc920c4e7)
![Screenshot_2024-06-22-17-12-27-19](https://github.com/geode-sdk/geode/assets/147040389/163cea35-273f-47f8-82d8-4092e393782c)
![Screenshot_2024-06-22-17-12-34-56](https://github.com/geode-sdk/geode/assets/147040389/98e6960d-38f7-41bd-8fac-1c00f349490a)
![Screenshot_2024-06-22-17-12-40-41](https://github.com/geode-sdk/geode/assets/147040389/492153a0-728f-4063-9a7f-ca4d8cacac60)
![Screenshot_2024-06-22-17-12-44-65](https://github.com/geode-sdk/geode/assets/147040389/8fdf8abf-6bd3-45bf-8f72-aeb45a25206b)

### Expected Behavior

I expected there was a button called "versions"

### Actual Behavior

![Screenshot_2024-06-22-17-03-25-69](https://github.com/geode-sdk/geode/assets/147040389/eb310cd7-2ae4-41b2-b024-674054e4a74d)

### Steps to Reproduce

Just view a mod

**Comment by cute-funny-cats-meow** [comment]
it was removed
