### ISSUE TITLE
1.4.0 Error 

### ISSUE THREAD

**Issue by Maax234** [geode-sdk/geode#947]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

1.4.0

### Expected Behavior

The game Launch normally

### Actual Behavior

![Screenshot_20240622-160732_Geode](https://github.com/geode-sdk/geode/assets/130312651/6151bf2f-42b7-4a47-a50d-69d5d2a3b637)

### Steps to Reproduce

Only press Launch , and show the error

**Comment by Maax234** [comment]
help , please :(

**Comment by skypulse1332** [comment]
Is Geode updated?
