### ISSUE TITLE
Crashes on opening File Explorer "Open" prompt if mods allow it.

### ISSUE THREAD

**Issue by Octostomp** [geode-sdk/geode#949]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0

### Mods Installed

== Installed Mods ==
x | [v1.1.5] adyagd.godlikefaces
x | [v1.1.1] alphalaneous.editorsounds
x | [v1.1.4] alphalaneous.ezclipboard
x | [v1.3.16] alphalaneous.happy_textures
x | [v1.0.5] alphalaneous.pages_api
x | [v1.2.3] alphalaneous.projectedstars
x | [v1.1.4] alphalaneous.random_tab
x | [v1.1.8] b1rtek.gddlintegration
x | [v1.1.2-beta.3] bitz.customprofiles
x | [v1.2.3] blueblock6.cleanstartpos
x | [v4.2.0-beta.2] cvolton.betterinfo
x | [v1.2.0-beta.1] cvolton.misc_bugfixes
x | [v1.3.3-alpha.2] elnexreal.copy_song_id
x | [v2.0.0-beta.10] elohmrow.death_tracker
x | [v0.2.0] flafy.autonong
x | [v2.10.1] fleym.nongd
x | [v1.3.0-beta.4] gdutilsdevs.gdutils
x | [v1.6.0] geode.custom-keybinds
x | [v3.0.0] geode.loader
x | [v1.12.0] geode.node-ids
x | [v1.0.2] hiimjustin000.na_demon
x | [v1.2.1] itzkiba.better_progression
x | [v1.0.0] mat.song-preview
x | [v1.6.0-alpha.2] omgrod.garage_plus
x | [v1.4.2] prevter.bettercrash
x | [v1.5.0] uproxide.more_difficulties
x | [v1.1.3] weebify.restartbtn
x | [v1.2.1-beta.2] ziegenhainy.xxlify

### Steps to Reproduce

1) Download any mod that allows you to open a file from within the game (E.G: Jukebox)
2) Perform the action that would cause the prompt for that to open.
3) Crashes. Note that some people do not experience this bug.

### Crash Report

[2024-06-22_16-48-57.txt](https://github.com/user-attachments/files/15938295/2024-06-22_16-48-57.txt)

### Additional Information

According to Fleeym [here](https://github.com/Fleeym/jukebox/issues/47#issuecomment-2172456631) this is a problem with Geode's crashlog handler, and thus I put this here. Stack trace doesn't seem to lead to Jukebox's DLL, so I think this is a geode problem.

**Comment by sphericle** [comment]
hi

**Comment by Octostomp** [comment]
ZCB Live also is affected by this

**Comment by dankmeme01** [comment]
this was an issue with bettercrashlogs, that should've been fixed by now. update that mod to the latest version.
