### ISSUE TITLE
Curl failed: SSL connect error

### ISSUE THREAD

**Issue by edwloef** [geode-sdk/geode#954]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.0.0

### Expected Behavior

no errors while downloading mods or mod lists

### Actual Behavior

"Curl failed: SSL connect error" or failed mod downloads

### Steps to Reproduce

1. Open geode page
2. Switch to featured tab

### Additional Information

Spamming the refresh button usually makes the mod lists download in some capacity. It seems random whether a mod will download or not at any given time.

Am running Geode through Proton GE 9.7 with `WINEDLLOVERRIDES="XInput1_4=n,b"`

**Comment by edwloef** [comment]
This seems to no longer be an issue for me.

**Comment by W2luck** [comment]
do you know how this was fixed
