### ISSUE TITLE
Is Geode on IOS

### ISSUE THREAD

**Issue by skypulse1332** [geode-sdk/geode#956]
### Your Question

Is Geode on IOS, if it's not will you add support to IOS?

**Comment by RoootTheFox** [comment]
no, and this won't happen anytime soon if ever due to technical issues with iOS (restrictions made by apple)

**Comment by qimiko** [comment]
duplicate of #528 

please don't get yourself scammed. it won't be a thing
https://twitter.com/GeodeSDK/status/1804255622331805814
