### ISSUE TITLE
Geode is not working

### ISSUE THREAD

**Issue by enessmr** [geode-sdk/geode#959]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.0.0

### Mods Installed

I cant

### Expected Behavior

Geode will work in GD 2.204.

### Actual Behavior

GD works but geode doesnt work

### Steps to Reproduce

I updated Geode

### Additional Information

Idk

**Comment by mocca200** [comment]
i think geode v3.0.0 is for geometry dash v2.206, not v2.204. so you can't update geode without it not working

**Comment by enessmr** [comment]
sIgh, I cant do download GD 2.206
