### ISSUE TITLE
`'type cast': cannot convert from 'void (__cdecl *)(cocos2d::CCObject *)' to 'cocos2d::SEL_MenuHandler'` error when using `menu_selector`

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#96]
### Platform

Windows

### Geode Version

v1.1.1

### Mods Installed

Bug is related to SDK

### Expected Behavior

When using `menu_selector` in a callback for `CCMenuItemToggler::create`, the program should compile and callback is ran when the button is clicked.

### Actual Behavior

The compiler errors out saying that

```
'type cast': cannot convert from 'void (__cdecl *)(cocos2d::CCObject *)' to 'cocos2d::SEL_MenuHandler'
```

### Steps to Reproduce

1. Create a new `CCMenuItemToggler` using the `create` member function.
2. Use a function like so passed in using `menu_selector`
```cpp
void toggleNoclip(CCObject* sender) {
    noclipenabled = !noclipenabled;
}
```

### Additional Information

This bug is related to the SDK, not the loader.

**Comment by poweredbypie** [comment]
This isn't a bug; it's how stock cocos2d 2.2.3 works. To fix this, put the callback in a class that inherits from CCObject:

```cpp
class A : public CCObject {
public:
    void toggleNoclip(CCObject* sender) {
        // ...
    }
}
```

**Comment by TechStudent10** [comment]
Okay this was fixed by making `toggleNoclip` a member function of my popup.

Detailed explanation: All I had to do was
1. Define `toggleNoclip` in my header file
2. Make `toggleNoclip` a member function of my popup
3. Profit

**Comment by TechStudent10** [comment]
Game still crashes but for a totally different reason that I am now going to spend hours on /s
