### ISSUE TITLE
Game failing to hook the game's memory on Snap version of Steam

### ISSUE THREAD

**Issue by JustHackedTV** [geode-sdk/geode#960]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0 (Website Download)

### Mods Installed

No mods installed, clean geode

### Steps to Reproduce

1) Lauch game
2) Crash

### Crash Report

Error Box:
![image](https://github.com/geode-sdk/geode/assets/78915697/538e827b-89a3-4e87-b80b-8a42556283ae)

Geode didn't generate any logs, but here is the steam console for help:
GameAction [AppID 322170, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 322170, ActionID 6] : LaunchApp changed task to Completed with ""
ThreadGetProcessExitCode: no such process 84841
ThreadGetProcessExitCode: no such process 84839
ThreadGetProcessExitCode: no such process 84766
ThreadGetProcessExitCode: no such process 84844
Game process updated : AppID 322170 "WINEDLLOVERRIDES="XInput1_4=n,b" /home/ian/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=322170 -- /home/ian/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/Geometry Dash/GeometryDash.exe'", ProcID 84840, IP 0.0.0.0:0
ThreadGetProcessExitCode: no such process 84912
ThreadGetProcessExitCode: no such process 84895
ThreadGetProcessExitCode: no such process 84878
ThreadGetProcessExitCode: no such process 84872
ThreadGetProcessExitCode: no such process 84859
ThreadGetProcessExitCode: no such process 84849
ThreadGetProcessExitCode: no such process 84846
ThreadGetProcessExitCode: no such process 84838
ThreadGetProcessExitCode: no such process 84765
ThreadGetProcessExitCode: no such process 84764
Game process removed: AppID 322170 "WINEDLLOVERRIDES="XInput1_4=n,b" /home/ian/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=322170 -- /home/ian/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/ian/snap/steam/common/.local/share/Steam/steamapps/common/Geometry Dash/GeometryDash.exe'", ProcID 84840

### Additional Information

I'm running Linux Ubuntu, using Proton 9.0-2
Launch Option: "WINEDLLOVERRIDES="XInput1_4=n,b" %command%"

**Comment by JustHackedTV** [comment]
Forgot to add, Version: Ubuntu 24.04 LTS

**Comment by fbfnysnshnsgnwg** [comment]
Way I installed geode (linux mint user)
Rename installer to GeometryDash.exe in game folder
Open gd through steam, running the installer
After installation, renamed to geode.exe and added
`WINEDLLOVERRIDES="xinput1_4=n,b" %command%`
When you run gd now, it should show geode button.
Proton:
Geometry Dash>Properties>Compatibility>Force the use of a specific Steam Play compatibility tool (check)

**Comment by qimiko** [comment]
> Way I installed geode (linux mint user)
> ...
> When you run gd now, it should show geode button.

are you using steam from snap? i think this is a known issue with the snap version of steam. should probably update the title to reflect that lol

**Comment by JustHackedTV** [comment]
> Way I installed geode (linux mint user) Rename installer to GeometryDash.exe in game folder Open gd through steam, running the installer After installation, renamed to geode.exe and added `WINEDLLOVERRIDES="xinput1_4=n,b" %command%` When you run gd now, it should show geode button. Proton: Geometry Dash>Properties>Compatibility>Force the use of a specific Steam Play compatibility tool (check)

I've used the same method, could fix it after multiple versions of proton. Ended up just re-installing Ubuntu and it fixed it, so probably some specific error with my instalation.
