### ISSUE TITLE
"Could not load Geode!" (outdated redist package)

### ISSUE THREAD

**Issue by mocca200** [geode-sdk/geode#961]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0

### Expected Behavior

Geode v3.0.0 should be able to load in Geometry Dash v2.206a with no errors or problems.

### Actual Behavior

![image](https://github.com/geode-sdk/geode/assets/42464205/845bb9c4-5e37-4bab-a0b9-bdc00de410a2)
The error message I got.

I have tried updating and repairing Microsoft Visual C++ Redistributable 2022 x86 and x64, but the same error shows up. (I downloaded it from the official Microsoft website.)

![image](https://github.com/geode-sdk/geode/assets/42464205/123f0fac-7f32-42a9-9498-784bc233c96b)
![image](https://github.com/geode-sdk/geode/assets/42464205/b6df5c40-0af1-4813-b818-7e4f09e8b43c)
(If I've got the wrong versions, I'm terribly sorry.)

Also, when I click Yes on the error message to supposedly update Microsoft Visual C++ Redistributable 2022, nothing happens and the same error message pops up again after I try running Geometry Dash.

### Steps to Reproduce

1. Install Geode v3.0.0
2. Run Geometry Dash v2.206a
3. Error pops up and Geode is not loaded, while Geometry Dash itself runs perfectly fine.
![image](https://github.com/geode-sdk/geode/assets/42464205/c336d5de-f094-4453-99cd-d6bb9d5f942c)
no geode :(

**Comment by mocca200** [comment]
Actually, when I click Yes on the error message it prompts me to download VC_redist.x64.exe through my web browser. But it's the same version I already have.

**Comment by iNUCi** [comment]
If you have a msvcp140.dll in your geometry dash folder delete it

**Comment by mocca200** [comment]
There is no msvcp140.dll in my gd folder

**Comment by iNUCi** [comment]
> There is no msvcp140.dll in my gd folder

Ok are there any files in the folder that start with msvcp or msvcr

**Comment by masckmaster2007** [comment]
> > There is no msvcp140.dll in my gd folder
> 
> Ok are there any files in the folder that start with msvcp or msvcr

same issue, I have none of that

**Comment by mocca200** [comment]
> > There is no msvcp140.dll in my gd folder
> 
> Ok are there any files in the folder that start with msvcp or msvcr

No, there are do dlls that start with msv

**Comment by mocca200** [comment]
> > There is no msvcp140.dll in my gd folder
> 
> Ok are there any files in the folder that start with msvcp or msvcr

no, there is nothing even similar

**Comment by Cvolton** [comment]
so none of these files are present, right?

![image](https://github.com/geode-sdk/geode/assets/5721187/e927e4c7-59be-418e-a5f5-8cf3b5f528b3)
![image](https://github.com/geode-sdk/geode/assets/5721187/ae0930d2-d112-431c-b84c-00a333bd8791)
![image](https://github.com/geode-sdk/geode/assets/5721187/0b1be11c-9b2f-4bf3-abe6-fc43683d473d)

**Comment by mocca200** [comment]
> so none of these files are present, right?
> 
> ![image](https://private-user-images.githubusercontent.com/5721187/342338206-e927e4c7-59be-418e-a5f5-8cf3b5f528b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzI5MDEsIm5iZiI6MTcxOTIzMjYwMSwicGF0aCI6Ii81NzIxMTg3LzM0MjMzODIwNi1lOTI3ZTRjNy01OWJlLTQxOGUtYTVmNS04Y2YzYjVmNTI4YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTIzNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZmYzljNjUxZDkzYTFmYzgxNWEyN2IxMjQyY2JjMzk0ZDM2MjIzOTMwODIxNWIyMWVhMjJjMzEzY2VlMDRjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U848ufGK8attFAvSfC-5oDOoLeF-WWA1FB0Or8hr4XY) ![image](https://private-user-images.githubusercontent.com/5721187/342338248-ae0930d2-d112-431c-b84c-00a333bd8791.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzI5MDEsIm5iZiI6MTcxOTIzMjYwMSwicGF0aCI6Ii81NzIxMTg3LzM0MjMzODI0OC1hZTA5MzBkMi1kMTEyLTQzMWMtYjg0Yy0wMGEzMzNiZDg3OTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTIzNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjU3ZjdiZGE4N2NhZTYxMmM2ZDcyMGQwZWNiOWE0NGMzNGNlOTk5MjYzNjlhMjY0ZDc3YmMxNGUwYzVjYTc5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tmmueDVfat0_ktHETatnNhj1I__s5fAGgzVboiEyN44) ![image](https://private-user-images.githubusercontent.com/5721187/342338303-0b1be11c-9b2f-4bf3-abe6-fc43683d473d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzI5MDEsIm5iZiI6MTcxOTIzMjYwMSwicGF0aCI6Ii81NzIxMTg3LzM0MjMzODMwMy0wYjFiZTExYy05YjJmLTRiZjMtYWJlNi1mYzQzNjgzZDQ3M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTIzNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjMwM2E3MjUwNjRkOGUwMDYwODAwOWU2OTk5ZGE4ZWFjMjA5OTI0NDRlYTZkMzY1MGJmM2EwMzkzNzA1Mzg0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YbgBOYoxSS4vhMEZjVG4PkzqYK7SvHe7vfdE_YVd-2g)

no, none of those are in there.

**Comment by Cvolton** [comment]
have you tried if the issue still happens on geode 3.1.1? we included a fix for another possible cause of the issue

**Comment by mocca200** [comment]
> have you tried if the issue still happens on geode 3.1.1? we included a fix for another possible cause of the issue

Yes! It works! Thanks for fixing it :D

**Comment by geometry-dash-player** [comment]
I have the same problem I tried to update geode but it didn't work

**Comment by cafth26-hue** [comment]
i have the same issue and idk how to fix it. i downloaded 3.1.1 and still no

**Comment by az1234ivan** [comment]
> i have the same issue and idk how to fix it. i downloaded 3.1.1 and still no

Seeing this a month later but have you found any fix yet?

**Comment by az1234ivan** [comment]
> i have the same issue and idk how to fix it. i downloaded 3.1.1 and still no

I just found a fix actually. for me the newest version of Microsoft Visual C++ was saving on C:\WINDOWS\System32\HealthAttestationClient and from my experience the game checks the version that is in the C:\WINDOWS\System32 folder. VERY BIG DIFFRENCE. To check what exact thing was causing my error I went to Event Viewer and It showed me an error with MSVCP140.HLL in C:\WINDOWS\System32 so I figured where it was andsimply put it on my desktop then copied the newest version from C:\WINDOWS\System32\HealthAttestationClient and put it there and everything was running good. 

<img width="532" height="127" alt="Image" src="https://github.com/user-attachments/assets/d4e4f88b-083f-4d25-a829-e0b40303c886" />

Keep in mind that there are multiple MSVCP140.HLL's, but in the error it shows what version it was. To find the exact file just go to the exact folder where the error occured and check every MSVCP140.HLL's version ( you can easily do that by going to properties then going to details ). Now you just gotta match the error with the version and move that version out and put the newest one where the old one was. Copy it, don't just move it, It may do something bad, but I haven't tested it.

Sorry if my explanation was bad btw, first post on here
