### ISSUE TITLE
Shows white screen

### ISSUE THREAD

**Issue by LumerGD120** [geode-sdk/geode#962]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### SDK commit

It doesn't show

### Geode Version

3.0.0

### Mods Installed

No mods is included on this bug

### Expected Behavior

0

### Actual Behavior

Shows white screen when i press the back button or restarting the game like in this video

https://github.com/geode-sdk/geode/assets/147040389/ca4ce761-1452-4561-9f4e-25a6e072eaee

### Steps to Reproduce

Pressing the back button or restarting the game

### Additional Information

Also when i press the bacl button it shows white screen not my home screen

**Comment by TheShadowMonarch98** [comment]
I am also having a white screen but im on windows and it   was probably qolmod
