### ISSUE TITLE
Fullscreen crashes

### ISSUE THREAD

**Issue by STGamer24YT** [geode-sdk/geode#963]
### Geode Issue

- [x] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0

### Steps to Reproduce

1. Have 2.206 (Fullscreen has problems in this version)
2. Toggle fullscreen

### Additional Information

Note: I don't know if this happens with borderless mode

**Comment by cursefroge** [comment]
cant reproduce, what mods do you have?

**Comment by STGamer24YT** [comment]
> cant reproduce, what mods do you have?

I don't know what mods I had at the time, but it doesn't happen to me anymore. I know I had BetterEdit, BetterInfo, and I don't know if I had BetterMenu or not.
