### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by gogopipichocho** [geode-sdk/geode#972]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.0.0

### Mods Installed

geode v2.0.0-beta.27

### Steps to Reproduce

when I open the Globed, it says two things: "Failed to fetch server error 502" and "Creating challenge failed, error 502" can someone help, please?

### Crash Report

when I open the Globed, it says two things: "Failed to fetch server error 502" and "Creating challenge failed, error 502" can someone help, please?

**Comment by Cvolton** [comment]
issue unrelated to geode, please use the correct channels to report to the globed mod developers

however i can also tell you that globed has been disabled on gd 2.205, so you need to update your game and geode to use it

**Comment by gogopipichocho** [comment]
ok, thank you so much :)
