### ISSUE TITLE
Geometry Dash crashes shortly after title screen is displayed.

### ISSUE THREAD

**Issue by relaxingOcean** [geode-sdk/geode#984]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

Geode 3.11

### Mods Installed

== Installed Mods ==
! | [v2.2.4] TheSillyDoggo.GradientPages
! | [v1.0.5] abb2k.backup
! | [v1.0.0] acaruso.horn
x | [v1.0.5] acaruso.pride
! | [v0.1.6] acaruso.slope
! | [v1.1.3] adam_729.deathmarkers
x | [v1.1.5] adyagd.godlikefaces
! | [v1.2.10] alphalaneous.deathlink
x | [v1.0.1] alphalaneous.is_it_sent
x | [v1.0.9] alphalaneous.pages_api
x | [v1.2.5] alphalaneous.projectedstars
x | [v1.1.4] alphalaneous.random_tab
x | [v1.8.1] beat.click-sound
! | [v1.0.0] bigmancozmo.skip_editor_save_confirm
! | [v1.0.1] bitz.darkmode_v4
! | [v1.0.4] bitz.moregames
x | [v1.1.0] capeling.colored_level_info_bg
! | [v1.1.4] capeling.demons_in_garage_2.2
! | [v1.0.5] capeling.gamemode_picker
x | [v1.0.1] capeling.garage-stats-menu
x | [v1.2.1] capeling.icon_profile
! | [v1.0.0] capeling.usable_explorers
! | [v1.0.4] cdc.level_thumbnails
! | [v1.0.1] coderqc.gdswearfilter
! | [v1.3.1] creatorcreepy.unixsync
! | [v1.0.0] creo.color_unlock_hack
x | [v4.2.0-beta.3] cvolton.betterinfo
x | [v1.2.0-beta.1] cvolton.misc_bugfixes
x | [v1.4.3] dankmeme.globed2
x | [v1.0.4] dogotrigger.level_history
! | [v1.0.1] elnexreal.auto_priority
! | [v1.3.1] elsai.a_daily_shop
! | [v1.0.2] elsai.pause_menu_zoom
x | [v1.0.8] firee.goldenbest
x | [v1.8.0] firee.prism
x | [v2.10.1] fleym.nongd
x | [v1.3.1] gdutilsdevs.gdutils
x | [v1.6.2] geode.custom-keybinds
x | [v1.7.0] geode.devtools
x | [v3.1.1] geode.loader
x | [v1.12.0] geode.node-ids
x | [v1.6.1] geode.texture-loader
! | [v1.2.0] grian.art_importer
x | [v1.1.1] hiimjustin000.demons_in_between
x | [v1.1.2] hiimjustin000.level_size
x | [v1.0.8] hiimjustin000.more_object_info
x | [v1.0.1] hiimjustin000.requested_ratings
! | [v6.4.3] hjfod.betteredit
x | [v2.1.0] hjfod.bettersave
x | [v1.2.1] hjfod.gdshare
x | [v1.2.0] hjfod.gmd-api
x | [v1.2.1] itzkiba.better_progression
x | [v1.1.0] itzkiba.elegant_rankings
x | [v1.2.0] itzkiba.grandpa_demon
! | [v1.1.0] itzkiba.id_hyperlinks
! | [v1.0.0] izzy.i_hate_you_top_lists
x | [v1.0.3] jouca.badgesapi
! | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.2] mat.draw-divide
x | [v1.0.4] mat.max-window
x | [v1.1.2] mat.run-info
! | [v1.1.1] mishpro.comments_in_pause_menu
x | [v1.0.0] ml5.shopping-list
x | [v1.3.0-beta.4] ml5.treasure-checklist
x | [v2.0.4-beta.13] muhammadgames.bettermenu
x | [v2.0.1] naxrin.progress_bar_color
! | [v1.1.1] naxrin.rgb_icons
! | [v1.0.5] nytelyte.garage_utilities
! | [v1.1.0] polsk.ratinginfo
x | [v1.5.0] prevter.bettercrash
! | [v2.3.2] prevter.openhack
! | [v1.2.0] raydeeux.breakingplatforming
! | [v1.2.0] raydeeux.erysedits
! | [v1.0.0] raydeeux.pausemenuloop
! | [v1.1.3] raydeeux.wholesomeendtexts
x | [v1.2.3] redlime.statchanges
! | [v1.0.2] relative.account_statuses
! | [v1.0.1] relative.advanced_song_search
! | [v1.0.0] relative.scroll_faster_with_ctrl
  | [v0.1.8] rooot.custom-gamemode-colors
x | [v1.1.3] rynat.better_unlock_info
x | [v1.0.0-alpha.1] sabe.persistenceapi
x | [v1.0.1-alpha.2] sabe.platformersaves
x | [v1.4.1] shineua.minecraft_splash
! | [v1.1.0] sofabeddd.colored_icon_kit
x | [v4.1.0-beta] spaghettdev.betterinputs
x | [v1.1.15] syzzi.click_between_frames
! | [v2024.229.0] tastyforreal.google-translate
! | [v1.0.1] techstudent10.hide_locks
! | [v1.0.1] thesillydoggo.animatedprofiles
! | [v1.0.0-beta.8] thesillydoggo.comment_emojis
! | [v1.6.9] thesillydoggo.entersearch
! | [v1.0.4] thesillydoggo.icon_kit_switcher
x | [v1.0.0-beta.1] thesillydoggo.newgrounds_explorer
! | [v1.6.8] tpdea.betterpause-Better
! | [v1.0.0] tpdea.wavetrailglowy
x | [v1.3.7] undefined0.editormusic
x | [v1.12.7] undefined0.gdtweaks
x | [v1.2.1] uproxide.autosong
x | [v1.5.0] uproxide.more_difficulties
! | [v1.3.0] uproxide.user_reviews
! | [v6.0.0-beta.7] user95401.mainlevelseditor
! | [v1.1.3] weebify.coins_in_pause_menu
x | [v1.0.4] weebify.level_info_in_pause_menu
x | [v1.1.3] weebify.restartbtn
! | [v1.0.0] xanii.auto_music_sync
! | [v1.0.0] xanii.level_ratings
  | [v1.0.1] xanii.super_expert
x | [v1.2.3] ziegenhainy.xxlify
! | [v1.0.0] zilko.literal_level_lengths
! | [v1.5.5] zilko.xdbot

### Steps to Reproduce

1. Start-up Geometry Dash
2. Wait for it to fully load
3. Crash.

### Crash Report

[2024-07-01_10-36-22.txt](https://github.com/user-attachments/files/16054544/2024-07-01_10-36-22.txt)
[Geode 2024-07-01 10.36.04.log](https://github.com/user-attachments/files/16054613/Geode.2024-07-01.10.36.04.log)

**Comment by Kingminer7** [comment]
Uninstall Demons In Between in safe mode or delete hiimjustin000.demons_in_between.geode in GeometryDash/geode/mods

**Comment by hiimjustin000** [comment]
> x | [v1.1.1] hiimjustin000.demons_in_between
Caused by this mod, it has been fixed though

**Comment by relaxingOcean** [comment]
Alright, thanks!
