### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by munakoiso123** [geode-sdk/geode#985]
### Geode Issue

- [x] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

2.206

### Expected Behavior

i expect that i could download mods or that mods that i have downloaded before 2.206 would work by now but they still dont

### Actual Behavior

![Geometry Dash Screenshot 2024 07 01 - 18 11 13 16](https://github.com/geode-sdk/geode/assets/153113376/06bfafa4-7d7b-4a3a-95da-628eb815a00d)
![Geometry Dash Screenshot 2024 07 01 - 18 11 32 23](https://github.com/geode-sdk/geode/assets/153113376/ad4f9a88-ceef-4785-9078-aceaa091a2ef)
![Geometry Dash Screenshot 2024 07 01 - 18 11 58 26](https://github.com/geode-sdk/geode/assets/153113376/cd94d768-19d5-4a70-b0b7-0b0ca3b099ba)

### Steps to Reproduce

i dont know

### Additional Information

i dont know if this is a bug or am i stupid but i have the newest version of geode so it should work but just doesnt.

**Comment by heavyutils** [comment]
Sorbets are down just wait

**Comment by heavyutils** [comment]
Why did I and probably everyone else get notified of this?
