### ISSUE TITLE
Crash on macOS Big Sur with an Intel chip

### ISSUE THREAD

**Issue by DelofJ** [geode-sdk/geode#991]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v3.1.1 (latest)

### Mods Installed

No mods, it was a fresh install

### Steps to Reproduce

1. Get an Intel MacBook Air from 2013
2. Install Steam and GD
3. Install Geode

### Crash Report

There is no other crashlog than the crash report directly prompted to me by macOS
[crashlog.txt](https://gist.github.com/DelofJ/950007c549a4e2746708de06f15865ff)

### Additional Information

I'm using an old Mac from 2013, and it's stuck on macOS 11 Big Sur
Idk if for some reason Big Sur is no longer supported
Before these recent updates, I have been able to install Geode without any issues, so I assumed it was gonna work fine

**Comment by iNUCi** [comment]
geode requres monterey now for some reason

I guess you have to test your luck with opencore legacy patcher

**Comment by qimiko** [comment]
known issue with ci builds, we're still figuring out a good fix (mostly waiting on testers)

but yeah, it's unintentional. if you build geode locally, it'll run on macos 11 just fine. hopefully fixed releases soon
