### ISSUE TITLE
BetterInfo only supports version 3.2.0 but the latest version is 3.1.1

### ISSUE THREAD

**Issue by Cebberi** [geode-sdk/geode#996]
### Geode Issue

- [ ] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

3.1.1

### Mods Installed

just installed it

### Expected Behavior

to download normally

### Actual Behavior

not downloading

### Steps to Reproduce

just try to download betterinfo

### Additional Information

IT IS NOT RELATED TO THE GEODE LOADER ITSELF

**Comment by Prevter** [comment]
Latest version of Geode is 3.2.0, the website is sadly outdated (you can still update in-game)

**Comment by Cebberi** [comment]
> Latest version of Geode is 3.2.0, the website is sadly outdated (you can still update in-game)

but how

**Comment by hiimjustin000** [comment]
> > Latest version of Geode is 3.2.0, the website is sadly outdated (you can still update in-game)
> 
> but how

Literally just open the game and it will tell you

**Comment by Cebberi** [comment]
i think it updated itself-
